$ErrorActionPreference='Continue'
$BridgeRoot=if($env:AAYS_BRIDGE_ROOT){$env:AAYS_BRIDGE_ROOT}else{'C:\AAYS_GITHUB_BRIDGE_CLEAN2'}
$ProjectRoot='C:\Users\cagda\Documents\GitHub\AAYS\terrayield_land_intelligence'
$TaskFile=Join-Path $BridgeRoot 'ai-tasks\current-task.json'
$StateFile=Join-Path $BridgeRoot 'ai-tasks\.last-task-id'
$ResultDir=Join-Path $BridgeRoot 'ai-results'
$HeartbeatDir=Join-Path $BridgeRoot 'ai-heartbeat'
$LogDir=Join-Path $BridgeRoot 'ai-runner-logs'
$TmpDir=Join-Path $BridgeRoot 'ai-tmp'
$ScriptDir=Join-Path $BridgeRoot 'ai-task-scripts'
$MutexName='Global\AAYS_AUTOPILOT_RUNNER_V6_SAFE_SYNC_SINGLE_INSTANCE'
$PollSeconds=12
New-Item -ItemType Directory -Force -Path $ResultDir,$HeartbeatDir,$LogDir,$TmpDir,$ScriptDir | Out-Null
$RunnerLog=Join-Path $LogDir ('autopilot-v6-safe-sync-'+(Get-Date -Format 'yyyyMMdd_HHmmss')+'.log')
$Mutex=New-Object System.Threading.Mutex($false,$MutexName)
if(-not $Mutex.WaitOne(1000)){Write-Host 'AAYS_AUTOPILOT_RUNNER_V6_ALREADY_RUNNING'; exit 0}
function Log($m){$line='['+(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')+'] '+$m; Write-Host $line; Add-Content -Encoding UTF8 -Path $RunnerLog -Value $line}
function WriteSafe($p,$t){$d=Split-Path $p -Parent; if(!(Test-Path $d)){New-Item -ItemType Directory -Force -Path $d|Out-Null}; [IO.File]::WriteAllText($p,$t,[Text.UTF8Encoding]::new($true))}
function Heartbeat($s){$txt="# AAYS Autopilot Runner V6 Safe Sync`n`nTime: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`nStatus: $s`nBridgeRoot: $BridgeRoot`nTaskFile: $TaskFile`nStateFile: $StateFile`nRunnerLog: $RunnerLog`n"; WriteSafe (Join-Path $HeartbeatDir 'autopilot-v6.md') $txt}
function SaveLocalState($msg){try{git -C $BridgeRoot add ai-results ai-heartbeat ai-runner-logs ai-tasks/.last-task-id 2>$null|Out-Null; $s=git -C $BridgeRoot status --short 2>$null; if($s){git -C $BridgeRoot commit -m $msg 2>$null|Out-Null}}catch{Log('SAVE_LOCAL_WARN: '+$_.Exception.Message)}}
function SyncRemote(){try{SaveLocalState 'Autopilot V6 local state before sync'; git -C $BridgeRoot fetch origin main --prune|Out-Null; git -C $BridgeRoot rebase origin/main 2>$null|Out-Null; if($LASTEXITCODE -ne 0){git -C $BridgeRoot rebase --abort 2>$null|Out-Null; SaveLocalState 'Autopilot V6 local state before hard sync'; git -C $BridgeRoot reset --hard origin/main|Out-Null}; git -C $BridgeRoot clean -fd ai-tmp 2>$null|Out-Null}catch{Log('SYNC_WARN: '+$_.Exception.Message)}}
function PushState($msg){try{SaveLocalState $msg; git -C $BridgeRoot fetch origin main --prune|Out-Null; git -C $BridgeRoot pull --rebase --autostash origin main 2>$null|Out-Null; git -C $BridgeRoot push origin main 2>$null|Out-Null}catch{Log('PUSH_WARN: '+$_.Exception.Message)}}
function AllowedWorkdir($p){try{$f=[IO.Path]::GetFullPath($p); $a=@($BridgeRoot,$ProjectRoot,'E:\AAYS_DATA'); foreach($x in $a){$af=[IO.Path]::GetFullPath($x); if($f.StartsWith($af,[StringComparison]::OrdinalIgnoreCase)){return $true}}; return $false}catch{return $false}}
function AllowedScript($p){try{$f=[IO.Path]::GetFullPath($p); $af=[IO.Path]::GetFullPath($ScriptDir); return $f.StartsWith($af,[StringComparison]::OrdinalIgnoreCase)}catch{return $false}}
function BuildCommand($task){$cmd=''; if($task.command){$cmd=[string]$task.command}; if([string]::IsNullOrWhiteSpace($cmd) -and $task.script_path){$sp=[string]$task.script_path; if(-not [IO.Path]::IsPathRooted($sp)){$sp=Join-Path $ScriptDir $sp}; $full=[IO.Path]::GetFullPath($sp); if(-not (AllowedScript $full)){return "Write-Output 'SCRIPT_PATH_NOT_ALLOWED: $full'; exit 9003"}; if(-not (Test-Path $full)){return "Write-Output 'SCRIPT_PATH_NOT_FOUND: $full'; exit 9004"}; $cmd="& '$full'; exit `$LASTEXITCODE"}; if([string]::IsNullOrWhiteSpace($cmd)){if($task.action -eq 'health_check'){return "Write-Output 'AAYS_HEALTH=OK'; Get-Date"}; return "Write-Output 'NO_COMMAND'; exit 9005"}; return $cmd}
function Blocked($cmd){$patterns=@('Remove-Item\s+-Recurse\s+-Force\s+C:\\','rm\s+-rf','Format-Volume','Clear-Disk','Remove-Partition','shutdown','Restart-Computer','Stop-Computer','cipher\s+/w','net\s+user','New-LocalUser','Set-LocalUser','\biex\b'); foreach($p in $patterns){if($cmd -match $p){return $true}}; return $false}
function RunText($text,$wd,$timeout,$id){$safe=$id -replace '[^a-zA-Z0-9_-]+','-'; $tmp=Join-Path $TmpDir ('v6-'+$safe+'.ps1'); WriteSafe $tmp $text; $psi=New-Object Diagnostics.ProcessStartInfo; $psi.FileName='powershell.exe'; $psi.Arguments='-NoProfile -ExecutionPolicy Bypass -File "'+$tmp+'"'; $psi.WorkingDirectory=$wd; $psi.RedirectStandardOutput=$true; $psi.RedirectStandardError=$true; $psi.UseShellExecute=$false; $psi.CreateNoWindow=$true; $p=New-Object Diagnostics.Process; $p.StartInfo=$psi; try{[void]$p.Start()}catch{return [pscustomobject]@{ExitCode=997;Output='PROCESS_START_FAILED';Error=$_.Exception.Message}}; $out=$p.StandardOutput.ReadToEndAsync(); $err=$p.StandardError.ReadToEndAsync(); $done=$p.WaitForExit($timeout*1000); if(-not $done){try{$p.Kill()}catch{}; return [pscustomobject]@{ExitCode=124;Output=$out.Result;Error=$err.Result+"`nTIMEOUT_AFTER_SECONDS=$timeout"}}; return [pscustomobject]@{ExitCode=$p.ExitCode;Output=$out.Result;Error=$err.Result}}
Log 'AAYS Autopilot Runner V6 Safe Sync started. Keep this window open.'
Heartbeat 'started'
PushState 'Autopilot V6 started'
while($true){try{SyncRemote; Heartbeat 'polling'; if(!(Test-Path $TaskFile)){Log 'No current-task.json'; Start-Sleep -Seconds $PollSeconds; continue}; $task=Get-Content -Raw -Encoding UTF8 $TaskFile|ConvertFrom-Json; $id=[string]$task.id; if([string]::IsNullOrWhiteSpace($id)){Log 'Task without id'; Start-Sleep -Seconds $PollSeconds; continue}; $last=''; if(Test-Path $StateFile){$last=(Get-Content -Raw -Encoding UTF8 $StateFile).Trim([char]0xFEFF).Trim()}; if($last -eq $id.Trim()){Log "Idle. Last task=$last"; Start-Sleep -Seconds $PollSeconds; continue}; $title=if($task.title){[string]$task.title}else{'Untitled task'}; $wd=if($task.working_directory){[string]$task.working_directory}else{$ProjectRoot}; $timeout=if($task.timeout_seconds){[int]$task.timeout_seconds}else{600}; if($timeout -lt 30){$timeout=30}; if($timeout -gt 14400){$timeout=14400}; $cmd=BuildCommand $task; Log "Task found: $id | $title | timeout=$timeout"; Heartbeat "running $id"; if(-not (AllowedWorkdir $wd)){$code=9001;$output="WORKDIR_NOT_ALLOWED: $wd";$err=''}elseif(Blocked $cmd){$code=9002;$output='BLOCKED_BY_RUNNER_SAFETY_POLICY';$err=$cmd}else{$run=RunText $cmd $wd $timeout $id; $code=$run.ExitCode; $output=$run.Output; $err=$run.Error}; $safe=$id -replace '[^a-zA-Z0-9_-]+','-'; $ts=Get-Date -Format 'yyyy-MM-dd_HH-mm-ss'; $res=Join-Path $ResultDir "$ts-$safe.md"; $md="# AAYS Autopilot Runner V6 Result`n`n## Task`n$title`n`n## Task ID`n$id`n`n## Time`n$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`n`n## Working Directory`n$wd`n`n## Timeout Seconds`n$timeout`n`n## Exit Code`n$code`n`n## Output`n````text`n$output`n`````n`n## Error`n````text`n$err`n`````n"; WriteSafe $res $md; WriteSafe $StateFile $id; Heartbeat "finished $id exit=$code"; PushState "Autopilot V6 result $id"; Log "Task finished: $id exit=$code"}catch{Log('LOOP_ERROR: '+$_.Exception.Message); Heartbeat ('error '+$_.Exception.Message); PushState 'Autopilot V6 error heartbeat'; Start-Sleep -Seconds $PollSeconds}}
