#!/usr/bin/env python3
import argparse,json,re
from collections import Counter,defaultdict
from pathlib import Path
P=re.compile(r'^[A-Z]{1,2}\d[A-Z\d]?\d[A-Z]{2}$')
def main():
 a=argparse.ArgumentParser();a.add_argument('input',type=Path);a.add_argument('--output',type=Path);x=a.parse_args();d=json.loads(x.input.read_text());r=d.get('rows',[]);g=defaultdict(list)
 for z in r:g[z['postcode']].append(z)
 dup={k:v for k,v in g.items() if len(v)>1};inv={k:len({(q['quality_band'],q['gigabit'],q['ufbb100'],q['sfbb'],q['unable30'],q['accuracy'],q['r2']) for q in v})==1 for k,v in dup.items()};c=Counter(q['join_class'] for q in r);conf=[q for q in r if q['join_class']=='conflict'];w=sum(q.get('join_distance') is not None and q['join_distance']<=250 for q in r)
 checks=[('slot_id',d.get('slot_id')=='internet_access_1'),('sixteen_rows',len(r)==16),('unique_parcels',len({q['parcel_id'] for q in r})==16),('unique_row_numbers',len({q['row_no'] for q in r})==16),('ten_postcodes',len(g)==10),('all_postcodes_normalized',all(P.fullmatch(q['postcode']) for q in r)),('all_values_in_range',all(all(0<=q[k]<=100 for k in ('gigabit','ufbb100','sfbb','unable30')) for q in r)),('all_speed_thresholds_monotonic',all(q['gigabit']<=q['ufbb100']<=q['sfbb'] for q in r)),('all_accuracy_2_of_4',all(q['accuracy']=='2/4' for q in r)),('all_r2_false',all(q['r2'] is False for q in r)),('duplicate_postcode_groups_two',len(dup)==2),('rm70yl_invariant',inv.get('RM70YL') is True),('rm70yx_invariant',inv.get('RM70YX') is True),('strong_count_3',c['strong']==3),('supported_count_10',c['supported']==10),('borderline_count_2',c['borderline']==2),('conflict_count_1',c['conflict']==1),('within_250m_count_13',w==13),('conflict_row_is_13',[q['row_no'] for q in conf]==[13]),('conflict_has_two_candidates',bool(conf) and len(conf[0].get('join_candidates',[]))==2),('official_direct_rows_zero',d.get('official_direct_rows_read',0)==0),('secondary_direct_rows_zero',d.get('secondary_direct_rows_read',0)==0),('business_rows_zero',d.get('business_rows_written',0)==0),('final_ready_false',d.get('final_ready') is False)]
 n=sum(bool(v) for _,v in checks);o={'schema_version':1,'slot_id':'internet_access_1','status':'PASS' if n==len(checks) else 'FAIL_CLOSED','checks_passed':n,'checks_failed':len(checks)-n,'checks_total':len(checks),'checks':[{'name':k,'pass':bool(v)} for k,v in checks],'business_rows_written':0,'fake_data':False,'final_ready':False};s=json.dumps(o,ensure_ascii=False,indent=2)+'\n';print(s,end='');x.output and x.output.write_text(s);return 0 if n==len(checks) else 1
if __name__=='__main__':raise SystemExit(main())
