#!/usr/bin/env python3
import json,subprocess,sys,tempfile
from pathlib import Path
SLOT='internet_access_2';SHARD=Path('docs/chatgpt_status/internet_access_parcel_layer_low_credit_20260612/shards/internet_access_2');WEB=Path('england_map_web/data/aays_18_slots/internet_access_2');SCRIPT=Path(__file__).with_name('024_validate_review_contract_consistency.py')
def write(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v)+'\n')
def fixture(root):
 chain=[f'A{i}' for i in range(16)]+['BASE_RUNNER_CODE_SHA256','RUNTIME_RUNNER_CODE_SHA256','COVERAGE_AWARE_EXTRACTOR_CODE_SHA256','COVERAGE_AWARE_CARRIER_CODE_SHA256','DISPATCH_EXECUTION_GATE_SHA256'];cmd='powershell ... -DispatchEvidenceRoot <DISPATCH_EVIDENCE_ROOT> -ExpectedReviewHeadSha <EXPECTED_REVIEW_HEAD_SHA>'
 progress={'slot_id':SLOT,'parcel_start':30762,'parcel_end':61522,'parcel_count':30761,'completed_operations':164,'total_operations':165,'visible_operation_rows':165,'official_source_candidates':8,'promoted_sources':5,'held_sources':1,'rejected_sources':2,'combined_validation_passed':475,'combined_validation_total':475,'zip_container_provenance_artifact_count':21,'dispatch_execution_gate_required':True,'actual_business_data_rows_written':0,'final_ready':False};prov={'slot_id':SLOT,'combined_validation':{'passed':475,'total':475},'required_chain':chain,'dispatch_execution_gate_selftest':{'passed':20,'total':20},'dispatch_bound_provenance_selftest':{'passed':18,'total':18},'actual_business_data_rows_written':0,'final_ready':False};ready={'slot_id':SLOT,'official_v2_semantic_preflight':{'combined_tests_passed':475,'combined_tests_total':475,'provenance_chain_artifact_count':21,'fresh_dispatch_execution_gate_tests_passed':20,'dispatch_bound_provenance_tests_passed':18},'actual_business_data_rows_written':0,'final_ready':False};scope={'slot_id':SLOT,'review_scope_file_count':97,'other_slot_path_count':0,'shared_state_path_count':0,'queue_path_count':0,'disallowed_path_count':0,'business_rows_written':0,'final_ready':False};t1={'slot_id':SLOT,'command':cmd,'preflight_validation':{'combined':{'passed':475,'total':475}},'write_policy':{'fake_data':False,'db_write':False,'migration':False,'production_deploy':False,'direct_push':False,'final_ready':False}};t2={'slot_id':SLOT,'canonical_command':cmd,'required_preflight':{'combined_all_suites':{'passed':475,'total':475}},'actual_business_data_rows_written':0,'final_ready':False}
 for p,v in [(WEB/'progress_latest.json',progress),(WEB/'provenance_contract_latest.json',prov),(WEB/'runner_readiness_latest.json',ready),(WEB/'final_review_scope_latest.json',scope),(SHARD/'runner_tasks/001_extract_shard2_postcode_candidates.task.json',t1),(SHARD/'runner_tasks/002_complete_candidate_integrity_extension.task.json',t2)]:write(root/p,v)
 write(root/WEB/'operations_latest.json',{'operations':[{'id':i,'status':'DONE'} for i in range(1,55)]+[{'id':55,'status':'OLD'}]});write(root/WEB/'scope_operations_latest.json',{'operations':[{'id':i,'status':'DONE'} for i in range(56,90)]+[{'id':90,'status':'OLD'}]});write(root/WEB/'operations_provenance_latest.json',{'operations':[{'id':55,'status':'DONE'},{'id':90,'status':'DONE'}]+[{'id':i,'status':'DONE'} for i in range(91,165)]+[{'id':165,'status':'BLOCKED'}]})
def run(r):return subprocess.run([sys.executable,str(SCRIPT),'--repo-root',str(r)],capture_output=True,text=True)
with tempfile.TemporaryDirectory() as t:
 r=Path(t);fixture(r);g=run(r);assert g.returncode==0,g.stderr;x=json.loads(g.stdout);assert x['tests_passed']==x['tests_total']==19 and x['provenance_chain_artifact_count']==21
 p=r/WEB/'progress_latest.json';v=json.loads(p.read_text());v['combined_validation_total']=474;write(p,v);b=run(r);assert b.returncode!=0 and 'progress_validation_total_match' in b.stderr
 fixture(r);p=r/WEB/'provenance_contract_latest.json';v=json.loads(p.read_text());v['required_chain'].remove('DISPATCH_EXECUTION_GATE_SHA256');write(p,v);b=run(r);assert b.returncode!=0 and ('provenance_validation_total_match' in b.stderr or 'dispatch_gate_chain_contract' in b.stderr)
 fixture(r);p=r/SHARD/'runner_tasks/001_extract_shard2_postcode_candidates.task.json';v=json.loads(p.read_text());v['command']='missing';write(p,v);b=run(r);assert b.returncode!=0 and 'task_dispatch_arguments_required' in b.stderr
 fixture(r);p=r/WEB/'final_review_scope_latest.json';v=json.loads(p.read_text());v['disallowed_path_count']=1;write(p,v);b=run(r);assert b.returncode!=0 and 'scope_is_exact_and_authorized' in b.stderr
print(json.dumps({'status':'PASS','tests_passed':19,'tests_total':19,'actual_business_data_rows_written':0,'final_ready':False},sort_keys=True))
