#!/usr/bin/env python3
"""Capture, validate and optionally download an official OS Terrain 50 archive.

The OS Data Hub download page is JavaScript-driven. This helper accepts the
actual network URL generated by that page, or a browser HAR containing it.
It records provenance and rejects non-HTTPS, non-ZIP, oversized, HTML, unsafe,
or archive-without-ASCII responses.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import urllib.parse
import urllib.request
import zipfile
from pathlib import Path
from typing import Any, Iterable, Iterator

OFFICIAL_PAGE = "https://osdatahub.os.uk/downloads/open/Terrain50"
MAX_DEFAULT_MB = 300
SAFE_HOST_SUFFIXES = (
    "osdatahub.os.uk",
    "os.uk",
    "ordnancesurvey.co.uk",
    "blob.core.windows.net",
    "azureedge.net",
)


def _walk(value: Any) -> Iterator[Any]:
    yield value
    if isinstance(value, dict):
        for nested in value.values():
            yield from _walk(nested)
    elif isinstance(value, list):
        for nested in value:
            yield from _walk(nested)


def _urls_from_har(path: Path) -> list[str]:
    payload = json.loads(path.read_text(encoding="utf-8-sig"))
    urls: list[str] = []
    for value in _walk(payload):
        if isinstance(value, dict):
            request = value.get("request")
            if isinstance(request, dict) and isinstance(request.get("url"), str):
                urls.append(request["url"])
            response = value.get("response")
            if isinstance(response, dict):
                redirect = response.get("redirectURL")
                if isinstance(redirect, str) and redirect:
                    urls.append(redirect)
        elif isinstance(value, str) and value.startswith("https://"):
            urls.append(value)
    return urls


def _candidate_score(url: str) -> int:
    lower = urllib.parse.unquote(url).casefold()
    score = 0
    if "terrain50" in lower or "terrain-50" in lower or "terr50" in lower:
        score += 8
    if ".zip" in lower:
        score += 5
    if "ascii" in lower or "grid" in lower or "dtm" in lower:
        score += 4
    if "2026" in lower or "july" in lower:
        score += 2
    return score


def _safe_host(url: str) -> bool:
    parsed = urllib.parse.urlparse(url)
    host = (parsed.hostname or "").casefold()
    return parsed.scheme == "https" and any(host == suffix or host.endswith("." + suffix) for suffix in SAFE_HOST_SUFFIXES)


def _filename(url: str, headers: Any) -> str:
    disposition = headers.get("Content-Disposition", "")
    match = re.search(r"filename\*?=(?:UTF-8''|\"?)([^\";]+)", disposition, flags=re.I)
    if match:
        return Path(urllib.parse.unquote(match.group(1))).name
    name = Path(urllib.parse.urlparse(url).path).name
    return name or "os_terrain50_download.zip"


def _stream_download(url: str, target: Path, timeout: int, max_bytes: int) -> tuple[int, str, dict[str, str]]:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "TerraYield-AAYS/height_difference_3"},
    )
    digest = hashlib.sha256()
    total = 0
    headers: dict[str, str] = {}
    target.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(request, timeout=timeout) as response, target.open("wb") as handle:
        headers = {key: value for key, value in response.headers.items()}
        content_type = (response.headers.get("Content-Type") or "").casefold()
        if "text/html" in content_type:
            raise ValueError("download returned HTML")
        while True:
            chunk = response.read(1024 * 1024)
            if not chunk:
                break
            total += len(chunk)
            if total > max_bytes:
                raise ValueError(f"download exceeds max bytes {max_bytes}")
            digest.update(chunk)
            handle.write(chunk)
    return total, digest.hexdigest(), headers


def _validate_zip(path: Path) -> dict[str, Any]:
    with path.open("rb") as handle:
        if handle.read(4) != b"PK\x03\x04":
            raise ValueError("download is not a ZIP archive")
    with zipfile.ZipFile(path) as archive:
        names = archive.namelist()
        unsafe = [
            name for name in names
            if Path(name).is_absolute() or ".." in Path(name).parts
        ]
        if unsafe:
            raise ValueError("unsafe archive paths detected")
        asc = [name for name in names if name.casefold().endswith(".asc")]
        gml = [name for name in names if name.casefold().endswith(".gml")]
        prj = [name for name in names if name.casefold().endswith(".prj")]
        if not asc:
            raise ValueError("archive contains no ASCII grid files")
        return {
            "archive_entry_count": len(names),
            "ascii_grid_count": len(asc),
            "gml_count": len(gml),
            "prj_count": len(prj),
            "sample_ascii_entries": asc[:10],
        }


def _write(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--har", type=Path, action="append", default=[])
    parser.add_argument("--url", action="append", default=[])
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--timeout", type=int, default=120)
    parser.add_argument("--max-download-mb", type=int, default=MAX_DEFAULT_MB)
    parser.add_argument("--download", action="store_true")
    parser.add_argument("--allow-host", action="append", default=[])
    args = parser.parse_args(argv)

    urls = list(args.url)
    for har in args.har:
        urls.extend(_urls_from_har(har))
    urls = list(dict.fromkeys(url for url in urls if isinstance(url, str) and url.startswith("https://")))
    scored = sorted(
        ((url, _candidate_score(url)) for url in urls),
        key=lambda pair: (-pair[1], pair[0]),
    )
    candidates = [url for url, score in scored if score >= 8]
    extra_hosts = tuple(value.casefold() for value in args.allow_host)

    report: dict[str, Any] = {
        "schema_version": 1,
        "slot_id": "height_difference_3",
        "official_download_page": OFFICIAL_PAGE,
        "input_url_count": len(urls),
        "candidate_url_count": len(candidates),
        "candidates": [],
        "downloaded_archive": None,
        "final_ready": False,
        "fake_data": False,
        "db_write": False,
        "migration": False,
        "production_deploy": False,
    }
    output_dir = args.output_dir.resolve()
    for url in candidates:
        parsed = urllib.parse.urlparse(url)
        allowed = _safe_host(url) or any(
            (parsed.hostname or "").casefold() == host
            or (parsed.hostname or "").casefold().endswith("." + host)
            for host in extra_hosts
        )
        entry = {
            "url": url,
            "score": _candidate_score(url),
            "https": parsed.scheme == "https",
            "host": parsed.hostname,
            "host_allowed": allowed,
        }
        report["candidates"].append(entry)
        if not allowed:
            continue
        if not args.download:
            continue
        provisional = output_dir / "terrain50_download.zip"
        try:
            size, sha256, headers = _stream_download(
                url,
                provisional,
                args.timeout,
                args.max_download_mb * 1024 * 1024,
            )
            name = _filename(url, headers)
            final_path = output_dir / name
            if final_path != provisional:
                provisional.replace(final_path)
            archive = _validate_zip(final_path)
            report["downloaded_archive"] = {
                "source_url": url,
                "path": str(final_path),
                "size_bytes": size,
                "sha256": sha256,
                "content_type": headers.get("Content-Type"),
                "content_disposition": headers.get("Content-Disposition"),
                **archive,
            }
            report["status"] = "OFFICIAL_TERRAIN50_ASCII_ARCHIVE_VALIDATED"
            _write(output_dir / "terrain50_download_manifest.json", report)
            print(json.dumps({"ok": True, "status": report["status"], "ascii": archive["ascii_grid_count"]}))
            return 0
        except Exception as exc:
            entry["download_error"] = f"{type(exc).__name__}: {exc}"
            provisional.unlink(missing_ok=True)

    if candidates and not args.download:
        report["status"] = "TERRAIN50_DOWNLOAD_URL_CAPTURED_NOT_DOWNLOADED"
        code = 0
    else:
        report["status"] = "BLOCKED_OFFICIAL_TERRAIN50_DOWNLOAD_URL_OR_VALID_ARCHIVE_REQUIRED"
        code = 2
    _write(output_dir / "terrain50_download_manifest.json", report)
    print(json.dumps({"ok": code == 0, "status": report["status"], "candidates": len(candidates)}))
    return code


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(json.dumps({"ok": False, "error": f"{type(exc).__name__}: {exc}"}), file=sys.stderr)
        raise
