#!/usr/bin/env python3
"""Fail-closed same-task coordinator wiring validator for height_difference_3 Batch143."""
from __future__ import annotations
import json,subprocess,sys
from pathlib import Path
from typing import Any
TASK_ID="height_difference_3-canonical-api-measurement-20260721-01";ATTEMPT="height-difference-3-20260721-011";CONT="6e8e709b6bad7b9807055e2b8b5de98cd4945ee3dee57825e72ba1b824eadd0f";BRANCH="codex/aays-single-runner-v5-20260706"
LEGACY="docs/chatgpt_status/topography/shards/height_difference_3/automation/023_runner_entry_canonical_api_measurement.py";RUN039="docs/chatgpt_status/topography/shards/height_difference_3/automation/039_runner_entry_batch133_prepare_publish_handoff.py";POST040="docs/chatgpt_status/topography/shards/height_difference_3/automation/040_runner_entry_batch133_post_publish_remote_readback.py";P037="docs/chatgpt_status/topography/shards/height_difference_3/automation/037_prepare_batch132_publish_manifest.py";READ038="docs/chatgpt_status/topography/shards/height_difference_3/automation/038_verify_batch132_origin_remote_readback.ps1"
REQUEST="docs/chatgpt_status/_shared/slots_21/height_difference_3/coordinator_requests/001_same_task_rewire_to_canonical_noarg.json";TASK="docs/chatgpt_status/_shared/slots_21/height_difference_3/current_task_latest.json";QUEUE="docs/chatgpt_status/topography/queue/height_difference_3_canonical_api_measurement_20260721_01.v3.task.json";QUEUEROOT="docs/chatgpt_status/topography/queue";OWNER="docs/chatgpt_status/_shared/slots_21/height_difference_3/ownership_latest.json"
V041="docs/chatgpt_status/topography/shards/height_difference_3/automation/041_validate_batch134_coordinator_wiring_request.py";B042="docs/chatgpt_status/topography/shards/height_difference_3/automation/042_run_batch135_fresh_origin_wiring_preflight.py";H043="docs/chatgpt_status/topography/shards/height_difference_3/automation/043_run_batch136_exact_branch_head_and_dependency_preflight.py";E044="docs/chatgpt_status/topography/shards/height_difference_3/automation/044_run_batch137_runtime_environment_preflight.py";H045="docs/chatgpt_status/topography/shards/height_difference_3/automation/045_run_batch140_fresh_runner_heartbeat_gate.py";V046="docs/chatgpt_status/topography/shards/height_difference_3/automation/046_validate_batch141_coordinator_rewire_receipt.py";G047="docs/chatgpt_status/topography/shards/height_difference_3/automation/047_generate_batch142_coordinator_rewire_receipt.py"
S036="docs/chatgpt_status/topography/shards/height_difference_3/automation/036_run_batch131_strict12_with_local_acceptance.ps1";S033="docs/chatgpt_status/topography/shards/height_difference_3/automation/033_run_batch130_prepare12_strict_measurement_chain.ps1";S032="docs/chatgpt_status/topography/shards/height_difference_3/automation/032_run_batch129_range_extract_and_prepare12.ps1";R076="docs/chatgpt_status/topography/shards/height_difference_3/runner_inputs/076_batch138_runtime_executable_identity_resume.json";R077="docs/chatgpt_status/topography/shards/height_difference_3/runner_inputs/077_batch139_remote_history_binding_resume.json";R078="docs/chatgpt_status/topography/shards/height_difference_3/runner_inputs/078_batch140_fresh_heartbeat_ttl_and_commit_delta_resume.json";R079="docs/chatgpt_status/topography/shards/height_difference_3/runner_inputs/079_batch141_coordinator_receipt_duplicate_census_and_entry_origin_resume.json";R080="docs/chatgpt_status/topography/shards/height_difference_3/runner_inputs/080_batch142_deterministic_receipt_generator_and_seal_resume.json"
ENVOUT="docs/chatgpt_status/topography/shards/height_difference_3/runner_outputs/041_batch137_runtime_environment_preflight/runtime_environment_preflight.json";HBOUT="docs/chatgpt_status/topography/shards/height_difference_3/runner_outputs/045_batch140_fresh_heartbeat_preflight/fresh_runner_heartbeat_preflight.json";RECEIPT="docs/chatgpt_status/topography/shards/height_difference_3/runner_outputs/047_batch141_coordinator_rewire_receipt/coordinator_runtime_rewire_receipt.json";RECEIPTVAL="docs/chatgpt_status/topography/shards/height_difference_3/runner_outputs/047_batch141_coordinator_rewire_receipt/coordinator_runtime_rewire_receipt_validation.json";SLOTHB="docs/chatgpt_status/_shared/slots_21/height_difference_3/heartbeat_latest.json";GLOBALHB="docs/chatgpt_status/_shared/heartbeat/stable_runner_daemon_heartbeat_latest.json"
EXPECTED_ROWS=list(range(61540,61552));NREAD=57;NOUT=22
def root(p:Path)->Path:
    for c in (p,*p.parents):
        if (c/"england_map_web").is_dir() and (c/"docs/chatgpt_status").is_dir():return c
    raise RuntimeError("REPO_ROOT_NOT_FOUND")
def load(p:Path)->dict[str,Any]:
    v=json.loads(p.read_text(encoding="utf-8-sig"));
    if not isinstance(v,dict):raise ValueError(f"expected object:{p}")
    return v
def git(r:Path,*a:str)->str:
    p=subprocess.run(["git","-C",str(r),*a],text=True,capture_output=True,check=False)
    if p.returncode:raise RuntimeError(f"git {' '.join(a)} failed:{p.stderr[-1200:]}")
    return p.stdout.strip()
def blob(r:Path,ref:str,rel:str)->str:
    v=git(r,"rev-parse",f"{ref}:{rel}").lower()
    if len(v)!=40:raise ValueError(f"bad blob:{ref}:{rel}:{v}")
    return v
def main()->int:
    r=root(Path(__file__).resolve());req=load(r/REQUEST);task=load(r/TASK);queue=load(r/QUEUE);own=load(r/OWNER);checks=[]
    def ck(n:str,p:bool,d:Any=None):
        checks.append({"name":n,"passed":bool(p),"detail":d})
        if not p:raise ValueError(f"wiring validation failed:{n}:{d}")
    ck("schema10",int(req.get("schema_version") or 0)>=10);ck("identity",req.get("task_id")==TASK_ID and req.get("attempt_id")==ATTEMPT and req.get("continuation_key")==CONT);ck("no_duplicate",req.get("new_task_forbidden") is True and req.get("duplicate_task_forbidden") is True and req.get("new_runner_forbidden") is True and req.get("parallel_runner_forbidden") is True)
    ck("task_identity",task.get("task_id")==TASK_ID and task.get("attempt_id")==ATTEMPT and task.get("continuation_key")==CONT);ck("task_entrypoints",task.get("script_path")==RUN039 and task.get("post_publish_script_path")==POST040)
    reads=list(task.get("read_paths") or []);outs=list(task.get("expected_outputs") or []);ck("task_57_reads",len(reads)==NREAD,len(reads));ck("task_22_outputs",len(outs)==NOUT,len(outs));ck("resume080_readable",R080 in reads);ck("generator_validator_readable",G047 in reads and V046 in reads);ck("queue_root_readable",QUEUEROOT in reads);ck("generated_receipts_are_outputs",HBOUT in outs and ENVOUT in outs and RECEIPT in outs and RECEIPTVAL in outs and RECEIPT not in reads and RECEIPTVAL not in reads)
    ck("queue_identity",queue.get("task_id")==TASK_ID and queue.get("attempt_id")==ATTEMPT);ck("queue_single_runner",queue.get("single_runner_only") is True and queue.get("new_runner") is False and queue.get("parallel_runner") is False);ck("queue_script_known",queue.get("script_path") in {LEGACY,RUN039},queue.get("script_path"))
    spec=f"refs/heads/{BRANCH}:refs/remotes/origin/{BRANCH}";git(r,"fetch","--no-tags","origin",spec);remote=git(r,"rev-parse",f"refs/remotes/origin/{BRANCH}");local=git(r,"rev-parse","HEAD");ck("heads",len(remote)==40 and len(local)==40)
    pre=req.get("preconditions") or {};ck("scope_contract",int(pre.get("canonical_current_task_read_path_count_required") or 0)==NREAD and int(pre.get("canonical_current_task_expected_output_count_required") or 0)==NOUT);ck("freshness_contract",pre.get("fresh_runner_heartbeat_gate_required") is True and int(pre.get("runtime_environment_preflight_ttl_seconds") or 0)==900 and pre.get("runtime_preflight_head_task_blob_binding_required") is True);ck("receipt_preconditions",pre.get("deterministic_coordinator_receipt_generator_required") is True and pre.get("coordinator_rewire_receipt_required") is True and int(pre.get("coordinator_rewire_receipt_ttl_seconds") or 0)==600 and pre.get("coordinator_receipt_nonce_required") is True and pre.get("coordinator_action_id_required") is True and pre.get("receipt_sha256_seal_required") is True and pre.get("control_plane_receipt_validation_byte_seal_required") is True);ck("history_preconditions",pre.get("fresh_pre_publish_origin_head_required") is True and pre.get("remote_history_binding_required") is True and pre.get("materialization_commit_all_manifest_paths_changed_required") is True)
    tb=blob(r,remote,TASK);qb=blob(r,remote,QUEUE);ck("task_pin",tb==str(pre.get("canonical_current_task_expected_blob_sha") or "").lower(),tb);ck("queue_pin",qb==str(pre.get("legacy_queue_expected_blob_sha") or "").lower(),qb);ck("local_task_remote",blob(r,"HEAD",TASK)==tb);ck("local_queue_remote",blob(r,"HEAD",QUEUE)==qb)
    paths=[REQUEST,TASK,QUEUE,P037,RUN039,POST040,READ038,V041,B042,H043,E044,H045,V046,G047,S036,S033,S032,R076,R077,R078,R079,R080];rb={};rows=[]
    for rel in paths:
        lb=blob(r,"HEAD",rel);rr=blob(r,remote,rel);ck(f"parity:{rel}",lb==rr,{"local":lb,"remote":rr});rb[rel]=rr;rows.append({"path":rel,"local_head_blob":lb,"remote_blob":rr})
    ck("critical_clean",git(r,"status","--porcelain","--untracked-files=no","--",*paths)=="")
    vc=req.get("validator_chain") or {};ic=req.get("runtime_identity_chain") or {};hc=req.get("remote_history_chain") or {};fc=req.get("freshness_chain") or {};cc=req.get("coordinator_receipt_chain") or {};seal=req.get("control_plane_seal_chain") or {};ov=req.get("coordinator_runtime_override") or {}
    pins=[("043",vc.get("exact_branch_head_gate_expected_blob_sha"),H043),("045",fc.get("fresh_heartbeat_gate_expected_blob_sha"),H045),("044",vc.get("runtime_environment_gate_expected_blob_sha"),E044),("042",vc.get("fresh_origin_bootstrap_expected_blob_sha"),B042),("041",vc.get("same_task_validator_expected_blob_sha"),V041),("046",cc.get("coordinator_receipt_validator_expected_blob_sha"),V046),("047",cc.get("coordinator_receipt_generator_expected_blob_sha"),G047),("039",ov.get("runtime_script_expected_blob_sha"),RUN039),("040",ov.get("post_publish_script_expected_blob_sha"),POST040),("037",hc.get("publish_manifest_037_expected_blob_sha"),P037),("038",hc.get("remote_readback_038_expected_blob_sha"),READ038),("036",ic.get("strict036_expected_blob_sha"),S036),("033",ic.get("strict033_expected_blob_sha"),S033),("032",ic.get("strict032_expected_blob_sha"),S032),("076",ic.get("resume_076_expected_blob_sha"),R076),("077",hc.get("resume_077_expected_blob_sha"),R077),("078",fc.get("resume_078_expected_blob_sha"),R078),("079",cc.get("resume_079_expected_blob_sha"),R079),("080",cc.get("resume_080_expected_blob_sha"),R080)]
    for n,p,rel in pins:ck(f"pin_{n}",str(p or "").lower()==rb[rel],{"pin":p,"remote":rb[rel]})
    ck("receipt_binding",cc.get("receipt_generator")==G047 and cc.get("receipt_validator")==V046 and int(cc.get("receipt_ttl_seconds") or 0)==600 and cc.get("queue_census_basis")==["task_id","attempt_id","idempotency_key"] and cc.get("coordinator_action_id_required") is True and cc.get("random_receipt_nonce_required") is True and cc.get("receipt_binding_includes_action_id_and_nonce") is True and cc.get("validator_emits_receipt_sha256") is True and cc.get("direct_entrypoint_control_plane_seal_required") is True)
    ck("control_plane_seal",seal.get("039_receipt_sha256_before_and_after_046_equal") is True and seal.get("039_receipt_sha256_unchanged_during_strict") is True and seal.get("039_validation_sha256_unchanged_during_strict") is True and seal.get("039_receipt_and_validation_sha256_unchanged_before_handoff") is True and seal.get("040_requires_receipt_and_validation_sha256_before_remote_readback") is True and seal.get("040_rechecks_receipt_and_validation_sha256_after_remote_readback") is True and seal.get("numeric_acceptance_fails_closed_on_control_plane_seal_drift") is True)
    ck("identity_propagation",ic.get("python_executable_propagates_044_039_036_033_032_and_040") is True and ic.get("powershell_executable_propagates_044_039_036_033_032_and_040") is True and ic.get("git_executable_propagates_044_039_handoff_040_038") is True);ck("history_binding",hc.get("runtime_039_captures_fresh_pre_publish_origin_head") is True and hc.get("manifest_binds_pre_publish_origin_head") is True and hc.get("materialization_commit_must_change_all_seven_manifest_paths") is True and hc.get("post_publish_040_requires_remote_history_and_commit_delta_binding") is True);ck("override",ov.get("use_existing_queue_record") is True and ov.get("do_not_create_new_queue_record") is True and ov.get("runtime_script_path")==RUN039 and ov.get("post_publish_script_path")==POST040 and ov.get("runtime_arguments")==[] and ov.get("post_publish_arguments")==[]);ck("rows",[int(x) for x in req.get("expected_rows") or []]==EXPECTED_ROWS)
    os_=str(own.get("state") or "");oid=own.get("owner_page_session_id");ck("owner_safe",os_=="UNCLAIMED" or (os_=="CLAIMED" and oid=="chatgpt-height-difference-3-batch143-20260726"),{"state":os_,"owner":oid})
    out=r/"docs/chatgpt_status/topography/shards/height_difference_3/runner_outputs/035_batch134_coordinator_wiring_qa/coordinator_wiring_request_validation.json";payload={"schema_version":12,"slot_id":"height_difference_3","task_id":TASK_ID,"continuation_key":CONT,"status":"ALREADY_ALIGNED" if queue.get("script_path")==RUN039 else "SAFE_FOR_COORDINATOR_RUNTIME_REWIRE_AFTER_DIRECT_CONTROL_PLANE_SEAL_GATES","checks_passed":len(checks),"checks_total":len(checks),"checks":checks,"fresh_remote_head":remote,"critical_blob_parity":rows,"expected_read_path_count":NREAD,"expected_output_count":NOUT,"direct_control_plane_receipt_validation_seal_pinned":True,"fresh_host_heartbeat_still_required":True,"coordinator_action_performed":False,"legacy_queue_mutated":False,"new_task_created":False,"new_runner_created":False,"numeric_values_written":0,"expected_rows":EXPECTED_ROWS,"final_ready":False,"fake_data":False};out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(payload,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps({"ok":True,"checks":len(checks),"output":str(out)}));return 0
if __name__=="__main__":
    try:raise SystemExit(main())
    except Exception as exc:
        print(json.dumps({"ok":False,"error":f"{type(exc).__name__}: {exc}"}),file=sys.stderr);raise
