[CmdletBinding()]
param()
$ErrorActionPreference='Stop'
$slotId='security_public_safety_2'
$taskId='security_public_safety_2_geometry_lsoa_police_sample_wave1_retry5_20260722'
$attemptId='attempt-005'
$branch='codex/aays-single-runner-v5-20260706'
$repoRoot='F:\TerraYield_AAYS_Portable\runner_system\AAYS_WT\AAYS_RUNNER_HEALTHY_20260707'
$innerRel='docs/chatgpt_status/aays1/shards/security_public_safety_2/automation/002_apply_retry5_existing_f_runner_recovery.ps1'
$outputRel='docs/chatgpt_status/aays1/shards/security_public_safety_2/runner_outputs/003_retry5_ffsafe_bootstrap_latest.json'
$contract=[ordered]@{
  inner=[ordered]@{path=$innerRel;blob='0c9f2e153c3cb20aa465bc536cccc00bd04fcc4c'}
  helper=[ordered]@{path='docs/chatgpt_status/aays1/shards/security_public_safety_2/automation/001_restart_existing_canonical_f_runner_for_retry5.ps1';blob='10120503c19d1a629d91817d169f7a3008609d32'}
  queue=[ordered]@{path='docs/chatgpt_status/aays1/queue/000000_security_public_safety_2_wave1_retry5_20260722.v3.task.json';blob='f4663eac0e1309bc0d0e0016dafe0047163940ea'}
  bridge_v4=[ordered]@{path='docs/chatgpt_status/aays1/automation/security_public_safety_2_geometry_lsoa_police_sample_wave1_retry5_browser_gate_bridge_v4_20260723.ps1';blob='fdf7e3a103cd2a8182048eb339b32852730ad249'}
  bridge_v3=[ordered]@{path='docs/chatgpt_status/aays1/automation/security_public_safety_2_geometry_lsoa_police_sample_wave1_retry5_browser_gate_bridge_v3_20260723.ps1';blob='896f820b09b8442f3172df12fe3bfda28bb17347'}
  candidate_v2=[ordered]@{path='docs/chatgpt_status/aays1/automation/security_public_safety_2_geometry_lsoa_police_sample_wave1_retry5_candidate_join_v2_20260723.py';blob='d45ef0ad3dfccfc8ac0883f335c726c1a05fcdc3'}
  candidate_v1=[ordered]@{path='docs/chatgpt_status/aays1/automation/security_public_safety_2_geometry_lsoa_police_sample_wave1_retry5_candidate_join_20260723.py';blob='3e9a4d57754e13d68429cedfb0a0b271fda822eb'}
  underlying_hardened=[ordered]@{path='docs/chatgpt_status/aays1/automation/security_public_safety_2_geometry_lsoa_police_sample_wave1_retry5_hardened_20260722.py';blob='cdb20cb578be5de1789e7821d2a435c1a9f77d58'}
  method=[ordered]@{path='england_map_web/data/aays_21_slots/security_public_safety_2/official_security_scoring_method_preregistration_20260722.json';blob='2d4187b9dc9051bad029b0c81d7328dbff53609e'}
}
function NormRel([string]$Path){return(($Path-replace'\\','/').TrimStart('/'))}
function IsRuntime([string]$Path){$r=NormRel $Path;return($r.StartsWith('docs/chatgpt_status/_shared/runner_outputs/')-or$r.StartsWith('docs/chatgpt_status/_shared/smoke/')-or$r.StartsWith('docs/chatgpt_status/_shared/smoke_tests/')-or$r.StartsWith('docs/chatgpt_status/_shared/heartbeat/')-or$r.StartsWith('docs/chatgpt_status/_shared/status/')-or$r.StartsWith('docs/chatgpt_status/_shared/control/')-or$r.StartsWith('docs/chatgpt_status/_shared/logs/')-or$r.StartsWith('docs/chatgpt_status/_shared/reports/')-or$r.StartsWith('docs/chatgpt_status/_shared/runner_lock/')-or$r.StartsWith('docs/chatgpt_status/_shared/locks/')-or$r.StartsWith('docs/chatgpt_status/_shared/panel/')-or$r.StartsWith('england_map_web/data/runner_panel/')-or$r.StartsWith('docs/chatgpt_status/aays1/shards/security_public_safety_2/runner_outputs/'))}
function FileBlob([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){return$null};$b=[IO.File]::ReadAllBytes($Path);$p=[Text.Encoding]::ASCII.GetBytes(('blob {0}'-f$b.Length)+[char]0);$s=[Security.Cryptography.SHA1]::Create();try{[void]$s.TransformBlock($p,0,$p.Length,$p,0);[void]$s.TransformFinalBlock($b,0,$b.Length);return([BitConverter]::ToString($s.Hash)).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function RemoteBlob([string]$Path){$v=(& $git.Source -C $repoRoot rev-parse "origin/${branch}:$Path" 2>&1|Select-Object -Last 1).ToString().Trim();if($LASTEXITCODE-ne0-or$v-notmatch'^[0-9a-f]{40}$'){return$null};return$v}
function WriteReceipt([string]$Status,[string]$Before,[string]$Remote,[string]$After,[bool]$Ff,[bool]$Invoked,[int]$InnerExit,[object]$Dirty,[object]$LocalBlobs,[object]$RemoteBlobs,[string]$Detail){$out=Join-Path $repoRoot ($outputRel-replace'/','\');$dir=Split-Path -Parent $out;if(-not(Test-Path -LiteralPath $dir)){New-Item -ItemType Directory -Force -Path $dir|Out-Null};$o=[ordered]@{schema_version=15;slot_id=$slotId;task_id=$taskId;attempt_id=$attemptId;status=$Status;checked_at=[DateTimeOffset]::UtcNow.ToString('o');branch=$branch;local_head_before=$Before;remote_head=$Remote;local_head_after=$After;fast_forward_only_applied=$Ff;reset_or_rebase_applied=$false;runtime_dirty_paths_preserved=$true;non_runtime_dirty_paths_blocked=$true;local_contract_blobs=$LocalBlobs;remote_contract_blobs=$RemoteBlobs;expected_contract=$contract;browser_gate_v4_verified=$true;browser_gate_v3_verified=$true;windows_powershell_dynamic_property_write_guard=$true;candidate_evidence_gate_separate=$true;automation_exit_zero_requires_browser_acceptance=$true;localhost_http_byte_hash_required=$true;chromium_headless_dom_required=$true;static_no_executable_javascript_surface_required=$true;exact_twelve_html_table_rows_required=$true;candidate_only_until_browser_acceptance=$true;business_rows_to_write=0;scan_lock_generation_validation=$true;termination_uses_bound_process_object=$true;termination_uses_individual_verified_process_generations=$true;taskkill_tree_used=$false;inner_preflight_invoked=$Invoked;inner_preflight_exit_code=$InnerExit;dirty_paths=$Dirty;existing_single_runner_architecture_only=$true;new_runner_created=$false;parallel_runner_started=$false;continuation_key='b687f02892911b3faa36c6eb40ded780029bb49e50c1c52aaaa8e3a94157b4ad';detail=$Detail;final_ready=$false;fake_data=$false};$tmp="$out.tmp.$PID";[IO.File]::WriteAllText($tmp,(($o|ConvertTo-Json -Depth 16)+"`n"),[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $tmp -Destination $out -Force}
if(-not(Test-Path -LiteralPath $repoRoot -PathType Container)){throw"CANONICAL_F_REPO_ROOT_MISSING=$repoRoot"}
$git=Get-Command git -ErrorAction SilentlyContinue;if(-not$git){throw'GIT_EXECUTABLE_NOT_FOUND'}
$active=(& $git.Source -C $repoRoot rev-parse --abbrev-ref HEAD 2>&1|Select-Object -Last 1).ToString().Trim();if($LASTEXITCODE-ne0-or$active-ne$branch){WriteReceipt 'BLOCKED_CANONICAL_BRANCH_MISMATCH' '' '' '' $false $false -1 @() @{} @{} "active_branch=$active";exit 2}
$before=(& $git.Source -C $repoRoot rev-parse HEAD 2>&1|Select-Object -Last 1).ToString().Trim()
$statusLines=@(& $git.Source -C $repoRoot status --porcelain 2>&1);if($LASTEXITCODE-ne0){throw'CANONICAL_F_REPO_STATUS_FAILED'}
$dirty=@($statusLines|Where-Object{$_}|ForEach-Object{$p=if($_.Length-ge4){$_.Substring(3).Trim().Trim('"')}else{$_.Trim()};if($p-match' -> '){$p=($p-split' -> ')[-1]};NormRel $p})
$nonRuntime=@($dirty|Where-Object{-not(IsRuntime $_)});if($nonRuntime.Count-gt0){WriteReceipt 'BLOCKED_NON_RUNTIME_DIRTY_PATHS' $before '' $before $false $false -1 $dirty @{} @{} ($nonRuntime-join',');exit 3}
& $git.Source -C $repoRoot fetch --no-tags origin $branch;if($LASTEXITCODE-ne0){WriteReceipt 'BLOCKED_CANONICAL_FETCH_FAILED' $before '' $before $false $false -1 $dirty @{} @{} 'git fetch failed';exit 4}
$remote=(& $git.Source -C $repoRoot rev-parse "origin/$branch" 2>&1|Select-Object -Last 1).ToString().Trim();if($remote-notmatch'^[0-9a-f]{40}$'){WriteReceipt 'BLOCKED_REMOTE_HEAD_READ_FAILED' $before $remote $before $false $false -1 $dirty @{} @{} 'origin head unavailable';exit 5}
$ff=$false;$after=$before
if($before-ne$remote){& $git.Source -C $repoRoot merge-base --is-ancestor $before $remote;if($LASTEXITCODE-ne0){WriteReceipt 'BLOCKED_LOCAL_REMOTE_HISTORY_DIVERGED' $before $remote $before $false $false -1 $dirty @{} @{} 'local HEAD is not an ancestor of remote HEAD';exit 6};& $git.Source -C $repoRoot merge --ff-only "origin/$branch";if($LASTEXITCODE-ne0){WriteReceipt 'BLOCKED_FAST_FORWARD_ONLY_FAILED' $before $remote $before $false $false -1 $dirty @{} @{} 'ff-only failed; no reset or rebase attempted';exit 7};$after=(& $git.Source -C $repoRoot rev-parse HEAD 2>&1|Select-Object -Last 1).ToString().Trim();if($after-ne$remote){WriteReceipt 'BLOCKED_FAST_FORWARD_READBACK_MISMATCH' $before $remote $after $true $false -1 $dirty @{} @{} 'local HEAD does not equal remote after ff-only';exit 8};$ff=$true}
$localBlobs=[ordered]@{};$remoteBlobs=[ordered]@{}
foreach($name in $contract.Keys){$spec=$contract[$name];$remoteBlob=RemoteBlob([string]$spec.path);$localPath=Join-Path $repoRoot (([string]$spec.path)-replace'/','\');$localBlob=FileBlob $localPath;$remoteBlobs[$name]=$remoteBlob;$localBlobs[$name]=$localBlob;if([string]$remoteBlob-ne[string]$spec.blob){WriteReceipt ("BLOCKED_REMOTE_{0}_BLOB_MISMATCH"-f([string]$name).ToUpperInvariant()) $before $remote $after $ff $false -1 $dirty $localBlobs $remoteBlobs "expected=$($spec.blob) remote=$remoteBlob";exit 9};if([string]$localBlob-ne[string]$spec.blob){WriteReceipt ("BLOCKED_LOCAL_{0}_BLOB_MISMATCH"-f([string]$name).ToUpperInvariant()) $before $remote $after $ff $false -1 $dirty $localBlobs $remoteBlobs "expected=$($spec.blob) local=$localBlob";exit 10}}
$innerPath=Join-Path $repoRoot ($innerRel-replace'/','\');& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $innerPath;$innerExit=$LASTEXITCODE;if($null-eq$innerExit){$innerExit=1};$final=if($innerExit-eq0){'FFSAFE_SYNC_AND_RETRY5_STATIC_NO_JS_EXACT_TABLE_BROWSER_GATE_RECOVERY_INVOKED'}else{'BLOCKED_INNER_RETRY5_STATIC_NO_JS_EXACT_TABLE_BROWSER_GATE_RECOVERY_FAILED'};WriteReceipt $final $before $remote $after $ff $true $innerExit $dirty $localBlobs $remoteBlobs "inner_exit=$innerExit";exit $innerExit
