[CmdletBinding()]
param([int]$TimeoutSeconds=300,[string]$InnerPath='')
$ErrorActionPreference='Stop'
$slotId='security_public_safety_2'
$taskId='security_public_safety_2_geometry_lsoa_police_sample_wave1_retry5_20260722'
$attemptId='attempt-005'
$branch='codex/aays-single-runner-v5-20260706'
$portableRoot='F:\TerraYield_AAYS_Portable'
$repoRoot='F:\TerraYield_AAYS_Portable\runner_system\AAYS_WT\AAYS_RUNNER_HEALTHY_20260707'
$ownershipRel='docs/chatgpt_status/_shared/slots_21/security_public_safety_2/ownership_latest.json'
$innerRel='docs\chatgpt_status\aays1\shards\security_public_safety_2\automation\003_ffsafe_sync_then_apply_retry5_recovery.ps1'
$innerBlob='d55995c5dda7cd477507e26e75d51d254822f9b7'
$outputRel='docs\chatgpt_status\aays1\shards\security_public_safety_2\runner_outputs\004_retry5_timeout_guard_latest.json'
$baselineCanonical=@();$trackedAttemptProcesses=@();$remainingTrackedAttemptProcesses=@();$timeoutSpawnedCanonical=@();$remainingTimeoutSpawnedCanonical=@();$spawnedCanonicalCleanup=@()
$runnerSpecs=@(
  [ordered]@{token='RUN_AAYS_STABLE_RUNNER_FROM_THIS_DISK.cmd';root=$portableRoot},
  [ordered]@{token='RUN_EXISTING_F_PORTABLE_SINGLE_RUNNER_HOTFIX_THEN_CONTINUE_20260709';root=$portableRoot},
  [ordered]@{token='devam.ps1';root=$repoRoot},
  [ordered]@{token='RUN_AAYS_STABLE_LEGACY_RUNNER_DAEMON_20260707.ps1';root=$repoRoot},
  [ordered]@{token='RUN_SINGLE_AAYS_MULTI_PAGE_QUEUE_RUNNER_STABLE_20260707.ps1';root=$repoRoot}
)
function GitBlob([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){return$null};$b=[IO.File]::ReadAllBytes($Path);$p=[Text.Encoding]::ASCII.GetBytes(('blob {0}'-f$b.Length)+[char]0);$s=[Security.Cryptography.SHA1]::Create();try{[void]$s.TransformBlock($p,0,$p.Length,$p,0);[void]$s.TransformFinalBlock($b,0,$b.Length);return([BitConverter]::ToString($s.Hash)).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function Norm([string]$Value){if($null-eq$Value){return''};return(($Value-replace'/','\').ToLowerInvariant())}
function IdentityKey([object]$Process){return('{0}|{1}'-f([int]$Process.ProcessId),([string]$Process.CreationDate))}
function Evidence([object]$Process){return[ordered]@{process_id=[int]$Process.ProcessId;parent_process_id=[int]$Process.ParentProcessId;creation_date=[string]$Process.CreationDate;identity_key=(IdentityKey $Process);command_line=[string]$Process.CommandLine}}
function AllCimProcesses{@(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue)}
function CanonicalRunnerProcesses([object[]]$Processes=@()){if($Processes.Count-eq0){$Processes=AllCimProcesses};$matched=@();foreach($proc in $Processes){if([string]::IsNullOrWhiteSpace([string]$proc.CommandLine)){continue};$command=Norm([string]$proc.CommandLine);foreach($spec in $runnerSpecs){if($command.Contains((Norm([string]$spec.token)))-and$command.Contains((Norm([string]$spec.root)))){$matched+=$proc;break}}};return@($matched|Group-Object ProcessId|ForEach-Object{$_.Group[0]})}
function ProcessTreeSnapshot([int]$RootPid){$all=AllCimProcesses;$root=@($all|Where-Object{[int]$_.ProcessId-eq$RootPid}|Select-Object -First 1);$result=@();if($root.Count-eq1){$result+=$root[0]};$queue=New-Object 'System.Collections.Generic.Queue[int]';$queue.Enqueue($RootPid);$seen=New-Object 'System.Collections.Generic.HashSet[int]';[void]$seen.Add($RootPid);while($queue.Count-gt0){$parent=$queue.Dequeue();foreach($proc in @($all|Where-Object{[int]$_.ParentProcessId-eq$parent})){if($seen.Add([int]$proc.ProcessId)){$result+=$proc;$queue.Enqueue([int]$proc.ProcessId)}}};return@($result)}
function StopTree([int]$ProcessId){$tk=Get-Command taskkill.exe -ErrorAction SilentlyContinue;if($tk){& $tk.Source /PID $ProcessId /T /F|Out-Null;return$LASTEXITCODE};try{Stop-Process -Id $ProcessId -Force -ErrorAction Stop;return 0}catch{if(-not(Get-Process -Id $ProcessId -ErrorAction SilentlyContinue)){return 0};return 1}}
function WriteReceipt([string]$Status,[int]$ExitCode,[bool]$TimedOut,[string]$ResolvedInner,[object]$Owner,[string]$RemoteHead,[bool]$KillAttempted,[int]$KillExit,[string]$Detail){$path=Join-Path $repoRoot $outputRel;$dir=Split-Path -Parent $path;if(-not(Test-Path -LiteralPath $dir)){New-Item -ItemType Directory -Force -Path $dir|Out-Null};$o=[ordered]@{schema_version=11;slot_id=$slotId;task_id=$taskId;attempt_id=$attemptId;status=$Status;checked_at=[DateTimeOffset]::UtcNow.ToString('o');timeout_seconds=$TimeoutSeconds;timed_out=$TimedOut;inner_exit_code=$ExitCode;inner_path=$ResolvedInner;inner_expected_blob=$innerBlob;temporary_inner_allowed=$true;remote_head=$RemoteHead;ownership_rechecked=$true;ownership_snapshot=$Owner;canonical_f_process_identity_required=$true;foreign_runner_process_fail_closed=$true;direct_heartbeat_requires_repo_root_branch_and_process_start=$true;lock_fallback_requires_pid_repo_root_instance_heartbeat_start_real_process_start_freshness_scope_branch=$true;process_tree_kill_attempted=$KillAttempted;process_tree_kill_exit_code=$KillExit;baseline_canonical_processes=@($baselineCanonical|ForEach-Object{Evidence $_});tracked_attempt_processes=@($trackedAttemptProcesses|ForEach-Object{Evidence $_});remaining_tracked_attempt_processes=@($remainingTrackedAttemptProcesses|ForEach-Object{Evidence $_});timeout_spawned_canonical_processes=@($timeoutSpawnedCanonical|ForEach-Object{Evidence $_});spawned_canonical_cleanup=@($spawnedCanonicalCleanup);remaining_timeout_spawned_canonical_processes=@($remainingTimeoutSpawnedCanonical|ForEach-Object{Evidence $_});timeout_tracking_uses_pid_and_creation_date=$true;timeout_cleanup_reenumerates_exact_canonical_f_processes=$true;preexisting_process_generations_preserved=$true;same_attempt=$true;new_runner_created=$false;parallel_runner_started=$false;detail=$Detail;final_ready=$false;fake_data=$false};$tmp="$path.tmp.$PID";[IO.File]::WriteAllText($tmp,(($o|ConvertTo-Json -Depth 16)+"`n"),[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $tmp -Destination $path -Force}
if(-not(Test-Path -LiteralPath $repoRoot -PathType Container)){throw"CANONICAL_F_REPO_ROOT_MISSING=$repoRoot"}
$git=Get-Command git.exe -ErrorAction SilentlyContinue;if(-not$git){throw'GIT_EXECUTABLE_NOT_FOUND'}
& $git.Source -C $repoRoot fetch --no-tags origin $branch;if($LASTEXITCODE-ne0){WriteReceipt 'BLOCKED_FRESH_OWNER_FETCH_FAILED' -1 $false '' @{} '' $false -1 'git fetch failed';exit 20}
$remoteHead=(& $git.Source -C $repoRoot rev-parse "origin/$branch" 2>&1|Select-Object -Last 1).ToString().Trim();if($remoteHead-notmatch'^[0-9a-f]{40}$'){WriteReceipt 'BLOCKED_REMOTE_HEAD_READ_FAILED' -1 $false '' @{} $remoteHead $false -1 'origin head unavailable';exit 20}
$ownershipText=(& $git.Source -C $repoRoot show "origin/${branch}:$ownershipRel" 2>&1|Out-String);$showExit=$LASTEXITCODE;if($showExit-ne0-or[string]::IsNullOrWhiteSpace($ownershipText)){WriteReceipt 'BLOCKED_REMOTE_OWNERSHIP_READ_FAILED' -1 $false '' @{} $remoteHead $false -1 "git_show_exit=$showExit";exit 22}
try{$ownership=$ownershipText|ConvertFrom-Json}catch{WriteReceipt 'BLOCKED_REMOTE_OWNERSHIP_INVALID_JSON' -1 $false '' @{} $remoteHead $false -1 $_.Exception.Message;exit 22}
$owner=[ordered]@{state=[string]$ownership.state;owner_page_session_id=$ownership.owner_page_session_id;heartbeat_at=$ownership.heartbeat_at;lease_expires_at=$ownership.lease_expires_at};$ownerPresent=(-not[string]::IsNullOrWhiteSpace([string]$ownership.owner_page_session_id))-or(-not[string]::IsNullOrWhiteSpace([string]$ownership.heartbeat_at))-or(-not[string]::IsNullOrWhiteSpace([string]$ownership.lease_expires_at));if([string]$ownership.slot_id-ne$slotId-or[string]$ownership.state-ne'unclaimed'-or$ownerPresent){WriteReceipt 'BLOCKED_LIVE_OR_NON_UNCLAIMED_OWNER_APPEARED' -1 $false '' $owner $remoteHead $false -1 'No recovery process was started.';exit 23}
$inner=if([string]::IsNullOrWhiteSpace($InnerPath)){Join-Path $repoRoot $innerRel}else{$InnerPath};$actual=GitBlob $inner;if($actual-ne$innerBlob){WriteReceipt 'BLOCKED_003_BLOB_MISMATCH' -1 $false $inner $owner $remoteHead $false -1 "expected=$innerBlob actual=$actual";exit 21}
$baselineCanonical=@(CanonicalRunnerProcesses)
$p=Start-Process -FilePath 'powershell.exe' -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',('"{0}"'-f$inner)) -WorkingDirectory $repoRoot -PassThru -WindowStyle Normal
if(-not$p.WaitForExit($TimeoutSeconds*1000)){
  $trackedAttemptProcesses=@(ProcessTreeSnapshot([int]$p.Id));$killExit=StopTree([int]$p.Id);Start-Sleep -Seconds 2
  $afterKill=AllCimProcesses;$afterKeys=@{};foreach($proc in $afterKill){$afterKeys[(IdentityKey $proc)]=$proc};$remainingTrackedAttemptProcesses=@($trackedAttemptProcesses|Where-Object{$afterKeys.ContainsKey((IdentityKey $_))})
  $baselineKeys=@($baselineCanonical|ForEach-Object{IdentityKey $_});$timeoutSpawnedCanonical=@(CanonicalRunnerProcesses($afterKill)|Where-Object{$baselineKeys-notcontains(IdentityKey $_)})
  $cleanup=@();foreach($proc in $timeoutSpawnedCanonical){$e=StopTree([int]$proc.ProcessId);$cleanup+=[ordered]@{process_id=[int]$proc.ProcessId;creation_date=[string]$proc.CreationDate;identity_key=(IdentityKey $proc);exit_code=$e;command_line=[string]$proc.CommandLine}};$spawnedCanonicalCleanup=@($cleanup);if($timeoutSpawnedCanonical.Count-gt0){Start-Sleep -Seconds 2}
  $finalProcesses=AllCimProcesses;$finalKeys=@{};foreach($proc in $finalProcesses){$finalKeys[(IdentityKey $proc)]=$proc};$remainingTrackedAttemptProcesses=@($trackedAttemptProcesses|Where-Object{$finalKeys.ContainsKey((IdentityKey $_))});$remainingTimeoutSpawnedCanonical=@(CanonicalRunnerProcesses($finalProcesses)|Where-Object{$baselineKeys-notcontains(IdentityKey $_)})
  $allGone=($remainingTrackedAttemptProcesses.Count-eq0-and$remainingTimeoutSpawnedCanonical.Count-eq0);$status=if($allGone){'BLOCKED_RETRY5_RECOVERY_TIMEOUT_ALL_ATTEMPT_GENERATIONS_TERMINATED'}else{'BLOCKED_RETRY5_RECOVERY_TIMEOUT_PROCESS_GENERATION_REMAINS'};WriteReceipt $status 124 $true $inner $owner $remoteHead $true $killExit "wrapper_pid=$($p.Id);tracked=$($trackedAttemptProcesses.Count);remaining_tracked=$($remainingTrackedAttemptProcesses.Count);remaining_spawned_canonical=$($remainingTimeoutSpawnedCanonical.Count)";if($allGone){exit 124}else{exit 125}
}
$exit=$p.ExitCode;$status=if($exit-eq0){'TIMEOUT_GUARDED_FFSAFE_RETRY5_RECOVERY_COMPLETED'}else{'BLOCKED_INNER_FFSAFE_RETRY5_RECOVERY_FAILED'};WriteReceipt $status $exit $false $inner $owner $remoteHead $false -1 "wrapper_pid=$($p.Id)";exit $exit
