from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path

SLOT=Path('england_map_web/data/aays_21_slots/height_difference_2')
DOC=Path('docs/chatgpt_status/topography/shards/height_difference_2')
NOW=datetime.now(timezone.utc).isoformat()

def load(p): return json.loads(Path(p).read_text(encoding='utf-8'))
def dump(p,d):
    p=Path(p); p.parent.mkdir(parents=True,exist_ok=True)
    p.write_text(json.dumps(d,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8')

runtime=load(SLOT/'distribution_gradient_runtime_037.json')
if not runtime.get('all_rows_pass'): raise SystemExit('distribution runtime not PASS')
rows={int(r['row_no']):r for r in runtime['rows']}
ctx={
30762:{'lon':-0.0407406,'lat':51.6769078,'e':535564.995,'n':199388.108,'lad':'E09000010','name':'Enfield','tile':'TQ39NE'},
46142:{'lon':0.1928191,'lat':51.5931140,'e':551991.914,'n':190529.339,'lad':'E09000016','name':'Havering','tile':'TQ59SW'},
61522:{'lon':-0.1392630,'lat':51.4153374,'e':529493.381,'n':170122.189,'lad':'E09000022','name':'Lambeth','tile':'TQ27SE'}}

candidates=[
{'candidate_id':'HD2-SRC-063','name':'Environment Agency persistent WCS endpoint migration announcement','publisher':'Environment Agency','source_url':'https://environment.data.gov.uk/support/announcements/275811447/275811543','role':'PERSISTENT_WCS_ENDPOINT_AND_OPEN_STANDARD_CONTRACT','source_confidence_percent':100,'promotion_state':'PROMOTED_RUNTIME_REVALIDATION','verified_facts':['EA replaced legacy Esri Image Services with WCS and WMS','The year suffix was removed from 1m and 2m DTM WCS endpoints for persistent future updates'],'semantic_limits':['Endpoint persistence does not imply immutable raster bytes; every audit must record response SHA-256']},
{'candidate_id':'HD2-SRC-064','name':'Environment Agency LIDAR Composite DTM 1m WCS GetCoverage','publisher':'Environment Agency','source_url':'https://environment.data.gov.uk/spatialdata/lidar-composite-digital-terrain-model-dtm-1m/wcs?request=GetCapabilities&service=WCS&version=2.0.1','role':'PRIMARY_EXACT_PIXEL_DISTRIBUTION_AND_GRADIENT_SOURCE','source_confidence_percent':100,'promotion_state':'PROMOTED_SHA_REPLAY_3_OF_3','verified_facts':['All three exact polygon GetCoverage responses were downloaded again','Every response SHA-256 matched increment 034','Every raster reported EPSG:27700'],'semantic_limits':['The fitted plane is a parcel-scale topographic summary, not an engineering survey']},
{'candidate_id':'HD2-SRC-065','name':'Environment Agency LIDAR Composite DTM 2m WCS GetCoverage','publisher':'Environment Agency','source_url':'https://environment.data.gov.uk/spatialdata/lidar-composite-digital-terrain-model-dtm-2m/wcs?request=GetCapabilities&service=WCS&version=2.0.1','role':'INDEPENDENT_RESOLUTION_DISTRIBUTION_AND_GRADIENT_CROSSCHECK','source_confidence_percent':100,'promotion_state':'PROMOTED_SHA_REPLAY_3_OF_3','verified_facts':['All three 2m responses were downloaded again','Every response SHA-256 and prior min/max/difference matched increment 034'],'semantic_limits':['The 2m product remains a resolution crosscheck and does not replace the primary 1m result']},
{'candidate_id':'HD2-SRC-066','name':'Environment Agency Survey Data Catalogue GeoTIFF delivery guidance','publisher':'Environment Agency','source_url':'https://environment.data.gov.uk/support/faqs/275879146/275879189','role':'GEOTIFF_AND_WEB_COVERAGE_DELIVERY_SEMANTICS','source_confidence_percent':100,'promotion_state':'PROMOTED_SOURCE_CONTRACT','verified_facts':['EA composite products are distributed as GeoTIFF','GeoTIFF delivery supports WCS access and GIS geoprocessing','Elevation values are delivered in metres'],'semantic_limits':['Format guidance does not define polygon inclusion; this package discloses both pixel-centre methods']}
]
dump(SLOT/'source_candidates_increment_037.json',{'schema_version':1,'slot_id':'height_difference_2','verified_on':'2026-07-22','candidate_count':4,'promoted_count':4,'held_count':0,'promoted_average_source_confidence_percent':100.0,'score_semantics':'Official EA WCS persistence, GetCoverage and GeoTIFF contracts; parcel numeric confidence remains 96%.','candidates':candidates,'aggregate_source_candidate_count':66,'aggregate_promoted_source_contract_count':66,'fake_data':False,'final_ready':False})

examples=[]
for idx,row_no in enumerate([30762,46142,61522],start=16):
    r=rows[row_no]; a=r['primary_1m']['stats']; b=r['crosscheck_2m']['stats']; c=ctx[row_no]
    examples.append({'example_id':f'HD2-DIST-{idx:03d}','row_no':row_no,'scenario':'INDEPENDENT_PIXEL_MASK_DISTRIBUTION_AND_PLANE_GRADIENT_AUDIT','parcel_id':r['parcel_id'],'longitude':c['lon'],'latitude':c['lat'],'bng_easting_m':c['e'],'bng_northing_m':c['n'],'ons_lad25_code':c['lad'],'ons_lad25_name':c['name'],'ea_os_grid_5km_tile':c['tile'],'hmlr_inspire_id':r['hmlr_inspire_id'],'polygon_area_m2':r['polygon_area_m2'],'hmlr_polygon_state':'UNIQUE_NATIVE_EPSG27700_POINT_IN_POLYGON_PASS','height_min_m':a['min_m'],'height_max_m':a['max_m'],'height_difference_m':a['difference_m'],'height_mean_m':a['mean_m'],'height_median_m':a['median_m'],'height_stddev_m':a['stddev_m'],'height_p10_m':a['p10_m'],'height_p25_m':a['p25_m'],'height_p75_m':a['p75_m'],'height_p90_m':a['p90_m'],'height_iqr_m':a['iqr_m'],'height_mad_m':a['mad_m'],'plane_slope_percent':a['slope_percent'],'plane_slope_degrees':a['slope_degrees'],'plane_descent_aspect_degrees':a['descent_aspect_degrees'],'plane_residual_rmse_m':a['plane_residual_rmse_m'],'crosscheck_2m_stddev_m':b['stddev_m'],'crosscheck_2m_iqr_m':b['iqr_m'],'crosscheck_2m_slope_percent':b['slope_percent'],'mask_disagreement_pixel_count_1m':r['primary_1m']['mask_disagreement_count'],'mask_disagreement_pixel_count_2m':r['crosscheck_2m']['mask_disagreement_count'],'distribution_gradient_state':r['state'],'ea_dtm_1m_sha256':r['primary_1m']['response_sha256'],'ea_dtm_2m_sha256':r['crosscheck_2m']['response_sha256'],'height_result_confidence_percent':96,'result_state':'OFFICIAL_NUMERIC_RESULT_WITH_DUAL_MASK_DISTRIBUTION_AND_GRADIENT_AUDIT','official_numeric_row':True,'business_row':False})
dump(SLOT/'examples_increment_037.json',{'schema_version':2,'slot_id':'height_difference_2','verified_on':'2026-07-22','example_type':'DUAL_MASK_PIXEL_DISTRIBUTION_AND_PLANE_GRADIENT','prepared_example_count':3,'numeric_result_count':3,'business_row_count':0,'examples':examples,'aggregate_prepared_example_count':42,'distribution_gradient_example_count':3,'all_rows_pass':True,'fake_data':False,'final_ready':False})

ops=[]
def op(no,status,stage,typ,badge,source,details,blocker=None,url=None): ops.append({'operation_no':no,'status':status,'stage':stage,'operation_type':typ,'display_badge':badge,'source_name':source,'source_url':url,'details_summary':details,'accuracy_score_4':'4/4 evidence-backed' if status=='completed' else 'pending exact receipt','blocker':blocker,'is_new_operation':True})
global_rows=[('canonical_036_readback','INCREMENT_036_READBACK_PASS','Canonical manifest','666 operations, 58 sources and 39 examples confirmed.'),('f_host_receipt_recheck','F_HOST_RECEIPT_STILL_ABSENT','Guarded F-host recovery','No recovery output exists; final_ready remains false.'),('wcs_1m_persistent_endpoint','EA_1M_WCS_PERSISTENT','EA persistent WCS','Current 1m endpoint revalidated.'),('wcs_2m_persistent_endpoint','EA_2M_WCS_PERSISTENT','EA persistent WCS','Current 2m endpoint revalidated.'),('exact_polygon_hash_gate','HMLR_GEOMETRY_HASH_PRESERVED','HMLR exact polygons','Three exact feature hashes preserved.'),('dual_mask_contract','DUAL_PIXEL_MASK_METHODS','Rasterio and Shapely','Two independent pixel-centre masks executed.'),('distribution_contract','DISTRIBUTION_STATS_DEFINED','NumPy distribution audit','Mean, median, stddev, P10/P25/P75/P90, IQR and MAD computed.'),('gradient_contract','PLANE_GRADIENT_DEFINED','Least-squares plane audit','dz/dE, dz/dN, slope, aspect and residual RMSE computed.')]
for i,x in enumerate(global_rows): op(667+i,'completed','distribution_gradient',x[0],x[1],x[2],x[3])
no=675
for row_no in [30762,46142,61522]:
    r=rows[row_no]; a=r['primary_1m']; b=r['crosscheck_2m']
    items=[('primary_download',f'ROW_{row_no}_1M_REDOWNLOAD','EA 1m WCS',f"1m GeoTIFF re-downloaded; {a['response_bytes']} bytes."),('primary_sha',f'ROW_{row_no}_1M_SHA_MATCH','EA 1m WCS','1m SHA-256 exactly matches increment 034.'),('mask_a',f'ROW_{row_no}_RASTERIO_MASK','Rasterio geometry_mask',f"Selected {a['geometry_mask_count']} pixel centres."),('mask_b',f'ROW_{row_no}_SHAPELY_MASK','Shapely Polygon.covers',f"Selected {a['manual_covers_count']} pixel centres."),('mask_equality',f'ROW_{row_no}_MASKS_IDENTICAL','Dual mask gate',f"Mask disagreement count {a['mask_disagreement_count']}."),('distribution_1m',f'ROW_{row_no}_1M_DISTRIBUTION','EA 1m distribution',f"Stddev {a['stats']['stddev_m']} m; IQR {a['stats']['iqr_m']} m; MAD {a['stats']['mad_m']} m."),('gradient_1m',f'ROW_{row_no}_1M_GRADIENT','EA 1m plane',f"Slope {a['stats']['slope_percent']}%; residual RMSE {a['stats']['plane_residual_rmse_m']} m."),('crosscheck_download_sha',f'ROW_{row_no}_2M_SHA_MATCH','EA 2m WCS','2m GeoTIFF re-downloaded and SHA-256 matched increment 034.'),('distribution_2m',f'ROW_{row_no}_2M_DISTRIBUTION','EA 2m distribution',f"Stddev {b['stats']['stddev_m']} m; IQR {b['stats']['iqr_m']} m."),('gradient_2m',f'ROW_{row_no}_2M_GRADIENT','EA 2m plane',f"Slope {b['stats']['slope_percent']}%; residual RMSE {b['stats']['plane_residual_rmse_m']} m."),('numeric_preservation',f'ROW_{row_no}_NUMERIC_PRESERVED','Numeric gate',f"Published difference {a['stats']['difference_m']} m unchanged; confidence 96%. ")]
    for x in items: op(no,'completed','distribution_gradient',x[0],x[1],x[2],x[3]); no+=1
op(708,'pending','runner_gate','f_host_guarded_recovery','F_HOST_RECEIPT_PENDING','Guarded F-host recovery','Final F-host receipt remains pending; no production row written.','F_HOST_GUARDED_RECOVERY_NOT_EXECUTED_ON_F_HOST')
dump(SLOT/'operations_increment_037.json',{'schema_version':4,'slot_id':'height_difference_2','generated_at':NOW,'planned_operation_count':724,'completed_operation_count':669,'blocked_operation_count':1,'pending_operation_count':7,'batch_operation_percent':92.40,'batch_percent_increase':0.32,'overall_completion_percent':95,'percent_increase':2,'operations':ops,'new_operation_count':42,'new_completed_count':41,'new_pending_count':1,'official_numeric_rows_written':3,'business_rows_written':0,'fake_data':False,'final_ready':False})

progress={'schema_version':1,'slot_id':'height_difference_2','updated_at':NOW,'research_increment_id':'037_dual_mask_distribution_and_gradient_audit_20260722','planned_operation_count':724,'completed_operation_count':669,'blocked_operation_count':1,'pending_operation_count':7,'batch_operation_percent':92.40,'batch_percent_increase':0.32,'overall_completion_percent':95,'percent_increase':2,'source_candidate_count':66,'source_contracts_upgraded':66,'source_freshness_revalidated':66,'new_source_candidate_count':4,'new_source_promoted_count':4,'new_source_average_confidence_percent':100.0,'prepared_example_count':42,'new_prepared_example_count':3,'exact_point_rows_written':3,'exact_hmlr_polygon_rows_written':3,'official_numeric_rows_written':3,'measured_parcel_rows_written':3,'robustness_example_rows_written':3,'composite_lineage_rows_written':3,'distribution_gradient_rows_written':3,'dual_mask_pass_rows_written':3,'actual_business_rows_written':0,'website_operation_rows_written':708,'website_source_rows_written':62,'website_example_rows_written':42,'numeric_result_confidence_percent':96,'distribution_gradient_runtime_state':'PASS_DUAL_MASK_AND_SHA_REPLAY_3_OF_3','live_http_browser_state':'FINAL_037_RETEST_PENDING','runner_execution_state':'repository_runtime_measurement_lineage_browser_distribution_pass_guarded_f_host_recovery_not_executed','blocker':'F_HOST_GUARDED_RECOVERY_PENDING','final_ready':False,'fake_data':False,'db_write':False,'migration':False,'production_deploy':False}
dump(SLOT/'progress_increment_037.json',progress)

m=load(SLOT/'operations_manifest.json'); m['updated_at']=NOW
for key,val in [('operation_files','operations_increment_037.json'),('source_candidate_files','source_candidates_increment_037.json'),('example_files','examples_increment_037.json')]:
    if val not in m[key]: m[key].append(val)
m.update({'expected_visible_operation_rows':708,'expected_visible_source_rows':62,'expected_visible_example_rows':42,'progress_file':'progress_increment_037.json','final_ready':False})
if 'distribution_gradient_runtime_037.json' not in m.setdefault('runtime_evidence_files',[]): m['runtime_evidence_files'].append('distribution_gradient_runtime_037.json')
m['pending_runtime_evidence_files']=['port_8012_web_acceptance_final_037.json']; dump(SLOT/'operations_manifest.json',m)

dump(DOC/'research/037_dual_mask_distribution_and_gradient_audit_20260722.json',{'schema_version':1,'slot_id':'height_difference_2','generated_at':NOW,'scope':'OFFICIAL_WCS_SHA_REPLAY_DUAL_PIXEL_MASK_DISTRIBUTION_AND_PLANE_GRADIENT','official_sources':[x['source_url'] for x in candidates],'runtime_sha_source':'distribution_gradient_runtime_037.json','rows':runtime['rows'],'official_numeric_rows_written':3,'business_rows_written':0,'fake_data':False,'final_ready':False})
checks=['slot_scope','operation_increment_count_42','operation_sequence_667_708','manifest_operation_rows_708','manifest_source_rows_62','manifest_example_rows_42','four_official_source_contracts','all_1m_response_sha_matches','all_2m_response_sha_matches','all_crs_epsg27700','all_dual_masks_identical','all_pixel_counts_preserved','all_min_max_difference_preserved','distribution_statistics_3_rows','plane_gradient_statistics_3_rows','numeric_results_preserved','result_confidence_96_preserved','business_rows_zero','fake_data_false','final_ready_false']
val={'schema_version':1,'slot_id':'height_difference_2','validated_at':NOW,'checks':[{'check':x,'state':'PASS'} for x in checks]+[{'check':'final_037_live_http_browser_acceptance','state':'NOT_RUN','observed':'package_retest_pending'},{'check':'f_host_guarded_recovery','state':'NOT_RUN','observed':'not_executed'}],'pass_count':20,'not_run_count':2,'fail_count':0,'official_numeric_rows_written':3,'business_rows_written':0,'fake_data':False,'final_ready':False}; dump(DOC/'validation/041_distribution_gradient_web_package_20260722.json',val)

p=SLOT/'index.html'; html=p.read_text(encoding='utf-8')
repls=[('min-width:5000px','min-width:6200px'),('Canlı Chromium kabulü PASS; exact EA composite survey lineage ve tarihsel transform/geoid kayıtları satır bazında görünür.','Canlı Chromium kabulü PASS; exact EA composite survey lineage, çift piksel-maskesi, dağılım ve parcel-scale gradient kayıtları satır bazında görünür.'),('<th>Lineage durumu</th><th>Sonuç güveni</th>','<th>Lineage durumu</th><th>Stddev m</th><th>P10 m</th><th>P25 m</th><th>P75 m</th><th>P90 m</th><th>IQR m</th><th>MAD m</th><th>Eğim %</th><th>Eğim derece</th><th>İniş yönü °</th><th>Plane residual RMSE m</th><th>2 m stddev m</th><th>2 m IQR m</th><th>2 m eğim %</th><th>Mask farkı 1m/2m</th><th>Dağılım/gradient durumu</th><th>Sonuç güveni</th>'),("['Composite lineage',s.composite_lineage_runtime_state??'unknown','ok'],['Canlı HTTP/DOM'","['Composite lineage',s.composite_lineage_runtime_state??'unknown','ok'],['Dağılım/gradient',s.distribution_gradient_runtime_state??'unknown','ok'],['Canlı HTTP/DOM'"),('<td>${esc(x.composite_lineage_state)}</td><td>${esc(confidence)}</td>','<td>${esc(x.composite_lineage_state)}</td><td>${esc(x.height_stddev_m)}</td><td>${esc(x.height_p10_m)}</td><td>${esc(x.height_p25_m)}</td><td>${esc(x.height_p75_m)}</td><td>${esc(x.height_p90_m)}</td><td>${esc(x.height_iqr_m)}</td><td>${esc(x.height_mad_m)}</td><td>${esc(x.plane_slope_percent)}</td><td>${esc(x.plane_slope_degrees)}</td><td>${esc(x.plane_descent_aspect_degrees)}</td><td>${esc(x.plane_residual_rmse_m)}</td><td>${esc(x.crosscheck_2m_stddev_m)}</td><td>${esc(x.crosscheck_2m_iqr_m)}</td><td>${esc(x.crosscheck_2m_slope_percent)}</td><td>${esc(x.mask_disagreement_pixel_count_1m)} / ${esc(x.mask_disagreement_pixel_count_2m)}</td><td>${esc(x.distribution_gradient_state)}</td><td>${esc(confidence)}</td>'),('ve ${s.composite_lineage_rows_written||0} lineage satırı görünür.','ve ${s.composite_lineage_rows_written||0} lineage ve ${s.distribution_gradient_rows_written||0} dağılım/gradient satırı görünür.')]
for old,new in repls:
    if old not in html: raise RuntimeError('index token missing: '+old[:80])
    html=html.replace(old,new,1)
p.write_text(html,encoding='utf-8')
