page_key: AAYS_REAL_TOPOGRAPHY_PRODUCT
branch: aays-runner-v17-icon-work-20260603-232706
automation: docs/chatgpt_status/AAYS_REAL_TOPOGRAPHY_PRODUCT/automation/RUN_DISTANCE_047_SELF_CONTAINED_REPAIR.ps1
retry: 20260615T0145Z
status: QUEUED_FOR_SINGLE_SHARED_RUNNER
source_global_slot: docs/chatgpt_status/AAYS_REAL_TOPOGRAPHY_PRODUCT/control/global_slot_request_20260615T0030Z.md
expected_report: docs/chatgpt_status/AAYS_REAL_TOPOGRAPHY_PRODUCT/reports/terrayield_047_distance_property_types_apply_patch_smoke_<timestamp>.md
parallelism: single_page_task_only_no_conflicting_db_or_runner_resource
notes: create fresh queue pickup signal because current-task refresh attempts are blocked and runner output is still missing
