const SK="deutsch_tests_instant_v1";
const ORDER=["tf","fill","mc","wordMatch","phraseMatch","prep"];
const TIT={tf:"A. Richtig/Falsch",fill:"B. Lückentext · 6 Optionen",mc:"C. Test · 5 Optionen",wordMatch:"D. C1/C2-Wörter mit deutscher Bedeutung verbinden",phraseMatch:"E. Kalıp ifadeleri / Kollokationen verbinden",prep:"F. Präposition einsetzen"};
const PREPS=["an","auf","aus","bei","durch","für","gegen","gegenüber","in","mit","nach","unter","von","vom","vor","zu","zur","am","im","zum","wegen","aufgrund","als","über"];
let selected="",selectedCategory="",current=[],meta={},log=new Map(),res=[],hangWords=[],hangIndex=0,hangScore=0;
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;'}[c]));
const norm=s=>String(s||"").trim().replace(/[.,;:!?]+$/," ").replace(/\s+/g," ").trim().toLocaleLowerCase("de-DE");
function sh(a){a=a.slice();for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function hide(){["quiz","hang","shared","lesson"].forEach(x=>$(x)&&$(x).classList.add("hide"));$("start").classList.add("hide")}
function menu(){["quiz","hang","shared","lesson"].forEach(x=>$(x)&&$(x).classList.add("hide"));$("start").classList.remove("hide"); if(selectedCategory) renderTests(selectedCategory); else renderCategoryChoice()}
function catOf(t){return t.category==="Genel Grammer"?"Genel Grammer":"Schreiben Fehlern"}
function allTests(){return window.DEUTSCH_TESTS||{}}
function pool(t){let p=[];(t.words||[]).forEach(x=>p.push(x));(t.hang||[]).forEach(x=>p.push(x));(t.fill||[]).forEach(x=>p.push(x[1]));(t.wordMatch||[]).forEach(x=>{p.push(x[0]);p.push(x[1])});(t.phraseMatch||[]).forEach(x=>{p.push(x[0]);p.push(x[1])});return [...new Map(p.filter(Boolean).map(x=>[norm(x),x])).values()]}
function opts(ans,p,n){let clean=[...new Map((p||[]).filter(Boolean).map(x=>[norm(x),x])).values()].filter(x=>norm(x)!==norm(ans));return sh([ans].concat(sh(clean).slice(0,n-1)))}
function bank(t){let g={tf:[],fill:[],mc:[],wordMatch:[],phraseMatch:[],prep:[]},all=pool(t);
(t.tf||[]).forEach(x=>g.tf.push({g:"tf",typ:"tf",sec:TIT.tf,q:x[0],a:x[1]?"Richtig":"Falsch",tag:x[2]}));
(t.fill||[]).forEach(x=>g.fill.push({g:"fill",typ:"r",sec:TIT.fill,q:x[0],a:x[1],op:opts(x[1],all,6),tag:x[2]}));
(t.mc||[]).forEach(x=>g.mc.push({g:"mc",typ:"r",sec:TIT.mc,q:x[0],a:x[1][x[2]],op:x[1].slice(0,5),tag:x[3]}));
let wm=t.wordMatch||[];wm.forEach((x,i)=>g.wordMatch.push({g:"wordMatch",typ:"r",sec:TIT.wordMatch,q:"Welche deutsche Bedeutung passt zu: „"+x[0]+"“?",a:x[1],op:opts(x[1],wm.filter((_,j)=>j!==i).map(y=>y[1]),5),tag:"Bedeutung"}));
let pm=t.phraseMatch||[];pm.forEach((x,i)=>g.phraseMatch.push({g:"phraseMatch",typ:"r",sec:TIT.phraseMatch,q:"Welche Ergänzung bildet eine korrekte Kollokation? „"+x[0]+" …“",a:x[1],op:opts(x[1],pm.filter((_,j)=>j!==i).map(y=>y[1]),5),tag:"Kollokation"}));
(t.prep||[]).forEach(x=>g.prep.push({g:"prep",typ:"r",sec:TIT.prep,q:x[0],a:x[1],op:opts(x[1],PREPS,6),tag:x[2]||"Präposition"}));
Object.keys(g).forEach(k=>g[k]=sh(g[k]));return g}
function build(t,n){let g=bank(t),base=Math.floor(n/ORDER.length),rem=n%ORDER.length,out=[];ORDER.forEach((k,i)=>out.push(...(g[k]||[]).slice(0,base+(i<rem?1:0))));return out}
function setControls(show){let c=$("modeControls"); if(c)c.classList.toggle("hide",!show)}
function renderCategoryChoice(){selectedCategory="";selected="";setControls(false);$("testList").innerHTML=`
  <h2>İlk olarak ana başlığı seç</h2>
  <p class="muted">Önce çalışma alanını seç. Sonra ilgili testleri, konu anlatımını veya harf kutucukları modunu açabilirsin.</p>
  <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px;margin-top:12px">
    <button class="opt" style="text-align:left" id="catGrammar"><b>Genel Grammer</b><br><span class="muted">Satzbau, Kasus, Artikel, Pronomen, Negation ve doğru gramerle yazma.</span></button>
    <button class="opt" style="text-align:left" id="catWrite"><b>Schreiben Fehlern</b><br><span class="muted">Mevcut kelime, kalıp, Präposition ve C1/C2 yazma hatası testleri.</span></button>
  </div>`;
  $("catGrammar").onclick=()=>renderTests("Genel Grammer");
  $("catWrite").onclick=()=>renderTests("Schreiben Fehlern");
}
function renderTests(cat){selectedCategory=cat;setControls(true);let entries=Object.entries(allTests()).filter(([k,t])=>catOf(t)===cat);if(!entries.length){$("testList").innerHTML='<p class="dberr">Bu ana başlık altında test bulunamadı.</p><button id="backCats">Ana başlıklara dön</button>';$("backCats").onclick=renderCategoryChoice;return}selected=entries[0][0];$("testList").innerHTML='<p><button class="ghost" id="backCats">← Ana başlıklara dön</button></p><h2>'+esc(cat)+'</h2><p class="muted">Şimdi bu ana başlık altındaki testi seç. Ardından konu anlatımı, test uzunluğu veya harf kutucukları modunu aç.</p>'+entries.map(([k,t],i)=>'<label class="opt"><input type="radio" name="tc" value="'+k+'" '+(i===0?'checked':'')+'> <b>'+esc(t.title)+'</b><br><span class="muted">'+esc(t.topic||"")+'</span></label>').join("");$("backCats").onclick=renderCategoryChoice;document.querySelectorAll('input[name="tc"]').forEach(e=>e.onchange=()=>selected=e.value)}
function init(){let tests=allTests();$("dbs").innerHTML='<b class="dbok">Sofortkontrolle aktiv</b>';renderCategoryChoice();$("btnShort").onclick=()=>start(15);$("btnMedium").onclick=()=>start(25);$("btnLong").onclick=()=>start(35);$("btnHang").onclick=startHangman;$("btnGrade").onclick=grade;$("btnDownload").onclick=downloadReport;$("btnBack").onclick=menu;$("btnBack2").onclick=menu;$("btnCheckHang").onclick=checkHang;$("btnNextHang").onclick=nextHang;$("btnClearLocal").onclick=clearLocal;hist()}
function start(n){if(!selected||!allTests()[selected]){renderCategoryChoice();return}let t=allTests()[selected];current=build(t,n);log=new Map();res=[];meta={title:t.title,topic:t.topic,len:n===15?"Az":n===25?"Orta":"Uzun",category:catOf(t),date:new Date().toISOString()};hide();$("quiz").classList.remove("hide");$("rep").classList.add("hide");$("ttl").textContent=t.title;$("meta").textContent="Ana başlık: "+meta.category+" · Thema: "+t.topic+" · "+meta.len+" · "+current.length+" Fragen · şık seçildiği anda kontrol edilir.";$("wb").innerHTML=(t.words||[]).map(w=>'<span class="pill">'+esc(w)+'</span>').join("");render();progress()}
function render(){let h="",num=1;ORDER.forEach(k=>{let qs=current.filter(q=>q.g===k);if(!qs.length)return;h+='<section style="border:1px solid #e5ded4;border-radius:14px;padding:12px;margin:14px 0;background:#fffdf9"><h3>'+esc(TIT[k])+' <span class="muted">('+qs.length+')</span></h3>';qs.forEach(q=>{q.id="q_"+(num-1);h+='<div class="q"><div class="qt">'+num+'. '+esc(q.q)+'</div>';if(q.typ==="tf")h+='<label class="opt"><input type="radio" name="'+q.id+'" value="true"> Richtig</label><label class="opt"><input type="radio" name="'+q.id+'" value="false"> Falsch</label>';else h+=q.op.map((o,j)=>'<label class="opt"><input type="radio" name="'+q.id+'" value="'+j+'"> '+String.fromCharCode(65+j)+') '+esc(o)+'</label>').join("");h+='<p class="muted">Fokus: '+esc(q.tag)+'</p><div id="fb_'+q.id+'"></div></div>';num++});h+='</section>'});$("qs").innerHTML=h;document.querySelectorAll("#qs input").forEach(e=>e.onchange=()=>{let q=current.find(x=>x.id===e.name);if(q)instant(q);progress()})}
function val(q){let c=document.querySelector('input[name="'+q.id+'"]:checked');return c?c.value:""}
function shown(q){let v=val(q);if(v==="")return "—";return q.typ==="tf"?(v==="true"?"Richtig":"Falsch"):q.op[Number(v)]}
function mark(q,ok){document.querySelectorAll('input[name="'+q.id+'"]').forEach(inp=>{let lab=inp.closest("label");lab.classList.remove("ok","no");let txt=q.typ==="tf"?(inp.value==="true"?"Richtig":"Falsch"):q.op[Number(inp.value)];if(norm(txt)===norm(q.a))lab.classList.add("ok")});let c=document.querySelector('input[name="'+q.id+'"]:checked');if(c&&!ok)c.closest("label").classList.add("no")}
function instant(q){let u=shown(q),ok=norm(u)===norm(q.a);mark(q,ok);$("fb_"+q.id).innerHTML=ok?'<p class="dbok"><b>Richtig.</b></p>':'<p class="dberr"><b>Falsch.</b> Richtig: <b>'+esc(q.a)+'</b></p>';if(!ok){let key=norm(q.sec+"|"+q.q+"|"+u+"|"+q.a);if(!log.has(key))log.set(key,{section:q.sec,tag:q.tag,q:q.q,u:u,a:q.a})}}
function check(q){let u=shown(q),ok=u!=="—"&&norm(u)===norm(q.a);if(u!=="—")mark(q,ok);return{section:q.sec,tag:q.tag,q:q.q,u:u,a:q.a,ok:ok}}
function progress(){let a=current.filter(q=>val(q)).length,t=current.length;$("pt").textContent=a+"/"+t+" bearbeitet";$("pb").style.width=t?(a/t*100)+"%":"0%"}
function local(){try{return JSON.parse(localStorage.getItem(SK)||"[]")}catch(e){return[]}}
function save(r){let h=local();h.unshift(r);localStorage.setItem(SK,JSON.stringify(h.slice(0,50)))}
function promptText(w){if(!w.length)return "Bu testte yanlışım yok.";let a=["Aşağıdaki Almanca C1/C2 kelime, kalıp ifade ve Präposition yanlışlarımı Türkçe açıkla. Her madde için doğru cevabın anlamını, benim cevabımın neden yanlış olduğunu, doğru kalıbı ve iki C1 Almanca örnek cümleyi ver.",""];w.forEach((x,i)=>a.push((i+1)+". Bölüm: "+x.section,"Soru: "+x.q,"Benim cevabım: "+x.u,"Doğru cevap: "+x.a,""));return a.join("\n")}
function grade(){res=current.map(check);let correct=res.filter(x=>x.ok).length;res.filter(x=>!x.ok&&x.u!=="—").forEach(x=>{let k=norm(x.section+"|"+x.q+"|"+x.u+"|"+x.a);if(!log.has(k))log.set(k,{section:x.section,tag:x.tag,q:x.q,u:x.u,a:x.a})});let wrong=[...log.values()],pct=Math.round(correct/res.length*100),r={...meta,score:correct,total:res.length,percent:pct,wrong:wrong};save(r);let text=promptText(wrong);$("out").innerHTML='<p><b>'+correct+'/'+res.length+' richtig – '+pct+'%</b></p><p><span class="dbok">Yanlışlar tekilleştirildi; aynı hata sadece bir kez görünür.</span></p><h3>ChatGPT’ye kopyalanacak metin</h3><textarea id="wrongPrompt" style="width:100%;min-height:230px;border:1px solid #cfc9bf;border-radius:10px;padding:10px;font:14px Arial">'+esc(text)+'</textarea><p><button id="copyPrompt">Metni kopyala</button></p><h3>Tekil yanlış listesi</h3>'+(wrong.length?wrong.map((x,i)=>'<div class="wrong"><b>Fehler '+(i+1)+'</b><p>'+esc(x.q)+'</p><p>Deine Antwort: '+esc(x.u)+'</p><p>Richtig: '+esc(x.a)+'</p></div>').join(""):'<p class="ok">Keine Fehler.</p>');$("rep").classList.remove("hide");$("copyPrompt").onclick=()=>{let t=$("wrongPrompt");t.select();navigator.clipboard&&navigator.clipboard.writeText(t.value)};$("rep").scrollIntoView({behavior:"smooth"});hist()}
function hist(){let h=local();window.currentHist=h;$("hist").innerHTML=h.length?h.map((r,i)=>'<div class="hist"><b>'+esc(r.title)+'</b><br><span class="muted">'+new Date(r.date).toLocaleString()+' · '+esc(r.category||"")+' · '+esc(r.len)+' · '+r.score+'/'+r.total+' · '+r.percent+'%</span><p><button data-h="'+i+'">Göster</button></p></div>').join(""):'<p class="muted">Henüz kayıt yok.</p>';document.querySelectorAll("[data-h]").forEach(b=>b.onclick=()=>{hide();showResult(window.currentHist[Number(b.dataset.h)])})}
function showResult(r){$("shared").classList.remove("hide");let text=promptText(r.wrong||[]);$("so").innerHTML='<p><b>'+esc(r.title)+'</b></p><p><b>'+r.score+'/'+r.total+' richtig – '+r.percent+'%</b></p><textarea style="width:100%;min-height:220px;border:1px solid #cfc9bf;border-radius:10px;padding:10px;font:14px Arial">'+esc(text)+'</textarea>'}
function clearLocal(){if(confirm("Bu cihazdaki local geçmiş silinsin mi?")){localStorage.removeItem(SK);hist()}}
function startHangman(){if(!selected||!allTests()[selected]){renderCategoryChoice();return}let t=allTests()[selected];hangWords=sh(t.hang||[]);hangIndex=0;hangScore=0;hide();$("hang").classList.remove("hide");$("ht").textContent="Harf kutucukları: "+t.title;showHang()}
function showHang(){let w=hangWords[hangIndex]||"";$("hh").textContent=(hangIndex+1)+"/"+hangWords.length;$("hm").textContent=w.replace(/[A-Za-zÄÖÜäöüß]/g,"_");$("hi").value="";$("hi").className="";$("hr").innerHTML=""}
function checkHang(){let w=hangWords[hangIndex]||"",ok=norm($("hi").value)===norm(w);$("hi").classList.add(ok?"ok":"no");if(ok)hangScore++;$("hr").innerHTML=ok?'<p class="dbok">Richtig.</p>':'<p class="dberr">Falsch. Richtig: <b>'+esc(w)+'</b></p>'}
function nextHang(){if(hangIndex<hangWords.length-1){hangIndex++;showHang()}else{$("hr").innerHTML='<p><b>Fertig: '+hangScore+'/'+hangWords.length+'</b></p><button id="hangRestart">Neu starten</button>';$("hangRestart").onclick=startHangman}}
function downloadReport(){if(!res.length){grade();return}let blob=new Blob([promptText([...log.values()])],{type:"text/plain;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="deutsch_tests_fehler.txt";a.click();URL.revokeObjectURL(a.href)}
document.addEventListener("DOMContentLoaded",()=>{try{init()}catch(e){console.error(e);$("testList").innerHTML='<p class="dberr">Uygulama başlatılamadı: '+esc(e.message)+'</p>'}});
