const STORAGE_KEY = "deutsch_tests_1_history_grouped_v1";
const GROUP_ORDER = ["tf", "fill", "mc", "wordMatch", "phraseMatch", "prep"];
const GROUP_TITLES = {
  tf: "A. Richtig/Falsch",
  fill: "B. Lückentext · 6 Optionen",
  mc: "C. Test · 5 Optionen",
  wordMatch: "D. C1/C2-Wörter mit deutscher Bedeutung verbinden",
  phraseMatch: "E. Kalıp ifadeleri / Kollokationen verbinden",
  prep: "F. Präposition einsetzen"
};
const PREP_OPTIONS = ["an", "auf", "aus", "bei", "durch", "für", "gegen", "gegenüber", "in", "mit", "nach", "unter", "von", "vom", "vor", "zu", "zur", "am"];
let selected = "t4";
let current = [];
let meta = {};
let results = [];
let hangWords = [];
let hangIndex = 0;
let hangScore = 0;
const $ = id => document.getElementById(id);
function esc(s){return String(s).replace(/[&<>']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;'}[ch]));}
function norm(s){return String(s||"").trim().replace(/[.,;:!?]+$/," ").replace(/\s+/g," ").trim().toLocaleLowerCase("de-DE");}
function shuffle(arr){const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function makeId(){return Date.now().toString(36)+Math.random().toString(36).slice(2,10);}
function hideAll(){["quiz","hang","shared"].forEach(id=>$(id).classList.add("hide"));$("start").classList.add("hide");}
function backToMenu(){["quiz","hang","shared"].forEach(id=>$(id).classList.add("hide"));$("start").classList.remove("hide");}
function optionPool(test){const pool=[];(test.words||[]).forEach(x=>pool.push(x));(test.hang||[]).forEach(x=>pool.push(x));(test.fill||[]).forEach(x=>pool.push(x[1]));(test.wordMatch||[]).forEach(x=>{pool.push(x[0]);pool.push(x[1]);});(test.phraseMatch||[]).forEach(x=>{pool.push(x[0]);pool.push(x[1]);});return [...new Map(pool.filter(Boolean).map(x=>[norm(x),x])).values()];}
function makeOptions(answer,pool,count){const clean=[...new Map((pool||[]).filter(Boolean).map(x=>[norm(x),x])).values()].filter(x=>norm(x)!==norm(answer));return shuffle([answer].concat(shuffle(clean).slice(0,count-1)));}
function makeFillOptions(answer,test){return makeOptions(answer,optionPool(test),6);}
function makePrepOptions(answer){return makeOptions(answer,PREP_OPTIONS,6);}
function makeBank(test){const groups={tf:[],fill:[],mc:[],wordMatch:[],phraseMatch:[],prep:[]};
(test.tf||[]).forEach(x=>groups.tf.push({group:"tf",type:"tf",section:GROUP_TITLES.tf,q:x[0],a:x[1]?"Richtig":"Falsch",bool:x[1],tag:x[2]}));
(test.fill||[]).forEach(x=>groups.fill.push({group:"fill",type:"radio",section:GROUP_TITLES.fill,q:x[0],a:x[1],options:makeFillOptions(x[1],test),tag:x[2]}));
(test.mc||[]).forEach(x=>groups.mc.push({group:"mc",type:"radio",section:GROUP_TITLES.mc,q:x[0],a:x[1][x[2]],options:x[1].slice(0,5),tag:x[3]}));
const wordDefs=test.wordMatch||[];wordDefs.forEach((x,i)=>{const defs=wordDefs.filter((_,j)=>j!==i).map(y=>y[1]);groups.wordMatch.push({group:"wordMatch",type:"radio",section:GROUP_TITLES.wordMatch,q:"Welche deutsche Bedeutung passt zu: „"+x[0]+"“?",a:x[1],options:makeOptions(x[1],defs,5),tag:"Bedeutung"});});
const phrasePairs=test.phraseMatch||[];phrasePairs.forEach((x,i)=>{const parts=phrasePairs.filter((_,j)=>j!==i).map(y=>y[1]);groups.phraseMatch.push({group:"phraseMatch",type:"radio",section:GROUP_TITLES.phraseMatch,q:"Welche Ergänzung bildet eine korrekte Kollokation? „"+x[0]+" …“",a:x[1],options:makeOptions(x[1],parts,5),tag:"Kollokation"});});
(test.prep||[]).forEach(x=>groups.prep.push({group:"prep",type:"radio",section:GROUP_TITLES.prep,q:x[0],a:x[1],options:makePrepOptions(x[1]),tag:x[2]||"Präposition"}));
Object.keys(groups).forEach(k=>groups[k]=shuffle(groups[k]));return groups;}
function buildQuestions(test,count){const groups=makeBank(test);const base=Math.floor(count/GROUP_ORDER.length);const rem=count%GROUP_ORDER.length;const out=[];GROUP_ORDER.forEach((key,i)=>{const need=base+(i<rem?1:0);out.push(...(groups[key]||[]).slice(0,need));});return out;}
function init(){const tests=window.DEUTSCH_TESTS||{};$("dbs").innerHTML='<b class="dbok">Gruppierter Modus aktiv</b>';$("testList").innerHTML=Object.entries(tests).map(([key,test],i)=>'<label class="opt"><input type="radio" name="tc" value="'+key+'" '+(i===0?'checked':'')+'> <b>'+esc(test.title)+'</b><br><span class="muted">'+esc(test.topic)+'</span></label>').join("");document.querySelectorAll('input[name="tc"]').forEach(el=>el.addEventListener("change",()=>{selected=el.value;}));$("btnShort").addEventListener("click",()=>startQuiz(15));$("btnMedium").addEventListener("click",()=>startQuiz(25));$("btnLong").addEventListener("click",()=>startQuiz(35));$("btnHang").addEventListener("click",startHangman);$("btnGrade").addEventListener("click",grade);$("btnDownload").addEventListener("click",downloadReport);$("btnBack").addEventListener("click",backToMenu);$("btnBack2").addEventListener("click",backToMenu);$("btnCheckHang").addEventListener("click",checkHang);$("btnNextHang").addEventListener("click",nextHang);$("btnClearLocal").addEventListener("click",clearLocal);historyRender();}
function startQuiz(count){const test=window.DEUTSCH_TESTS[selected];current=buildQuestions(test,count);meta={shareId:makeId(),slug:test.slug,title:test.title,topic:test.topic,len:count===15?"Az":count===25?"Orta":"Uzun",date:new Date().toISOString()};hideAll();$("quiz").classList.remove("hide");$("rep").classList.add("hide");$("ttl").textContent=test.title;$("meta").textContent="Thema: "+test.topic+" · Länge: "+meta.len+" · Fragen: "+current.length+" · Aufbau: klare Gruppen, nur Inhalt des gewählten Tests.";$("wb").innerHTML=test.words.map(w=>'<span class="pill">'+esc(w)+'</span>').join("");renderQuestions();progress();}
function renderQuestions(){let html="";let number=1;GROUP_ORDER.forEach(groupKey=>{const groupQuestions=current.filter(q=>q.group===groupKey);if(!groupQuestions.length)return;html+='<section class="qgroup" style="border:1px solid #e5ded4;border-radius:14px;padding:12px;margin:14px 0;background:#fffdf9"><h3 style="margin:0 0 8px;color:#183642">'+esc(GROUP_TITLES[groupKey])+' <span class="muted">('+groupQuestions.length+')</span></h3>';groupQuestions.forEach(q=>{q.id="q_"+(number-1);html+='<div class="q"><div class="qt">'+number+'. '+esc(q.q)+'</div>';if(q.type==="radio"){html+=q.options.map((o,j)=>'<label class="opt"><input type="radio" name="'+q.id+'" value="'+j+'"> '+String.fromCharCode(65+j)+') '+esc(o)+'</label>').join("");}else if(q.type==="tf"){html+='<label class="opt"><input type="radio" name="'+q.id+'" value="true"> Richtig</label><label class="opt"><input type="radio" name="'+q.id+'" value="false"> Falsch</label>';}html+='<p class="muted">Fokus: '+esc(q.tag)+'</p></div>';number++;});html+='</section>';});$("qs").innerHTML=html;document.querySelectorAll("#qs input").forEach(el=>{el.addEventListener("input",progress);el.addEventListener("change",progress);});}
function userValue(q){const checked=document.querySelector('input[name="'+q.id+'"]:checked');return checked?checked.value:"";}
function mark(q,ok){document.querySelectorAll('input[name="'+q.id+'"]').forEach(input=>input.closest("label").classList.remove("ok","no"));const checked=document.querySelector('input[name="'+q.id+'"]:checked');if(checked)checked.closest("label").classList.add(ok?"ok":"no");}
function checkQuestion(q){const raw=userValue(q);let shown=raw||"—";let ok=false;if(q.type==="radio"){shown=raw===""?"—":q.options[Number(raw)];ok=norm(shown)===norm(q.a);}else if(q.type==="tf"){shown=raw===""?"—":(raw==="true"?"Richtig":"Falsch");ok=norm(shown)===norm(q.a);}mark(q,ok);return{section:q.section,tag:q.tag,q:q.q,u:shown,a:q.a,ok:ok};}
function progress(){const answered=current.filter(q=>userValue(q)).length;const total=current.length;$("pt").textContent=answered+"/"+total+" bearbeitet";$("pb").style.width=total?(answered/total*100)+"%":"0%";}
function localHistory(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");}catch(e){return[];}}
function saveLocal(result){const h=localHistory();h.unshift(result);localStorage.setItem(STORAGE_KEY,JSON.stringify(h.slice(0,50)));}
function encodeResult(obj){return encodeURIComponent(btoa(unescape(encodeURIComponent(JSON.stringify(obj)))));}
function decodeResult(str){return JSON.parse(decodeURIComponent(escape(atob(decodeURIComponent(str)))));}
async function grade(){results=current.map(checkQuestion);const correct=results.filter(r=>r.ok).length;const wrong=results.filter(r=>!r.ok);const percent=Math.round(correct/results.length*100);const result={...meta,score:correct,total:results.length,percent:percent,wrong:wrong};saveLocal(result);const link=location.origin+location.pathname+"#result="+encodeResult(result);$("out").innerHTML='<p><b>'+correct+'/'+results.length+' richtig – '+percent+'%</b></p><p><span class="dbok">Sonuç local kaydedildi.</span></p><p><input id="lnk" value="'+esc(link)+'" readonly onclick="this.select()"></p><button id="copyBtn">Link kopieren</button><h3>Falsche Antworten</h3>'+(wrong.length?wrong.map((x,i)=>'<div class="wrong"><b>Fehler '+(i+1)+'</b> <span class="pill">'+esc(x.section)+'</span><p>'+esc(x.q)+'</p><p>Deine Antwort: '+esc(x.u)+'</p><p>Richtig: '+esc(x.a)+'</p></div>').join(""):'<p class="ok">Keine Fehler.</p>');$("rep").classList.remove("hide");$("copyBtn").addEventListener("click",()=>{const input=$("lnk");input.select();if(navigator.clipboard)navigator.clipboard.writeText(input.value);});$("rep").scrollIntoView({behavior:"smooth"});historyRender();}
function historyRender(){const h=localHistory();window.currentHist=h;$("hist").innerHTML=h.length?h.map((r,i)=>'<div class="hist"><b>'+esc(r.title)+'</b><br><span class="muted">'+new Date(r.date).toLocaleString()+' · '+esc(r.len)+' · '+r.score+'/'+r.total+' · '+r.percent+'% · local</span><p><button data-hist="'+i+'">Göster</button></p></div>').join(""):'<p class="muted">Henüz kayıt yok.</p>';document.querySelectorAll("[data-hist]").forEach(btn=>btn.addEventListener("click",()=>{hideAll();showResult(window.currentHist[Number(btn.dataset.hist)]);}));}
function showResult(r){$("shared").classList.remove("hide");$("so").innerHTML='<p><b>'+esc(r.title||r.test_title)+'</b></p><p>'+esc(r.topic||'')+'</p><p><b>'+r.score+'/'+r.total+' richtig – '+r.percent+'%</b></p>'+((r.wrong&&r.wrong.length)?r.wrong.map((x,i)=>'<div class="wrong"><b>Fehler '+(i+1)+'</b><p>'+esc(x.q)+'</p><p>Deine Antwort: '+esc(x.u)+'</p><p>Richtig: '+esc(x.a)+'</p></div>').join(""):'<p class="ok">Keine Fehler.</p>');$("shared").scrollIntoView({behavior:"smooth"});}
function clearLocal(){if(confirm("Bu cihazdaki local geçmiş silinsin mi?")){localStorage.removeItem(STORAGE_KEY);historyRender();}}
function startHangman(){const test=window.DEUTSCH_TESTS[selected];hangWords=shuffle(test.hang||[]);hangIndex=0;hangScore=0;hideAll();$("hang").classList.remove("hide");$("ht").textContent="Adam asmaca: "+test.title;showHang();}
function showHang(){const word=hangWords[hangIndex]||"";$("hh").textContent=(hangIndex+1)+"/"+hangWords.length+" · Begriff vollständig schreiben";$("hm").textContent=word.replace(/[A-Za-zÄÖÜäöüß]/g,"_");$("hi").value="";$("hi").className="";$("hr").innerHTML="";}
function checkHang(){const word=hangWords[hangIndex]||"";const user=$("hi").value;const ok=norm(user)===norm(word);$("hi").classList.add(ok?"ok":"no");if(ok)hangScore++;$("hr").innerHTML=ok?'<p class="dbok">Richtig.</p>':'<p class="dberr">Falsch. Richtig: <b>'+esc(word)+'</b></p>';}
function nextHang(){if(hangIndex<hangWords.length-1){hangIndex++;showHang();}else{$("hr").innerHTML='<p><b>Fertig: '+hangScore+'/'+hangWords.length+'</b></p><button id="hangRestart">Neu starten</button>';$("hangRestart").addEventListener("click",startHangman);}}
function downloadReport(){if(!results.length){grade();return;}const wrong=results.filter(r=>!r.ok);const lines=["Deutsch Tests 1 Bericht",meta.title,""];wrong.forEach((x,i)=>lines.push((i+1)+". "+x.q,"Deine Antwort: "+x.u,"Richtig: "+x.a,""));const blob=new Blob([lines.join("\n")],{type:"text/plain;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="deutsch_tests_bericht.txt";a.click();URL.revokeObjectURL(a.href);}
document.addEventListener("DOMContentLoaded",()=>{try{init();if(location.hash.startsWith("#result=")){hideAll();showResult(decodeResult(location.hash.slice(8)));}}catch(e){console.error(e);$("testList").innerHTML='<p class="dberr">Uygulama başlatılamadı: '+esc(e.message)+'</p>';}});
