window.DEUTSCH_TESTS = window.DEUTSCH_TESTS || {};
window.DEUTSCH_TESTS.t11 = {
  slug: "grammatik_praepositionen_kasus_feste_verbindungen",
  title: "11. Grammatik, Präpositionen, Kasus und feste Verbindungen",
  topic: "Kasus · Präpositionen · Verbendstellung · feste Verbindungen · akademischer Stil",
  words: [
    "Präpositionen und Kasus",
    "der Bedarf an + Dativ",
    "Einfluss auf + Akkusativ",
    "Interesse an + Dativ",
    "Beitrag zu + Dativ",
    "Singular und Plural",
    "wegen des Bedarfs an",
    "Verbform und Satzstruktur",
    "Präpositionen und feste Verbindungen",
    "Nebensätze und Verbendstellung",
    "Auf diese Weise kann … gefördert werden.",
    "Herkunft mit aus statt von",
    "aufgrund vs. wegen",
    "in Bezug auf",
    "Funktion von in Bezug auf",
    "verfügen über",
    "Fortschritte erzielen",
    "Artikel, Endungen und Nomen",
    "an etwas teilhaben lassen",
    "zugunsten + Genitiv",
    "sich von etwas abwenden",
    "sich auf etwas auswirken",
    "bestehen in + Dativ",
    "Raum schaffen für + Akkusativ",
    "mit ihrer Hilfe",
    "auf diese Weise",
    "liegen in + Dativ",
    "zum Einsatz bringen",
    "Schutz vor + Dativ / Nomen",
    "im Umgang mit anderen sicherer werden",
    "den Grundstein für + Akkusativ legen",
    "Auswirkungen auf + Akkusativ",
    "im Kontakt mit + Dativ",
    "im Umgang mit + Dativ",
    "anstatt bei seiner Familie zu leben",
    "anstatt + Infinitiv mit zu",
    "sich ergeben"
  ],
  fill: [
    ["Wegen des ____ an qualifizierten Fachkräften müssen neue Ausbildungswege geschaffen werden.", "Bedarfs", "Genitiv nach wegen"],
    ["Der Bedarf ____ qualifizierten Fachkräften ist in vielen Branchen deutlich gestiegen.", "an", "Nomen + Präposition"],
    ["Medien können erheblichen Einfluss ____ die öffentliche Meinungsbildung ausüben.", "auf", "Akkusativ"],
    ["Ein frühes Interesse ____ wissenschaftlichen Fragen kann durch projektorientierten Unterricht geweckt werden.", "an", "Dativ"],
    ["Solche Maßnahmen leisten einen Beitrag ____ gesellschaftlichen Integration.", "zur", "zu + Dativ"],
    ["Bei der Herkunft aus einem Land verwendet man im Deutschen normalerweise nicht „von“, sondern ____.", "aus", "Herkunft"],
    ["Im formellen Stil wirkt ____ sachlicher und schriftsprachlicher als „wegen“.", "aufgrund", "Stil"],
    ["____ auf die gesellschaftliche Wirkung sozialer Medien ist eine differenzierte Analyse notwendig.", "In Bezug", "Sachliche Struktur"],
    ["Wer über ausgeprägte Sprachkenntnisse ____ kann, argumentiert meist sicherer.", "verfügt", "verfügen über"],
    ["Im akademischen Stil klingt „Fortschritte ____“ stärker als eine schwere Nominalkonstruktion.", "erzielen", "idiomatische Verbindung"],
    ["Bildung kann Menschen an gesellschaftlichen Prozessen ____ lassen.", "teilhaben", "teilhaben lassen"],
    ["Diese Entwicklung kann sich langfristig ____ das Konsumverhalten auswirken.", "auf", "sich auswirken auf"],
    ["Die zentrale Schwierigkeit besteht ____ der falschen Verbindung von Nomen, Präposition und Kasus.", "in", "bestehen in + Dativ"],
    ["Gute Schulen schaffen Raum ____ individuelle Entwicklung.", "für", "Akkusativ"],
    ["____ ihrer Hilfe können komplexe Verfahren schneller umgesetzt werden.", "Mit", "mit ihrer Hilfe"],
    ["Der Vorteil dieser Methode liegt ____ ihrer praktischen Anwendbarkeit.", "in", "liegen in + Dativ"],
    ["Geeignete Verfahren müssen systematisch zum Einsatz ____ werden.", "gebracht", "zum Einsatz bringen"],
    ["Ein funktionierendes Rechtssystem bietet Schutz ____ willkürlicher Benachteiligung.", "vor", "Schutz vor"],
    ["Im Umgang ____ anderen kann man an sozialer Sicherheit gewinnen.", "mit", "Dativ"],
    ["Frühe Förderung kann den Grundstein ____ spätere Sprachkenntnisse legen.", "für", "Akkusativ"],
    ["Digitale Medien können unmittelbare Auswirkungen ____ die Sprechentwicklung haben.", "auf", "Akkusativ"],
    ["____ bei seiner Familie zu leben, entschied er sich für ein WG-Zimmer.", "Anstatt", "Infinitiv mit zu"],
    ["Aus einem Auslandsaufenthalt können sich bessere Zukunftschancen ____.", "ergeben", "sich ergeben"],
    ["Auf diese Weise kann interkulturelle Kompetenz gezielt ____ werden.", "gefördert", "Passiv"],
    ["Ein Nebensatz mit „dass“ verlangt die finite Verbform am ____.", "Ende", "Verbendstellung"]
  ],
  mc: [
    ["Welche Formulierung ist grammatisch und idiomatisch korrekt?", ["wegen des Bedarfs an qualifizierten Fachkräften", "wegen der Bedarf nach qualifizierten Fachkräften", "wegen dem Bedarf auf qualifizierte Fachkräfte", "wegen den Bedarf an qualifizierte Fachkräften", "wegen Bedarf von qualifizierte Fachkräfte"], 0, "Kasus und Präposition"],
    ["Welche Verbindung ist korrekt?", ["Einfluss auf die Zuschauer ausüben", "Einfluss an die Zuschauer ausüben", "Einfluss über den Zuschauern ausüben", "Einfluss mit die Zuschauer ausüben", "Einfluss von die Zuschauer ausüben"], 0, "Einfluss auf + Akkusativ"],
    ["Welche Variante ist im formellen Stil vorzuziehen?", ["aufgrund zunehmender sozialer Ungleichheit", "wegen dem zunehmenden sozialen Ungleichheit", "von zunehmender sozialer Ungleichheit wegen", "durch die wegen zunehmende Ungleichheit", "wegen zunehmender sozialer Ungleichheit ist immer falsch"], 0, "aufgrund vs. wegen"],
    ["Welche Aussage zur Herkunft ist korrekt?", ["Bei der Herkunft aus einem Land verwendet man aus.", "Bei der Herkunft aus einem Land verwendet man grundsätzlich von.", "Aus ist bei Ländern immer unidiomatisch.", "Von ist sachlicher als aus, wenn man Herkunft ausdrückt.", "Aus darf nur bei Städten verwendet werden."], 0, "Herkunft"],
    ["Welche Struktur ist sachlich-präzise für argumentative Texte?", ["in Bezug auf die gesellschaftlichen Folgen", "bei Bezug mit gesellschaftlichen Folgen", "in Beziehung auf gesellschaftliche Folgen", "von Bezug zu gesellschaftlichen Folgen", "auf Bezug der gesellschaftlichen Folgen"], 0, "in Bezug auf"],
    ["Welche Verbindung muss als feste Einheit gelernt werden?", ["über ausreichende Mittel verfügen", "an ausreichende Mittel verfügen", "mit ausreichenden Mitteln verfügen", "für ausreichende Mittel verfügen", "aus ausreichenden Mitteln verfügen"], 0, "verfügen über"],
    ["Welche Formulierung ist idiomatisch?", ["Fortschritte erzielen", "Fortschritte machen ist immer falsch", "Fortschritte verursachen", "Fortschritte besetzen", "Fortschritte verfügen"], 0, "Fortschritte erzielen"],
    ["Welche Struktur ist korrekt?", ["an gesellschaftlichen Prozessen teilhaben lassen", "bei gesellschaftliche Prozesse teilhaben lassen", "auf gesellschaftlichen Prozessen teilhaben lassen", "in gesellschaftliche Prozesse teilhaben lassen", "über gesellschaftlichen Prozessen teilhaben lassen"], 0, "teilhaben lassen"],
    ["Welche Genitivstruktur ist korrekt?", ["zugunsten benachteiligter Gruppen", "zugunsten benachteiligten Gruppen", "zugunsten von benachteiligte Gruppen", "zugunsten der benachteiligten Gruppe ist immer falsch", "zugunsten mit benachteiligten Gruppen"], 0, "zugunsten + Genitiv"],
    ["Welche Formulierung ist korrekt?", ["sich von traditionellen Mustern abwenden", "sich auf traditionelle Muster abwenden", "sich mit traditionellen Mustern abwenden", "sich gegen traditionellen Mustern abwenden", "sich zu traditionellen Mustern abwenden"], 0, "sich abwenden von"],
    ["Welche Variante erfüllt Nebensatzregel und Verbendstellung?", ["Dies zeigt, dass Medien Informationen schneller verbreiten können.", "Dies zeigt, dass Medien können Informationen schneller verbreiten.", "Dies zeigt, dass können Medien Informationen schneller verbreiten.", "Dies zeigt, dass Medien schneller können Informationen verbreiten.", "Dies zeigt, dass Informationen können Medien schneller verbreiten."], 0, "Nebensatz"],
    ["Welche Infinitivstruktur ist korrekt?", ["anstatt bei seiner Familie zu leben", "anstatt bei seiner Familie leben", "anstatt zu bei seiner Familie leben", "anstatt bei seiner Familie gelebt", "anstatt seiner Familie zu bei leben"], 0, "anstatt + Infinitiv mit zu"]
  ],
  tf: [
    ["Der Ausdruck „der Bedarf an qualifizierten Fachkräften“ verlangt nach „an“ den Dativ.", true, "Bedarf an + Dativ"],
    ["„Einfluss auf + Akkusativ“ ist eine feste Struktur, die als Einheit gelernt werden sollte.", true, "Einfluss auf"],
    ["Nach „wegen“ steht im formellen Standarddeutsch typischerweise der Genitiv.", true, "wegen + Genitiv"],
    ["Bei der Herkunft aus einem Land ist „von“ idiomatischer als „aus“.", false, "Herkunft"],
    ["„Aufgrund“ wirkt in formellen Texten häufig sachlicher und schriftsprachlicher als „wegen“.", true, "Stil"],
    ["„In Bezug auf“ ist eine typische sachliche Struktur in argumentativen Texten.", true, "Akademischer Stil"],
    ["„Verfügen über“ kann frei mit jeder beliebigen Präposition ersetzt werden.", false, "feste Verbindung"],
    ["„Fortschritte erzielen“ ist eine idiomatische Verbindung im formellen Stil.", true, "Kollokation"],
    ["„Bestehen in + Dativ“ ist korrekt, wenn man den Kern eines Problems beschreibt.", true, "bestehen in"],
    ["„Raum schaffen für + Akkusativ“ ist eine feste und produktive akademische Struktur.", true, "Raum schaffen für"],
    ["„Auswirkungen auf + Akkusativ“ ist falsch; korrekt ist immer „Auswirkungen an“.", false, "Auswirkungen auf"],
    ["„Anstatt + Infinitiv mit zu“ verlangt in der Regel eine Infinitivgruppe mit zu.", true, "Infinitiv"],
    ["„Sich ergeben“ kann verwendet werden, wenn sich Chancen oder Folgen aus einer Situation entwickeln.", true, "sich ergeben"],
    ["Nebensätze mit „dass“ behalten die finite Verbform an zweiter Position.", false, "Verbendstellung"]
  ],
  wordMatch: [
    ["Präpositionen und Kasus", "System fester Verbindungen, in dem Präpositionen bestimmte Fälle verlangen"],
    ["der Bedarf an + Dativ", "Nomen-Präposition-Verbindung, bei der das Bezugswort nach an im Dativ steht"],
    ["Einfluss auf + Akkusativ", "Struktur, mit der eine Wirkung auf Personen, Prozesse oder Entwicklungen beschrieben wird"],
    ["Interesse an + Dativ", "feste Verbindung zur Bezeichnung eines thematischen oder persönlichen Interesses"],
    ["Beitrag zu + Dativ", "Verbindung, mit der man eine fördernde Wirkung auf ein Ziel oder Thema ausdrückt"],
    ["Herkunft mit aus statt von", "Regel, nach der bei Ländern, Städten oder Regionen gewöhnlich aus verwendet wird"],
    ["aufgrund vs. wegen", "stilistische Unterscheidung zwischen sachlich-schriftsprachlicher und allgemeinsprachlicher Ursache"],
    ["in Bezug auf", "sachlich-präzise Struktur zur thematischen Eingrenzung eines Arguments"],
    ["verfügen über", "feste Verbindung zur Bezeichnung vorhandener Mittel, Fähigkeiten oder Ressourcen"],
    ["Fortschritte erzielen", "idiomatische gehobene Formulierung für eine erfolgreiche Entwicklung"],
    ["Nebensätze und Verbendstellung", "Regel, nach der die finite Verbform im Nebensatz am Ende steht"],
    ["zugunsten + Genitiv", "gehobene Präposition zur Angabe, wem etwas nützt"],
    ["bestehen in + Dativ", "Struktur zur Definition des Wesens oder Kerns eines Problems"],
    ["anstatt + Infinitiv mit zu", "Infinitivkonstruktion, die eine nicht gewählte Alternative ausdrückt"],
    ["sich ergeben", "Verb zur Beschreibung von Chancen, Folgen oder Möglichkeiten, die aus einer Situation entstehen"]
  ],
  phraseMatch: [
    ["der Bedarf an", "+ Dativ"],
    ["Einfluss auf", "+ Akkusativ"],
    ["Interesse an", "+ Dativ"],
    ["Beitrag zu", "+ Dativ"],
    ["wegen des Bedarfs", "an …"],
    ["Herkunft", "mit aus statt von"],
    ["im formellen Stil eher", "aufgrund"],
    ["sachlich-präzise", "in Bezug auf"],
    ["Fortschritte", "erzielen"],
    ["an etwas", "teilhaben lassen"],
    ["zugunsten", "+ Genitiv"],
    ["sich von etwas", "abwenden"],
    ["sich auf etwas", "auswirken"],
    ["bestehen in", "+ Dativ"],
    ["Raum schaffen für", "+ Akkusativ"],
    ["mit", "ihrer Hilfe"],
    ["auf diese Weise", "kann … gefördert werden"],
    ["liegen in", "+ Dativ"],
    ["geeignete Verfahren", "zum Einsatz bringen"],
    ["Schutz vor", "+ Dativ / Nomen"],
    ["über Mittel", "verfügen"],
    ["im Umgang mit", "+ Dativ"],
    ["den Grundstein für", "+ Akkusativ legen"],
    ["Auswirkungen auf", "+ Akkusativ"],
    ["im Kontakt mit", "+ Dativ"],
    ["anstatt", "+ Infinitiv mit zu"],
    ["aus einer Situation", "sich ergeben"]
  ],
  prep: [
    ["Der Bedarf ___ qualifizierten Fachkräften steigt.", "an", "Dativ"],
    ["Medien üben Einfluss ___ Jugendliche aus.", "auf", "Akkusativ"],
    ["Interesse ___ gesellschaftlichen Fragen kann früh geweckt werden.", "an", "Dativ"],
    ["Bildung leistet einen Beitrag ___ sozialen Integration.", "zur", "zu + Dativ"],
    ["___ des Bedarfs an Fachkräften werden neue Programme entwickelt.", "wegen", "Genitiv"],
    ["Die Studentin kommt ___ der Türkei, nicht „von der Türkei“.", "aus", "Herkunft"],
    ["___ zunehmender sozialer Ungleichheit gewinnt Bildungspolitik an Bedeutung.", "aufgrund", "formeller Stil"],
    ["___ Bezug auf die Arbeitsrechte ist eine klare Regelung notwendig.", "in", "in Bezug auf"],
    ["Viele Jugendliche verfügen ___ gute digitale Kompetenzen.", "über", "feste Verbindung"],
    ["Diese Maßnahme lässt Kinder ___ kulturellen Angeboten teilhaben.", "an", "teilhaben an"],
    ["Die Entscheidung wurde ___ benachteiligter Gruppen getroffen.", "zugunsten", "Genitiv"],
    ["Immer mehr Menschen wenden sich ___ fleischbasierten Essgewohnheiten ab.", "von", "sich abwenden von"],
    ["Diese Entwicklung wirkt sich ___ das Konsumverhalten aus.", "auf", "Akkusativ"],
    ["Das Problem besteht ___ der unklaren Satzstruktur.", "in", "Dativ"],
    ["Schulen schaffen Raum ___ individuelle Entwicklung.", "für", "Akkusativ"],
    ["Der Vorteil liegt ___ der präzisen Verbindung von Verb und Nomen.", "in", "Dativ"],
    ["Neue Verfahren werden ___ Einsatz gebracht.", "zum", "zum Einsatz bringen"],
    ["Gesetze bieten Schutz ___ Diskriminierung.", "vor", "Dativ/Nomen"],
    ["Im Umgang ___ anderen wird man sicherer.", "mit", "Dativ"],
    ["Frühe Sprachpraxis legt den Grundstein ___ spätere Ausdruckssicherheit.", "für", "Akkusativ"],
    ["Digitale Medien haben Auswirkungen ___ die Öffentlichkeit.", "auf", "Akkusativ"],
    ["___ bei seiner Familie zu leben, organisiert er sich ein WG-Zimmer.", "anstatt", "Infinitiv mit zu"],
    ["Daraus können sich neue Zukunftschancen ___.", "ergeben", "Verb"],
    ["Im Kontakt ___ Muttersprachlern kann man an mündlicher Sicherheit gewinnen.", "mit", "Dativ"]
  ],
  hang: [
    "der Bedarf an qualifizierten Fachkräften",
    "Einfluss auf die Zuschauer ausüben",
    "Interesse an gesellschaftlichen Fragen wecken",
    "einen Beitrag zur Integration leisten",
    "wegen des Bedarfs an Fachkräften",
    "Herkunft mit aus statt von",
    "im formellen Stil eher aufgrund",
    "in Bezug auf die gesellschaftlichen Folgen",
    "über ausreichende Mittel verfügen",
    "Fortschritte erzielen",
    "an gesellschaftlichen Prozessen teilhaben lassen",
    "zugunsten benachteiligter Gruppen",
    "sich von traditionellen Mustern abwenden",
    "sich auf das Konsumverhalten auswirken",
    "bestehen in der unklaren Satzstruktur",
    "Raum schaffen für individuelle Entwicklung",
    "mit ihrer Hilfe",
    "auf diese Weise kann etwas gefördert werden",
    "im Umgang mit anderen sicherer werden",
    "den Grundstein für Sprachkenntnisse legen",
    "Auswirkungen auf die Öffentlichkeit haben",
    "im Kontakt mit Muttersprachlern",
    "anstatt bei seiner Familie zu leben",
    "anstatt Infinitiv mit zu",
    "sich bessere Zukunftschancen ergeben"
  ]
};
