window.DEUTSCH_TESTS = {
  t4: {
    slug: "mindestlohn_einkommen_absicherung",
    title: "4. Mindestlohn, Einkommen und wirtschaftliche Absicherung",
    topic: "Mindestlohn · Einkommen · wirtschaftliche Absicherung",
    words: ["Mindestlohn","Bezahlung","Lohn","Einkommen","Binnennachfrage","Geldumlauf","finanzielle Absicherung","Einkommensverlust","Lohnuntergrenze","Lohndruck","Entlohnung","Armutsrisiko","Binnenmarkt","wirtschaftliche Stabilisierung","wirtschaftliche Festigung","stabilisierende Wirkung","zu niedriger Bezahlung","geringes Einkommen","regionaler Handel","finanzieller Druck"],
    fill: [
      ["Eine verbindliche ____ verhindert ruinösen Wettbewerb über niedrige Löhne.","Lohnuntergrenze","Nomen"],
      ["Ein dauerhaft ____ schwächt soziale Teilhabe und Kaufkraft.","geringes Einkommen","Kollokation"],
      ["Der gesetzliche ____ schützt Arbeitnehmer vor existenzgefährdender Entlohnung.","Mindestlohn","Nomen"],
      ["Zu niedrige ____ kann Motivation und betriebliche Bindung beeinträchtigen.","Bezahlung","Nomen"],
      ["Zusätzliches ____ wird von einkommensschwachen Haushalten oft unmittelbar konsumiert.","Einkommen","Nomen"],
      ["Verlässliche Einkommen halten den ____ aufrecht.","Geldumlauf","Nomen"],
      ["Eine kräftige ____ stützt den Binnenmarkt.","Binnennachfrage","Nomen"],
      ["Ein plötzlicher ____ belastet Haushalte ohne Rücklagen.","Einkommensverlust","Nomen"],
      ["Bei schwacher Tarifbindung steigt häufig der ____.","Lohndruck","Nomen"],
      ["Eine angemessene ____ ermöglicht soziale Anerkennung.","Entlohnung","Nomen"],
      ["Nicht existenzsichernde Löhne erhöhen das ____.","Armutsrisiko","Nomen"],
      ["Ein stabiler ____ setzt breite Kaufkraft voraus.","Binnenmarkt","Nomen"]
    ],
    mc: [
      ["Welche Formulierung ist C1-gerecht?",["Der Mindestlohn kann Arbeitnehmer vor zu niedriger Bezahlung schützen.","Mindestlohn macht alle reich.","Lohn ist einfach Geld.","Arbeitnehmer kaufen Einkommen.","Der Markt zahlt automatisch fair."],0,"C1"],
      ["Welche Kollokation ist korrekt?",["eine stabilisierende Wirkung entfalten","eine Wirkung machen","eine Wirkung verdienen","Wirkung bezahlen","bei Wirkung stehen"],0,"Kollokation"],
      ["Welche Aussage ist fachlich korrekt?",["Binnennachfrage hängt auch vom verfügbaren Einkommen ab.","Binnennachfrage ist nur Export.","Geldumlauf bedeutet Stillstand.","Lohndruck bedeutet hohe Entlohnung.","Armutsrisiko betrifft nie Beschäftigte."],0,"Wirtschaft"],
      ["Welche Wendung passt zu sozialer Absicherung?",["Schutz vor Einkommensverlust bieten","Einkommen gegen Markt essen","Lohn mit Nachfrage verdrängen","Armutsrisiko verkaufen","Geldumlauf verlieren"],0,"Kollokation"],
      ["Welche Aussage vermeidet eine zu starke Verallgemeinerung?",["Der Mindestlohn kann das Armutsrisiko verringern.","Der Mindestlohn löst jedes Armutsproblem vollständig.","Lohnuntergrenzen sind immer wirkungslos.","Niedrige Löhne stärken immer die Wirtschaft.","Bezahlung hat keine soziale Funktion."],0,"Argumentation"],
      ["Welche Struktur ist nominalsprachlich korrekt?",["zur wirtschaftlichen Stabilisierung beitragen","zur Wirtschaft stabil machen","die Stabilität verdienen","wirtschaftlich in Lohn gehen","Nachfrage unter Druck essen"],0,"Nominalstil"]
    ],
    tf: [
      ["Der Mindestlohn kann Arbeitnehmer vor zu niedriger Bezahlung schützen.",true,"Grundfunktion"],
      ["Lohndruck ist ein Synonym für besonders hohe Entlohnung.",false,"Begriff"],
      ["Ein geringes Einkommen kann das Armutsrisiko erhöhen.",true,"Risiko"],
      ["Binnennachfrage hängt auch vom verfügbaren Einkommen privater Haushalte ab.",true,"Wirtschaft"],
      ["Finanzielle Absicherung bedeutet völlige Risikolosigkeit.",false,"Präzision"],
      ["Ein stabiler Geldumlauf kann regionale Betriebe stützen.",true,"Wirtschaft"],
      ["Der Binnenmarkt hat mit Kaufkraft nichts zu tun.",false,"Begriff"],
      ["Eine angemessene Entlohnung kann soziale Teilhabe erleichtern.",true,"Soziales"]
    ],
    wordMatch: [
      ["der Mindestlohn","gesetzlich oder politisch festgelegte unterste Bezahlungsgrenze"],
      ["die Binnennachfrage","Nachfrage nach Gütern und Dienstleistungen innerhalb einer Volkswirtschaft"],
      ["der Geldumlauf","Zirkulation von Geld zwischen Haushalten, Unternehmen und Staat"],
      ["die Lohnuntergrenze","Mindestniveau, unter das die Entlohnung nicht fallen darf"],
      ["der Lohndruck","Druck, niedrigere Löhne oder schlechtere Bedingungen hinzunehmen"],
      ["die Entlohnung","Vergütung für geleistete Arbeit"],
      ["das Armutsrisiko","Wahrscheinlichkeit, trotz Einkommen in materielle Not zu geraten"],
      ["der Binnenmarkt","wirtschaftlicher Markt innerhalb eines Landes oder Wirtschaftsraums"],
      ["die finanzielle Absicherung","Mindestmaß an Schutz vor existenzieller Unsicherheit"],
      ["der Einkommensverlust","Wegfall oder deutliche Verringerung bisheriger Einnahmen"]
    ],
    phraseMatch: [
      ["Arbeitnehmer", "vor zu niedriger Bezahlung schützen"],
      ["die Binnennachfrage", "unterstützen"],
      ["den Geldumlauf", "sicherstellen"],
      ["Schutz", "vor Einkommensverlust bieten"],
      ["ein stabiles Einkommen", "gewährleisten"],
      ["von einer Lohnuntergrenze", "profitieren"],
      ["unter Lohndruck", "geraten"],
      ["eine angemessene Entlohnung", "sichern"],
      ["Geld", "in den regionalen Handel bringen"],
      ["eine stabilisierende Wirkung", "entfalten"]
    ],
    prep: [
      ["Arbeitnehmer profitieren ___ einer Lohnuntergrenze.","von","Präposition"],
      ["Der Mindestlohn schützt ___ zu niedriger Bezahlung.","vor","Präposition"],
      ["Viele Beschäftigte stehen ___ finanziellem Druck.","unter","Präposition"],
      ["Diese Maßnahme trägt ___ wirtschaftlichen Stabilisierung bei.","zur","Präposition"],
      ["Zusätzliches Geld fließt ___ den regionalen Handel.","in","Präposition"],
      ["Die Nachfrage hängt ___ verfügbaren Einkommen ab.","vom","Präposition"],
      ["Eine Lohnstruktur wirkt sich ___ den Binnenmarkt aus.","auf","Präposition"],
      ["Der Schutz richtet sich ___ Einkommensverlust.","gegen","Präposition"]
    ],
    hang: ["Mindestlohn","Bezahlung","Einkommen","Binnennachfrage","Geldumlauf","Lohnuntergrenze","Lohndruck","Entlohnung","Armutsrisiko","Binnenmarkt","Einkommensverlust"]
  },
  t5: {
    slug: "wirtschaft_arbeit_karriere_wettbewerb",
    title: "5. Wirtschaft, Arbeit, Karriere und Wettbewerb",
    topic: "Karriere · Wettbewerb · Markt · Verbraucher · Arbeitsrechte · Gehalt · Gewinn",
    words: ["Karrierefortschritt","Arbeiterrechte","Arbeitsrechte","Arbeitnehmerrechte","Wettbewerb","Entwicklungs- und Schwellenländer","Markt","Konkurrenz","Verbraucher","kulturelle Verdrängung","Konsumverhalten","Rollen im Marktkontext","Gehalt","Arbeitnehmer","finanzieller Gewinn","Gewinnbeteiligung","wirtschaftliche Stabilität","wirtschaftliche Entlastung","wirtschaftliche Absicherung","beruflicher Aufstieg","berufliches Vorankommen","berufliche Vernetzung","Leistungsdruck","passende Stelle","Produkte und Dienstleistungen","Gewinn erzielen","nach Gewinn streben","Qualität verbessern","Kosten senken","Arbeitsrechte schützen","Marktanteile verlieren","den Markt dominieren","lokale Gastronomie","Konsumgewohnheiten","globale Unternehmen","lokale Unternehmen","kleine Betriebe","globale Ketten","internationale Ketten","Fast-Food-Ketten","Ausdruckssicherheit","direkter Austausch","Einblick in","an Bedeutung gewinnen"],
    fill: [
      ["Durch gezielte Weiterbildung lässt sich die Karriere ____.","vorantreiben","Verb"],
      ["Ein starkes Netzwerk kann berufliche ____ ermöglichen.","Vernetzung","Nomen"],
      ["Mentoringprogramme können beruflichen ____ fördern.","Aufstieg","Kollokation"],
      ["Neue Qualifikationen können berufliches ____ ermöglichen.","Vorankommen","Kollokation"],
      ["Wer systematisch Kompetenzen erweitert, kann Karrierefortschritt ____.","erreichen","Verb"],
      ["Das Wirtschaftswachstum ____ schneller zu.","nimmt","Verb"],
      ["In wirtschaftlichen Aussagen soll man präzise ____ verwenden.","Verben","Wirtschaftssprache"],
      ["Unternehmen können Produkte und Dienstleistungen erfolgreicher ____.","anbieten","Verb"],
      ["Produkte und Dienstleistungen werden auf dem Markt angeboten oder ____.","verkauft","Passiv"],
      ["Ein intensiver Wettbewerb kann einen Vorteil für Verbraucher ____.","bringen","Verb"],
      ["Unternehmen versuchen häufig, Gewinn zu ____.","erzielen","Kollokation"],
      ["Viele Unternehmen streben nach ____.","Gewinn","Nomen"],
      ["Wettbewerb kann Unternehmen dazu zwingen, Kosten zu ____.","senken","Verb"],
      ["Wettbewerb kann die Qualität eines Produkts ____.","verbessern","Verb"],
      ["Der Staat muss Maßnahmen zum Schutz der Arbeitsrechte ____.","ergreifen","Verb"],
      ["Die Durchsetzung der Arbeitsrechte muss rechtlich ____ werden.","sichergestellt","Passiv"],
      ["Verbraucher können von niedrigeren Preisen ____.","profitieren","Verb"],
      ["Kleine Betriebe verlieren gegenüber globalen Ketten zunehmend ____.","Marktanteile","Nomen"],
      ["Globale Unternehmen können den Markt zunehmend ____.","dominieren","Verb"],
      ["Globale Ketten können lokale gastronomische Betriebe ____.","verdrängen","Verb"],
      ["Diese Entwicklung kann zur Verdrängung der lokalen ____ führen.","Gastronomie","Nomen"],
      ["Globale Unternehmen spielen eine zentrale Rolle bei wirtschaftlichen ____.","Veränderungen","Nomen"],
      ["Internationale Ketten können die Konsumgewohnheiten vieler Menschen im Alltag ____.","verändern","Verb"],
      ["Verbraucher bevorzugen globale Unternehmen häufiger als ____ Unternehmen.","lokale","Adjektiv"],
      ["Die Marktstruktur kann sich auf das Gehalt der Arbeitnehmer ____.","auswirken","Verb"],
      ["Gewinnbeteiligungen lassen Mitarbeiter am finanziellen Gewinn ____.","teilhaben","Verb"],
      ["Ein Unternehmen kann eine finanzielle Gewinnbeteiligung ____.","gewähren","Verb"],
      ["Durch direkte Kommunikation kann man an Ausdruckssicherheit ____.","gewinnen","Verb"],
      ["Man kann Einblick in komplexe wirtschaftliche Zusammenhänge ____.","gewinnen","Verb"],
      ["Flexible Arbeitsformen können zur wirtschaftlichen Entlastung ____.","beitragen","Verb"],
      ["Im Laufe der Zeit kann diese Entwicklung an Bedeutung ____.","gewinnen","Kollokation"]
    ],
    mc: [
      ["Welche Formulierung ist personalsprachlich korrekt?",["Eine Stelle wird besetzt.","Eine Stelle wird befüllt.","Eine Stelle wird gegessen.","Eine Stelle wird konsumiert.","Eine Stelle wird gedrückt."],0,"Personalsprachlich"],
      ["Welche Aussage verwendet ein starkes Verb statt Nominalstil?",["Unternehmen verbessern die Qualität.","Die Verbesserung der Qualität wird durchgeführt.","Es gibt eine Durchführung der Verbesserung.","Qualität wird in Verbesserung gesetzt.","Verbesserung macht Qualität."],0,"Wirtschaftssprache"],
      ["Welche Kollokation ist korrekt?",["Gewinn erzielen","Gewinn essen","Gewinn besetzen","Gewinn verdrängen","Gewinn anbieten"],0,"Kollokation"],
      ["Welche Formulierung ist C1-gerecht?",["Unternehmen können ihre Preise senken, sodass Verbraucher von niedrigeren Preisen profitieren.","Firmen machen Sachen billiger.","Preise profitieren Unternehmen.","Konkurrenz isst Kosten.","Der Markt macht Leute."],0,"C1"],
      ["Welche Aussage ist differenziert?",["Globale Ketten können Preise senken, gleichzeitig aber lokale Strukturen verdrängen.","Globale Unternehmen sind immer schlecht.","Lokale Betriebe verlieren nie Marktanteile.","Verbraucher haben keine Rolle.","Konsum verändert niemals Märkte."],0,"Argumentation"],
      ["Welche Verbindung passt zu Gehalt?",["sich auf das Gehalt der Arbeitnehmer auswirken","Gehalt verdrängt lokale Gastronomie","Gehalt bietet Produkte an","Gehalt dominiert Verbraucher","Gehalt strebt nach Preisen"],0,"Kollokation"],
      ["Welche Aussage ist wirtschaftssprachlich präzise?",["Unternehmen streben nach Gewinn und versuchen, Kosten zu senken.","Unternehmen wollen Geld und machen Dinge.","Märkte sind einfach Konkurrenz.","Verbraucher verlieren immer.","Gewinnbeteiligung bedeutet Lohnverlust."],0,"Wirtschaftssprache"]
    ],
    tf: [
      ["Berufliche Vernetzung kann berufliches Vorankommen ermöglichen.",true,"Karriere"],
      ["Gewinnen an verlangt in dieser Struktur den Akkusativ.",false,"Dativ"],
      ["Unternehmen können nach Gewinn streben und zugleich Kosten senken wollen.",true,"Wirtschaft"],
      ["Lokale Unternehmen können gegenüber globalen Unternehmen Marktanteile verlieren.",true,"Markt"],
      ["Verbraucher spielen im Marktkontext keine Rolle.",false,"Marktkontext"],
      ["Globale Unternehmen können Konsumgewohnheiten vieler Menschen verändern.",true,"Konsum"],
      ["Arbeitsrechte müssen nicht durchgesetzt werden, wenn Wettbewerb besteht.",false,"Arbeitsrechte"],
      ["Gewinnbeteiligung kann Mitarbeiter am finanziellen Gewinn teilhaben lassen.",true,"Gehalt"],
      ["Entwicklungs- und Schwellenländer sind immer in demselben Maße wirksam wie Industrieländer.",false,"Vergleich"],
      ["Präzise Verben sind in wirtschaftlichen Aussagen oft besser als unnötiger Nominalstil.",true,"Stil"]
    ],
    wordMatch: [
      ["Karrierefortschritt","messbare oder wahrnehmbare Verbesserung der beruflichen Entwicklung"],
      ["berufliche Vernetzung","Aufbau nützlicher beruflicher Kontakte"],
      ["Arbeitnehmerrechte","rechtliche Ansprüche und Schutzrechte von Beschäftigten"],
      ["Verbraucher","Personen, die Produkte oder Dienstleistungen nachfragen"],
      ["Gewinnbeteiligung","finanzielle Beteiligung von Mitarbeitern am Unternehmenserfolg"],
      ["wirtschaftliche Stabilität","relativ verlässlicher Zustand wirtschaftlicher Ordnung"],
      ["kulturelle Verdrängung","Zurückdrängung lokaler Strukturen durch dominante globale Anbieter"],
      ["Konsumverhalten","Art und Weise, wie Menschen kaufen und verbrauchen"],
      ["Marktanteile","Anteile eines Unternehmens oder einer Gruppe am Gesamtmarkt"],
      ["Entwicklungs- und Schwellenländer","Länder mit noch nicht vollständig industrialisierten Wirtschaftsstrukturen"],
      ["Konkurrenz","Wettbewerb zwischen Anbietern auf einem Markt"],
      ["Gehalt","regelmäßige Vergütung eines Arbeitnehmers"]
    ],
    phraseMatch: [
      ["die Karriere", "vorantreiben"],
      ["berufliche Vernetzung", "ermöglichen"],
      ["beruflichen Aufstieg", "fördern"],
      ["Karrierefortschritt", "erreichen"],
      ["Gewinn", "erzielen"],
      ["nach Gewinn", "streben"],
      ["die Qualität", "verbessern"],
      ["Kosten", "senken"],
      ["Arbeitsrechte", "schützen"],
      ["Marktanteile", "verlieren"],
      ["den Markt", "dominieren"],
      ["lokale Betriebe", "verdrängen"],
      ["Konsumgewohnheiten", "verändern"],
      ["eine Gewinnbeteiligung", "gewähren"],
      ["an Ausdruckssicherheit", "gewinnen"],
      ["Einblick in wirtschaftliche Zusammenhänge", "gewinnen"]
    ],
    prep: [
      ["Verbraucher können ___ niedrigeren Preisen profitieren.","von","Präposition"],
      ["Lokale Unternehmen verlieren ___ globalen Unternehmen Marktanteile.","gegenüber","Präposition"],
      ["Im Laufe der Zeit kann diese Entwicklung ___ Bedeutung gewinnen.","an","Präposition"],
      ["Man kann Einblick ___ wirtschaftliche Zusammenhänge gewinnen.","in","Präposition"],
      ["Diese Entwicklung wirkt sich ___ das Gehalt der Arbeitnehmer aus.","auf","Präposition"],
      ["Unternehmen streben häufig ___ Gewinn.","nach","Präposition"],
      ["Globale Unternehmen spielen eine Rolle ___ wirtschaftlichen Veränderungen.","bei","Präposition"],
      ["Kleine Betriebe verlieren Marktanteile ___ globalen Ketten.","gegenüber","Präposition"],
      ["Mitarbeiter können ___ finanziellen Gewinn teilhaben.","am","Präposition"],
      ["Eine Maßnahme kann ___ wirtschaftlichen Entlastung beitragen.","zur","Präposition"]
    ],
    hang: ["Karrierefortschritt","Arbeiterrechte","Arbeitsrechte","Arbeitnehmerrechte","Verbraucher","Konkurrenz","Gehalt","Gewinnbeteiligung","Marktanteile","Konsumverhalten","Konsumgewohnheiten","wirtschaftliche Stabilität","wirtschaftliche Entlastung","beruflicher Aufstieg","berufliches Vorankommen","berufliche Vernetzung","globale Unternehmen","lokale Unternehmen","kleine Betriebe","globale Ketten","internationale Ketten","Ausdruckssicherheit","Einblick"]
  }
};
