(function(){
'use strict';
var key='sf2_5';
var source='5. Sprach Fehlern.docx';
window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};
window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};
var LONG=[
`<h3>Schreiben_fehler_5 · Mindestlohn, betriebliche Kosten, Arbeitsmarkt, Inflation und Mehrsprachigkeit</h3>`,
`<p><b>Niveau:</b> C1/C2 · Rektion · Präpositionen mit Kasus · Nominalisierung · Nomen-Verb-Verbindungen · kohärente Argumentation</p>`,
`<h4>1. Ziel des Kapitels</h4>`,
`<p>Dieses Kapitel erklärt typische Fehler aus Texten über Mindestlohn, betriebliche Kosten, Arbeitsmarkt, Inflation und Mehrsprachigkeit. Es geht nicht darum, einzelne Korrekturen auswendig zu lernen, sondern ein stabiles sprachliches System aufzubauen. C1/C2-Schreiben verlangt präzise Rektion, sichere Präpositionen, idiomatische Kollokationen, klare Nominalgruppen und eine vorsichtige, differenzierte Argumentationslogik.</p>`,
`<p>Die wiederkehrenden Fehler betreffen fünf Bereiche: falsche Rektion, unklare Nominalgruppen, fehlende Modalverben, unidiomatische Kollokationen und mangelnde Parallelität. Statt <i>Ausgaben machen</i> verwendet man <b>Ausgaben tätigen</b> oder <b>Geld ausgeben</b>. Statt <i>Freundschaften machen</i> schreibt man <b>Freundschaften schließen</b> oder <b>Freundschaften knüpfen</b>. Statt <i>eine Sprache fokussieren</i> ist <b>sich auf eine Sprache konzentrieren</b> idiomatischer.</p>`,
`<h4>2. Mindestlohn und Binnenwirtschaft</h4>`,
`<p>Beim Thema Mindestlohn ist die Verbklammer besonders wichtig. In einem Nebensatz mit <b>weil</b> steht das konjugierte Verb am Ende. Korrekt ist: <i>weil er die Binnennachfrage unterstützen und den Geldumlauf sicherstellen kann.</i> Das zweite Pronomen wird nicht wiederholt, wenn sich beide Prädikatsteile auf dasselbe Subjekt beziehen. Außerdem ist <b>Geldumlauf</b> prägnanter als <i>der Umlauf des Geldes</i>.</p>`,
`<p>Für wirtschaftliche Wirkungen sind folgende Muster zentral: <b>die Binnennachfrage stützen</b>, <b>die Kaufkraft einkommensschwacher Haushalte stärken</b>, <b>den Geldumlauf aufrechterhalten</b>, <b>Konsumimpulse setzen</b> und <b>zur Stabilisierung binnenwirtschaftlicher Nachfrage beitragen</b>. Ein Modell lautet: <i>Ein angemessener Mindestlohn kann die Kaufkraft einkommensschwacher Haushalte stärken und dadurch die Binnennachfrage stabilisieren.</i></p>`,
`<h4>3. Präpositionen im Themenfeld Mindestlohn</h4>`,
`<p>Mehrere feste Präpositionsmuster müssen sicher beherrscht werden. <b>Zu etwas beitragen</b> verlangt den Dativ: <i>Der Mindestlohn kann zur Stärkung der Kaufkraft beitragen.</i> <b>Sich auf etwas auswirken</b> verlangt den Akkusativ: <i>Eine Lohnerhöhung wirkt sich auf die Konsumnachfrage aus.</i> <b>Aufgrund + Genitiv</b> markiert im formellen Stil eine Ursache: <i>Aufgrund höherer Einkommen steigt die Kaufkraft bestimmter Haushalte.</i></p>`,
`<p>Auch <b>in</b> muss unterschieden werden. Bei statischer Bedeutung steht der Dativ: <i>Die zusätzlichen Einkommen können in allen Bereichen des Alltags relevant werden.</i> Bei Richtung steht der Akkusativ: <i>Zusätzliches Einkommen kann in verschiedene Konsumbereiche fließen.</i> Diese Unterscheidung ist für präzise wirtschaftliche Argumentation entscheidend.</p>`,
`<h4>4. Betriebliche Kosten und Branchen</h4>`,
`<p>Im wirtschaftlichen Kontext müssen Personen, Betriebe und Branchen klar unterschieden werden. Statt <i>Handwerkers oder Friseurs</i> schreibt man <b>Handwerksbetriebe oder Friseursalons</b>, wenn Betriebe gemeint sind. Statt <i>Betriebe, die ihre Branchen mit niedrigen Gewinnspannen haben</i> lautet die idiomatische Form: <b>Betriebe, die in Branchen mit niedrigen Gewinnspannen tätig sind</b>. Die Struktur <b>in + Dativ</b> beschreibt hier einen Tätigkeitsbereich.</p>`,
`<p>Wichtige Muster sind <b>über begrenzten Spielraum verfügen</b>, <b>unter Kostendruck stehen</b>, <b>Kosten auf Kunden abwälzen</b>, <b>an Wettbewerbsfähigkeit verlieren</b> und <b>von Preissteigerungen betroffen sein</b>. Ein präziser Satz lautet: <i>Kleine Betriebe verfügen oft nur über begrenzten finanziellen Spielraum und können steigende Lohnkosten nicht ohne Weiteres intern ausgleichen.</i></p>`,
`<h4>5. Arbeitsplätze, Inflation und vorsichtige Kausalität</h4>`,
`<p>Wirtschaftliche Argumentationen sollten keine zu starken Automatismen behaupten. Statt <i>automatische Inflation</i> verwendet man <b>inflationäre Tendenzen</b> oder <b>preistreibende Effekte</b>. Statt <i>zerstört Arbeitsplätze</i> ist <b>kann die Arbeitsplatzsicherheit gefährden</b> differenzierter. C1/C2-Sprache markiert Bedingungen, Risiken und Tendenzen, statt einfache Ursache-Wirkung-Ketten absolut zu setzen.</p>`,
`<p>Geeignete Strukturen sind <b>es kann zu + Dativ kommen</b>, <b>eine Gefahr für + Akkusativ darstellen</b>, <b>sich auf + Akkusativ auswirken</b>, <b>einhergehen mit + Dativ</b> und <b>in Zusammenhang stehen mit + Dativ</b>. Beispiel: <i>Wenn Betriebe höhere Lohnkosten nicht durch Produktivitätssteigerungen ausgleichen können, kann es zu einer Gefährdung von Arbeitsplätzen kommen.</i></p>`,
`<h4>6. Nomen-Verb-Verbindungen im Wirtschaftskontext</h4>`,
`<p>Für das Thema Mindestlohn sind viele Nomen-Verb-Verbindungen relevant: <b>einen Beitrag leisten</b>, <b>Auswirkungen auf etwas haben</b>, <b>eine Rolle spielen</b>, <b>Kaufkraft in Umlauf bringen</b>, <b>Dienstleistungen in Anspruch nehmen</b>, <b>Maßnahmen ergreifen</b>, <b>unter Druck geraten</b>, <b>Kosten tragen</b>, <b>Einfluss auf etwas nehmen</b>, <b>eine Belastung darstellen</b> und <b>Spielraum für faire Löhne schaffen</b>.</p>`,
`<p>Diese Verbindungen sind stärker als einfache Verben, wenn sie einen abstrakten Zusammenhang präzise benennen. Ein Satz wie <i>Der Mindestlohn hilft der Wirtschaft</i> wirkt zu allgemein. Besser ist: <i>Ein gesetzlicher Mindestlohn kann einen Beitrag zur Verringerung von Erwerbsarmut leisten und gleichzeitig Konsumimpulse im Binnenmarkt setzen.</i></p>`,
`<h4>7. Mehrsprachigkeit und Spracherwerb</h4>`,
`<p>Im Themenfeld Mehrsprachigkeit entstehen Fehler vor allem durch unklare Bezüge, falsche Präpositionen und nicht parallele Aufzählungen. Korrekt sind <b>mehrsprachig aufwachsende Kinder</b>, <b>im frühen Kindesalter mit mehreren Sprachen in Berührung kommen</b>, <b>im familiären Umfeld Sprachkompetenz aufbauen</b>, <b>Sicherheit beim Sprechen gewinnen</b>, <b>zwischen verschiedenen Sprachen wechseln</b> und <b>ein besseres Verständnis für kulturelle Unterschiede entwickeln</b>.</p>`,
`<p>Besonders wichtig ist die Unterscheidung zwischen <b>Verständnis für + Akkusativ</b> und <b>Toleranz gegenüber + Dativ</b>. Man schreibt: <i>Kinder können ein besseres Verständnis für kulturelle Unterschiede entwickeln und anderen Kulturen gegenüber mehr Toleranz zeigen.</i> Die beiden Nomen verlangen unterschiedliche Ergänzungen; deshalb muss die Aufzählung parallel und grammatisch sauber aufgebaut werden.</p>`,
`<h4>8. Satzbau, Passiv und Adverbialformen</h4>`,
`<p>Nach <b>dadurch</b> steht das konjugierte Verb auf Position zwei: <i>Dadurch können sie sich nicht vollständig auf eine Sprache konzentrieren.</i> In Nebensätzen mit <b>weil</b> oder <b>da</b> steht das finite Verb am Ende. Passiv mit Modalverb folgt dem Muster <b>Partizip II + werden + Modalverb</b>: <i>Das zusätzliche Einkommen kann für alltägliche Ausgaben verwendet werden.</i></p>`,
`<p>Feste Adverbialformen müssen ebenfalls gelernt werden: <b>am selben Tag</b>, nicht <i>in dem gleichen Tag</i>; <b>zu Hause</b>, nicht <i>in sein Haus</i>; <b>in allen Bereichen</b>, nicht <i>in alle Bereiche</i>, wenn eine statische Bedeutung gemeint ist. Diese scheinbar kleinen Korrekturen entscheiden oft darüber, ob ein Text idiomatisch wirkt.</p>`,
`<h4>9. Konnektoren und Abwägung</h4>`,
`<p>Argumentative Texte wirken reifer, wenn Gegensätze differenziert verbunden werden. Nützlich sind <b>allerdings</b>, <b>gleichzeitig</b>, <b>dennoch</b>, <b>unter bestimmten Umständen</b>, <b>sofern</b>, <b>insbesondere wenn</b> und <b>nicht außer Acht lassen</b>. Beispiel: <i>Ein höherer Mindestlohn kann die Kaufkraft stärken; gleichzeitig dürfen mögliche Belastungen kleiner Betriebe nicht außer Acht gelassen werden.</i></p>`,
`<p>Für Mehrsprachigkeit kann man formulieren: <i>Mehrsprachig aufwachsende Kinder kommen bereits im familiären Umfeld mit unterschiedlichen sprachlichen Strukturen in Berührung. Dadurch können sie nicht nur Sprachkompetenz erwerben, sondern auch ein besseres Verständnis für kulturelle Unterschiede entwickeln.</i> Die Struktur <b>nicht nur ..., sondern auch ...</b> verlangt auch hier Parallelität.</p>`,
`<h4>10. Modellabsätze</h4>`,
`<p><b>Mindestlohn:</b> Ein angemessener Mindestlohn kann die Kaufkraft einkommensschwacher Haushalte stärken und dadurch die Binnennachfrage stabilisieren. Da Arbeitnehmer, die den Mindestlohn erhalten, einen großen Teil ihres Einkommens unmittelbar wieder ausgeben, kann der Geldumlauf im Binnenmarkt gefördert werden. Gleichzeitig muss berücksichtigt werden, dass kleinere Betriebe in Branchen mit niedrigen Gewinnspannen durch steigende Lohnkosten unter Druck geraten können.</p>`,
`<p><b>Mehrsprachigkeit:</b> Mehrsprachig aufwachsende Kinder kommen bereits im familiären Umfeld mit unterschiedlichen sprachlichen Strukturen in Berührung. Dadurch können sie nicht nur Sprachkompetenz erwerben, sondern auch ein besseres Verständnis für kulturelle Unterschiede entwickeln. Allerdings kann der gleichzeitige Gebrauch mehrerer Sprachen in bestimmten Lernphasen dazu führen, dass sich Kinder nicht vollständig auf eine Sprache konzentrieren. Entscheidend ist daher eine kontinuierliche sprachliche Förderung, die Mehrsprachigkeit als Ressource begreift.</p>`,
`<h4>11. Schreibkontrolle</h4>`,
`<p>Vor der Abgabe sollte geprüft werden, ob das Modalverb im Nebensatz am Ende steht, ob Nominalgruppen natürlich gebildet sind, ob Präpositionen den richtigen Kasus steuern, ob wirtschaftliche Kausalität vorsichtig formuliert ist und ob Kollokationen idiomatisch sind. Besonders wichtig sind <b>den Geldumlauf sicherstellen</b>, <b>Ausgaben tätigen</b>, <b>in Branchen tätig sein</b>, <b>unter Kostendruck stehen</b>, <b>inflationäre Tendenzen begünstigen</b>, <b>Freundschaften schließen</b>, <b>sich auf eine Sprache konzentrieren</b>, <b>Verständnis für etwas entwickeln</b> und <b>Toleranz gegenüber anderen Kulturen zeigen</b>.</p>`
].join('');
var P=[
['die Binnennachfrage stabilisieren','Kollokation','Ein Mindestlohn kann die Binnennachfrage ___.','stabilisieren','wirtschaftliche Nachfrage sichern'],
['den Geldumlauf sicherstellen','NVV','Er kann den Geldumlauf im Binnenmarkt ___.','sicherstellen','Geldbewegung sichern'],
['zur Stärkung der Kaufkraft beitragen','zu + Dativ','Der Mindestlohn kann ___ Stärkung der Kaufkraft beitragen.','zur','positiv beitragen'],
['sich auf die Konsumnachfrage auswirken','auf + Akkusativ','Eine Lohnerhöhung wirkt sich ___ die Konsumnachfrage aus.','auf','Wirkungsbereich'],
['in Branchen tätig sein','in + Dativ','Viele Kleinbetriebe sind ___ Branchen mit niedrigen Margen tätig.','in','Tätigkeitsbereich'],
['über Spielraum verfügen','über + Akkusativ','Kleine Betriebe verfügen oft nur ___ begrenzten Spielraum.','über','Ressourcen haben'],
['unter Kostendruck stehen','unter + Dativ','Friseursalons können ___ Kostendruck stehen.','unter','Belastung'],
['Kosten auf Kunden abwälzen','auf + Akkusativ','Unternehmen wälzen höhere Kosten ___ Kunden ab.','auf','Kosten weitergeben'],
['zu Arbeitsplatzverlusten führen','zu + Dativ','Hohe Kosten können ___ Arbeitsplatzverlusten führen.','zu','Folge'],
['inflationäre Tendenzen begünstigen','Kollokation','Stark steigende Kosten können inflationäre Tendenzen ___.','begünstigen','Risiko vorsichtig ausdrücken'],
['Freundschaften schließen','Kollokation','Mehrsprachige Kinder können leichter Freundschaften ___.','schließen','soziale Beziehungen aufbauen'],
['Toleranz gegenüber Kulturen zeigen','gegenüber + Dativ','Kinder können Toleranz ___ anderen Kulturen zeigen.','gegenüber','Haltung ausdrücken']
];
var MC=[['Welche Form ist korrekt?',['den Geldumlauf sicherstellen','den Umlauf des Gelds machen','Geldumlauf bauen','Geldumlauf erledigen'],0,'Kompositum / Kollokation'],['Welche Form ist idiomatisch?',['Ausgaben tätigen','Ausgaben machen','Ausgaben bauen','Ausgaben abschließen'],0,'Kollokation'],['Welche Struktur ist korrekt?',['Betriebe, die in Branchen tätig sind','Betriebe, die Branchen haben','Betriebe mit ihre Branchen','Betriebe, die Branchen besitzen'],0,'in + Dativ'],['Welche Form ist C1/C2-gerecht?',['inflationäre Tendenzen begünstigen','automatische Inflation machen','sicher Inflation verursachen','Inflation automatisch entwickeln'],0,'vorsichtige Kausalität'],['Welche Form ist korrekt?',['Freundschaften schließen','Freundschaften machen','Freundschaften bauen','Freundschaften erledigen'],0,'Kollokation']];
var TF=[['Im Nebensatz mit weil steht das konjugierte Verb am Ende.',true,'Satzbau'],['Aufgrund verlangt im formellen Stil häufig den Genitiv.',true,'Kasus'],['Freundschaften machen ist die idiomatische C1/C2-Form.',false,'Kollokation'],['Toleranz gegenüber anderen Kulturen verlangt gegenüber + Dativ.',true,'Rektion'],['Sich auf eine Sprache konzentrieren ist idiomatisch.',true,'Reflexive Struktur'],['Automatische Inflation ist eine präzise ökonomische Formulierung.',false,'Argumentative Vorsicht']];
window.DEUTSCH_TESTS[key]={category:'Schreiben Fehler 2',slug:'schreiben_fehler_5_mindestlohn_betriebliche_kosten_mehrsprachigkeit',title:'Schreiben_fehler_5 · Mindestlohn, betriebliche Kosten, Arbeitsmarkt, Inflation und Mehrsprachigkeit',topic:'C1/C2 · Rektion · Präpositionen · Nominalisierung · NVV/FVG · Argumentation',source:source,words:P.map(function(x){return x[0];}),fill:P.map(function(x){return [x[2],x[3],x[1]];}),mc:MC,tf:TF,wordMatch:P.map(function(x){return [x[0],x[4]];}),phraseMatch:[['Mindestlohn','stabilisiert die Binnennachfrage'],['Kleinbetriebe','stehen unter Kostendruck'],['Inflation','kann als Tendenz begünstigt werden'],['Mehrsprachigkeit','fördert interkulturelle Kompetenz'],['Kinder','schließen Freundschaften']],prep:P.map(function(x){return [x[2],x[3],x[1]];}),hang:P.map(function(x){return x[0];})};
window.DEUTSCH_LESSONS[key]={source:source,longSourceVerified:true,short:'<h3>Schreiben_fehler_5 · Kurzüberblick</h3><p>Dieses Modul behandelt Mindestlohn, betriebliche Kosten, Arbeitsmarkt, Inflation und Mehrsprachigkeit. Trainiert werden Rektion, Präpositionen, Nominalisierung, Nomen-Verb-Verbindungen und kohärente Argumentation.</p>',medium:'<h3>Schreiben_fehler_5 · Erweiterte Erklärung</h3><p>Zentrale Muster sind <b>die Binnennachfrage stabilisieren</b>, <b>den Geldumlauf sicherstellen</b>, <b>zur Stärkung der Kaufkraft beitragen</b>, <b>in Branchen mit niedrigen Gewinnspannen tätig sein</b>, <b>unter Kostendruck stehen</b>, <b>inflationäre Tendenzen begünstigen</b>, <b>Freundschaften schließen</b>, <b>sich auf eine Sprache konzentrieren</b> und <b>Toleranz gegenüber anderen Kulturen zeigen</b>.</p>',long:LONG};
function active(){var t=(document.getElementById('lessonTitle')||{}).textContent||'';return t.indexOf('Schreiben_fehler_5')>-1||t.indexOf('Schreibfehler 5')>-1||t.indexOf('Mindestlohn, betriebliche Kosten')>-1;}
function visible(){var x=document.getElementById('lesson');return !x||!/(^|\s)hide(\s|$)/.test(x.className||'');}
function render(){if(!visible()||!active())return;var title=document.getElementById('lessonTitle'),meta=document.getElementById('lessonMeta'),content=document.getElementById('lessonContent');if(title)title.textContent='Lektion: Schreiben_fehler_5 · Mindestlohn, betriebliche Kosten, Arbeitsmarkt, Inflation und Mehrsprachigkeit';if(meta)meta.textContent='Niveau: C1/C2 · Deutsch';if(content&&content.innerHTML!==LONG)content.innerHTML=LONG;}
render();setTimeout(render,200);setTimeout(render,900);setInterval(render,200);document.addEventListener('click',function(){setTimeout(render,80);setTimeout(render,300);setTimeout(render,900);},true);try{new MutationObserver(function(){setTimeout(render,30);}).observe(document.documentElement,{childList:true,subtree:true,characterData:true});}catch(e){}
window.AAYS_SF2_5_SOURCE_WORD_OK=true;
})();