window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};
window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};

window.DEUTSCH_TESTS.t43={
  category:'Bevor Schreiben',
  slug:'freizeit_planen_nachteile_c1_c2',
  title:'Freizeit planen – Nachteile · C1/C2 Nachteilsabsatz',
  topic:'Erörterung · Nachteile · Freizeitplanung',
  source:'Freizeitplanung_Nachteile_4_C1_C2_15_20_pruefungsnah.docx',
  words:['die Spontaneität','die persönliche Freiheit','der Termindruck','die Überplanung','die innere Ruhe','die Erholung','die Work-Life-Balance','die mentale Belastung','die Frustration','die Planänderung','der Erholungswert','die soziale Beziehung','die Gelassenheit','die Lebensfreude'],
  fill:[
    ['Eine zu starke Freizeitplanung kann die ____ einschränken.','Spontaneität','Nomen'],
    ['Wenn jeder freie Moment geplant wird, kann zusätzlicher ____ entstehen.','Termindruck','Nomen'],
    ['Zu viele Termine können den ____ der Freizeit verringern.','Erholungswert','Nomen'],
    ['Starre Pläne können bei Änderungen ____ auslösen.','Frustration','Nomen'],
    ['Freizeit sollte Raum für Erholung und ____ lassen.','Spontaneität','Nomen'],
    ['Eine flexible Planung hilft, soziale Konflikte zu ____.','vermeiden','Verb'],
    ['Wer Pausen ständig kontrolliert, kann innere Ruhe ____.','verlieren','NVV'],
    ['Bei zu vielen Aktivitäten kann sich die Work-Life-Balance ____.','verschlechtern','Verb']
  ],
  mc:[
    ['Welche Nomen-Verb-Verbindung ist korrekt?',['Spontaneität einschränken','Spontaneität machen','Spontaneität tun','Spontaneität gehen','Spontaneität haben machen'],0,'NVV'],
    ['Welche Formulierung passt in einen Nachteilsabsatz?',['Ein zentraler Nachteil liegt darin, dass zu starre Freizeitplanung zusätzlichen Termindruck erzeugen kann.','Freizeitplanung ist schlecht, weil Freizeit schlecht ist.','Man plant Freizeit und alles ist immer falsch.','Nachteile sind, wenn Menschen keine Freizeit mögen.','Planung macht automatisch Probleme.'],0,'Satzbaustein'],
    ['Welche Präposition ist korrekt?',['unter Termindruck geraten','in Termindruck geraten','auf Termindruck geraten','mit Termindruck geraten','für Termindruck geraten'],0,'Präposition'],
    ['Welche Verbindung ist prüfungsnah?',['den Erholungswert verringern','den Erholungswert machen','den Erholungswert tun','den Erholungswert gehen','den Erholungswert bekommen machen'],0,'NVV'],
    ['Welche Aussage ist differenziert formuliert?',['Freizeitplanung ist nicht grundsätzlich negativ; problematisch wird sie, wenn sie zu starr oder zu voll wird.','Freizeitplanung ist immer falsch.','Alle Menschen sollen spontan bleiben.','Termine sind grundsätzlich schlecht.','Wer plant, hat keine Freizeit.'],0,'Differenzierung'],
    ['Welche Formulierung drückt eine Folge aus?',['Dies führt dazu, dass Freizeit weniger entspannend wirkt.','Trotzdem Freizeit weil Plan.','Freizeit hat auch viele Dinge.','Man kann sagen Freizeit.','Die Planung und der Kalender.'],0,'Folge'],
    ['Welche Präposition passt? Freizeit sollte Raum ___ spontane Entscheidungen lassen.',['für','mit','gegen','durch','über'],0,'Präposition'],
    ['Welche Wendung passt zu sozialen Konflikten?',['Rücksicht auf andere nehmen','Rücksicht mit andere machen','Rücksicht zu andere gehen','Rücksicht von andere tun','Rücksicht andere setzen'],0,'NVV']
  ],
  tf:[
    ['Freizeitplanung kann problematisch werden, wenn sie zu starr wird.',true,'Argument'],
    ['Zu viel Planung kann den freien Charakter der Freizeit schwächen.',true,'Inhalt'],
    ['Freizeitplanung ist in jedem Fall negativ.',false,'Differenzierung'],
    ['Ein voller Freizeitkalender kann zusätzlichen Stress verursachen.',true,'NVV'],
    ['Erholung muss immer produktiv und genau kontrolliert sein.',false,'Bewertung'],
    ['Starre Pläne können soziale Beziehungen belasten.',true,'Argument']
  ],
  wordMatch:[
    ['die Spontaneität','Fähigkeit, frei und ohne festen Plan zu handeln'],
    ['der Termindruck','Druck durch zu viele oder zu enge Termine'],
    ['die Überplanung','zu genaue oder zu volle Organisation der Zeit'],
    ['der Erholungswert','die entspannende Wirkung einer freien Zeit'],
    ['die Gelassenheit','ruhiger und flexibler Umgang mit Änderungen'],
    ['die mentale Belastung','psychischer Druck oder innere Anspannung']
  ],
  phraseMatch:[
    ['Spontaneität','einschränken'],
    ['zusätzlichen Stress','verursachen'],
    ['Erholung','erschweren'],
    ['innere Ruhe','verlieren'],
    ['soziale Beziehungen','belasten'],
    ['Flexibilität','bewahren'],
    ['Freizeit zur Pflicht','machen'],
    ['den Erholungswert','verringern']
  ],
  prep:[
    ['Menschen können ___ Termindruck geraten.','unter','unter Termindruck geraten'],
    ['Freizeit sollte Raum ___ spontane Entscheidungen lassen.','für','Raum für + Akkusativ'],
    ['Ein Nachteil liegt ____, dass Freizeit zur Pflicht werden kann.','darin','liegen darin, dass'],
    ['Planung sollte sich ___ den eigenen Bedürfnissen orientieren.','an','sich orientieren an + Dativ']
  ],
  hang:['Spontaneität einschränken','unter Termindruck geraten','Freizeit zur Pflicht machen','Erholung erschweren','innere Ruhe verlieren','soziale Beziehungen belasten','Flexibilität bewahren','den Erholungswert verringern','zusätzlichen Stress verursachen','Planung lockern']
};

window.DEUTSCH_LESSONS.t43={
  source:'Freizeitplanung_Nachteile_4_C1_C2_15_20_pruefungsnah.docx',
  short:'<h3>Freizeit planen – Nachteile · Kurz</h3><p>Freizeitplanung ist nicht automatisch schlecht. Problematisch wird sie, wenn sie zu streng, zu voll oder zu leistungsorientiert ist. Dann kann freie Zeit ihren freien Charakter verlieren: Spontaneität nimmt ab, Termindruck steigt, echte Erholung wird schwieriger und soziale Kontakte können belastet werden.</p>',
  medium:'<h3>Freizeit planen – Nachteile · Mittel</h3><p>Eine zu starke Freizeitplanung kann in einer Erörterung als Nachteil dargestellt werden, wenn sie freie Zeit wie einen zweiten Arbeitsplan behandelt. Statt Erholung und Leichtigkeit entstehen dann Kalenderdruck, Selbstkontrolle und Frustration. Besonders kritisch ist, dass Menschen sich auch in der Freizeit verpflichtet fühlen, etwas Sinnvolles oder Produktives zu tun. Dadurch sinkt der Erholungswert. Außerdem können starre Pläne soziale Konflikte auslösen, wenn Freunde, Familie oder eigene Bedürfnisse nicht zum Plan passen.</p>',
  long:`<h3>Freizeit planen – Nachteile · ausführliche C1/C2-Konuanlatımı</h3>
<p><b>Quelle:</b> Freizeitplanung_Nachteile_4_C1_C2_15_20_pruefungsnah.docx</p>
<p><b>Ziel:</b> Dieses Kapitel ist nur für die Nachteile der Freizeitplanung gedacht. Es trennt den Nachteilsabsatz klar vom vorhandenen Vorteilsabsatz. Im Mittelpunkt steht nicht die Behauptung, Planung sei grundsätzlich schlecht, sondern eine differenzierte C1/C2-Position: Freizeitplanung kann nützlich sein, wird aber problematisch, wenn sie zu starr, zu voll oder zu leistungsorientiert wird.</p>

<h4>1. Kurze Orientierung zum Thema</h4>
<p>Freizeitplanung bedeutet, dass Menschen freie Zeit bewusst organisieren. Sie planen zum Beispiel Sport, Treffen mit Freunden, Familienzeit, Hobbys, Erholung, Ausflüge oder digitale Pausen. Auf den ersten Blick wirkt das sinnvoll, weil Planung Orientierung gibt und verhindert, dass Zeit unbewusst vergeht. In einem Nachteilsaufsatz musst du jedoch zeigen, dass Planung auch kippen kann. Freizeit soll eigentlich Freiheit, Spontaneität, Entspannung und Abstand vom Alltag ermöglichen. Wenn jeder freie Abend oder jedes Wochenende schon im Voraus festgelegt ist, kann Freizeit ihren offenen Charakter verlieren.</p>
<p>Für die Prüfung ist besonders wichtig: Schreibe nicht einfach „Freizeitplanung ist schlecht“. Das wäre zu undifferenziert. Besser ist: Freizeitplanung ist dann problematisch, wenn sie freie Zeit in einen zusätzlichen Pflichtbereich verwandelt. Genau diese Einschränkung wirkt auf C1/C2-Niveau reif, weil sie zeigt, dass du nicht schwarz-weiß argumentierst. Du kannst schreiben, dass Planung Orientierung geben kann, aber gleichzeitig Flexibilität und ungeplante Ruhe erhalten bleiben müssen.</p>

<h4>2. Grundthese für deine Erörterung</h4>
<p>Eine zu starke Freizeitplanung kann problematisch sein, weil sie Spontaneität einschränkt, zusätzlichen Termindruck erzeugt, echte Erholung erschwert und soziale Beziehungen belasten kann. Freizeit wird dann nicht mehr als freier Raum erlebt, sondern wie ein weiterer Teil des Pflichtalltags.</p>
<p><b>Prüfungsformel:</b> Beobachtung → Erklärung → Beispiel → Ergebnis → Risiko → Anwendungsbereich → kurz- und langfristige Wirkung → Bewertung.</p>

<h4>3. Allgemeines Wortfeld</h4>
<table><tr><td><b>Nomen</b></td><td>die Freizeitplanung, die freie Zeit, die Spontaneität, die Freiheit, der Termindruck, die Überplanung, die innere Ruhe, die Erholung, die Work-Life-Balance, die mentale Belastung, die Frustration, die Planänderung, der Erholungswert, die soziale Beziehung, die Gelassenheit, die Lebensfreude, die Selbstkontrolle, die Entspannungsfähigkeit.</td></tr><tr><td><b>Verben / NVV</b></td><td>Spontaneität einschränken, zusätzlichen Stress verursachen, unter Termindruck geraten, Freizeit zur Pflicht machen, Erholung erschweren, Ruhephasen vernachlässigen, den Erholungswert verringern, innere Ruhe verlieren, soziale Beziehungen belasten, Flexibilität bewahren, Planung lockern, auf Bedürfnisse achten, Konflikte vermeiden, Rücksicht nehmen.</td></tr><tr><td><b>Adjektive</b></td><td>starr, überplant, verpflichtend, unflexibel, belastend, hektisch, kontrolliert, angespannt, erschöpfend, fremdbestimmt, frustrierend, weniger erholsam, sozial belastend, unausgeglichen.</td></tr></table>

<h4>Nachteil 1: Weniger Spontaneität und weniger persönliche Freiheit</h4>
<table><tr><td><b>Kurze Idee</b></td><td>Ein erster Nachteil besteht darin, dass zu viel Freizeitplanung die Spontaneität einschränken kann. Freizeit soll eigentlich Raum für freie Entscheidungen bieten. Wenn aber jeder Abend, jeder Kurs, jedes Treffen und jedes Wochenende schon im Kalender steht, bleibt wenig Platz für ungeplante Momente. Dadurch wirkt Freizeit nicht mehr offen, sondern kontrolliert.</td></tr><tr><td><b>Beobachtungen aus dem Alltag</b></td><td>Viele Menschen planen jeden Abend im Voraus, füllen Wochenenden mit mehreren Aktivitäten, halten sich stark an Kalender und To-do-Listen oder erleben sogar Hobbys als feste Pflichttermine. Spontane Treffen mit Freunden werden schwieriger, weil der Plan kaum Lücken enthält. Selbst Erholung wird manchmal vorher genau festgelegt.</td></tr><tr><td><b>Detaillierte Erklärung</b></td><td>Planung gibt zwar Orientierung, aber sie kann auch Freiheit begrenzen. In der Freizeit ändern sich Bedürfnisse häufig: Manchmal möchte man Freunde sehen, manchmal braucht man Ruhe, manchmal ergibt sich eine gute Gelegenheit unerwartet. Wenn ein Plan zu starr ist, entscheidet nicht mehr das aktuelle Bedürfnis, sondern der Kalender. Besonders für Menschen, die schon im Beruf, im Studium oder in der Familie stark organisiert leben müssen, kann eine zusätzlich durchgeplante Freizeit den Eindruck verstärken, nie wirklich frei zu sein.</td></tr><tr><td><b>Konkrete Beispiele</b></td><td>Ein spontaner Spaziergang fällt aus, weil bereits ein Kurs geplant ist. Ein Freund möchte sich kurzfristig treffen, aber der Kalender ist voll. Ein freier Abend wird sofort mit Aufgaben gefüllt. Jemand fühlt sich schuldig, wenn ein geplanter Sporttermin ausfällt. Ein Familienbesuch wird nicht als schöne Begegnung erlebt, sondern als Pflichttermin. Eine Planänderung führt zu innerer Unruhe.</td></tr><tr><td><b>Folgen</b></td><td>Die Folge kann weniger Spontaneität, geringere persönliche Freiheit, innere Anspannung und weniger Offenheit für neue Erfahrungen sein. Freizeit wird als Pflicht empfunden. Menschen verlieren leichter den Kontakt zu ihren aktuellen Bedürfnissen.</td></tr><tr><td><b>C1/C2-Wörter und NVV</b></td><td>die Spontaneität, die persönliche Freiheit, die Selbstkontrolle, die Fremdbestimmung, die Leichtigkeit, die Planänderung; Spontaneität einschränken, Flexibilität verringern, Freizeit zur Pflicht machen, Spielraum lassen, auf Bedürfnisse achten, einen Plan lockern.</td></tr></table>
<p><b>Musterabsatz:</b> Ein wesentlicher Nachteil der Freizeitplanung liegt darin, dass sie die Spontaneität einschränken kann. Wenn jeder freie Abend oder jedes Wochenende im Voraus festgelegt wird, bleibt wenig Raum für spontane Entscheidungen. Menschen richten sich dann stärker nach ihrem Kalender als nach ihren aktuellen Bedürfnissen. Gerade Freizeit sollte jedoch Freiheit und Leichtigkeit ermöglichen. Wenn sie zu stark geplant wird, kann sie sich wie ein weiterer Pflichtbereich anfühlen. Langfristig kann dies dazu führen, dass man weniger flexibel lebt und spontane soziale Kontakte seltener entstehen.</p>

<h4>Nachteil 2: Zusätzlicher Stress durch Überplanung und Termindruck</h4>
<table><tr><td><b>Kurze Idee</b></td><td>Ein zweiter Nachteil besteht darin, dass Freizeitplanung zusätzlichen Stress verursachen kann. Wer seine freie Zeit mit zu vielen Aktivitäten füllt, hat zwar einen vollen Kalender, aber nicht automatisch mehr Lebensqualität. Besonders problematisch ist, wenn Freizeitaktivitäten wie Aufgaben behandelt werden und dadurch neuer Termindruck entsteht.</td></tr><tr><td><b>Beobachtungen aus dem Alltag</b></td><td>Der Kalender ist auch am Wochenende voll. Mehrere Freizeitaktivitäten finden an einem Tag statt. Menschen hetzen von einem Termin zum nächsten. Hobbys, Kurse, Sport und Treffen müssen ständig koordiniert werden. Am Sonntagabend fühlen sich manche erschöpfter als vor dem Wochenende.</td></tr><tr><td><b>Detaillierte Erklärung</b></td><td>Freizeitplanung soll eigentlich entlasten. Sie kann aber das Gegenteil bewirken, wenn zu viele Aktivitäten eingeplant werden. Dann entsteht das Gefühl, jede freie Stunde sinnvoll nutzen zu müssen. Aus Freizeit wird eine Art zweiter Arbeitsplan. Im modernen Alltag wollen viele Menschen auch in ihrer Freizeit produktiv wirken: Sport treiben, Freunde treffen, sich weiterbilden, gesund kochen, die Wohnung ordnen und gleichzeitig erholen. Wenn alles gleichzeitig passieren soll, entsteht kein Ausgleich, sondern neue Hektik.</td></tr><tr><td><b>Konkrete Beispiele</b></td><td>Am Samstag stehen Sport, Einkaufen, Familienbesuch und Freunde direkt hintereinander auf dem Plan. Nach der Arbeit folgen Fitnessstudio, Sprachkurs und Haushalt. Ein Hobby wird belastend, weil man regelmäßig erscheinen muss. Ein Urlaubstag wird so stark geplant, dass man sich kaum erholt. Ein Termin dauert länger als erwartet und bringt den ganzen Tagesplan durcheinander.</td></tr><tr><td><b>Folgen und Risiken</b></td><td>Mögliche Folgen sind mehr Termindruck, weniger Erholung, Hektik, mentale Belastung und eine schlechtere Work-Life-Balance. Langfristig können Überforderung, dauerhafte innere Unruhe und Erschöpfung entstehen. Freizeit verliert dann ihren eigentlichen Erholungswert.</td></tr><tr><td><b>C1/C2-Wörter und NVV</b></td><td>der Termindruck, die Überplanung, die Hektik, die Überforderung, die Erschöpfung, die Doppelbelastung, der volle Kalender; zusätzlichen Stress verursachen, den Kalender überfüllen, von Termin zu Termin hetzen, Ruhephasen vernachlässigen, unter Termindruck geraten, den Erholungswert verringern.</td></tr></table>
<p><b>Musterabsatz:</b> Ein weiterer Nachteil der Freizeitplanung besteht darin, dass sie zusätzlichen Stress verursachen kann. Viele Menschen versuchen, ihre freie Zeit möglichst sinnvoll zu nutzen und planen deshalb zahlreiche Aktivitäten. Nach Arbeit, Studium oder Schule folgen dann Sport, Treffen, Kurse oder Familienbesuche. Dadurch entsteht schnell ein voller Kalender. Statt sich zu erholen, hetzt man von Termin zu Termin. Infolgedessen verliert Freizeit ihren eigentlichen Erholungswert und kann sogar zu Überforderung führen.</p>

<h4>Nachteil 3: Verlust echter Erholung und innerer Ruhe</h4>
<table><tr><td><b>Kurze Idee</b></td><td>Ein dritter Nachteil ist der mögliche Verlust echter Erholung. Freizeit ist nicht nur dazu da, Aufgaben zu erledigen oder Aktivitäten zu sammeln. Sie soll auch Raum für Ruhe, Nichtstun und Abstand vom Alltag bieten. Wenn Freizeit zu stark geplant wird, kann sogar Erholung zu einer Aufgabe werden.</td></tr><tr><td><b>Beobachtungen aus dem Alltag</b></td><td>Viele Menschen wollen ihre Freizeit produktiv nutzen. Nichtstun gilt als Zeitverschwendung. Pausen werden geplant und bewertet. Soziale Medien zeigen produktive Freizeit, perfekte Routinen und Selbstoptimierung. Manche fühlen sich beim Ausruhen schuldig. Entspannung wird in Apps, Kalender oder To-do-Listen eingetragen.</td></tr><tr><td><b>Detaillierte Erklärung</b></td><td>Erholung braucht nicht immer einen festen Plan. Manchmal ist gerade das Ungeplante wichtig, damit der Kopf zur Ruhe kommt. Wer jede freie Stunde mit einem Ziel verbindet, kann schwer abschalten. Dann wird Freizeit mit Leistung verbunden. Das Problem liegt nicht darin, dass jemand Sport macht oder liest. Problematisch wird es, wenn jede Aktivität einen Zweck erfüllen muss: gesünder werden, produktiver werden, sozialer sein, mehr lernen oder sich selbst optimieren. Dadurch verliert freie Zeit ihre entspannende Funktion.</td></tr><tr><td><b>Konkrete Beispiele</b></td><td>Ein Spaziergang muss gleichzeitig Fitnessziel erfüllen. Lesen steht als Pflicht auf einer Liste. Yoga wird nicht zur Entspannung, sondern zum Pflichtprogramm. Ein freier Sonntag wird mit Haushalt, Kursen und Selbstoptimierungsaufgaben gefüllt. Jemand fühlt sich schlecht, wenn er schläft oder einfach nichts tut. Erholung wird mit Apps und Routinen kontrolliert.</td></tr><tr><td><b>Folgen</b></td><td>Die Folgen können weniger innere Ruhe, schlechtere Erholung, mehr Selbstkontrolle, geringerer Genuss und mentale Müdigkeit sein. Langfristig kann die Entspannungsfähigkeit abnehmen. Freizeit verliert ihren Sinn, wenn sie nur noch als weiterer Leistungsbereich verstanden wird.</td></tr><tr><td><b>C1/C2-Wörter und NVV</b></td><td>die Regeneration, die innere Ruhe, das Nichtstun, das schlechte Gewissen, die Entspannungsfähigkeit, die mentale Erschöpfung; Erholung erschweren, innere Ruhe verlieren, Freizeit kontrollieren, Entspannung verhindern, Regeneration beeinträchtigen, Druck zur Selbstoptimierung erzeugen.</td></tr></table>
<p><b>Musterabsatz:</b> Auch der Verlust echter Erholung spricht gegen eine zu starke Freizeitplanung. Freizeit sollte eigentlich Raum für Entspannung, Ruhe und Abstand vom Alltag bieten. Wenn jedoch jede freie Stunde geplant wird, entsteht das Gefühl, auch in der Freizeit etwas leisten zu müssen. Manche Menschen fühlen sich sogar schuldig, wenn sie einfach nichts tun. Dadurch wird Erholung erschwert. Langfristig kann dies zu innerer Unruhe, mentaler Erschöpfung und sinkender Lebensqualität führen.</p>

<h4>Nachteil 4: Frustration und soziale Konflikte durch starre Pläne</h4>
<table><tr><td><b>Kurze Idee</b></td><td>Ein vierter Nachteil liegt darin, dass zu feste Freizeitpläne Frustration und Konflikte verursachen können. Freizeit hängt oft von anderen Menschen, vom Wetter, von Stimmung oder von unerwarteten Ereignissen ab. Wenn Pläne zu starr sind, reagieren Menschen schneller enttäuscht oder gereizt, wenn etwas nicht funktioniert.</td></tr><tr><td><b>Beobachtungen aus dem Alltag</b></td><td>Freunde haben unterschiedliche Zeitpläne. Familienmitglieder haben verschiedene Bedürfnisse. Wetter oder Müdigkeit passen nicht zum Plan. Treffen werden verschoben. Eine kurzfristige Absage wird persönlich genommen. Geplante Aktivitäten erzeugen Erwartungen, die nicht immer erfüllt werden.</td></tr><tr><td><b>Detaillierte Erklärung</b></td><td>Freizeit ist selten vollständig kontrollierbar. Gerade soziale Aktivitäten hängen davon ab, ob andere Menschen Zeit, Lust und Energie haben. Wenn man zu stark an einem Plan festhält, können kleine Änderungen als Störung empfunden werden. Dadurch entstehen unnötige Konflikte. Ein weiterer Punkt ist die Erwartung: Wenn eine Aktivität lange geplant wurde, erwartet man oft, dass sie besonders schön oder erholsam wird. Wenn die Realität anders ist, entsteht Enttäuschung. Somit kann Planung nicht nur Ordnung schaffen, sondern auch Druck auf Beziehungen ausüben.</td></tr><tr><td><b>Konkrete Beispiele</b></td><td>Ein Freund sagt kurzfristig ab und man ist stark enttäuscht. Ein Familienausflug wird geplant, aber jemand ist krank oder müde. Schlechtes Wetter zerstört einen Wochenendplan. Ein Partner möchte spontan etwas anderes machen, aber der Plan steht fest. Kinder haben andere Bedürfnisse als im Kalender vorgesehen. Freunde fühlen sich unter Druck gesetzt, weil jedes Treffen organisiert ist.</td></tr><tr><td><b>Folgen und Risiken</b></td><td>Mögliche Folgen sind Frustration, weniger Gelassenheit, soziale Konflikte, höhere Erwartungen und angespannte Kommunikation. Langfristig kann eine zu starre Freizeitplanung Beziehungen belasten, weil Rücksicht und Flexibilität abnehmen. Planung wird dann wichtiger als das eigentliche gemeinsame Erlebnis.</td></tr><tr><td><b>C1/C2-Wörter und NVV</b></td><td>die Frustration, der soziale Konflikt, die starre Planung, die Erwartung, die Enttäuschung, die Rücksichtnahme, die Kompromissbereitschaft; Frustration auslösen, Konflikte verursachen, an starren Plänen festhalten, Erwartungen erhöhen, Kompromisse finden, soziale Beziehungen belasten, Flexibilität bewahren.</td></tr></table>
<p><b>Musterabsatz:</b> Ein weiterer Nachteil der Freizeitplanung liegt in möglichen sozialen Konflikten. Freizeitaktivitäten hängen oft von anderen Menschen, vom Wetter oder von der eigenen Stimmung ab. Wenn Pläne zu starr sind, können kleine Änderungen schnell Frustration auslösen. Zum Beispiel kann eine kurzfristige Absage eines Freundes oder schlechtes Wetter einen ganzen Wochenendplan durcheinanderbringen. Wer dann nicht flexibel reagieren kann, erlebt Freizeit weniger entspannt. Langfristig kann eine zu strenge Planung Beziehungen belasten, weil Erwartungen steigen und spontane Bedürfnisse weniger berücksichtigt werden.</p>

<h4>Einleitungssätze</h4>
<ul><li>In der heutigen Gesellschaft wird häufig darüber diskutiert, wie Menschen ihre Freizeit sinnvoll gestalten sollten.</li><li>Auf den ersten Blick wirkt Freizeitplanung hilfreich, weil sie Ordnung und Übersicht schafft.</li><li>Bei genauerer Betrachtung zeigt sich jedoch, dass eine zu starke Planung auch Nachteile mit sich bringen kann.</li><li>Besonders problematisch ist, dass Freizeit ihren freien Charakter verlieren kann, wenn sie zu streng organisiert wird.</li></ul>
<h4>Schluss-Satzbausteine</h4>
<ul><li>Abschließend lässt sich festhalten, dass Freizeitplanung nicht nur Vorteile, sondern auch deutliche Nachteile haben kann.</li><li>Meiner Ansicht nach sollte Freizeit nicht vollständig durchgeplant werden, weil sie sonst ihren Erholungswert verliert.</li><li>Entscheidend ist, dass Planung Orientierung gibt, aber nicht zur zusätzlichen Belastung wird.</li><li>Eine gute Lösung besteht darin, wichtige Termine zu planen, aber gleichzeitig freie Zeitfenster offen zu lassen.</li></ul>
<h4>Kopya kâğıdı</h4>
<p><b>Wichtigste Wörter:</b> die Spontaneität, die Freiheit, der Termindruck, die Überplanung, die innere Ruhe, die mentale Belastung, die Frustration, die Planänderung, die Work-Life-Balance, die Lebensfreude, die soziale Beziehung, die Gelassenheit.</p>
<p><b>Wichtigste NVV:</b> Spontaneität einschränken, zusätzlichen Stress verursachen, Freizeit zur Pflicht machen, unter Termindruck geraten, Erholung erschweren, Ruhephasen vernachlässigen, den Erholungswert verringern, innere Ruhe verlieren, soziale Beziehungen belasten, Flexibilität bewahren.</p>
<p><b>Mini-Merksätze:</b> zu viel Planung → weniger Spontaneität → weniger Freiheit. Voller Kalender → Hektik → mehr Stress. Freizeit als Pflicht → weniger Erholung → mentale Erschöpfung. Starre Pläne → hohe Erwartungen → Enttäuschung → soziale Konflikte.</p>
<h4>Übungen</h4>
<p><b>Lückensätze:</b> 1. Ein zentraler Nachteil liegt darin, dass Planung die ____ einschränken kann. 2. Zu viele Aktivitäten können zusätzlichen ____ verursachen. 3. Wenn Freizeit wie eine Pflicht wirkt, verliert sie ihren ____. 4. Starre Pläne können soziale ____ verursachen. 5. Freizeit sollte auch Raum für ____ und innere Ruhe bieten.</p>
<p><b>Sätze verbinden:</b> Viele Menschen planen ihr Wochenende sehr genau. Dadurch entsteht manchmal neuer Termindruck. / Freizeit soll eigentlich erholen. Zu viel Planung kann diesen Zweck verhindern. / Freunde sagen kurzfristig ab. Starre Pläne können dadurch Frustration auslösen.</p>
<p><b>Çeviri:</b> Çok fazla boş zaman planlaması spontane kararları sınırlandırabilir. Boş zaman bir görev gibi hissedildiğinde gerçek dinlenme zorlaşır. Dolu bir takvim yeni stres yaratabilir. Uzun vadede bu durum yaşam kalitesini azaltabilir.</p>
<p><b>Schreibaufgabe:</b> Schreibe einen Absatz mit 120–150 Wörtern zum Thema: Warum kann zu starke Freizeitplanung echte Erholung erschweren? Nutze mindestens fünf Wörter aus der Wortliste und zwei Satzbausteine.</p>`
};
