(function(){
  var KEY='t36';
  window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};
  window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};
  window.LESSONS=window.LESSONS||{};
  function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\n/g,'<br>');}
  function table(rows){var h='<table class="satzmuster-table"><thead><tr>'; rows[0].forEach(function(c){h+='<th>'+esc(c)+'</th>';}); h+='</tr></thead><tbody>'; rows.slice(1).forEach(function(r){h+='<tr>'; r.forEach(function(c){h+='<td>'+esc(c)+'</td>';}); h+='</tr>';}); return h+'</tbody></table>';}
  function box(title, lines){return '<table class="satzmuster-table"><tbody><tr><td><b>'+esc(title)+'</b><br>'+esc(lines.join('\n'))+'</td></tr></tbody></table>';}
  var intro='<style>.satzmuster-wrap{font-family:Arial,Helvetica,sans-serif;line-height:1.55}.satzmuster-wrap h3{font-family:Georgia,serif;color:#183642;margin-top:0}.satzmuster-wrap h4{font-family:Georgia,serif;color:#8a5a44;margin:22px 0 8px}.satzmuster-table{width:100%;border-collapse:collapse;margin:12px 0;font-size:14px}.satzmuster-table th{background:#183642;color:#fff;text-align:left;padding:9px;border:1px solid #183642}.satzmuster-table td{vertical-align:top;border:1px solid #d8d3ca;padding:8px;background:#fff}.satzmuster-table tr:nth-child(even) td{background:#fcfbf8}.satzmuster-source{font-size:13px;color:#6b7280;margin-bottom:12px}.satzmuster-box{border:1px solid #d8d3ca;background:#fcfbf8;border-radius:12px;padding:12px;margin:12px 0}</style><div class="satzmuster-wrap"><h3>Satzmustern 1 – C1/C2 Erörterung: Satzmuster sicher lernen</h3><p class="satzmuster-source">Quelle: C1_C2_Eroerterung_Satzmuster_Konuanlatimi(1).docx. Konu anlatımı + kullanım mantığı + örnekler + kopya kâğıdı.</p>';
  var long=intro+
  box('Amaç',['Bu dosya, C1/C2 düzeyinde Erörterung yazarken kullanabileceğin kalıpları ezberlemek için hazırlandı.','Her kalıp; kullanım yeri, Türkçe mantığı ve sınavda uygulanabilecek örnek cümlelerle verildi.','Kalıpları tek tek ezberlemek yerine, metindeki görevlerine göre öğren: giriş, karşılaştırma, gerekçe, sonuç, etki ve alternatif.'])+
  '<h4>0. Ezberleme mantığı: Kalıbı değil, görevini öğren</h4><ul><li>Girişte durum tarif etmek için: Es scheint, dass ... / Es sieht so aus, als ob ... / heutzutage ...</li><li>Genel kabul veya veri göstermek için: Es gilt als allgemein anerkannt, dass ... / Aktuelle Statistiken belegen, dass ...</li><li>Avantaj-dezavantaj başlatmak için: Ein wesentlicher Vorteil/Nachteil besteht darin, dass ...</li><li>Sebep vermek için: Dies lässt sich damit begründen, dass ... / Der Grund dafür liegt darin, dass ...</li><li>Sonuç çıkarmak için: Daraus ergibt sich, dass ... / Infolgedessen könnte ...</li><li>Etkiyi açıklamak için: X beeinflusst Y dahingehend, dass ...</li><li>Alternatif veya yanlış davranış göstermek için: Anstatt ... zu ..., neigt ... dazu, ... zu ...</li></ul>'+box('Altın formül',['Konu + Kalıp + Sebep + Sonuç = güçlü C1/C2 cümlesi','Örnek: Werbung beeinflusst Konsumenten dahingehend, dass sie dazu neigen, Entscheidungen zu treffen, die weniger auf eigenem Bedarf als auf äußerer Beeinflussung beruhen.'])+
  '<h4>1. Girişte durum tasvir etme</h4><p>Bu kalıplar metnin ilk cümlelerinde kullanılır. Amaç, konuyu doğrudan tartışmaya başlamadan önce mevcut durumu akademik ama anlaşılır biçimde tanıtmaktır.</p>'+table([
  ['Funktion','DEU-Kalip','TR-Anlam','Beispiel / Einsatz'],['Giriş / izlenim','Es scheint, dass ...','... gibi gözüküyor','Es scheint, dass digitale Medien den Alltag vieler Menschen stärker prägen als früher.'],['Giriş / izlenim','Es sieht so aus, als ob ...','... gibi gözüküyor','Es sieht so aus, als ob immer mehr Studierende digitale Lernangebote nutzen.'],['Zaman ifadesi','heutzutage / derzeit / zurzeit / in diesen Tagen','günümüzde / şu anda / bu günlerde','Heutzutage spielen soziale Medien bei der Meinungsbildung eine zentrale Rolle.'],['Genel kabul','Es gilt als allgemein anerkannt, dass ...','Genel olarak kabul edilen görüş şudur:','Es gilt als allgemein anerkannt, dass Bildung eine wichtige Grundlage für berufliche Chancen bildet.'],['Veri ile giriş','Aktuelle Statistiken belegen, dass ...','Güncel istatistikler göstermektedir ki ...','Aktuelle Statistiken belegen, dass der Anteil digitaler Lernangebote in den letzten Jahren gestiegen ist.']])+
  box('Sınavda kullanma taktiği',['Girişte kesin konuşmak istemiyorsan: Es scheint, dass ...','Daha akademik başlamak istiyorsan: Es gilt als allgemein anerkannt, dass ...','Grafik veya istatistik anlatıyorsan: Aktuelle Statistiken belegen, dass ...'])+
  '<h4>2. Durumu açıklama ve A-B ilişkisini kurma</h4><p>Bu bölüm özellikle konu anlatımında çok işe yarar. Bir konuyu açıklamadan önce iki unsur arasındaki ilişkiyi göstermek C1/C2 seviyesinde daha olgun bir yazı etkisi verir.</p>'+table([
  ['Funktion','DEU-Kalip','TR-Anlam','Beispiel / Einsatz'],['Durumu açıklama','Um die vorliegende Situation angemessen zu erläutern, muss zunächst ...','Mevcut durumu uygun şekilde açıklamak için öncelikle ...','Um die vorliegende Situation angemessen zu erläutern, muss zunächst der Zusammenhang zwischen Medienkonsum und Meinungsbildung betrachtet werden.'],['Anlama koşulu','Für ein angemessenes Verständnis der Situation ist es unerlässlich, ...','Durumu doğru anlamak için ... gereklidir','Für ein angemessenes Verständnis der Situation ist es unerlässlich, sowohl soziale als auch wirtschaftliche Faktoren zu berücksichtigen.'],['A-B ilişkisi','Zunächst ist zu klären, wie [A] mit [B] zusammenhängt.','Öncelikle A ile B arasındaki bağlantı açıklanmalıdır.','Zunächst ist zu klären, wie Werbung mit Konsumdruck zusammenhängt.'],['A-B ilişkisi','Um [Thema] angemessen zu erläutern, muss zunächst geklärt werden, inwiefern [A] und [B] zusammenhängen.','Konuyu açıklamak için A ve B’nin ne ölçüde ilişkili olduğu açıklanmalıdır.','Um Online-Studium angemessen zu erläutern, muss zunächst geklärt werden, inwiefern Flexibilität und Bildungsgerechtigkeit zusammenhängen.']])+
  box('Ezber iskeleti',['Zunächst ist zu klären, wie A mit B zusammenhängt.','Entscheidend ist dabei, dass ...','Bu iki cümle birlikte kullanıldığında konu anlatımı çok daha akademik görünür.'])+
  '<h4>3. Vorteile / Nachteile başlatma kalıpları</h4><p>Erörterung yazısında paragrafın ilk cümlesi çok önemlidir. Aşağıdaki kalıplar avantaj veya dezavantaj paragrafına güçlü bir başlangıç yapmanı sağlar.</p>'+table([
  ['Funktion','DEU-Kalip','TR-Anlam','Beispiel / Einsatz'],['Ana argüman','Ein wesentlicher Vorteil/Nachteil von ... besteht darin, dass ...','Önemli bir avantaj/dezavantaj şudur ki ...','Ein wesentlicher Nachteil von Fertiggerichten besteht darin, dass sie eine unausgewogene Ernährung begünstigen können.'],['Ana argüman','Ein zentraler Aspekt ... ist, dass ...','Önemli bir husus şudur ki ...','Ein zentraler Aspekt des Online-Studiums ist, dass Studierende ortsunabhängig lernen können.'],['Sorun vurgusu','Problematisch ist insbesondere, dass ...','Özellikle sorunlu olan şudur ki ...','Problematisch ist insbesondere, dass soziale Medien unrealistische Ideale vermitteln können.'],['Lehine/aleyhine','Dafür/dagegen spricht vor allem, dass ...','Bunun lehine/aleyhine olan en önemli neden ...','Dafür spricht vor allem, dass Fertiggerichte den Alltag bei Zeitdruck deutlich erleichtern.'],['Belirleyici nokta','Ausschlaggebend ist, dass ...','Belirleyici olan şey şudur ki ...','Ausschlaggebend ist, dass viele Menschen wegen beruflicher Verpflichtungen kaum Zeit zum Kochen haben.'],['Argüman','Ein tragfähiges Argument für/gegen ... ist, dass ...','Geçerli bir argüman şudur ki ...','Ein tragfähiges Argument gegen ständige Werbung ist, dass sie künstliche Bedürfnisse erzeugen kann.'],['Sıkça söylenen argüman','Ein häufig angeführtes Argument lautet, dass ...','Sıkça öne sürülen argüman şudur ki ...','Ein häufig angeführtes Argument für Online-Studium lautet, dass es flexiblere Lernzeiten ermöglicht.'],['İleri sürmek/itiraz','Für/gegen ... kann man anführen/einwenden, dass ...','Lehine/aleyhine şunu öne sürebilir/itiraz edebiliriz','Gegen Fertiggerichte kann man einwenden, dass sie oft viele Zusatzstoffe enthalten.']])+
  '<h4>4. Bağlama ve iki fikri aynı cümlede verme</h4>'+table([
  ['Funktion','DEU-Kalip','TR-Anlam','Beispiel / Einsatz'],['İki eşit unsur','sowohl ... als auch ...','hem ... hem de ...','Fertiggerichte sparen sowohl Zeit als auch Aufwand.'],['İki sonuç','sowohl dazu führen, dass ..., als auch dazu, dass ...','hem şuna yol açar, hem de buna yol açar','Soziale Medien können sowohl dazu führen, dass Informationen schneller verbreitet werden, als auch dazu, dass Falschmeldungen leichter entstehen.'],['İkinci vurgu güçlü','nicht nur ..., sondern auch ...','sadece ... değil, aynı zamanda ...','Online-Studium ermöglicht nicht nur flexibles Lernen, sondern fördert auch digitale Kompetenzen.'],['Eş değer iki unsur','ebenso ... wie ...','... kadar ... da','Der Zeitdruck belastet Studierende ebenso wie Berufstätige.'],['Resmi ve kısa','sowie','ve / bunun yanında','Das Online-Studium bietet Flexibilität sowie einen leichteren Zugang zu Lernmaterialien.'],['Daha şık bağlama','wie auch','ve ayrıca / olduğu gibi','Diese Entwicklung betrifft Schüler wie auch Studierende.']])+
  box('Dikkat',['nicht nur ..., sondern auch ... kalıbında ikinci unsur biraz daha vurgulu gelir.','sowohl ... als auch ... daha dengeli ve nötrdür.','sowie yazılı dilde çok kullanışlıdır; kısa ve akademik görünür.'])+
  '<h4>5. Begründung ve Folge: Sebep-sonuç zinciri kurma</h4>'+table([
  ['Funktion','DEU-Kalip','TR-Anlam','Beispiel / Einsatz'],['Gerekçe','Dies lässt sich damit begründen, dass ...','Bu, şununla gerekçelendirilebilir:','Dies lässt sich damit begründen, dass viele Menschen im Alltag unter erheblichem Zeitdruck stehen.'],['Gerekçe','Der Grund dafür liegt darin, dass ...','Bunun nedeni şudur:','Der Grund dafür liegt darin, dass digitale Angebote jederzeit verfügbar sind.'],['Sonuç','Daraus ergibt sich, dass ...','Bundan şu sonuç çıkar:','Daraus ergibt sich, dass Studierende ihre Lernzeiten flexibler planen können.'],['Sonuç','Infolgedessen könnte ...','Bunun sonucu olarak ... olabilir','Infolgedessen könnte der Konsum von Fertiggerichten langfristig zunehmen.'],['Sonuç','Dies hätte zur Folge, dass ...','Bunun sonucu şu olurdu:','Dies hätte zur Folge, dass traditionelle Kochgewohnheiten an Bedeutung verlieren.'],['Sorun yoğunlaşır','Besonders problematisch wird dies, wenn ...','Bu özellikle şu durumda sorunlu hâle gelir:','Besonders problematisch wird dies, wenn Jugendliche Informationen ungeprüft übernehmen.']])+
  box('Paragraf zinciri',['1. Ein wesentlicher Nachteil besteht darin, dass ...','2. Dies lässt sich damit begründen, dass ...','3. Daraus ergibt sich, dass ...','4. Langfristig könnte dies dazu führen, dass ...'])+
  '<h4>6. Karşıtlık ve alternatif davranış kalıpları</h4>'+table([
  ['Funktion','DEU-Kalip','TR-Anlam','Beispiel / Einsatz'],['Karşıt görüş','Im Gegensatz dazu bin ich der Meinung, dass ...','Buna karşılık ben şu görüşteyim:','Im Gegensatz dazu bin ich der Meinung, dass digitale Medien nicht nur informieren, sondern auch manipulieren können.'],['Bir yandan/diğer yandan','Einerseits ..., andererseits ...','Bir yandan ..., diğer yandan ...','Einerseits erleichtern Fertiggerichte den Alltag, andererseits können sie ungesunde Essgewohnheiten fördern.'],['Yerine','anstatt dass ...','... yapmak yerine','Der Schüler nutzte sein Handy, anstatt dass er sich auf den Unterricht konzentrierte.'],['Yerine + zu','Anstatt [Handlung 1] zu ..., neigt [Subjekt] dazu, [Handlung 2] zu ...','1. eylemi yapmak yerine, özne 2. eyleme yönelir','Anstatt Informationen kritisch zu prüfen, neigen viele Nutzer dazu, Inhalte ungeprüft zu teilen.'],['Nominal yapı','Anstelle von [Nominalisierung 1] setzt [Subjekt] zunehmend auf [Nominalisierung 2].','1. şey yerine giderek 2. şeye yönelir','Anstelle persönlicher Kommunikation setzen viele Menschen zunehmend auf digitale Nachrichten.'],['Odak değişimi','Statt [Handlung 1] in den Vordergrund zu stellen, rückt [Subjekt] eher [Handlung 2] in den Mittelpunkt.','1. şeyi ön plana koymak yerine 2. şeyi merkeze alır','Statt langfristige Gesundheit in den Vordergrund zu stellen, rücken viele Konsumenten eher schnelle Verfügbarkeit in den Mittelpunkt.']])+
  '<h4>7. Etki kalıpları: A kişilere B yaptırır / B’ye yöneltir</h4>'+table([
  ['Funktion','DEU-Kalip','TR-Anlam','Beispiel / Einsatz'],['Etki','[Einflussfaktor] beeinflusst [Person/Gruppe] dahingehend, dass sie dazu neigen, ... zu ...','Etken, grubu öyle etkiler ki ... yapmaya eğilim gösterir.','Soziale Medien beeinflussen Jugendliche dahingehend, dass sie dazu neigen, sich ständig mit anderen zu vergleichen.'],['Koşul yaratma','[Einflussfaktor] schafft Bedingungen, unter denen [Person/Gruppe] eher dazu neigt/neigen, ... zu ...','Etken, grubun ... yapmaya yatkın olduğu koşullar oluşturur.','Anonymität im Internet schafft Bedingungen, unter denen Nutzer eher dazu neigen, respektlos zu kommunizieren.'],['Yöneltme','[Einflussfaktor] kann [Person/Gruppe] dazu verleiten, Entscheidungen zu treffen, die weniger auf ... als auf ... beruhen.','Etken kişiyi, kendi ihtiyacından çok dış baskıya dayalı karar almaya sevk eder.','Werbung kann Konsumenten dazu verleiten, Entscheidungen zu treffen, die weniger auf eigenem Bedarf als auf äußerer Beeinflussung beruhen.']])+
  box('Sınavda çok güçlü cümle',['[Thema] beeinflusst [Zielgruppe] dahingehend, dass sie dazu neigt, [Handlung] zu [Verb].','Örnek: Online-Lernen beeinflusst Studierende dahingehend, dass sie dazu neigen, ihre Lernzeiten selbstständiger zu planen.'])+
  '<h4>8. Ülke ve toplum türleri</h4>'+table([
  ['Funktion','DEU-Kalip','TR-Anlam','Beispiel / Einsatz'],['Ülke grupları','Entwicklungs- und Schwellenländer','Gelişmekte olan ve yükselen ekonomiler','In Entwicklungs- und Schwellenländern ist der Zugang zu digitaler Bildung nicht immer ausreichend gesichert.'],['Ülke grupları','Industrieländer','Sanayileşmiş ülkeler','In Industrieländern ist die digitale Infrastruktur meist besser ausgebaut.'],['Yer belirleme','in Entwicklungs- und Schwellenländern','gelişmekte olan ve yükselen ekonomilerde','In Entwicklungs- und Schwellenländern können Online-Angebote neue Bildungschancen eröffnen.'],['Yer belirleme','in Industrieländern','sanayileşmiş ülkelerde','In Industrieländern stehen Fragen der Datenschutzsicherheit stärker im Vordergrund.']])+
  '<h4>9. Erörterung paragraf şablonları</h4>'+box('Vorteil paragrafı',['Ein wesentlicher Vorteil von [Thema] besteht darin, dass [Hauptvorteil].','Dies lässt sich damit begründen, dass [Begründung].','Besonders für [Zielgruppe] kann dies eine große Entlastung darstellen.','Daraus ergibt sich, dass [konkretes Ergebnis].','Langfristig könnte dies dazu beitragen, dass [Langzeitwirkung].'])+box('Nachteil paragrafı',['Ein zentraler Nachteil von [Thema] liegt darin, dass [Hauptproblem].','Problematisch ist insbesondere, dass [kritischer Punkt].','Dies lässt sich damit begründen, dass [Begründung].','Infolgedessen kann es dazu kommen, dass [Folge].','Langfristig könnte dies [Risiko] verstärken.'])+box('Grafik/Statistik girişi',['Aktuelle Statistiken belegen, dass [Entwicklung].','Es sieht so aus, als ob [Tendenz].','Um diese Entwicklung angemessen zu erläutern, muss zunächst geklärt werden, inwiefern [A] und [B] zusammenhängen.','Ein besonders aussagekräftiger Hinweis darauf ist [Beobachtung].'])+
  '<h4>10. Konulara uygulanmış örnek cümleler</h4><ul><li><b>Werbung:</b> Werbung kann Konsumenten dazu verleiten, Entscheidungen zu treffen, die weniger auf eigenem Bedarf als auf äußerer Beeinflussung beruhen.</li><li><b>Fertiggerichte:</b> Ein wesentlicher Nachteil von Fertiggerichten besteht darin, dass sie langfristig eine unausgewogene Ernährung begünstigen können.</li><li><b>Online-Studium:</b> Ein zentraler Vorteil des Online-Studiums liegt darin, dass Studierende ihre Lernzeiten flexibler gestalten können.</li><li><b>Einfluss der Medien:</b> Soziale Medien beeinflussen die Meinungsbildung dahingehend, dass Nutzer häufig nur noch Inhalte sehen, die ihre bisherigen Ansichten bestätigen.</li><li><b>Lebenslanges Lernen:</b> Problematisch ist insbesondere, dass lebenslanges Lernen in einen ständigen Optimierungsdruck umschlagen kann.</li><li><b>Massentourismus:</b> Dagegen kann man einwenden, dass Massentourismus die Lebensqualität der lokalen Bevölkerung erheblich beeinträchtigen kann.</li><li><b>Teamarbeit:</b> Einerseits kann Teamarbeit kreative Lösungen fördern, andererseits kann sie durch Meinungsverschiedenheiten den Arbeitsprozess verlangsamen.</li></ul>'+ 
  '<h4>11. Übungen zum Einprägen</h4><p>Bu alıştırmaların amacı kalıpları aktif kullanmaktır. Her cümlede kalıbı değil, cümlenin işlevini düşün: giriş, gerekçe, sonuç, etki, karşıtlık.</p>'+table([
  ['Aufgabe','Satzanfang','Deine Ergänzung'],['1','Ein wesentlicher Nachteil von Werbung besteht darin, dass ...','____________________________________________'],['2','Dies lässt sich damit begründen, dass ...','____________________________________________'],['3','Daraus ergibt sich, dass ...','____________________________________________'],['4','Online-Studium beeinflusst Studierende dahingehend, dass ...','____________________________________________'],['5','Anstatt Informationen kritisch zu prüfen, neigen viele Nutzer dazu, ...','____________________________________________'],['6','Einerseits bieten Fertiggerichte ..., andererseits ...','____________________________________________'],['7','Problematisch ist insbesondere, dass ...','____________________________________________'],['8','Langfristig könnte dies dazu führen, dass ...','____________________________________________']])+
  '<h4>12. Lösungen / Musterantworten</h4><ul><li>Ein wesentlicher Nachteil von Werbung besteht darin, dass sie künstliche Bedürfnisse erzeugen und Konsumenten unter Kaufdruck setzen kann.</li><li>Dies lässt sich damit begründen, dass Werbebotschaften häufig mit Emotionen, Statussymbolen und sozialen Erwartungen arbeiten.</li><li>Daraus ergibt sich, dass viele Menschen Produkte kaufen, die sie eigentlich nicht benötigen.</li><li>Online-Studium beeinflusst Studierende dahingehend, dass sie dazu neigen, ihre Lernzeiten selbstständiger zu organisieren.</li><li>Anstatt Informationen kritisch zu prüfen, neigen viele Nutzer dazu, Inhalte ungeprüft zu übernehmen und weiterzuleiten.</li><li>Einerseits bieten Fertiggerichte eine schnelle Lösung im Alltag, andererseits können sie ungesunde Essgewohnheiten fördern.</li><li>Problematisch ist insbesondere, dass soziale Medien unrealistische Ideale vermitteln und dadurch Vergleichsdruck erzeugen können.</li><li>Langfristig könnte dies dazu führen, dass kritisches Denken geschwächt und gesellschaftliche Polarisierung verstärkt wird.</li></ul>'+ 
  '<h4>13. Einseitige Kopya Kâğıdı: En kullanışlı kalıplar</h4>'+table([
  ['Funktion','Kalıp'],['Giriş','Heutzutage spielt [Thema] eine immer wichtigere Rolle.'],['Genel kabul','Es gilt als allgemein anerkannt, dass ...'],['Durum açıklama','Um die vorliegende Situation angemessen zu erläutern, muss zunächst ...'],['Avantaj','Ein wesentlicher Vorteil von [Thema] besteht darin, dass ...'],['Dezavantaj','Ein zentraler Nachteil von [Thema] liegt darin, dass ...'],['Sorun','Problematisch ist insbesondere, dass ...'],['Sebep','Dies lässt sich damit begründen, dass ...'],['Sonuç','Daraus ergibt sich, dass ...'],['Uzun vadede','Langfristig könnte dies dazu führen, dass ...'],['Etki','[Thema] beeinflusst [Gruppe] dahingehend, dass sie dazu neigt, ... zu ...'],['Karşıtlık','Einerseits ..., andererseits ...'],['Yerine','Anstatt ... zu ..., neigt [Subjekt] dazu, ... zu ...']])+
  box('3 aşamalı ezber yöntemi',['1. Her gün 5 kalıp seç ve aynı konu üzerinde 5 cümle kur.','2. Ertesi gün aynı kalıpları farklı konuda kullan: Werbung, Online-Studium, Fertiggerichte, Medien.','3. Sınavdan önce sadece 13. bölümdeki kopya kâğıdını tekrar et.'])+'</div>';

  var test={category:'Genel Grammer',cat:'Genel Grammer',slug:'satzmuster_1_c1_c2_eroerterung',title:'Satzmustern 1 · C1/C2 Erörterung Satzmuster',topic:'Giriş · durum açıklama · Vorteile/Nachteile · Begründung · Folge · Kontrast · Etki kalıpları · Kopya kâğıdı',words:['Es scheint dass','Es sieht so aus als ob','heutzutage','Es gilt als allgemein anerkannt dass','Aktuelle Statistiken belegen dass','Um die vorliegende Situation angemessen zu erläutern','Zunächst ist zu klären wie A mit B zusammenhängt','Ein wesentlicher Vorteil besteht darin dass','Ein zentraler Nachteil liegt darin dass','Problematisch ist insbesondere dass','Dies lässt sich damit begründen dass','Daraus ergibt sich dass','Langfristig könnte dies dazu führen dass','Einerseits andererseits','Anstatt zu','sowohl als auch','nicht nur sondern auch','dahingehend dass'],
  fill:[['Girişte izlenim vermek için kullanılan kalıp: Es scheint, ____.','dass','Giriş'],['Genel kabul kalıbı: Es gilt als allgemein anerkannt, ____.','dass','Genel kabul'],['Veri ile giriş: Aktuelle Statistiken ____, dass ...','belegen','Statistik'],['A-B ilişkisi: Zunächst ist zu klären, wie A mit B ____.','zusammenhängt','A-B'],['Avantaj başlangıcı: Ein wesentlicher Vorteil besteht ____, dass ...','darin','Vorteil'],['Dezavantaj başlangıcı: Ein zentraler Nachteil liegt ____, dass ...','darin','Nachteil'],['Gerekçe: Dies lässt sich damit ____, dass ...','begründen','Begründung'],['Sonuç: Daraus ergibt ____, dass ...','sich','Folge'],['Uzun vadeli sonuç: Langfristig könnte dies dazu ____, dass ...','führen','Langzeit'],['Etki: X beeinflusst Y dahingehend, dass sie dazu ____, ... zu ...','neigen','Einfluss'],['Karşıtlık: Einerseits ..., ____.','andererseits','Kontrast'],['Yerine: Anstatt Informationen kritisch zu prüfen, neigen viele Nutzer ____, Inhalte ungeprüft zu teilen.','dazu','Alternative']],
  mc:[['Hangi kalıp girişte temkinli bir izlenim verir?',['Es scheint, dass ...','Daraus ergibt sich, dass ...','Langfristig könnte dies dazu führen, dass ...'],0,'Giriş'],['Hangi kalıp sebep açıklar?',['Dies lässt sich damit begründen, dass ...','Es sieht so aus, als ob ...','Einerseits ..., andererseits ...'],0,'Begründung'],['Hangi kalıp sonuç çıkarır?',['Daraus ergibt sich, dass ...','Es gilt als allgemein anerkannt, dass ...','Anstatt ... zu ...'],0,'Folge'],['İki eşit unsur için hangi yapı uygundur?',['sowohl ... als auch ...','dahingehend, dass ...','Der Grund dafür liegt darin ...'],0,'Verbindung'],['Etkileme kalıbı hangisidir?',['X beeinflusst Y dahingehend, dass ...','X gilt als allgemein anerkannt ...','X besteht sowohl ...'],0,'Einfluss'],['Kopya kâğıdındaki dezavantaj kalıbı hangisidir?',['Ein zentraler Nachteil von [Thema] liegt darin, dass ...','Heutzutage spielt [Thema] eine immer wichtigere Rolle.','Aktuelle Statistiken belegen, dass ...'],0,'Kopya']],
  tf:[['Kalıpları görevlerine göre öğrenmek gerekir.',true,'Mantık'],['Es scheint, dass ... sonuç kalıbıdır.',false,'Giriş'],['Dies lässt sich damit begründen, dass ... gerekçe verir.',true,'Begründung'],['Daraus ergibt sich, dass ... sonuç çıkarır.',true,'Folge'],['Einerseits ..., andererseits ... karşıtlık kurar.',true,'Kontrast'],['Anstatt ... zu ... yerine yapılan davranışı gösterebilir.',true,'Alternative'],['dahingehend, dass ... etkinin yönünü açıklar.',true,'Einfluss'],['Industrieländer sanayileşmiş ülkeler anlamına gelir.',true,'Länder']],
  wordMatch:[['Es scheint, dass ...','... gibi gözüküyor'],['Es gilt als allgemein anerkannt, dass ...','Genel kabul edilen görüş şudur'],['Aktuelle Statistiken belegen, dass ...','Güncel istatistikler göstermektedir ki'],['Dies lässt sich damit begründen, dass ...','Bu şununla gerekçelendirilebilir'],['Daraus ergibt sich, dass ...','Bundan şu sonuç çıkar'],['Problematisch ist insbesondere, dass ...','Özellikle sorunlu olan şudur'],['Einerseits ..., andererseits ...','Bir yandan ..., diğer yandan ...'],['Anstatt ... zu ...','... yapmak yerine']],
  phraseMatch:[['Es scheint,','dass ...'],['Es sieht so aus,','als ob ...'],['Ein wesentlicher Vorteil besteht','darin, dass ...'],['Ein zentraler Nachteil liegt','darin, dass ...'],['Dies lässt sich damit','begründen, dass ...'],['Daraus ergibt','sich, dass ...'],['Langfristig könnte dies dazu','führen, dass ...'],['nicht nur ...,','sondern auch ...'],['sowohl ...','als auch ...']],
  prep:[['Ein wesentlicher Vorteil besteht ___, dass ...','darin','bestehen darin'],['Ein zentraler Nachteil liegt ___, dass ...','darin','liegen darin'],['Daraus ergibt ___, dass ...','sich','sich ergeben'],['Langfristig könnte dies dazu führen, ___ ...','dass','führen dazu dass'],['Im Gegensatz ___ bin ich der Meinung, dass ...','dazu','im Gegensatz dazu'],['Anstatt Informationen kritisch ___ prüfen, ...','zu','anstatt zu'],['X beeinflusst Y dahingehend, ___ ...','dass','dahingehend dass'],['Der Zugang ___ Bildung ist entscheidend.','zu','Zugang zu']],
  hang:['Es scheint dass digitale Medien den Alltag prägen','Es gilt als allgemein anerkannt dass Bildung wichtig ist','Aktuelle Statistiken belegen dass digitale Lernangebote zunehmen','Ein wesentlicher Vorteil besteht darin dass','Ein zentraler Nachteil liegt darin dass','Dies lässt sich damit begründen dass','Daraus ergibt sich dass','Langfristig könnte dies dazu führen dass','Einerseits andererseits','Anstatt Informationen kritisch zu prüfen','nicht nur sondern auch','sowohl als auch','dahingehend dass','Entwicklungs und Schwellenländer']};
  window.DEUTSCH_TESTS[KEY]=test;
  var lesson={short:'<h3>Satzmustern 1 – Kurz</h3><p>Bu bölüm C1/C2 Erörterung yazısında kullanılan temel Satzmuster kalıplarını görevlerine göre öğretir: giriş yapmak, durum açıklamak, avantaj/dezavantaj başlatmak, gerekçe vermek, sonuç çıkarmak, karşıtlık kurmak, etki açıklamak ve paragraf şablonu oluşturmak.</p><p><b>Altın mantık:</b> Konu + Kalıp + Sebep + Sonuç.</p>',medium:'<h3>Satzmustern 1 – Orta</h3><p>Giriş için Es scheint, dass..., Es gilt als allgemein anerkannt, dass... ve Aktuelle Statistiken belegen, dass... kullanılır. Durum açıklarken Um die vorliegende Situation angemessen zu erläutern... ve Zunächst ist zu klären, wie A mit B zusammenhängt yapıları metni daha akademik gösterir.</p><p>Avantaj/dezavantaj paragrafları Ein wesentlicher Vorteil/Nachteil besteht darin, dass..., Problematisch ist insbesondere, dass... veya Dafür/dagegen spricht vor allem, dass... gibi kalıplarla başlar. Gerekçe için Dies lässt sich damit begründen, dass..., sonuç için Daraus ergibt sich, dass... kullanılır.</p>',long:long};
  window.DEUTSCH_LESSONS[KEY]=lesson; window.LESSONS[KEY]=lesson;
  function ensureVisible(){var box=document.getElementById('testList'); if(!box)return; var h=(box.querySelector('h2')||{}).textContent||''; if(String(h).trim()!=='Genel Grammer')return; if(box.querySelector('input[name="tc"][value="'+KEY+'"]'))return; var label=document.createElement('label'); label.className='opt'; label.innerHTML='<input type="radio" name="tc" value="'+KEY+'"> <b>'+test.title+'</b><br><span class="muted">'+test.topic+'</span>'; var after=null; ['t15','t14'].some(function(k){var i=box.querySelector('input[name="tc"][value="'+k+'"]'); if(i&&i.closest('label')){after=i.closest('label');return true;} return false;}); if(after)after.after(label); else box.appendChild(label);}
  if(!window.__SATZMUSTER1_VISIBLE_EVENTS){window.__SATZMUSTER1_VISIBLE_EVENTS=true; document.addEventListener('click',function(){setTimeout(ensureVisible,80);},true); document.addEventListener('DOMContentLoaded',function(){setTimeout(ensureVisible,250);});}
  setTimeout(ensureVisible,300);
})();