(function(){
'use strict';
var key='sf2_3';
var source='3. Sprach Fehlern.docx';
window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};
window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};
var LONG=[
`<h3>Schreiben_fehler_3 · Sprachfehler, Präpositionen und NVV</h3>`,
`<p><b>Niveau:</b> C1/C2 · Veganismus · Produktionsbedingungen · Selbstvertrauen · lebenslanges Lernen · Rektion · NVV/FVG</p>`,
`<h4>1. Ziel des Kapitels</h4>`,
`<p>Dieses Kapitel behandelt typische Fehler, die in anspruchsvollen argumentativen Texten zu Veganismus, Produktionsbedingungen, Selbstvertrauen, Gewinnbeteiligung und lebenslangem Lernen auftreten. Der Schwerpunkt liegt nicht auf einzelnen Vokabeln, sondern auf vollständigen Ausdrucksmustern. Auf C1/C2-Niveau reicht es nicht, ein Nomen oder ein Verb zu kennen. Entscheidend ist, welche Ergänzung das Wort verlangt, welche Präposition dazugehört, welcher Kasus folgt und welche Kollokation im Deutschen natürlich klingt.</p>`,
`<p>Die zentrale Arbeitsweise besteht darin, Formulierungen als feste Einheiten zu speichern: <b>die Förderung des Veganismus</b>, <b>die Verbreitung veganer Lebensweisen</b>, <b>eine Hinwendung zu pflanzenbasierter Ernährung</b>, <b>sich von fleischbasierten Gewohnheiten abwenden</b>, <b>an traditionellen Essgewohnheiten festhalten</b>, <b>Bewusstsein für Tierwohl schaffen</b>, <b>unter besseren Produktionsbedingungen herstellen</b>, <b>am finanziellen Gewinn teilhaben</b>, <b>das Selbstvertrauen stärken</b> und <b>Nutzen aus Weiterbildung ziehen</b>. Diese Muster verbinden Wortschatz, Grammatik und Stil.</p>`,
`<h4>2. Rektion als Grundlage genauer Sätze</h4>`,
`<p>Rektion bedeutet, dass ein Verb, Nomen oder Adjektiv eine bestimmte Ergänzung verlangt. Wer <b>festhalten</b> verwendet, braucht in diesem Muster <b>an + Dativ</b>: <i>Viele Menschen halten an traditionellen Essgewohnheiten fest.</i> Wer eine Abkehr beschreibt, verwendet <b>sich von + Dativ abwenden</b>: <i>Immer mehr Konsumenten wenden sich von fleischbasierten Gewohnheiten ab.</i> Die Präpositionen sind hier nicht austauschbar. Sie tragen die Bedeutung der Richtung, Bindung oder Distanz.</p>`,
`<p>Auch Nominalstrukturen haben Rektion. <b>Die Förderung des Veganismus</b> verlangt einen Genitiv, weil die geförderte Sache näher bestimmt wird. <b>Auswirkungen auf + Akkusativ haben</b> beschreibt eine Wirkung, die sich auf einen Bereich richtet: <i>Gewinnbeteiligungen können Auswirkungen auf das Gehalt haben.</i> <b>Nutzen aus + Dativ ziehen</b> beschreibt den praktischen Gewinn aus einer Handlung oder Erfahrung: <i>Beschäftigte können aus Weiterbildung langfristigen Nutzen ziehen.</i></p>`,
`<h4>3. Veganismus und gesellschaftlicher Wandel</h4>`,
`<p>Im Themenfeld Veganismus entstehen häufig Fehler durch direkte Übersetzung oder ungenaue Wortbildung. Nicht idiomatisch ist eine Formulierung wie <i>Steigerung der Veganismus</i>. Präziser sind <b>die Förderung des Veganismus</b>, <b>die Verbreitung veganer Lebensweisen</b> oder <b>eine zunehmende Hinwendung zu pflanzenbasierter Ernährung</b>. Diese Ausdrücke zeigen einen gesellschaftlichen Prozess und eignen sich daher für Erörterungen, in denen Wertewandel, Konsumentscheidungen und ökologische Verantwortung diskutiert werden.</p>`,
`<p>Ein gehobener Satz lautet: <i>Die Förderung des Veganismus kann als Ausdruck eines veränderten Bewusstseins für Tierwohl, Nachhaltigkeit und Konsumverantwortung verstanden werden.</i> Ein weiterer Satz wäre: <i>Die Verbreitung veganer Lebensweisen hängt eng mit Bildungsangeboten, medialer Sichtbarkeit und veränderten Produktangeboten zusammen.</i> Beide Beispiele enthalten präzise Nominalgruppen und vermeiden unklare oder künstliche Formulierungen.</p>`,
`<h4>4. Hinwendung, Abwendung und Festhalten</h4>`,
`<p>Für Veränderungen im Ernährungsverhalten sind drei Muster besonders wichtig. Erstens: <b>eine Hinwendung zu + Dativ</b>. Beispiel: <i>In urbanen Milieus lässt sich eine Hinwendung zu pflanzenbasierter Ernährung beobachten.</i> Zweitens: <b>sich von + Dativ abwenden</b>. Beispiel: <i>Ein Teil der Konsumenten wendet sich von fleischbasierten Gewohnheiten ab.</i> Drittens: <b>an + Dativ festhalten</b>. Beispiel: <i>Viele Menschen halten aus kulturellen oder familiären Gründen an traditionellen Essgewohnheiten fest.</i></p>`,
`<p>Diese drei Strukturen sind nicht nur grammatisch verschieden, sondern auch semantisch präzise. <b>Hinwendung</b> beschreibt eine Orientierung auf etwas Neues. <b>Abwendung</b> beschreibt Distanzierung von einem bisherigen Muster. <b>Festhalten</b> beschreibt Stabilität oder Beharrung. In einem C1/C2-Text können diese Begriffe verwendet werden, um gesellschaftliche Gegensätze differenziert darzustellen.</p>`,
`<h4>5. Bewusstsein, Akzeptanz und Bedeutung</h4>`,
`<p>Das Muster <b>Bewusstsein für + Akkusativ schaffen</b> eignet sich für Themen wie Tierwohl, Umweltbelastung oder Konsumethik. Beispiele: <i>Dokumentationen können Bewusstsein für industrielle Tierhaltung schaffen.</i> <i>Bildungskampagnen schaffen Bewusstsein für die Folgen alltäglicher Konsumentscheidungen.</i> Nach <b>für</b> steht hier der Akkusativ. Die Struktur ist besonders hilfreich, wenn erklärt werden soll, wie Öffentlichkeit, Medien oder Bildung eine Haltung verändern.</p>`,
`<p>Wenn eine Idee gesellschaftlich angenommen wird, verwendet man <b>Akzeptanz in + Dativ finden</b>: <i>Vegane Produkte finden in der Gesellschaft zunehmend Akzeptanz.</i> Eine ähnliche Entwicklung lässt sich mit <b>an Bedeutung gewinnen</b> ausdrücken: <i>Pflanzenbasierte Ernährung gewinnt in der Bevölkerung an Bedeutung.</i> Diese Formulierungen sind präziser als allgemeine Sätze wie <i>Veganismus wird mehr</i> oder <i>Menschen mögen Veganismus mehr</i>.</p>`,
`<h4>6. Produktionsbedingungen und Passivstrukturen</h4>`,
`<p>Beim Thema Produktionsbedingungen ist das Passiv besonders wichtig, weil häufig nicht die handelnde Person, sondern der Herstellungsprozess im Vordergrund steht. Korrekt ist: <b>Produkte können unter besseren Bedingungen hergestellt werden.</b> Das Muster lautet: Modalverb + Partizip II + werden. Weitere Beispiele sind: <i>Lebensmittel sollten unter transparenteren Bedingungen produziert werden.</i> <i>Tierische Produkte müssen unter strengeren Standards kontrolliert werden.</i> <i>Arbeitsabläufe können durch klare Vorgaben verbessert werden.</i></p>`,
`<p>Die Präposition <b>unter + Dativ</b> beschreibt hier die Bedingungen, unter denen ein Prozess stattfindet. Man schreibt <i>unter besseren Produktionsbedingungen</i>, nicht <i>bei besseren Produktionsbedingungen</i>, wenn die Rahmenbedingungen gemeint sind. Der Ausdruck <b>Produktionsbedingungen</b> ist außerdem präziser als unklare Wörter wie <i>Produktphase</i> oder <i>Produktezeit</i>.</p>`,
`<h4>7. Zielrichtung und Bewertung mit Genitiv</h4>`,
`<p>Das Wort <b>zugunsten</b> steht im gehobenen Register mit dem Genitiv. Beispiel: <i>Kaufentscheidungen können zugunsten tierfreundlicher Unternehmen ausfallen.</i> Diese Formulierung ist nützlich, wenn eine Entscheidung im Interesse einer Gruppe, eines Unternehmens oder einer Entwicklung getroffen wird. Sie ist formeller als einfache Ausdrücke wie <i>für tierfreundliche Unternehmen</i>, aber sie sollte nur dann verwendet werden, wenn eine klare Bewertung oder Verschiebung zugunsten einer Seite gemeint ist.</p>`,
`<p>Auch Genitivstrukturen wie <b>die Förderung des Veganismus</b>, <b>die Verbesserung der Produktionsbedingungen</b> und <b>die Stärkung des Selbstvertrauens</b> tragen zu einem gehobenen Stil bei. Dabei ist wichtig, den Genitiv nicht künstlich zu häufen. Ein guter Satz bleibt lesbar und zeigt klar, welches Nomen welches andere Nomen näher bestimmt.</p>`,
`<h4>8. Gewinnbeteiligung und wirtschaftliche Teilhabe</h4>`,
`<p>Im wirtschaftlichen Kontext ist die Verbindung <b>am finanziellen Gewinn teilhaben</b> besonders wichtig. Das Verb <b>teilhaben</b> verlangt <b>an + Dativ</b>. Beispiel: <i>Beschäftigte sollten am finanziellen Gewinn eines Unternehmens teilhaben.</i> Eine verwandte Struktur lautet <b>jemanden an etwas teilhaben lassen</b>: <i>Faire Unternehmen lassen Mitarbeitende am wirtschaftlichen Erfolg teilhaben.</i> Beide Ausdrücke sind präziser als <i>am Gewinn teilnehmen</i>, das in diesem Kontext nicht idiomatisch ist.</p>`,
`<p>Die Struktur kann in Argumentationen über Gerechtigkeit, Motivation und Arbeitszufriedenheit verwendet werden. Ein C1/C2-Satz lautet: <i>Eine transparente Gewinnbeteiligung kann dazu beitragen, dass Mitarbeitende ihre Leistung stärker mit dem Erfolg des Unternehmens verbinden.</i> Hier wird wirtschaftliche Teilhabe nicht nur benannt, sondern in einen argumentativen Zusammenhang gestellt.</p>`,
`<h4>9. Selbstvertrauen und persönliche Entwicklung</h4>`,
`<p>Das Muster <b>das Selbstvertrauen stärken</b> ist eine natürliche Kollokation. Beispiele: <i>Erfolgserlebnisse können das Selbstvertrauen nachhaltig stärken.</i> <i>Der Erwerb neuer Kompetenzen stärkt das Selbstvertrauen, weil Lernende ihre eigene Handlungsfähigkeit erfahren.</i> Besonders wichtig ist der Pronomenbezug bei <b>man</b>. Standardsprachlich heißt es: <i>Man stärkt sein Selbstvertrauen, wenn man seine Fähigkeiten erweitert.</i> Nicht passend wäre eine Form mit <i>ihr</i>, wenn kein feminines Bezugswort vorhanden ist.</p>`,
`<p>Selbstvertrauen lässt sich in C1/C2-Texten mit weiteren Strukturen verbinden: <b>Kompetenzen erweitern</b>, <b>Erfolgserlebnisse ermöglichen</b>, <b>innere Sicherheit gewinnen</b>, <b>Herausforderungen bewältigen</b> und <b>Verantwortung übernehmen</b>. Dadurch wird die persönliche Entwicklung nicht nur emotional, sondern analytisch beschrieben.</p>`,
`<h4>10. Lebenslanges Lernen und Belastung</h4>`,
`<p>Lebenslanges Lernen kann berufliche Chancen eröffnen, aber auch Belastungen erzeugen. Für diese Ambivalenz sind präzise Satzmuster notwendig. Man schreibt: <i>Beschäftigte können aus Weiterbildung beruflichen Nutzen ziehen.</i> Ebenso korrekt ist: <i>Weiterbildung muss mit familiären und beruflichen Verpflichtungen in Einklang gebracht werden.</i> Das Muster <b>in Einklang bringen mit + Dativ</b> beschreibt die Vereinbarkeit verschiedener Anforderungen.</p>`,
`<p>Wenn Gründe im gehobenen Register angegeben werden, eignet sich <b>aufgrund + Genitiv</b>: <i>Aufgrund beruflicher Verpflichtungen fehlt vielen Erwachsenen die Zeit für regelmäßige Weiterbildung.</i> Wenn eine Belastung beschrieben wird, kann man <b>unter Druck stehen</b> verwenden: <i>Viele Beschäftigte stehen unter Druck, sich ständig weiterzubilden.</i> Diese Formulierung ist stärker als ein allgemeines <i>haben Stress</i> und passt besser zu einem formellen Text.</p>`,
`<h4>11. Freiheit, Verpflichtungen und Rücksicht</h4>`,
`<p>Das Muster <b>bestehen in + Dativ</b> beschreibt den Kern eines Vorteils oder einer Eigenschaft. Beispiel: <i>Der Vorteil flexibler Lernangebote besteht in der persönlichen Freiheit.</i> Nach <b>in</b> steht hier der Dativ. Für die Berücksichtigung äußerer Bedingungen verwendet man <b>Rücksicht auf + Akkusativ nehmen</b>: <i>Lernangebote müssen Rücksicht auf familiäre Verpflichtungen nehmen.</i> Diese Struktur ist für argumentatives Schreiben sehr wertvoll, weil sie soziale Realität und individuelle Möglichkeiten verbindet.</p>`,
`<p>Ein differenzierter Satz lautet: <i>Flexible Weiterbildung kann persönliche Freiheit ermöglichen, sofern sie Rücksicht auf berufliche Belastungen, familiäre Verpflichtungen und unterschiedliche Lernbiografien nimmt.</i> Hier werden mehrere Aspekte integriert, ohne dass der Satz unkontrolliert wirkt.</p>`,
`<h4>12. Satzbau: dass-Satz, Hauptsatzstellung und Parallelität</h4>`,
`<p>Viele Fehler entstehen nicht durch Wortschatz, sondern durch Satzbau. Nach <b>dass</b> steht das finite Verb am Ende: <i>Das Ergebnis zeigt, dass sich Ernährungsgewohnheiten verändern.</i> Nach einem vorangestellten Adverb wie <b>dadurch</b> steht das finite Verb im Hauptsatz auf Position zwei: <i>Dadurch kann lebenslanges Lernen zu einer Belastung werden.</i> Diese Verbzweitstellung ist für klare und korrekte Argumentation unverzichtbar.</p>`,
`<p>Auch Parallelität ist wichtig. Korrekt ist: <i>das Erlernen eines Instruments, einer Sprache oder neuer sozialer Fähigkeiten</i>. Die Elemente der Aufzählung sind formal vergleichbar. Eine ungleichmäßige Struktur wirkt unruhig und kann den Inhalt verdecken. Auf C1/C2-Niveau sollte jede Aufzählung darauf geprüft werden, ob die Teile grammatisch und stilistisch parallel sind.</p>`,
`<h4>13. Nomen-Verb-Verbindungen im argumentativen Text</h4>`,
`<p>Nomen-Verb-Verbindungen machen abstrakte Zusammenhänge sichtbar. Dazu gehören <b>Einfluss auf Entscheidungen ausüben</b>, <b>einen Beitrag zur Förderung leisten</b>, <b>eine Debatte über Tierhaltung anstoßen</b>, <b>Nutzen aus Weiterbildung ziehen</b> und <b>in Einklang bringen</b>. Diese Strukturen sind besonders hilfreich, wenn Ursachen, Wirkungen, Bewertungen oder Lösungsmöglichkeiten beschrieben werden.</p>`,
`<p>Sie sollten jedoch nicht mechanisch eingesetzt werden. Ein Text wird nicht besser, wenn jedes einfache Verb durch eine schwere Nominalstruktur ersetzt wird. Entscheidend ist die Funktion. <b>Eine Debatte anstoßen</b> passt, wenn eine öffentliche Diskussion beginnt. <b>Einfluss ausüben</b> passt, wenn eine Entscheidung geprägt wird. <b>Einen Beitrag leisten</b> passt, wenn eine Maßnahme eine positive Entwicklung unterstützt.</p>`,
`<h4>14. Modellabsatz</h4>`,
`<p>Die Förderung des Veganismus kann als Teil eines breiteren gesellschaftlichen Wertewandels verstanden werden, da immer mehr Menschen Bewusstsein für Tierwohl, Nachhaltigkeit und Produktionsbedingungen entwickeln. Gleichzeitig halten viele Verbraucher aus kulturellen oder persönlichen Gründen an traditionellen Essgewohnheiten fest. Eine differenzierte Debatte sollte daher nicht nur moralische Forderungen formulieren, sondern auch berücksichtigen, unter welchen Bedingungen Lebensmittel hergestellt werden und welche Alternativen tatsächlich verfügbar sind. Bildungsangebote können in diesem Zusammenhang einen Beitrag zur Förderung reflektierter Konsumentscheidungen leisten.</p>`,
`<p>Lebenslanges Lernen zeigt eine ähnliche Ambivalenz. Einerseits können Beschäftigte aus Weiterbildung beruflichen Nutzen ziehen und ihr Selbstvertrauen stärken. Andererseits stehen viele Erwachsene aufgrund beruflicher Verpflichtungen unter Druck und müssen Lernphasen mit Familienleben, Arbeit und Erholung in Einklang bringen. Entscheidend ist daher, Lernangebote so zu gestalten, dass sie persönliche Freiheit ermöglichen und gleichzeitig Rücksicht auf reale Lebensbedingungen nehmen.</p>`,
`<h4>15. Fehlerdiagnose und Schreibkontrolle</h4>`,
`<p>Vor der Abgabe sollte jede zentrale Struktur überprüft werden. Heißt es <b>die Förderung des Veganismus</b> und nicht <i>die Steigerung der Veganismus</i>? Steht nach <b>festhalten an</b> der Dativ? Wird <b>Bewusstsein für + Akkusativ</b> korrekt verwendet? Ist das Passiv mit Modalverb richtig aufgebaut? Lautet die Struktur <b>am Gewinn teilhaben</b> und nicht <i>am Gewinn teilnehmen</i>? Wird bei <b>man</b> der richtige Possessivbezug verwendet?</p>`,
`<p>Ein überzeugender C1/C2-Text entsteht durch kontrollierte Präzision. Rektion, Kasus, Kollokation, Satzbau und Textlogik müssen zusammenpassen. Wer die hier behandelten Muster sicher beherrscht, kann über Veganismus, Produktionsbedingungen, Selbstvertrauen und lebenslanges Lernen differenziert schreiben, ohne unnatürliche Übersetzungen oder unklare Satzstrukturen zu verwenden.</p>`
].join('');
var P=[['die Förderung des Veganismus','Förderung + Genitiv','Die Förderung ___ Veganismus setzt gesellschaftliche Aufklärung voraus.','des','gezielte Unterstützung veganer Lebensweisen'],['die Verbreitung veganer Lebensweisen','Verbreitung + Genitiv','Die Verbreitung ___ Lebensweisen hängt mit Bildung und Konsumangeboten zusammen.','veganer','gesellschaftliche Ausdehnung veganer Praxis'],['Hinwendung zu pflanzenbasierter Ernährung','Hinwendung zu + Dativ','In urbanen Milieus lässt sich eine Hinwendung ___ pflanzenbasierter Ernährung beobachten.','zu','Orientierung in Richtung pflanzlicher Ernährung'],['sich von fleischbasierten Gewohnheiten abwenden','sich abwenden von + Dativ','Immer mehr Menschen wenden sich ___ fleischbasierten Gewohnheiten ab.','von','bisherige Konsumroutinen aufgeben'],['an traditionellen Essgewohnheiten festhalten','festhalten an + Dativ','Viele Menschen halten ___ traditionellen Essgewohnheiten fest.','an','bei vertrauten Ernährungsroutinen bleiben'],['Bewusstsein für Tierwohl schaffen','Bewusstsein für + Akkusativ','Kampagnen können Bewusstsein ___ Tierwohl schaffen.','für','Menschen für ethische Produktionsfragen sensibilisieren'],['Akzeptanz in der Gesellschaft finden','Akzeptanz finden in + Dativ','Vegane Produkte finden ___ der Gesellschaft zunehmend Akzeptanz.','in','gesellschaftlich angenommen werden'],['unter besseren Produktionsbedingungen herstellen','unter + Dativ','Lebensmittel sollten ___ besseren Produktionsbedingungen hergestellt werden.','unter','Produktion unter faireren Umständen ermöglichen'],['am finanziellen Gewinn teilhaben','teilhaben an + Dativ','Beschäftigte sollten ___ finanziellen Gewinn teilhaben.','am','wirtschaftlich beteiligt sein'],['Nutzen aus Weiterbildung ziehen','Nutzen aus + Dativ','Beschäftigte können ___ Weiterbildung beruflichen Nutzen ziehen.','aus','praktisch profitieren']];
var MC=[['Welche Formulierung ist korrekt?',['die Förderung des Veganismus','die Steigerung der Veganismus','die Förderung über Veganismus','die Förderungen an Veganismus'],0,'Genitiv und Kollokation'],['Welche Satzstruktur ist korrekt?',['Das Ergebnis zeigt, dass sich Ernährungsgewohnheiten verändern.','Das Ergebnis ist eindeutig, dass sich Ernährungsgewohnheiten verändern.','Das Ergebnis zeigt, dass verändern sich Gewohnheiten.','Das Ergebnis zeigt, dass sich Gewohnheiten verändern sich.'],0,'dass-Satz'],['Welche Passivstruktur mit Modalverb ist korrekt?',['Produkte können unter besseren Bedingungen hergestellt werden.','Produkte können unter besseren Bedingungen herstellen werden.','Produkte werden können unter besseren Bedingungen hergestellt.','Produkte können bei besseren Bedingungen hergestellt können.'],0,'Passiv'],['Welche Rektion verlangt bestehen?',['bestehen in der persönlichen Freiheit','bestehen in die persönliche Freiheit','bestehen auf der persönlichen Freiheit','bestehen über persönliche Freiheit'],0,'bestehen in + Dativ'],['Welche NVV ersetzt beeinflussen gehoben?',['Einfluss auf Konsumentscheidungen ausüben','Einfluss über Konsumentscheidungen machen','Einfluss an Konsumentscheidungen nehmen','auf Konsumentscheidungen Einfluss geben'],0,'NVV']];
var TF=[['Rektion bedeutet, dass ein Verb, Nomen oder Adjektiv eine bestimmte Präposition und einen bestimmten Kasus verlangt.',true,'Definition'],['Festhalten verlangt in diesem Muster an + Dativ.',true,'Rektion'],['Bewusstsein für Tierwohl schaffen verlangt für + Akkusativ.',true,'Rektion'],['Nach dadurch steht im Hauptsatz das finite Verb auf Position 2.',true,'Verbzweitstellung'],['Teilnehmen am Gewinn ist präziser als am Gewinn teilhaben.',false,'teilhaben'],['Zugunsten steht im gehobenen Register mit dem Genitiv.',true,'Genitiv'],['Ein obwohl-Satz darf ohne finites Verb stehen.',false,'Nebensatz'],['Nutzen aus Weiterbildung ziehen verlangt aus + Dativ.',true,'Rektion']];
window.DEUTSCH_TESTS[key]={category:'Schreiben Fehler 2',slug:'schreiben_fehler_3_sprachfehler_praepositionen_nvv',title:'Schreiben_fehler_3 · Sprachfehler, Präpositionen und NVV',topic:'C1/C2 · Veganismus · Produktionsbedingungen · Selbstvertrauen · lebenslanges Lernen · Rektion · NVV/FVG',source:source,words:P.map(function(x){return x[0];}),fill:P.map(function(x){return [x[2],x[3],x[1]];}),mc:MC,tf:TF,wordMatch:P.map(function(x){return [x[0],x[4]];}),phraseMatch:[['Veganismus','gesellschaftliche Akzeptanz finden'],['Produktionsbedingungen','unter besseren Bedingungen herstellen'],['Selbstvertrauen','durch Erfolgserlebnisse stärken'],['Weiterbildung','Nutzen aus neuen Kompetenzen ziehen'],['Kaufentscheidungen','zugunsten tierfreundlicher Unternehmen treffen']],prep:P.map(function(x){return [x[2],x[3],x[1]];}),hang:['die Förderung des Veganismus','die Verbreitung veganer Lebensweisen','Hinwendung zu pflanzenbasierter Ernährung','sich von Gewohnheiten abwenden','an Essgewohnheiten festhalten','Bewusstsein für Tierwohl schaffen','Akzeptanz in der Gesellschaft finden','unter besseren Produktionsbedingungen herstellen','am finanziellen Gewinn teilhaben','das Selbstvertrauen stärken','unter Druck stehen','Rücksicht auf Verpflichtungen nehmen','Nutzen aus Weiterbildung ziehen','in Einklang bringen mit Familienleben']};
window.DEUTSCH_LESSONS[key]={source:source,longSourceVerified:true,short:'<h3>Schreiben_fehler_3 · Kurzüberblick</h3><p>Dieses Modul behandelt Sprachfehler zu Veganismus, Produktionsbedingungen, Selbstvertrauen und lebenslangem Lernen. Im Zentrum stehen Rektion, Präpositionen, Kasus, Satzbau, Nominalstil und Nomen-Verb-Verbindungen.</p>',medium:'<h3>Schreiben_fehler_3 · Erweiterte Erklärung</h3><p>Die wichtigsten Muster sind <b>die Förderung des Veganismus</b>, <b>die Verbreitung veganer Lebensweisen</b>, <b>sich von Gewohnheiten abwenden</b>, <b>an Essgewohnheiten festhalten</b>, <b>Bewusstsein für Tierwohl schaffen</b>, <b>unter besseren Produktionsbedingungen herstellen</b>, <b>am finanziellen Gewinn teilhaben</b>, <b>das Selbstvertrauen stärken</b> und <b>Nutzen aus Weiterbildung ziehen</b>. Entscheidend sind Präposition, Kasus, Kollokation und Textfunktion.</p>',long:LONG};
function active(){var t=(document.getElementById('lessonTitle')||{}).textContent||'';var c=(document.getElementById('lessonContent')||{}).textContent||'';return t.indexOf('Schreiben_fehler_3')>-1||t.indexOf('Schreibfehler 3')>-1||c.indexOf('Veganismus')>-1||c.indexOf('Produktionsbedingungen')>-1;}
function visible(){var x=document.getElementById('lesson');return !x||!/(^|\s)hide(\s|$)/.test(x.className||'');}
function render(){if(!visible()||!active())return;var title=document.getElementById('lessonTitle'),meta=document.getElementById('lessonMeta'),content=document.getElementById('lessonContent');if(title)title.textContent='Lektion: Schreiben_fehler_3 · Sprachfehler, Präpositionen und NVV';if(meta)meta.textContent='Niveau: C1/C2 · Deutsch';if(content&&content.innerHTML!==LONG)content.innerHTML=LONG;}
render();setTimeout(render,200);setTimeout(render,900);setInterval(render,180);document.addEventListener('click',function(){setTimeout(render,60);setTimeout(render,240);setTimeout(render,800);},true);try{new MutationObserver(function(){setTimeout(render,30);}).observe(document.documentElement,{childList:true,subtree:true,characterData:true});}catch(e){}
window.AAYS_SF2_3_1500_DE_ONLY_OK=true;
})();
