(function(){
'use strict';
var key='t_video_schule_nachteile';
var source='Videoueberwachung_in_der_Schule_Nachteile_C1C2(2).docx';
window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};
window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};
var LONG=[
`<h3>Videoüberwachung in der Schule – Nachteile · C1/C2-Erörterungstraining</h3>`,
`<p><b>Quelle:</b> Videoueberwachung_in_der_Schule_Nachteile_C1C2(2).docx</p>`,
`<p><b>Fokus:</b> Dieses Modul behandelt ausschließlich die Seite der Nachteile. Es ist als eigenständiger Nachteilsbutton im Bereich Bevor Schreiben gedacht und wird nicht mit Vorteilsargumenten vermischt.</p>`,
`<h4>1. Grundidee des Themas</h4>`,
`<p>Videoüberwachung in der Schule wirkt auf den ersten Blick wie eine einfache Sicherheitsmaßnahme. Kameras können Eingänge, Flure, Pausenhöfe oder Aufenthaltsbereiche erfassen und sollen dadurch Diebstahl, Gewalt oder das Eindringen fremder Personen verhindern. Für eine prüfungsstarke Erörterung reicht diese oberflächliche Betrachtung jedoch nicht aus. Schulen sind keine neutralen Verwaltungsgebäude, sondern Lern- und Lebensräume, in denen Kinder und Jugendliche Wissen erwerben, Beziehungen aufbauen, Fehler machen, Konflikte lösen und ihre Persönlichkeit entwickeln. Genau deshalb muss kritisch geprüft werden, ob eine dauerhafte technische Beobachtung zu einem pädagogischen Umfeld passt.</p>`,
`<p>Der zentrale Gedanke eines Nachteilsaufsatzes lautet: Sicherheit darf nicht automatisch jede Maßnahme rechtfertigen. Auch wenn Schutz ein berechtigtes Ziel ist, muss eine Schule verhältnismäßig handeln. Eine Maßnahme ist nur dann überzeugend, wenn sie notwendig, angemessen und mit milderen Mitteln nicht erreichbar ist. Bei Kameras entsteht ein Spannungsverhältnis zwischen dem Wunsch nach Sicherheit und dem Anspruch auf Privatsphäre, Vertrauen, persönliche Entwicklung und Datenschutz. Ein guter C1/C2-Text erklärt daher nicht nur, dass Kameras problematisch sein können, sondern zeigt präzise, wodurch die Probleme entstehen und welche Folgen sie für Schülerinnen und Schüler, Lehrkräfte, Eltern und das Schulklima haben.</p>`,
`<p>Für die Prüfung eignet sich eine klare dreiteilige Argumentation. Erstens kann Videoüberwachung in die Privatsphäre eingreifen und den geschützten Lernraum verändern. Zweitens kann sie psychischen Druck, Anpassungszwang und Unsicherheit erzeugen. Drittens entstehen Datenschutzrisiken, Missbrauchsmöglichkeiten und ein zusätzlicher organisatorischer Kontrollaufwand. Diese drei Nachteile lassen sich mit konkreten Situationen aus dem Schulalltag verbinden: dem Pausenhof, dem Flur, der Mensa, dem Eingangsbereich, dem Konfliktgespräch, der gespeicherten Aufnahme oder der Frage, wer Zugriff auf Bilddaten erhält.</p>`,
`<h4>2. Nachteil 1: Eingriff in die Privatsphäre</h4>`,
`<p>Ein wesentlicher Nachteil der Videoüberwachung besteht darin, dass sie in die Privatsphäre der Schülerinnen und Schüler eingreifen kann. Privatsphäre bedeutet im schulischen Kontext nicht, dass Regeln bedeutungslos wären. Sie bedeutet vielmehr, dass junge Menschen einen gewissen geschützten Raum brauchen, in dem sie sich bewegen, sprechen, lachen, streiten, sich entschuldigen, scheitern und wieder neu beginnen können, ohne dass jede Handlung technisch dokumentiert wird. Gerade in der Schule ist dieser Raum wichtig, weil Jugendliche dort nicht nur Unterricht erhalten, sondern auch soziale Sicherheit und Selbstständigkeit entwickeln.</p>`,
`<p>Kameras auf Fluren, in Pausenhöfen oder in Aufenthaltsräumen erfassen nicht nur mögliche Regelverstöße. Sie erfassen auch private Gespräche, Freundschaften, Unsicherheiten, peinliche Situationen, emotionale Reaktionen und alltägliche Begegnungen. Wenn ein Schüler nach einem Streit weint, eine Schülerin sich wegen ihres Aussehens unsicher fühlt oder Jugendliche in der Pause vertraulich miteinander sprechen, werden solche Momente Teil eines technischen Systems. Genau darin liegt die Problematik: Die Kamera unterscheidet nicht zwischen sicherheitsrelevanten Vorfällen und normalen privaten Situationen. Sie registriert zunächst alles, was in ihrem Sichtfeld geschieht.</p>`,
`<p>Aus pädagogischer Sicht ist außerdem wichtig, dass die Schule ein Vertrauensraum bleiben sollte. Wenn Schülerinnen und Schüler das Gefühl haben, grundsätzlich unter Verdacht zu stehen, kann das Vertrauensverhältnis zur Schule geschwächt werden. Die Institution sendet dann möglicherweise das Signal, dass Kontrolle wichtiger ist als pädagogische Beziehung. Zwar kann eine Kamera einen Vorfall dokumentieren, aber sie kann kein Vertrauen aufbauen, keine Konflikte pädagogisch bearbeiten und kein Gespräch ersetzen. Eine Schule, die zu stark auf Überwachung setzt, läuft Gefahr, ihren Charakter als offener Lern- und Lebensraum zu verlieren.</p>`,
`<p>In einer Erörterung lässt sich dieser Nachteil besonders gut mit dem Begriff der Verhältnismäßigkeit erklären. Wenn Konflikte durch mehr Aufsicht, klare Regeln, Schulsozialarbeit, persönliche Gespräche oder Präventionsprojekte bearbeitet werden können, wirkt eine flächendeckende Videoüberwachung unverhältnismäßig. Der Schutz vor Gefahren muss mit dem Schutz der Privatsphäre abgewogen werden. Ein starker Satz lautet: Auch wenn Sicherheit ein legitimes Ziel ist, darf sie nicht dazu führen, dass Schülerinnen und Schüler ihren Schulalltag wie in einem überwachten Raum erleben.</p>`,
`<h4>3. C1/C2-Muster zu Privatsphäre und Vertrauensverlust</h4>`,
`<p>Für diesen ersten Nachteil sind folgende Ausdrucksmuster besonders wichtig: <b>in die Privatsphäre eingreifen</b>, <b>das Vertrauen beeinträchtigen</b>, <b>ein Gefühl permanenter Kontrolle erzeugen</b>, <b>die persönliche Freiheit einschränken</b>, <b>eine Grenze überschreiten</b>, <b>einen geschützten Lernraum verändern</b>, <b>unter Beobachtung stehen</b>, <b>mildere Mittel in Betracht ziehen</b>, <b>pädagogische Beziehungen schwächen</b> und <b>ein Klima des Misstrauens entstehen lassen</b>. Diese Verbindungen sind stärker als einfache Aussagen wie Kameras sind schlecht, weil sie konkrete Wirkungen benennen.</p>`,
`<p>Ein prüfungstauglicher Absatz kann folgendermaßen aufgebaut werden: Ein erster Nachteil besteht darin, dass Videoüberwachung in die Privatsphäre der Schülerinnen und Schüler eingreift. Besonders problematisch ist dies, weil Jugendliche in der Schule nicht nur lernen, sondern auch persönliche Erfahrungen sammeln. Wenn Kameras auf dem Pausenhof oder in Aufenthaltsräumen jede Bewegung erfassen, entsteht leicht ein Gefühl ständiger Beobachtung. Dadurch kann das Vertrauen zwischen Schule und Lernenden beeinträchtigt werden. Aus pädagogischer Sicht sollte daher geprüft werden, ob mildere Mittel wie Aufsichtspersonal, Schulsozialarbeit oder klare Regeln denselben Zweck erfüllen können.</p>`,
`<h4>4. Nachteil 2: psychischer Druck und Anpassungszwang</h4>`,
`<p>Ein weiterer Nachteil liegt darin, dass Videoüberwachung psychischen Druck ausüben kann. Dieser Druck muss nicht offen sichtbar sein. Schon das Wissen, dass eine Kamera vorhanden ist, kann ausreichen, damit Jugendliche ihr Verhalten kontrollieren. Sie fragen sich, wer die Aufnahme sieht, ob ihr Verhalten später bewertet wird oder ob eine peinliche Situation gegen sie verwendet werden könnte. Solche Gedanken können den Schulalltag belasten, auch wenn die Kamera offiziell nur der Sicherheit dienen soll.</p>`,
`<p>Jugendliche befinden sich in einer Lebensphase, in der Selbstwahrnehmung, Anerkennung und Unsicherheit eine große Rolle spielen. Viele Schülerinnen und Schüler achten ohnehin stark darauf, wie sie von anderen wahrgenommen werden. Wenn zusätzlich Kameras installiert werden, kann dieses Gefühl der Bewertung verstärkt werden. Manche Jugendliche verhalten sich dann weniger spontan, vermeiden bestimmte Orte, sprechen vorsichtiger oder ziehen sich zurück. Dadurch verliert die Schule ein Stück ihrer sozialen Lebendigkeit.</p>`,
`<p>Besonders wichtig ist der Unterschied zwischen äußerer Ordnung und echter pädagogischer Wirkung. Kameras können dazu führen, dass sich Jugendliche oberflächlich ruhiger verhalten. Das bedeutet aber nicht automatisch, dass sie Regeln verstehen, Rücksichtnahme lernen oder Verantwortung übernehmen. Wenn sich Schülerinnen und Schüler nur aus Angst vor Kontrolle korrekt verhalten, bleibt der pädagogische Nutzen begrenzt. Eine Schule sollte nicht nur regelkonformes Verhalten erzwingen, sondern Verantwortungsbewusstsein fördern.</p>`,
`<p>Auch Konflikte verschwinden durch Überwachung nicht unbedingt. Sie können in unbeobachtete Bereiche verlagert werden. Jugendliche lernen dann möglicherweise nicht, Konflikte offen auszutragen und pädagogisch begleitet zu lösen, sondern sie lernen, Kontrolle zu umgehen. Damit wird das Problem nicht bearbeitet, sondern nur verschoben. Für einen C1/C2-Text ist diese Differenzierung entscheidend: Videoüberwachung kann Verhalten anpassen, aber sie ersetzt keine Einsicht, keine Gesprächskultur und keine soziale Verantwortung.</p>`,
`<h4>5. C1/C2-Muster zu Druck, Verhalten und Entwicklung</h4>`,
`<p>Für diesen zweiten Nachteil eignen sich folgende Wörter und Verbindungen: <b>psychischen Druck ausüben</b>, <b>sich beobachtet fühlen</b>, <b>das Verhalten anpassen</b>, <b>Unsicherheit verstärken</b>, <b>spontanes Verhalten hemmen</b>, <b>aus Angst vor Kontrolle handeln</b>, <b>Verantwortungsbewusstsein fördern</b>, <b>innere Einsicht entwickeln</b>, <b>Konflikte verdrängen</b>, <b>soziale Entwicklung beeinträchtigen</b> und <b>pädagogische Begleitung ersetzen</b>. Besonders stark ist die Formulierung: Kontrolle ersetzt keine pädagogische Einsicht.</p>`,
`<p>Ein möglicher Prüfungsabsatz lautet: Hinzu kommt, dass Videoüberwachung nicht nur äußere Ordnung schafft, sondern auch inneren Druck erzeugen kann. Jugendliche befinden sich in einer Phase, in der sie Freiräume für persönliche Entwicklung benötigen. Wenn sie ihr Verhalten nur aus Angst vor Kontrolle ändern, ist der pädagogische Nutzen begrenzt. Sie handeln dann möglicherweise korrekt, aber nicht aus Überzeugung. Langfristig kann ein solches Klima die Offenheit im Schulalltag beeinträchtigen und die Entwicklung von Selbstständigkeit schwächen.</p>`,
`<h4>6. Nachteil 3: Datenschutzrisiken und Missbrauchsmöglichkeiten</h4>`,
`<p>Ein dritter Nachteil betrifft den Datenschutz. Videoüberwachung bedeutet nicht nur, dass Kameras Bilder aufnehmen. Es entstehen Bilddaten, die gespeichert, geschützt, ausgewertet und rechtlich korrekt behandelt werden müssen. Gerade in Schulen ist dies besonders heikel, weil viele betroffene Personen minderjährig sind. Bildaufnahmen von Minderjährigen sind sensible Daten. Deshalb muss besonders sorgfältig geregelt werden, wer Zugriff erhält, wie lange Aufnahmen gespeichert werden, wann sie gelöscht werden und wie unbefugter Zugriff verhindert wird.</p>`,
`<p>Jede Kamera schafft neue Verantwortung. Die Schule muss technische Systeme warten, Löschfristen festlegen, Zuständigkeiten klären, Zugriffsrechte beschränken und Eltern transparent informieren. Das ist organisatorisch anspruchsvoll und bindet Ressourcen. Eine Schule, die eigentlich Bildung, Beratung und pädagogische Begleitung leisten soll, muss dadurch zusätzliche Verwaltungs- und Kontrollaufgaben übernehmen. Wenn Personal, Zeit oder Fachwissen fehlen, können Datenschutzprobleme entstehen.</p>`,
`<p>Auch die Gefahr der Fehlinterpretation ist nicht zu unterschätzen. Ein Video zeigt oft nur einen Ausschnitt, nicht die ganze Wahrheit. Ein kurzer Ausschnitt kann die Reaktion eines Schülers zeigen, aber nicht die vorherige Provokation. Eine emotionale Szene kann ohne Kontext falsch bewertet werden. Wenn Aufnahmen intern weitergegeben, zu lange gespeichert oder von unbefugten Personen angesehen werden, kann das Vertrauen von Eltern und Schülerinnen und Schülern nachhaltig beschädigt werden.</p>`,
`<p>Hinzu kommt, dass Videoüberwachung Kosten verursacht. Kameras müssen angeschafft, installiert, gewartet und geschützt werden. Technische Dienstleister können beteiligt sein, wodurch neue Datenschutzfragen entstehen. Geld, Zeit und Aufmerksamkeit, die in Überwachungstechnik fließen, fehlen möglicherweise für Schulsozialarbeit, Prävention, mehr Aufsichtspersonal oder pädagogische Projekte. Deshalb ist Videoüberwachung nicht nur eine Sicherheitsmaßnahme, sondern auch eine organisatorische und finanzielle Belastung.</p>`,
`<h4>7. C1/C2-Muster zu Datenschutz und Kontrollaufwand</h4>`,
`<p>Wichtige Begriffe sind <b>der Datenschutz</b>, <b>die Bilddaten</b>, <b>der Zugriff</b>, <b>die Speicherung</b>, <b>die Löschfrist</b>, <b>die Zuständigkeit</b>, <b>der Kontrollaufwand</b>, <b>die Missbrauchsgefahr</b>, <b>die Fehlinterpretation</b>, <b>der technische Dienstleister</b>, <b>die Wartung</b>, <b>die Anschaffungskosten</b>, <b>das Sicherheitsversprechen</b> und <b>die Verhältnismäßigkeit</b>. Starke Nomen-Verb-Verbindungen sind: <b>Daten speichern</b>, <b>Aufnahmen auswerten</b>, <b>Zugriff gewähren</b>, <b>Zugriff beschränken</b>, <b>Löschfristen festlegen</b>, <b>Missbrauch verhindern</b>, <b>Kosten verursachen</b>, <b>Verantwortung tragen</b>, <b>Ressourcen binden</b> und <b>Vertrauen beschädigen</b>.</p>`,
`<p>Ein prüfungsnaher Absatz kann so formuliert werden: Ein weiterer problematischer Aspekt betrifft den Umgang mit sensiblen Bilddaten. Gerade bei Minderjährigen muss besonders sorgfältig geprüft werden, wer Zugriff auf die Aufnahmen erhält. Hinzu kommt, dass technische Systeme nicht nur angeschafft, sondern auch gewartet und kontrolliert werden müssen. Ein kurzer Videoausschnitt kann eine Situation verfälschen, wenn der Zusammenhang fehlt. Statt Sicherheit zu garantieren, kann die Maßnahme neue organisatorische und rechtliche Probleme schaffen.</p>`,
`<h4>8. Aufbau einer vollständigen Nachteilserörterung</h4>`,
`<p>Eine vollständige Erörterung sollte klar strukturiert sein. In der Einleitung kann man schreiben, dass in vielen Schulen darüber diskutiert wird, ob Videoüberwachung zu mehr Sicherheit beitragen kann. Danach sollte die Streitfrage genannt werden: Ist Videoüberwachung in Schulen ein legitimes Sicherheitsmittel oder ein Eingriff in einen geschützten Lernraum? Anschließend folgen die drei Nachteile in getrennten Absätzen. Jeder Absatz sollte eine Behauptung, eine Erklärung, ein Beispiel, eine Folge und eine Bewertung enthalten.</p>`,
`<p>Für den ersten Absatz eignet sich der Schwerpunkt Privatsphäre und Vertrauensverlust. Für den zweiten Absatz passt psychischer Druck und Anpassungszwang. Für den dritten Absatz sollte der Umgang mit sensiblen Bilddaten erklärt werden. Der Schluss kann abwägend formuliert werden: Videoüberwachung kann zwar Sicherheit versprechen, bringt aber erhebliche Nachteile mit sich. Aus meiner Sicht sollte eine Schule zuerst auf Vertrauen, klare Regeln, persönliche Gespräche, Aufsicht und Schulsozialarbeit setzen, bevor sie zu dauerhafter Überwachung greift.</p>`,
`<h4>9. Vollständige Muster-Erörterung</h4>`,
`<p>In vielen Schulen wird darüber nachgedacht, ob Videoüberwachung zu mehr Sicherheit beitragen kann. Auf den ersten Blick wirkt diese Maßnahme praktisch, weil Konflikte, Diebstähle oder fremde Personen schneller erkannt werden könnten. Trotzdem sollte sorgfältig geprüft werden, ob Kameras in einem schulischen Umfeld wirklich angemessen sind. Schulen sind nicht nur Orte der Ordnung, sondern auch Räume des Lernens, der persönlichen Entwicklung und des Vertrauens. Aus diesem Grund bringt Videoüberwachung mehrere Nachteile mit sich.</p>`,
`<p>Ein erster wichtiger Nachteil besteht darin, dass Videoüberwachung in die Privatsphäre der Schülerinnen und Schüler eingreifen kann. Jugendliche verbringen einen großen Teil ihres Alltags in der Schule. Sie sprechen in Pausen mit Freunden, lösen Konflikte, machen Fehler und erleben persönliche Situationen. Wenn diese Momente durch Kameras erfasst werden, verändert sich der Charakter des Schulraums. Die Schule wirkt dann weniger wie ein geschützter Lernort und stärker wie ein kontrollierter Bereich. Zwar ist Sicherheit ein berechtigtes Ziel, doch darf sie nicht dazu führen, dass junge Menschen sich ständig beobachtet fühlen. Langfristig kann dadurch das Vertrauen zwischen Schule und Lernenden geschwächt werden.</p>`,
`<p>Darüber hinaus kann Videoüberwachung psychischen Druck erzeugen. Viele Schülerinnen und Schüler achten ohnehin darauf, wie sie von anderen wahrgenommen werden. Wenn zusätzlich Kameras installiert sind, kann dieses Gefühl der Bewertung noch stärker werden. Jugendliche passen ihr Verhalten dann möglicherweise nur äußerlich an, weil sie Angst vor Kontrolle haben. Das bedeutet jedoch nicht, dass sie Verantwortung übernehmen oder Regeln wirklich verstehen. Eine Schule sollte nicht nur Disziplin erzwingen, sondern die Entwicklung von Selbstständigkeit fördern. Wenn Konflikte lediglich in unbeobachtete Bereiche verschoben werden, ist pädagogisch wenig gewonnen.</p>`,
`<p>Ein weiterer problematischer Punkt betrifft den Datenschutz. Kameras erzeugen sensible Bilddaten, und gerade bei Minderjährigen muss sehr genau geregelt werden, wer Zugriff auf diese Aufnahmen hat. Auch Löschfristen, technische Sicherheit und Zuständigkeiten müssen klar sein. Wenn Aufnahmen falsch verwendet oder ohne vollständigen Zusammenhang betrachtet werden, können Schülerinnen und Schüler ungerecht beurteilt werden. Hinzu kommt, dass Kameras Kosten verursachen und organisatorische Ressourcen binden. Dieses Geld und diese Aufmerksamkeit könnten stattdessen in Schulsozialarbeit, mehr Aufsichtspersonal oder Präventionsprojekte investiert werden.</p>`,
`<p>Zusammenfassend lässt sich sagen, dass Videoüberwachung in der Schule zwar Sicherheit versprechen kann, aber erhebliche Nachteile mit sich bringt. Sie kann die Privatsphäre einschränken, psychischen Druck erzeugen und neue Datenschutzprobleme schaffen. Aus meiner Sicht sollte eine Schule daher zuerst auf Vertrauen, klare Regeln, persönliche Gespräche und pädagogische Prävention setzen. Eine sichere Schule entsteht nicht allein durch Kameras, sondern vor allem durch ein respektvolles und verantwortungsbewusstes Miteinander.</p>`,
`<h4>10. Persönliche Schreibkontrolle</h4>`,
`<p>Vor der Abgabe sollte geprüft werden, ob der Text wirklich nur Nachteile behandelt. Werden die drei Hauptpunkte klar getrennt? Wird die Privatsphäre mit konkreten Orten wie Flur, Pausenhof oder Aufenthaltsraum verbunden? Wird psychischer Druck nicht nur behauptet, sondern mit Anpassungszwang und schwächerer Selbstständigkeit erklärt? Wird Datenschutz als zentrales Gegenargument behandelt und nicht nur als Nebenaspekt erwähnt? Sind Nomen-Verb-Verbindungen wie <b>in die Privatsphäre eingreifen</b>, <b>Druck ausüben</b>, <b>Vertrauen beeinträchtigen</b>, <b>Zugriff beschränken</b> und <b>Ressourcen binden</b> korrekt eingesetzt? Ein starker C1/C2-Text entsteht durch klare Begriffe, logische Verbindungen und konkrete Beispiele.</p>`
].join('');
var P=[
['in die Privatsphäre eingreifen','in + Akkusativ','Videoüberwachung kann ___ die Privatsphäre der Lernenden eingreifen.','in','persönlichen Schutzraum verletzen'],
['das Vertrauen beeinträchtigen','NVV','Ständige Beobachtung kann das Vertrauen zwischen Schule und Lernenden ___.','beeinträchtigen','Vertrauensverhältnis schwächen'],
['ein Gefühl permanenter Kontrolle erzeugen','NVV','Kameras können ein Gefühl permanenter Kontrolle ___.','erzeugen','Kontrollwahrnehmung schaffen'],
['unter Beobachtung stehen','unter + Dativ','Schülerinnen und Schüler haben das Gefühl, ständig ___ Beobachtung zu stehen.','unter','beobachtet werden'],
['psychischen Druck ausüben','NVV','Kameras können psychischen Druck auf Jugendliche ___.','ausüben','Belastung erzeugen'],
['das Verhalten anpassen','Kollokation','Viele Jugendliche passen ihr Verhalten aus Angst vor Kontrolle ___.','an','sich kontrollierter verhalten'],
['Konflikte pädagogisch bearbeiten','Kollokation','Konflikte sollten nicht nur registriert, sondern pädagogisch ___ werden.','bearbeitet','erzieherisch lösen'],
['sensible Bilddaten speichern','Kollokation','Kameras können sensible Bilddaten von Minderjährigen ___.','speichern','Aufnahmen sichern'],
['Zugriff auf Aufnahmen beschränken','auf + Akkusativ','Die Schule muss den Zugriff ___ Aufnahmen beschränken.','auf','Datenzugang begrenzen'],
['Löschfristen festlegen','NVV','Für Videoaufnahmen müssen klare Löschfristen ___ werden.','festgelegt','Speicherdauer regeln'],
['Missbrauch verhindern','Kollokation','Technische und organisatorische Regeln sollen Missbrauch ___.','verhindern','falsche Nutzung vermeiden'],
['Ressourcen binden','NVV','Kameras können finanzielle und organisatorische Ressourcen ___.','binden','Mittel beanspruchen'],
['aus dem Zusammenhang reißen','feste Wendung','Ein Videoausschnitt kann eine Situation ___ dem Zusammenhang reißen.','aus','Kontext verlieren'],
['mildere Mittel in Betracht ziehen','NVV','Vor Kameras sollte die Schule mildere Mittel in Betracht ___.','ziehen','Alternativen prüfen'],
['ein Klima des Misstrauens erzeugen','NVV','Dauerhafte Überwachung kann ein Klima des Misstrauens ___.','erzeugen','Schulklima belasten']
];
var MC=[
['Welche Grundthese passt ausschließlich zu Nachteilen?',['Videoüberwachung kann Privatsphäre einschränken, Druck erzeugen und Datenschutzrisiken schaffen.','Videoüberwachung hat nur Vorteile für Schulen.','Kameras lösen alle pädagogischen Probleme automatisch.','Videoüberwachung ersetzt Gespräche vollständig.'],0,'Grundthese'],
['Welche Formulierung ist C1/C2-gerecht?',['in die Privatsphäre eingreifen','Privatsphäre kaputt machen','Schüler filmen ist schlecht','Kameras machen Schule böse'],0,'Register'],
['Welche Folge passt zu dauerhafter Beobachtung?',['Das Vertrauensverhältnis kann geschwächt werden.','Alle Schüler lernen automatisch besser.','Datenschutz wird überflüssig.','Konflikte verschwinden endgültig.'],0,'Folge'],
['Welche Formulierung beschreibt psychischen Druck?',['Jugendliche passen ihr Verhalten aus Angst vor Kontrolle an.','Jugendliche haben immer mehr Spaß.','Kameras ersetzen Selbstständigkeit positiv.','Alle Konflikte werden pädagogisch gelöst.'],0,'Nachteil 2'],
['Welche Datenschutzformulierung ist korrekt?',['Zugriff auf Aufnahmen beschränken','Zugriff an Aufnahmen machen','Aufnahmen ohne Kontext beurteilen als Lösung','Daten ewig speichern'],0,'Datenschutz'],
['Welche Aussage ist prüfungsstark?',['Ein Video zeigt oft nur einen Ausschnitt, nicht den vollständigen Zusammenhang.','Ein Video ist immer die ganze Wahrheit.','Bilddaten von Minderjährigen sind unwichtig.','Löschfristen braucht man nicht.'],0,'Fehlinterpretation'],
['Welche NVV passt?',['Ressourcen binden','Ressourcen machen','Ressourcen stehen','Ressourcen filmen'],0,'NVV'],
['Welche Alternative ist pädagogisch sinnvoller?',['mehr Aufsicht, Schulsozialarbeit und klare Regeln prüfen','noch mehr Kameras ohne Datenschutz einsetzen','alle Pausenräume dauerhaft filmen','Aufnahmen beliebig weitergeben'],0,'Alternative']
];
var TF=[
['Das Modul behandelt ausschließlich Nachteile der Videoüberwachung in der Schule.',true,'Fokus'],
['Videoüberwachung kann in die Privatsphäre der Schülerinnen und Schüler eingreifen.',true,'Nachteil 1'],
['Kameras können Vertrauen automatisch und immer stärken.',false,'Bewertung'],
['Psychischer Druck kann entstehen, wenn Jugendliche sich dauerhaft beobachtet fühlen.',true,'Nachteil 2'],
['Konflikte werden durch Kameras immer pädagogisch gelöst.',false,'Pädagogik'],
['Bilddaten von Minderjährigen sind besonders sensibel.',true,'Datenschutz'],
['Ein kurzer Videoausschnitt kann ohne Kontext falsch interpretiert werden.',true,'Fehlinterpretation'],
['Mehr Überwachung bedeutet auch mehr Verantwortung.',true,'Kontrollaufwand']
];
window.DEUTSCH_TESTS[key]={category:'Bevor Schreiben',slug:'videoueberwachung_in_der_schule_nachteile_c1_c2',title:'Videoüberwachung in der Schule – Nachteile · C1/C2 Nachteilsabsatz',topic:'Erörterung · Nachteile · Schule · Privatsphäre · Datenschutz',source:source,words:P.map(function(x){return x[0];}),fill:P.map(function(x){return [x[2],x[3],x[1]];}),mc:MC,tf:TF,wordMatch:P.map(function(x){return [x[0],x[4]];}),phraseMatch:[['Privatsphäre','einschränken'],['Vertrauen','beeinträchtigen'],['psychischen Druck','ausüben'],['Verhalten','anpassen'],['Bilddaten','speichern'],['Zugriff','beschränken'],['Ressourcen','binden'],['mildere Mittel','in Betracht ziehen']],prep:P.map(function(x){return [x[2],x[3],x[1]];}),hang:['in die Privatsphäre eingreifen','das Vertrauen beeinträchtigen','ein Gefühl permanenter Kontrolle erzeugen','unter Beobachtung stehen','psychischen Druck ausüben','das Verhalten anpassen','Konflikte pädagogisch bearbeiten','sensible Bilddaten speichern','Zugriff auf Aufnahmen beschränken','Löschfristen festlegen','Missbrauch verhindern','Ressourcen binden','aus dem Zusammenhang reißen','mildere Mittel in Betracht ziehen','ein Klima des Misstrauens erzeugen']};
window.DEUTSCH_LESSONS[key]={source:source,longSourceVerified:true,short:'<h3>Videoüberwachung in der Schule – Nachteile · Kurzüberblick</h3><p>Dieses Modul behandelt ausschließlich Nachteile. Die drei zentralen Argumente sind: Eingriff in die Privatsphäre, psychischer Druck durch ständige Beobachtung und Datenschutzrisiken durch sensible Bilddaten von Minderjährigen.</p>',medium:'<h3>Videoüberwachung in der Schule – Nachteile · Erweiterte Erklärung</h3><p>Videoüberwachung kann den Charakter der Schule als geschützten Lern- und Lebensraum verändern. Sie kann das Vertrauen zwischen Schule und Lernenden beeinträchtigen, Jugendliche zu äußerlich angepasstem Verhalten drängen und neue organisatorische Verantwortung beim Umgang mit Bilddaten schaffen. Für C1/C2-Texte sind besonders wichtig: <b>in die Privatsphäre eingreifen</b>, <b>Druck ausüben</b>, <b>Vertrauen beeinträchtigen</b>, <b>Bilddaten speichern</b>, <b>Zugriff beschränken</b> und <b>Ressourcen binden</b>.</p>',long:LONG};
function active(){var t=(document.getElementById('lessonTitle')||{}).textContent||'';return t.indexOf('Videoüberwachung in der Schule')>-1||t.indexOf('videoueberwachung_in_der_schule_nachteile')>-1;}
function visible(){var x=document.getElementById('lesson');return !x||!/(^|\s)hide(\s|$)/.test(x.className||'');}
function render(){if(!visible()||!active())return;var title=document.getElementById('lessonTitle'),meta=document.getElementById('lessonMeta'),content=document.getElementById('lessonContent');if(title)title.textContent='Lektion: Videoüberwachung in der Schule – Nachteile';if(meta)meta.textContent='Niveau: C1/C2 · Erörterung · Nachteile';if(content&&content.innerHTML!==LONG)content.innerHTML=LONG;}
render();setTimeout(render,250);setTimeout(render,900);document.addEventListener('click',function(){setTimeout(render,80);setTimeout(render,300);},true);
window.AAYS_BEFORE_VIDEO_SCHULE_NACHTEILE_OK=true;
})();