window.DEUTSCH_TESTS = window.DEUTSCH_TESTS || {};
window.DEUTSCH_TESTS.t9 = {
  slug: "persoenlichkeit_selbstverwirklichung_individualitaet",
  title: "9. Persönlichkeit, Selbstverwirklichung und Individualität",
  topic: "Persönlichkeit · Selbstverwirklichung · Individualität · Selbstsicherheit · Freiheit · Begabung",
  words: [
    "Selbstverwirklichung",
    "eine spürbare Verbesserung der Selbstverwirklichung",
    "eine Förderung der Selbstverwirklichung",
    "das Gefühl der Selbstsicherheit",
    "Persönlichkeit",
    "Selbstsicherheit",
    "Persönlichkeitsentwicklung und Individualität",
    "Persönlichkeit und Entwicklung",
    "Entfaltung",
    "Selbstständigkeit",
    "persönliche Freiheit",
    "individuelle Entwicklung",
    "Begabung",
    "Lebensbereich",
    "Individualität",
    "Selbstwertgefühl",
    "Alltag und Selbstständigkeit",
    "Entfaltung der eigenen Persönlichkeit",
    "Raum für individuelle Entwicklung",
    "eigene Begabungen",
    "persönliche Interessen",
    "neue Perspektiven",
    "Menschsein"
  ],
  fill: [
    ["Künstlerische Bildung kann zur ____ beitragen, wenn sie individuelle Ausdrucksformen ernst nimmt.", "Selbstverwirklichung", "Nomen"],
    ["Ein unterstützendes Umfeld kann eine spürbare Verbesserung der ____ ermöglichen.", "Selbstverwirklichung", "Genitiv"],
    ["Die gezielte Förderung persönlicher Interessen kann eine ____ der Selbstverwirklichung bewirken.", "Förderung", "Nomen"],
    ["Erfolgreiche Erfahrungen stärken häufig das Gefühl der ____.", "Selbstsicherheit", "Nomen"],
    ["Bildung kann zur Entfaltung der eigenen ____ beitragen.", "Persönlichkeit", "Nomen"],
    ["Selbstständige Entscheidungen können persönliche ____ ermöglichen.", "Freiheit", "Nomen"],
    ["Ein offenes Lernumfeld schafft Raum für individuelle ____.", "Entwicklung", "Nomen"],
    ["Jugendliche sollten die Möglichkeit erhalten, eigene ____ zu entfalten.", "Begabungen", "Nomen"],
    ["Wer persönliche Interessen gezielt verfolgt, stärkt häufig sein ____.", "Selbstwertgefühl", "Nomen"],
    ["Neue Erfahrungen können neue ____ eröffnen.", "Perspektiven", "Nomen"],
    ["Die Frage, was es bedeutet, ____ zu sein, berührt grundlegende Aspekte der Persönlichkeitsentwicklung.", "Mensch", "Begriff"],
    ["Selbstständigkeit im Alltag setzt voraus, Verantwortung in verschiedenen ____ zu übernehmen.", "Lebensbereichen", "Dativ Plural"],
    ["Persönlichkeitsentwicklung und ____ hängen eng miteinander zusammen.", "Individualität", "Nomen"],
    ["Die Entfaltung persönlicher Interessen kann neue Perspektiven ____.", "hervorbringen", "Verb"],
    ["Ein unterstützender sozialer Kontext spielt eine Rolle bei der ____.", "Selbstverwirklichung", "Nomen"],
    ["Alltag und ____ bilden einen wichtigen Bereich individueller Entwicklung.", "Selbstständigkeit", "Nomen"]
  ],
  mc: [
    ["Welche Formulierung ist C1/C2-gerecht?", ["Ein unterstützendes Umfeld kann zur Entfaltung der eigenen Persönlichkeit beitragen.", "Ein gutes Umfeld macht Leute besser.", "Persönlichkeit wächst irgendwie.", "Freiheit macht Entwicklung.", "Menschen sind halt individuell."], 0, "C1/C2"],
    ["Welche Kollokation ist korrekt?", ["zur Selbstverwirklichung beitragen", "an Selbstverwirklichung essen", "Selbstverwirklichung aufmachen", "mit Selbstverwirklichung stoßen", "Selbstverwirklichung verdrängen"], 0, "Kollokation"],
    ["Welche Struktur beschreibt Entwicklung präzise?", ["Raum für individuelle Entwicklung schaffen", "individuelle Entwicklung in Raum essen", "Raum an Entwicklung verursachen", "Entwicklung gegen Begabung fördern", "Individualität in Freiheit verkaufen"], 0, "Kollokation"],
    ["Welche Aussage ist differenziert?", ["Selbstverwirklichung setzt persönliche Freiheit voraus, bleibt aber häufig von sozialen Bedingungen abhängig.", "Selbstverwirklichung ist immer völlig privat.", "Individualität hat mit Gesellschaft nichts zu tun.", "Begabung entwickelt sich ohne Förderung automatisch.", "Selbstständigkeit bedeutet, keine Hilfe anzunehmen."], 0, "Argumentation"],
    ["Welche Wendung passt zu Begabung?", ["eigene Begabungen entfalten", "Begabungen verursachen", "Begabungen auf Freiheit stoßen", "Begabung im Selbstwertgefühl essen", "Begabungen gegenüber Entwicklung verbrauchen"], 0, "Kollokation"],
    ["Welche Formulierung ist akademisch am präzisesten?", ["Die Förderung individueller Entwicklung kann das Selbstwertgefühl stärken.", "Entwicklung macht Gefühl gut.", "Menschen bekommen mehr Selbst.", "Individualität ist ein Ding im Alltag.", "Persönlichkeit passiert durch Freiheit."], 0, "Akademischer Stil"],
    ["Welche Verbindung passt zu Perspektiven?", ["neue Perspektiven eröffnen", "Perspektiven an Selbstständigkeit essen", "Perspektiven gegenüber Freiheit verbrauchen", "Perspektiven für Menschsein verursachen", "Perspektiven unter Begabung geraten"], 0, "Kollokation"],
    ["Welche Aussage vermeidet Vereinfachung?", ["Persönliche Freiheit kann individuelle Entwicklung ermöglichen, garantiert sie jedoch nicht automatisch.", "Freiheit löst jedes Entwicklungsproblem.", "Selbstsicherheit entsteht immer allein.", "Individualität ist unabhängig von Lebensbereichen.", "Selbstwertgefühl ist rein wirtschaftlich."], 0, "Differenzierung"]
  ],
  tf: [
    ["Zur Selbstverwirklichung beitragen bedeutet, Bedingungen zu schaffen, unter denen persönliche Potenziale entwickelt werden können.", true, "Bedeutung"],
    ["Eine spürbare Verbesserung der Selbstverwirklichung beschreibt eine wahrnehmbare Stärkung persönlicher Entfaltungsmöglichkeiten.", true, "Bedeutung"],
    ["Persönliche Freiheit ermöglichen und Raum für individuelle Entwicklung schaffen sind sinnverwandte Formulierungen.", true, "Synonymie"],
    ["Eigene Begabungen entfalten bedeutet, persönliche Fähigkeiten zu unterdrücken.", false, "Bedeutung"],
    ["Ein Beitrag zur Selbstverwirklichung leisten ist grammatisch falsch; korrekt ist: einen Beitrag zur Selbstverwirklichung leisten.", true, "Grammatik"],
    ["Selbstsicherheit und Selbstwertgefühl sind vollständig identische Begriffe.", false, "Begriff"],
    ["Die Entfaltung der eigenen Persönlichkeit kann mit individueller Entwicklung verbunden sein.", true, "Persönlichkeit"],
    ["Persönliche Interessen gezielt zu verfolgen kann neue Perspektiven eröffnen.", true, "Entwicklung"],
    ["Was es bedeutet, Mensch zu sein, ist eine Formulierung, die existenzielle und anthropologische Fragen berührt.", true, "Menschsein"],
    ["Alltag und Selbstständigkeit haben mit Persönlichkeitsentwicklung grundsätzlich nichts zu tun.", false, "Alltag"]
  ],
  wordMatch: [
    ["die Selbstverwirklichung", "Prozess, in dem eine Person eigene Fähigkeiten, Werte und Lebensziele entfaltet"],
    ["eine spürbare Verbesserung der Selbstverwirklichung", "deutlich wahrnehmbare Stärkung persönlicher Entfaltungsmöglichkeiten"],
    ["eine Förderung der Selbstverwirklichung", "gezielte Unterstützung individueller Entfaltung und persönlicher Entwicklung"],
    ["das Gefühl der Selbstsicherheit", "subjektives Empfinden, kompetent, handlungsfähig und innerlich stabil zu sein"],
    ["die Persönlichkeit", "Gesamtheit charakterlicher, emotionaler und sozialer Eigenschaften einer Person"],
    ["die Selbstsicherheit", "Fähigkeit, in Situationen überzeugt und stabil aufzutreten"],
    ["die Entfaltung", "Prozess, in dem vorhandene Fähigkeiten oder Eigenschaften sichtbar und wirksam werden"],
    ["die Selbstständigkeit", "Fähigkeit, Entscheidungen und Aufgaben eigenverantwortlich zu bewältigen"],
    ["die persönliche Freiheit", "Möglichkeit, das eigene Leben nach persönlichen Werten und Zielen zu gestalten"],
    ["die individuelle Entwicklung", "persönlicher Entwicklungsprozess, der Fähigkeiten, Interessen und Identität umfasst"],
    ["die Begabung", "besondere Fähigkeit oder Anlage, die entwickelt werden kann"],
    ["der Lebensbereich", "Teil des Lebens, etwa Beruf, Familie, Bildung, Freizeit oder Alltag"],
    ["die Individualität", "Eigenart einer Person, die sie von anderen unterscheidet"],
    ["das Selbstwertgefühl", "Bewertung des eigenen Wertes und der eigenen Bedeutung"],
    ["das Menschsein", "grundlegende Frage nach Würde, Verantwortung, Freiheit und menschlicher Existenz"]
  ],
  phraseMatch: [
    ["zur Selbstverwirklichung", "beitragen"],
    ["einen Beitrag zur Selbstverwirklichung", "leisten"],
    ["eine Rolle bei der Selbstverwirklichung", "spielen"],
    ["zur Entfaltung der eigenen Persönlichkeit", "beitragen"],
    ["persönliche Freiheit", "ermöglichen"],
    ["Raum für individuelle Entwicklung", "schaffen"],
    ["eigene Begabungen", "entfalten"],
    ["persönliche Interessen gezielt", "verfolgen"],
    ["neue Perspektiven", "hervorbringen"],
    ["neue Perspektiven", "eröffnen"],
    ["verstehen, was es bedeutet", "Mensch zu sein"],
    ["das Gefühl der", "Selbstsicherheit"],
    ["eine spürbare Verbesserung der", "Selbstverwirklichung"],
    ["eine Förderung der", "Selbstverwirklichung"],
    ["Alltag und", "Selbstständigkeit"],
    ["Persönlichkeitsentwicklung und", "Individualität"]
  ],
  prep: [
    ["Ein unterstützendes Umfeld kann ___ Selbstverwirklichung beitragen.", "zur", "Präposition"],
    ["Bildung kann einen Beitrag ___ Selbstverwirklichung leisten.", "zur", "Präposition"],
    ["Soziale Anerkennung kann eine Rolle ___ der Selbstverwirklichung spielen.", "bei", "Präposition"],
    ["Kreative Tätigkeiten können ___ Entfaltung der eigenen Persönlichkeit beitragen.", "zur", "Präposition"],
    ["Ein offener Lernraum schafft Raum ___ individuelle Entwicklung.", "für", "Präposition"],
    ["Jugendliche sollten eigene Begabungen ___ können.", "entfalten", "Feste Verbindung"],
    ["Wer persönliche Interessen gezielt verfolgt, kann ___ Selbstsicherheit gewinnen.", "an", "Präposition"],
    ["Neue Erfahrungen können Perspektiven ___ unterschiedliche Lebensbereiche eröffnen.", "für", "Präposition"],
    ["Die Frage, was es bedeutet, Mensch ___ sein, ist grundlegend für ein reflektiertes Menschenbild.", "zu", "Infinitivstruktur"],
    ["Selbstständigkeit zeigt sich häufig ___ Alltag.", "im", "Präposition"],
    ["Das Selbstwertgefühl hängt häufig ___ Erfahrungen in verschiedenen Lebensbereichen zusammen.", "mit", "Präposition"],
    ["Individuelle Entwicklung besteht nicht nur ___ äußerem Erfolg.", "in", "Präposition"]
  ],
  hang: [
    "zur Selbstverwirklichung beitragen",
    "einen Beitrag zur Selbstverwirklichung leisten",
    "eine Rolle bei der Selbstverwirklichung spielen",
    "zur Entfaltung der eigenen Persönlichkeit beitragen",
    "persönliche Freiheit ermöglichen",
    "Raum für individuelle Entwicklung schaffen",
    "eigene Begabungen entfalten",
    "persönliche Interessen gezielt verfolgen",
    "neue Perspektiven hervorbringen",
    "neue Perspektiven eröffnen",
    "verstehen, was es bedeutet, Mensch zu sein",
    "eine spürbare Verbesserung der Selbstverwirklichung",
    "eine Förderung der Selbstverwirklichung",
    "das Gefühl der Selbstsicherheit",
    "Persönlichkeitsentwicklung und Individualität",
    "Persönlichkeit und Entwicklung",
    "die Selbstständigkeit",
    "die persönliche Freiheit",
    "die individuelle Entwicklung",
    "das Selbstwertgefühl"
  ]
};
