window.DEUTSCH_TESTS = window.DEUTSCH_TESTS || {};
window.DEUTSCH_TESTS.t6 = {
  slug: "umwelt_ressourcen_nachhaltigkeit",
  title: "6. Umwelt, Ressourcen und Nachhaltigkeit",
  topic: "Umwelt · Ressourcen · Umweltschutzstandards · Ressourcenverbrauch · rohstoffreiche Regionen",
  words: [
    "Umwelt und Ressourcen",
    "Schaden an der Umwelt",
    "Schäden an der Natur",
    "Ressourcenverbrauch",
    "übermäßiger Ressourcenverbrauch",
    "Umweltschutzstandards",
    "höhere Umweltschutzstandards",
    "Belastungen für die Umwelt",
    "erhebliche Belastungen für die Umwelt",
    "negative Auswirkungen auf die Umwelt",
    "Ressourcen",
    "Ressourcen in hohem Maße",
    "rohstoffreiche Regionen",
    "aufgrund des übermäßigen Ressourcenverbrauchs",
    "aufgrund ihres hohen Ressourcenverbrauchs",
    "konkrete Beispiele zu Umweltschutzstandards",
    "konkrete Beispiele mit Ressourcenverbrauch",
    "insbesondere in rohstoffreichen Regionen"
  ],
  fill: [
    ["Unternehmen müssen verbindliche ____ einhalten, wenn ökologische Mindestanforderungen nicht bloß symbolisch bleiben sollen.", "Umweltschutzstandards", "Nomen"],
    ["Strengere gesetzliche Vorgaben können zu höheren ____ führen.", "Umweltschutzstandards", "Kollokation"],
    ["Ein unkontrollierter Abbau von Rohstoffen kann erhebliche ____ hervorrufen.", "Belastungen für die Umwelt", "Kollokation"],
    ["Industrielle Produktionsprozesse können große ____ verursachen, wenn ökologische Schutzmechanismen fehlen.", "Schäden", "Nomen"],
    ["Der übermäßige ____ gilt als eine zentrale Ursache langfristiger Umweltprobleme.", "Ressourcenverbrauch", "Nomen"],
    ["Einige Industriezweige verbrauchen Ressourcen in hohem ____.", "Maße", "Kollokation"],
    ["Solche Eingriffe können negative Auswirkungen auf die ____ haben.", "Umwelt", "Nomen"],
    ["Der Abbau seltener Rohstoffe verursacht insbesondere in ____ erhebliche ökologische Konflikte.", "rohstoffreichen Regionen", "Kalıp ifade"],
    ["Aufgrund des ____ Ressourcenverbrauchs geraten ökologische Systeme zunehmend unter Druck.", "übermäßigen", "Adjektivdeklination"],
    ["Aufgrund ihres hohen ____ stehen bestimmte Branchen besonders in der Kritik.", "Ressourcenverbrauchs", "Genitiv"],
    ["Konkrete Beispiele zu ____ zeigen, wie stark politische Regulierung ökologische Risiken begrenzen kann.", "Umweltschutzstandards", "Kalıp ifade"],
    ["Konkrete Beispiele mit ____ machen sichtbar, wie sehr Konsum und Produktion miteinander verbunden sind.", "Ressourcenverbrauch", "Kalıp ifade"]
  ],
  mc: [
    ["Welche Formulierung ist C1/C2-gerecht?", ["Ein übermäßiger Ressourcenverbrauch kann erhebliche Belastungen für die Umwelt hervorrufen.", "Viele Sachen machen die Natur schlecht.", "Ressourcen gehen weg und Umwelt ist kaputt.", "Firmen verbrauchen Dinge und das ist nicht gut.", "Die Umwelt bekommt Probleme wegen Sachen."], 0, "C1/C2"],
    ["Welche Kollokation ist korrekt?", ["Schäden an der Umwelt verursachen", "Schäden in Umwelt essen", "Umwelt auf Schäden verbrauchen", "Ressourcen an Schäden einhalten", "Natur zu Standards verkaufen"], 0, "Kollokation"],
    ["Welche Formulierung passt zu Standards?", ["Umweltschutzstandards einhalten", "Umweltschutzstandards verbrauchen", "Umweltschutzstandards hervorrufen", "Umweltschutzstandards schädigen", "Umweltschutzstandards abbauen"], 0, "Verb-Nomen-Verbindung"],
    ["Welche Aussage ist sprachlich präzise?", ["Der Ressourcenverbrauch nimmt in bestimmten Branchen ein problematisches Ausmaß an.", "Ressourcen sind viel und gehen weg.", "Verbrauch macht Umwelt.", "Standards haben Natur kaputt.", "Regionen sind rohstoffreich kaputt."], 0, "Wirtschafts-/Umweltsprache"],
    ["Welche Wendung erklärt eine Ursache korrekt?", ["aufgrund des übermäßigen Ressourcenverbrauchs", "wegen dem Ressourcen viel", "durch Ressourcenverbrauchs", "aufgrund übermäßiger Verbrauch", "infolge Ressourcen verbrauchen"], 0, "Genitiv"],
    ["Welche Aussage ist differenziert?", ["Höhere Umweltschutzstandards können ökologische Schäden begrenzen, verursachen aber häufig Anpassungsdruck für Unternehmen.", "Umweltschutzstandards lösen jedes Umweltproblem sofort.", "Ressourcenverbrauch ist immer völlig harmlos.", "Rohstoffreiche Regionen sind nie betroffen.", "Umweltbelastungen entstehen ohne Ursache."], 0, "Argumentation"],
    ["Welche Struktur ist korrekt?", ["Belastungen für die Umwelt hervorrufen", "Belastungen an die Umwelt gewinnen", "Belastungen für Umwelt einhalten", "Belastungen von Ressourcen verbrauchen", "Belastungen durch Standards schützen"], 0, "Kollokation"],
    ["Welche Aussage verbindet Ursache und Folge angemessen?", ["Ein hoher Ressourcenverbrauch kann negative Auswirkungen auf die Umwelt haben.", "Die Umwelt verbraucht hohe Auswirkungen.", "Ressourcenstandards führen an Natur.", "Schäden halten Ressourcen ein.", "Regionen verursachen Standards."], 0, "Ursache/Folge"]
  ],
  tf: [
    ["Umweltschutzstandards einzuhalten bedeutet, ökologische Mindestanforderungen verbindlich zu beachten.", true, "Definition"],
    ["Der Ausdruck „Schäden an der Umwelt verursachen“ ist fachsprachlich korrekt.", true, "Kollokation"],
    ["Ressourcen in hohem Maße zu verbrauchen bedeutet, Ressourcen nur sehr sparsam einzusetzen.", false, "Bedeutung"],
    ["Erhebliche Belastungen für die Umwelt können durch intensiven Rohstoffabbau entstehen.", true, "Umwelt"],
    ["Aufgrund des übermäßigen Ressourcenverbrauchs steht mit Dativ und benötigt keinen Genitiv.", false, "Genitiv"],
    ["Rohstoffreiche Regionen können besonders stark von Umweltbelastungen betroffen sein.", true, "Kontext"],
    ["Negative Auswirkungen auf die Umwelt sind dasselbe wie höhere Umweltschutzstandards.", false, "Begriff"],
    ["Konkrete Beispiele mit Ressourcenverbrauch können ökologische Zusammenhänge veranschaulichen.", true, "Kalıp ifade"],
    ["Schäden an der Natur verursachen und Schäden an der Umwelt verursachen sind sinnverwandte Formulierungen.", true, "Synonymie"],
    ["Belastungen für die Umwelt hervorrufen ist eine unidiomatische Formulierung.", false, "Kollokation"]
  ],
  wordMatch: [
    ["der Ressourcenverbrauch", "Nutzung und Verbrauch natürlicher oder wirtschaftlicher Ressourcen"],
    ["der übermäßige Ressourcenverbrauch", "Ressourcennutzung, die über ein ökologisch vertretbares Maß hinausgeht"],
    ["Umweltschutzstandards", "Regeln und Mindestanforderungen zum Schutz von Umwelt und Natur"],
    ["Schäden an der Umwelt", "negative, oft langfristige Beeinträchtigungen ökologischer Systeme"],
    ["Belastungen für die Umwelt", "Einwirkungen, die ökologische Systeme zusätzlich beanspruchen oder schwächen"],
    ["negative Auswirkungen auf die Umwelt", "nachteilige Folgen für Natur, Ökosysteme oder Lebensgrundlagen"],
    ["rohstoffreiche Regionen", "Gebiete, in denen viele wirtschaftlich nutzbare natürliche Ressourcen vorkommen"],
    ["Umwelt und Ressourcen", "Themenfeld, das Natur, Rohstoffe, Verbrauch und Schutzmaßnahmen umfasst"],
    ["Ressourcen in hohem Maße", "Ressourcen in besonders großer Menge oder Intensität"],
    ["konkrete Beispiele zu Umweltschutzstandards", "anschauliche Fälle, die ökologische Regeln und deren Wirkung verdeutlichen"]
  ],
  phraseMatch: [
    ["Umweltschutzstandards", "einhalten"],
    ["zu höheren Umweltschutzstandards", "führen"],
    ["Schäden", "verursachen"],
    ["Schäden an der Umwelt", "verursachen"],
    ["Schäden an der Natur", "verursachen"],
    ["große Schäden", "verursachen"],
    ["Belastungen für die Umwelt", "hervorrufen"],
    ["erhebliche Belastungen für die Umwelt", "verursachen"],
    ["negative Auswirkungen auf die Umwelt", "haben"],
    ["Ressourcen", "verbrauchen"],
    ["Ressourcen in hohem Maße", "verbrauchen"],
    ["konkrete Beispiele", "mit Ressourcenverbrauch"],
    ["konkrete Beispiele", "zu Umweltschutzstandards"],
    ["aufgrund des übermäßigen", "Ressourcenverbrauchs"],
    ["insbesondere in", "rohstoffreichen Regionen"]
  ],
  prep: [
    ["Strengere Regeln können ___ höheren Umweltschutzstandards führen.", "zu", "Präposition"],
    ["Industrieanlagen können Schäden ___ der Umwelt verursachen.", "an", "Präposition"],
    ["Bestimmte Eingriffe verursachen Schäden ___ der Natur.", "an", "Präposition"],
    ["Solche Prozesse können Belastungen ___ die Umwelt hervorrufen.", "für", "Präposition"],
    ["Ein hoher Ressourcenverbrauch kann negative Auswirkungen ___ die Umwelt haben.", "auf", "Präposition"],
    ["___ des übermäßigen Ressourcenverbrauchs müssen strengere Maßnahmen ergriffen werden.", "aufgrund", "Präposition"],
    ["___ ihres hohen Ressourcenverbrauchs stehen bestimmte Branchen in der Kritik.", "aufgrund", "Präposition"],
    ["Umweltprobleme treten insbesondere ___ rohstoffreichen Regionen auf.", "in", "Präposition"],
    ["Konkrete Beispiele ___ Umweltschutzstandards zeigen den Nutzen verbindlicher Regeln.", "zu", "Präposition"],
    ["Konkrete Beispiele ___ Ressourcenverbrauch verdeutlichen den Zusammenhang zwischen Konsum und Umweltbelastung.", "mit", "Präposition"]
  ],
  hang: [
    "Ressourcenverbrauch",
    "Umweltschutzstandards",
    "übermäßiger Ressourcenverbrauch",
    "Schäden an der Umwelt",
    "Schäden an der Natur",
    "Belastungen für die Umwelt",
    "negative Auswirkungen",
    "rohstoffreiche Regionen",
    "Umwelt und Ressourcen",
    "Ressourcen verbrauchen",
    "Umweltschutzstandards einhalten"
  ]
};
