window.DEUTSCH_TESTS = window.DEUTSCH_TESTS || {};
window.DEUTSCH_TESTS.t8 = {
  slug: "gesellschaft_kultur_bewusstsein",
  title: "8. Gesellschaft, Kultur und Bewusstsein",
  topic: "Gesellschaft · Kultur · Bewusstsein · Identität · Vielfalt · Reflexion · Menschenbild",
  words: [
    "Kultur und Gesellschaft",
    "Kultur und Struktur",
    "kulturelle Verdrängung lokaler Strukturen",
    "Identität und Vielfalt",
    "Gesellschaft und Unterstützung",
    "Perspektiven, Gesellschaft und Reflexion",
    "Gesellschaft und Denken",
    "Offenheit",
    "Menschsein",
    "Denken, Gesellschaft und Argumentation",
    "gesellschaftliche Weiterentwicklung",
    "Gesellschaft, Denken und Reflexion",
    "Menschenbild",
    "Bewusstsein für gesellschaftliche Ungleichheit",
    "kulturelle Vielfalt",
    "urbane Identität",
    "Toleranz gegenüber anderen Kulturen",
    "respektvoller Umgang",
    "Respekt vor anderen Kulturen",
    "Offenheit gegenüber Neuem",
    "lokale Strukturen",
    "unter den Menschen",
    "differenziertes Menschenbild"
  ],
  fill: [
    ["Kulturelle Bildung kann ein stärkeres ____ für gesellschaftliche Ungleichheit schaffen.", "Bewusstsein", "Nomen"],
    ["Globale Konsumformen können zur kulturellen ____ lokaler Strukturen beitragen.", "Verdrängung", "Nomen"],
    ["Internationale Ketten spielen häufig eine zentrale Rolle bei der kulturellen Verdrängung lokaler ____.", "Strukturen", "Nomen"],
    ["Eine einseitige Standardisierung kann kulturelle Vielfalt ____.", "einschränken", "Verb"],
    ["Die wachsende Präsenz globaler Marken kann die urbane ____ vieler Städte verändern.", "Identität", "Nomen"],
    ["Interkulturelle Begegnungen können die Gesellschaft ____ machen.", "offener", "Adjektiv"],
    ["Kritische Reflexion kann zur gesellschaftlichen ____ beitragen.", "Weiterentwicklung", "Nomen"],
    ["Der Wert solcher Projekte liegt im Beitrag zur gesellschaftlichen ____.", "Weiterentwicklung", "Nomen"],
    ["Bildung kann Offenheit gegenüber ____ fördern.", "Neuem", "Dativ"],
    ["Ein reflektierter Umgang mit Vielfalt hilft, ein differenziertes ____ zu entwickeln.", "Menschenbild", "Nomen"],
    ["Wer Toleranz gegenüber anderen Kulturen zeigt, trägt zum respektvollen ____ bei.", "Umgang", "Nomen"],
    ["Respekt vor anderen Kulturen kann Vertrauen ____ den Menschen stärken.", "unter", "Präposition"],
    ["Gesellschaftliche Debatten können neue Perspektiven eröffnen und das Denken ____.", "erweitern", "Verb"],
    ["Die Auseinandersetzung mit Kultur und Gesellschaft kann Reflexion ____.", "anregen", "Verb"],
    ["Ein offenes Menschenbild setzt die Bereitschaft voraus, anderen Kulturen Toleranz ____.", "entgegenzubringen", "Verb"],
    ["Kulturelle Vielfalt kann urbane Identität nicht nur prägen, sondern auch ____.", "verändern", "Verb"]
  ],
  mc: [
    ["Welche Formulierung ist C1/C2-gerecht?", ["Kulturelle Bildung kann Bewusstsein für gesellschaftliche Ungleichheit schaffen.", "Kultur macht Leute netter.", "Gesellschaft ist viel Denken.", "Menschenbild ist, wie Menschen sind.", "Vielfalt macht Städte anders."], 0, "C1/C2"],
    ["Welche Kollokation ist korrekt?", ["Bewusstsein für gesellschaftliche Ungleichheit schaffen", "Bewusstsein an Ungleichheit machen", "Ungleichheit auf Bewusstsein essen", "Bewusstsein mit Gesellschaft verdrängen", "Ungleichheit gegen Kultur fördern"], 0, "Kollokation"],
    ["Welche Struktur beschreibt kulturelle Veränderung präzise?", ["zur kulturellen Verdrängung lokaler Strukturen beitragen", "lokale Strukturen in Kultur essen", "Kultur macht die Struktur weg", "Verdrängung bei Vielfalt kaufen", "Identität zu Gesellschaft benutzen"], 0, "Kultur"],
    ["Welche Aussage ist differenziert?", ["Globale Einflüsse können kulturelle Vielfalt bereichern, zugleich aber lokale Strukturen verdrängen.", "Globale Einflüsse sind immer zerstörerisch.", "Lokale Strukturen verändern sich niemals.", "Kulturelle Vielfalt hat keinen gesellschaftlichen Wert.", "Offenheit bedeutet, alles unkritisch zu übernehmen."], 0, "Argumentation"],
    ["Welche Verbindung passt zu Offenheit?", ["Offenheit gegenüber Neuem fördern", "Offenheit an Neuem verursachen", "Offenheit in Gesellschaft essen", "Neues mit Offenheit verdrängen", "Offenheit für Dativ stoßen"], 0, "Rektion"],
    ["Welche Formulierung ist im akademischen Stil am präzisesten?", ["Ein differenziertes Menschenbild kann zur gesellschaftlichen Reflexion beitragen.", "Menschen sehen Menschen anders.", "Gesellschaft denkt über Leute.", "Menschsein ist einfach Mensch sein.", "Kultur macht viele Perspektiven."], 0, "Akademischer Stil"],
    ["Welche Wendung passt zu Toleranz?", ["anderen Kulturen Toleranz entgegenbringen", "andere Kulturen Toleranz verursachen", "Toleranz an anderen Kulturen essen", "Kulturen mit Toleranz verdrängen", "Toleranz auf Menschenbild stoßen"], 0, "Kollokation"],
    ["Welche Aussage vermeidet eine zu starke Vereinfachung?", ["Kulturelle Verdrängung kann urbane Identität verändern, ohne kulturelle Vielfalt vollständig aufzuheben.", "Kulturelle Verdrängung zerstört immer jede Kultur vollständig.", "Urbane Identität ist unwichtig.", "Gesellschaftliche Weiterentwicklung entsteht automatisch.", "Respekt vor anderen Kulturen ist nur privat relevant."], 0, "Differenzierung"]
  ],
  tf: [
    ["Bewusstsein für gesellschaftliche Ungleichheit zu schaffen bedeutet, soziale Unterschiede sichtbar und reflektierbar zu machen.", true, "Bedeutung"],
    ["Kulturelle Verdrängung lokaler Strukturen kann mit einer Veränderung urbaner Identität verbunden sein.", true, "Kultur"],
    ["Offenheit gegenüber Neuem bedeutet, jede Veränderung unkritisch zu akzeptieren.", false, "Präzision"],
    ["Ein differenziertes Menschenbild berücksichtigt, dass Menschen durch Kultur, Erfahrung und gesellschaftliche Bedingungen geprägt sind.", true, "Menschenbild"],
    ["Respekt vor + Dativ ist eine feste Verbindung.", true, "Rektion"],
    ["Toleranz gegenüber anderen Kulturen zu zeigen und anderen Kulturen Toleranz entgegenzubringen sind sinnverwandte Formulierungen.", true, "Kollokation"],
    ["Zur gesellschaftlichen Weiterentwicklung beitragen ist eine unidiomatische Struktur.", false, "Kollokation"],
    ["Kulturelle Vielfalt einzuschränken kann langfristig gesellschaftliche Offenheit schwächen.", true, "Argumentation"],
    ["Das Menschsein bezeichnet ausschließlich biologische Eigenschaften des Menschen.", false, "Begriff"],
    ["Reflexion kann dazu beitragen, gesellschaftliches Denken weiterzuentwickeln.", true, "Reflexion"]
  ],
  wordMatch: [
    ["die kulturelle Verdrängung lokaler Strukturen", "Prozess, bei dem lokale kulturelle Formen durch dominante externe Einflüsse zurückgedrängt werden"],
    ["die Offenheit", "Bereitschaft, neue Perspektiven, Erfahrungen oder Lebensweisen nicht vorschnell abzulehnen"],
    ["das Menschsein", "grundlegende Frage danach, was menschliche Existenz, Verantwortung und Würde ausmacht"],
    ["die gesellschaftliche Weiterentwicklung", "Veränderungsprozess, durch den eine Gesellschaft reflektierter, gerechter oder offener werden kann"],
    ["das Menschenbild", "Vorstellung davon, was den Menschen prägt und wie menschliches Verhalten zu verstehen ist"],
    ["kulturelle Vielfalt", "Nebeneinander unterschiedlicher kultureller Ausdrucksformen, Lebensweisen und Traditionen"],
    ["urbane Identität", "kulturelles und soziales Profil einer Stadt, das ihre Eigenart prägt"],
    ["gesellschaftliche Ungleichheit", "ungleiche Verteilung von Chancen, Ressourcen, Anerkennung oder Teilhabe"],
    ["Reflexion", "bewusste gedankliche Auseinandersetzung mit Erfahrungen, Werten oder gesellschaftlichen Strukturen"],
    ["Respekt vor anderen Kulturen", "anerkennende Haltung gegenüber Lebensweisen und Wertvorstellungen anderer kultureller Gruppen"],
    ["Perspektiven", "unterschiedliche Sichtweisen, aus denen gesellschaftliche Fragen betrachtet werden können"],
    ["lokale Strukturen", "örtlich gewachsene soziale, kulturelle oder wirtschaftliche Ordnungen"],
    ["Identität und Vielfalt", "Zusammenhang zwischen Zugehörigkeit, Selbstverständnis und kultureller Unterschiedlichkeit"],
    ["Denken, Gesellschaft und Argumentation", "Bereich, in dem gesellschaftliche Fragen begründet, reflektiert und sprachlich differenziert behandelt werden"]
  ],
  phraseMatch: [
    ["Bewusstsein für etwas", "schaffen"],
    ["Bewusstsein für gesellschaftliche Ungleichheit", "schaffen"],
    ["einen wichtigen Beitrag dazu", "leisten, Bewusstsein zu schaffen"],
    ["zur kulturellen Verdrängung lokaler Strukturen", "beitragen"],
    ["eine Rolle bei der kulturellen Verdrängung", "spielen"],
    ["eine zentrale Rolle bei der kulturellen Verdrängung lokaler Strukturen", "spielen"],
    ["kulturelle Vielfalt", "einschränken"],
    ["urbane Identität", "verändern"],
    ["die urbane Identität vieler Städte", "verändern"],
    ["die Gesellschaft", "offener machen"],
    ["zur gesellschaftlichen Weiterentwicklung", "beitragen"],
    ["im Beitrag zur gesellschaftlichen Weiterentwicklung", "liegen"],
    ["Offenheit gegenüber Neuem", "fördern"],
    ["ein differenziertes Menschenbild", "entwickeln"],
    ["Toleranz gegenüber anderen Kulturen", "zeigen"],
    ["anderen Kulturen Toleranz", "entgegenbringen"],
    ["zum respektvollen Umgang", "beitragen"],
    ["Respekt vor", "anderen Kulturen zeigen"],
    ["unter den", "Menschen"],
    ["Perspektiven, Gesellschaft und Reflexion", "miteinander verbinden"]
  ],
  prep: [
    ["Kulturelle Bildung kann Bewusstsein ___ gesellschaftliche Ungleichheit schaffen.", "für", "Präposition"],
    ["Globale Marken können ___ kulturellen Verdrängung lokaler Strukturen beitragen.", "zur", "Präposition"],
    ["Internationale Ketten spielen eine Rolle ___ der kulturellen Verdrängung.", "bei", "Präposition"],
    ["Eine solche Entwicklung kann eine zentrale Rolle ___ der kulturellen Verdrängung lokaler Strukturen spielen.", "bei", "Präposition"],
    ["Offenheit ___ Neuem kann gesellschaftliches Lernen fördern.", "gegenüber", "Präposition"],
    ["Toleranz ___ anderen Kulturen zu zeigen, ist ein Zeichen sozialer Reife.", "gegenüber", "Präposition"],
    ["Man kann anderen Kulturen Toleranz ___.", "entgegenbringen", "Feste Verbindung"],
    ["Respekt ___ anderen Kulturen setzt Reflexionsfähigkeit voraus.", "vor", "Präposition"],
    ["Der Wert des Projekts liegt ___ seinem Beitrag zur gesellschaftlichen Weiterentwicklung.", "in", "Präposition"],
    ["Kulturelle Vielfalt kann ___ den Menschen Offenheit fördern.", "unter", "Präposition"],
    ["Ein differenziertes Menschenbild entwickelt sich häufig ___ der Auseinandersetzung mit anderen Perspektiven.", "durch", "Präposition"],
    ["Solche Debatten tragen ___ respektvollen Umgang bei.", "zum", "Präposition"]
  ],
  hang: [
    "Bewusstsein für gesellschaftliche Ungleichheit schaffen",
    "kulturelle Verdrängung lokaler Strukturen",
    "zur kulturellen Verdrängung beitragen",
    "eine zentrale Rolle spielen",
    "kulturelle Vielfalt einschränken",
    "urbane Identität verändern",
    "die Gesellschaft offener machen",
    "gesellschaftliche Weiterentwicklung",
    "Offenheit gegenüber Neuem fördern",
    "ein differenziertes Menschenbild entwickeln",
    "Toleranz gegenüber anderen Kulturen zeigen",
    "anderen Kulturen Toleranz entgegenbringen",
    "zum respektvollen Umgang beitragen",
    "Respekt vor anderen Kulturen",
    "unter den Menschen",
    "Kultur und Gesellschaft",
    "Identität und Vielfalt",
    "Gesellschaft und Reflexion",
    "das Menschsein",
    "das Menschenbild"
  ]
};
