window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};
window.DEUTSCH_TESTS.t23={
  category:'Bevor Schreiben',
  slug:'ebooks_nachteile_c1_c2',
  title:'E-Books – Nachteile · C1/C2 Nachteilsabsatz',
  topic:'Erörterung · Nachteile von E-Books · Augenbelastung · technische Abhängigkeit · Datenschutz · klassisches Lesegefühl · Besitzfreiheit',
  words:[
    'E-Books','digitale Bücher','der Nachteilsabsatz','die Bildschirmbelastung','die Augenbelastung','die Konzentrationsfähigkeit','die Reizüberflutung','das Lesevergnügen','die Lesemotivation','das oberflächliche Lesen','die technische Abhängigkeit','die Plattformabhängigkeit','die Zugriffsbeschränkung','der Datenschutz','die Datenspeicherung','die Datensicherheit','die Anbieterbindung','die Besitzfrage','das traditionelle Leseerlebnis','die Haptik des Buches','die emotionale Bindung','die eingeschränkte Weitergabe','die Besitzfreiheit','die kulturelle Bedeutung des Buches','die Kontrolle über Inhalte','die digitale Kontrolle','gesundheitliche Beschwerden','langfristig betrachtet','aus gesundheitlicher Sicht','aus technischer Perspektive','unter diesen Umständen'
  ],
  fill:[
    ['Ein E-Book ist ein digitales Buch, das auf einem E-Reader, Tablet, Smartphone oder Computer gelesen ____.','wird','Definition'],
    ['Dieses Thema eignet sich für einen Nachteilsabsatz, weil E-Books gesundheitliche, technische und kulturelle Probleme ____ können.','verursachen','Grundthese'],
    ['Ein zentraler Nachteil von E-Books liegt in der möglichen Belastung der ____.','Augen','Nachteil 1'],
    ['Längeres Lesen auf digitalen Geräten kann die Konzentrationsfähigkeit ____.','beeinträchtigen','Konzentration'],
    ['Digitale Geräte können durch Benachrichtigungen und Apps zu ____ führen.','Ablenkung','Reizüberflutung'],
    ['Langfristig könnte dies oberflächliches Lesen ____.','begünstigen','Lesen'],
    ['Kleine Bildschirme können den Lesekomfort deutlich ____.','verringern','Lesekomfort'],
    ['Lange Bildschirmzeiten können zu Ermüdung und Kopfschmerzen ____.','führen','Gesundheit'],
    ['Ein weiterer Nachteil besteht in der technischen ____.','Abhängigkeit','Nachteil 2'],
    ['Ohne Akku, Gerät oder passende Software ist der Zugriff auf E-Books ____.','eingeschränkt','Technik'],
    ['Viele digitale Bücher sind an bestimmte Plattformen oder Nutzerkonten ____.','gebunden','Plattformabhängigkeit'],
    ['Bei Kontoproblemen kann man den Zugriff auf Inhalte ____.','verlieren','Zugriff'],
    ['Anbieter können Nutzerdaten und das Leseverhalten ____.','speichern','Datenschutz'],
    ['Die Erfassung von Lesedaten kann Datenschutzprobleme ____.','verursachen','Datenschutz'],
    ['Plattformen können die Kontrolle über gekaufte Inhalte ____.','einschränken','Kontrolle'],
    ['Neben technischen Problemen kann auch der Verlust des klassischen ____ als Nachteil betrachtet werden.','Lesegefühls','Nachteil 3'],
    ['Gedruckte Bücher besitzen für viele Menschen eine besondere kulturelle ____.','Bedeutung','Kultur'],
    ['Bei E-Books ist die Möglichkeit, Bücher zu verleihen oder weiterzugeben, häufig ____.','eingeschränkt','Weitergabe'],
    ['Die Haptik des Buches geht bei digitalen Texten weitgehend ____.','verloren','Haptik'],
    ['Dadurch kann das Lesen weniger persönlich und weniger unabhängig ____.','wirken','Bewertung'],
    ['Ein guter Nachteilsabsatz beginnt mit einer Beobachtung, erklärt die Ursache, nennt ein Beispiel und zeigt eine ____.','Folge','Absatzstruktur'],
    ['Aus technischer Perspektive ist problematisch, dass digitale Bequemlichkeit auch Abhängigkeit ____ kann.','erzeugen','Bewertung'],
    ['Die Grundthese lautet: E-Books können zwar den Zugang zu Texten erleichtern, bringen jedoch gesundheitliche, technische und kulturelle Nachteile mit ____.','sich','Grundthese'],
    ['Auf C1/C2-Niveau sollte man nicht nur sagen, dass E-Books schlecht sind, sondern die Folgen präzise ____.','begründen','Stil']
  ],
  mc:[
    ['Welche Grundthese passt zum Nachteilsabsatz über E-Books?',['E-Books können zwar den Zugang zu Texten erleichtern, bringen jedoch gesundheitliche, technische und kulturelle Nachteile mit sich.','E-Books sind schlecht, weil digitale Bücher nicht gut sind.','E-Books sind immer schlechter als gedruckte Bücher.','Digitale Bücher sind unpraktisch und sollten vermieden werden.','E-Books haben nur Nachteile und keinen Nutzen.'],0,'Grundthese'],
    ['Welche Formulierung beschreibt Nachteil 1 am präzisesten?',['Ein zentraler Nachteil von E-Books liegt in der möglichen Augenbelastung und im geringeren Lesekomfort bei längerer Bildschirmnutzung.','E-Books tun den Augen weh und sind deshalb schlecht.','Bildschirme sind ungesund, darum sind Bücher besser.','Lesen am Tablet ist nervig und macht keinen Spaß.','E-Books sind schlecht für alle Leser.'],0,'Augenbelastung'],
    ['Welche Argumentationskette ist logisch?',['Bildschirmbelastung → Ablenkung und Ermüdung → geringere Konzentration → geringere Lernqualität','Digitales Buch → moderne Technik → schneller Zugriff → besseres Lesen','E-Book → kein Papier → immer umweltfreundlich → keine Nachteile','Bildschirm → Akku → Datenschutz → Haptik → Vorteile','Lesen → Buch → Gerät → Plattform → Spaß'],0,'Prüfungslogik'],
    ['Welche Aussage zu technischer Abhängigkeit ist C1/C2-gerecht?',['Ohne funktionierendes Gerät, ausreichend Akku oder passende Software kann der Zugriff auf digitale Bücher eingeschränkt sein.','Wenn der Akku leer ist, sind E-Books dumm.','Man braucht Technik und das ist immer schlecht.','E-Books gehen nicht, wenn das Gerät kaputt ist, also sind sie sinnlos.','Technik ist schwer und deswegen sind E-Books schlecht.'],0,'Technik'],
    ['Welche Aussage beschreibt Datenschutzprobleme präzise?',['Anbieter können Lesedaten erfassen, wodurch das Leseverhalten der Nutzer nachvollziehbar werden kann.','Firmen können alles sehen, deshalb sind E-Books gefährlich.','Datenschutz ist bei Büchern immer egal.','E-Books speichern manchmal etwas und das ist schlecht.','Gedruckte Bücher haben auch Apps und Daten.'],0,'Datenschutz'],
    ['Welche Nomen-Verb-Verbindung ist korrekt?',['die Konzentration beeinträchtigen','die Konzentration beschädigen machen','Konzentration benutzen gegen Lesen','die Konzentration schlecht tun','Konzentration verlieren machen'],0,'NVV'],
    ['Welche Formulierung passt zum klassischen Lesegefühl?',['E-Books können das traditionelle Leseerlebnis nicht vollständig ersetzen, weil Haptik, Sichtbarkeit und Weitergabe begrenzt bleiben.','E-Books fühlen sich nicht wie Bücher an, darum sind sie schlecht.','Gedruckte Bücher riechen besser und das reicht als Argument.','E-Books sind ohne Regal weniger schön.','Digitale Texte haben kein Gefühl.'],0,'Lesegefühl'],
    ['Welche Aussage ist zu absolut und daher stilistisch schwach?',['E-Books zerstören die Konzentration aller Leser.','E-Books können bei längerer Bildschirmnutzung die Konzentration beeinträchtigen.','Digitale Reize können oberflächliches Lesen begünstigen.','Unter bestimmten Umständen kann die Lesemotivation sinken.','Für längere Lernphasen kann digitales Lesen problematisch sein.'],0,'Fehlerdiagnose'],
    ['Welche Konnektorformel leitet eine Folge ein?',['Dies führt dazu, dass ...','Ein zentraler Nachteil besteht darin, dass ...','Der Grund dafür liegt darin, dass ...','Dies zeigt sich beispielsweise daran, dass ...','Zwar ..., jedoch ...'],0,'Konnektoren'],
    ['Welche Formulierung eignet sich als Bewertung?',['Langfristig betrachtet kann dies die Lesemotivation und Lernqualität beeinträchtigen.','Das ist einfach schlecht.','Am Ende sind E-Books nicht gut.','Die Leute lesen dann weniger, vielleicht.','Man muss schauen, ob es schlimm ist.'],0,'Bewertung'],
    ['Welche Aussage zur Besitzfreiheit ist präzise?',['Bei digitalen Büchern ist die Besitzfreiheit häufig begrenzt, weil Inhalte an Plattformen oder Nutzerkonten gebunden sein können.','Man besitzt E-Books nie und kann gar nichts damit machen.','Gedruckte Bücher gehören immer mehr als digitale Bücher.','E-Books kann man nicht anfassen, also besitzt man sie nicht.','Besitzfreiheit gibt es bei digitalen Medien nicht.'],0,'Besitzfreiheit'],
    ['Welche Absatzstruktur ist für einen Nachteilsabsatz geeignet?',['Beobachtung → Argument → Erklärung → Beispiel → Folge → Bewertung','Meinung → Liste → Ende → Beispiel → Thema → Wiederholung','Definition → Vorteil → Gegenbeispiel → Schluss ohne Bewertung','Quelle → Zitat → persönliche Meinung → Ende','Problem → anderes Thema → Beispiel → neue These'],0,'Absatzstruktur']
  ],
  tf:[
    ['Der Fokus des Dokuments liegt ausschließlich auf Nachteilen, Risiken und problematischen Folgen von E-Books.',true,'Fokus'],
    ['Ein guter Nachteilsabsatz sollte nur behaupten, dass E-Books schlecht sind.',false,'Argumentation'],
    ['Bildschirmbelastung kann Augenbelastung und Konzentrationsprobleme begünstigen.',true,'Augen'],
    ['Digitale Ablenkungen können die Aufmerksamkeit beim Lesen schwächen.',true,'Konzentration'],
    ['Technische Abhängigkeit bedeutet, dass E-Books ohne Gerät, Akku oder Software nicht uneingeschränkt nutzbar sind.',true,'Technik'],
    ['Datenschutz spielt beim Lesen digitaler Bücher keine Rolle.',false,'Datenschutz'],
    ['Plattformabhängigkeit kann die Kontrolle über gekaufte Inhalte einschränken.',true,'Plattform'],
    ['Das traditionelle Leseerlebnis ist bei E-Books in jeder Hinsicht identisch mit gedruckten Büchern.',false,'Lesegefühl'],
    ['Die eingeschränkte Weitergabe digitaler Bücher kann als Nachteil gesehen werden.',true,'Weitergabe'],
    ['Nicht jede digitale Bequemlichkeit ist automatisch unproblematisch.',true,'Bewertung'],
    ['Die Formulierung „E-Books sind schlecht für die Augen“ ist für C1/C2 ausreichend präzise.',false,'Stil'],
    ['Ein C1/C2-Absatz sollte Ursache, Folge und Bewertung miteinander verbinden.',true,'Schreiben']
  ],
  wordMatch:[
    ['die Bildschirmbelastung','Belastung, die durch längere Nutzung digitaler Bildschirme entsteht'],
    ['die Augenbelastung','mögliche Anstrengung oder Ermüdung der Augen beim Lesen'],
    ['die Konzentrationsfähigkeit','Fähigkeit, Aufmerksamkeit über längere Zeit auf einen Text zu richten'],
    ['die Reizüberflutung','Übermaß an digitalen Eindrücken, Benachrichtigungen oder Ablenkungen'],
    ['das oberflächliche Lesen','weniger intensives Lesen mit geringer Tiefe und geringerer Aufmerksamkeit'],
    ['die technische Abhängigkeit','Abhängigkeit von Geräten, Akku, Software oder Plattformen'],
    ['die Plattformabhängigkeit','Bindung digitaler Inhalte an bestimmte Anbieter oder Nutzerkonten'],
    ['die Zugriffsbeschränkung','Begrenzung des Zugangs zu digitalen Inhalten'],
    ['der Datenschutz','Schutz personenbezogener Daten und Nutzungsinformationen'],
    ['die Datenspeicherung','Erfassung und Speicherung von Nutzungs- oder Lesedaten'],
    ['die Besitzfreiheit','Möglichkeit, ein Buch frei zu besitzen, weiterzugeben oder zu verkaufen'],
    ['das traditionelle Leseerlebnis','kulturelle und sinnliche Erfahrung des Lesens eines gedruckten Buches']
  ],
  phraseMatch:[
    ['die Konzentration','beeinträchtigen'],
    ['zu Ermüdung','führen'],
    ['den Lesekomfort','verringern'],
    ['die Aufmerksamkeit','schwächen'],
    ['das Leseverhalten','verändern'],
    ['gesundheitliche Beschwerden','verursachen'],
    ['von Geräten','abhängig sein'],
    ['den Zugriff auf Inhalte','verlieren'],
    ['Nutzerdaten','speichern'],
    ['Datenschutzprobleme','verursachen'],
    ['die Kontrolle über Inhalte','einschränken'],
    ['digitale Abhängigkeit','verstärken'],
    ['das traditionelle Leseerlebnis','nicht vollständig ersetzen'],
    ['die Haptik des Buches','verlieren'],
    ['eine emotionale Bindung','aufbauen'],
    ['die Weitergabe digitaler Bücher','einschränken'],
    ['die kulturelle Bedeutung des Buches','schwächen'],
    ['einen Nachteil','präzise benennen'],
    ['eine Folge','überzeugend darstellen'],
    ['eine Bewertung','differenziert formulieren']
  ],
  prep:[
    ['Ein zentraler Nachteil ___ E-Books liegt in der möglichen Belastung der Augen.','von','Nachteil von'],
    ['Längeres Lesen ___ digitalen Geräten kann die Konzentration beeinträchtigen.','auf','lesen auf'],
    ['Digitale Geräte können ___ Reizüberflutung führen.','zu','führen zu + Dativ'],
    ['Die Gefahr besteht darin, dass Leser ___ Benachrichtigungen abgelenkt werden.','durch','Passiv mit durch'],
    ['Ein weiterer Nachteil besteht ___ der technischen Abhängigkeit.','in','bestehen in + Dativ'],
    ['Ohne Akku ist der Zugriff ___ E-Books eingeschränkt.','auf','Zugriff auf + Akkusativ'],
    ['Viele digitale Bücher sind ___ bestimmte Plattformen gebunden.','an','gebunden an + Akkusativ'],
    ['Anbieter können Daten ___ das Leseverhalten speichern.','über','Daten über'],
    ['Bei digitalen Büchern stellt sich die Besitzfrage anders ___ bei gedruckten Büchern.','als','anders als'],
    ['E-Books bieten das klassische Lesegefühl nur ___ eingeschränkt.','sehr','Gradpartikel'],
    ['Die Kontrolle ___ gekaufte Inhalte kann verringert werden.','über','Kontrolle über + Akkusativ'],
    ['Langfristig kann dies ___ einer geringeren Lesemotivation führen.','zu','führen zu + Dativ']
  ],
  hang:[
    'Belastung der Augen und geringerer Lesekomfort','technische Abhängigkeit und Datenschutzprobleme','Verlust des klassischen Lesegefühls','eingeschränkte Besitzfreiheit','die Konzentration beeinträchtigen','zu Ermüdung führen','den Lesekomfort verringern','die Aufmerksamkeit schwächen','das Leseverhalten verändern','gesundheitliche Beschwerden verursachen','von Geräten abhängig sein','den Zugriff auf Inhalte verlieren','Nutzerdaten speichern','Datenschutzprobleme verursachen','die Kontrolle über Inhalte einschränken','digitale Abhängigkeit verstärken','das traditionelle Leseerlebnis nicht vollständig ersetzen','die Haptik des Buches geht verloren','die eingeschränkte Weitergabe digitaler Bücher','langfristig betrachtet','aus gesundheitlicher Sicht','aus technischer Perspektive','unter diesen Umständen','oberflächliches Lesen begünstigen'
  ]
};
