(function(){
'use strict';
var key='t_video_schule_nachteile';
var source='Videoueberwachung_in_der_Schule_Nachteile_C1C2(3).docx';
window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};
window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};
var LONG=[
`<h3>Videoüberwachung in der Schule – Nachteile · C1/C2-Erörterungstraining</h3>`,
`<h4>Nachteil 1: Eingriff in die Privatsphäre und Verlust eines geschützten Lernraums</h4>`,
`<p>Ein zentraler Nachteil der Videoüberwachung in der Schule besteht darin, dass sie in die Privatsphäre der Schülerinnen und Schüler eingreifen kann. Die Schule ist nicht nur ein Gebäude, in dem Unterricht stattfindet, sondern ein sozialer Lern- und Lebensraum. Jugendliche verbringen dort einen großen Teil ihres Alltags, sprechen mit Freunden, lösen Konflikte, machen Fehler, zeigen Unsicherheit und entwickeln Schritt für Schritt ihre Persönlichkeit. Genau deshalb braucht die Schule Bereiche, in denen sich junge Menschen ohne ständige technische Beobachtung bewegen können. Wenn Kameras dauerhaft sichtbar sind, verändert sich dieser geschützte Raum. Die Schule wirkt dann nicht mehr nur wie ein Ort des Vertrauens, sondern zunehmend wie ein kontrollierter Bereich, in dem jede Bewegung dokumentiert werden könnte.</p>`,
`<p>Besonders problematisch ist, dass Kameras nicht unterscheiden, ob eine Situation sicherheitsrelevant oder privat ist. Eine Kamera auf dem Pausenhof kann zwar einen Streit erfassen, sie zeichnet aber zugleich Gespräche, Freundschaften, peinliche Momente, emotionale Reaktionen und alltägliche Unsicherheiten auf. Eine Kamera im Flur filmt nicht nur Regelverstöße, sondern auch den Schüler, der verspätet ankommt, die Schülerin, die sich nach einem Streit zurückzieht, oder Jugendliche, die vertraulich miteinander sprechen. Dadurch werden normale private Situationen Teil eines technischen Systems. Gerade bei Minderjährigen ist das heikel, weil sie die langfristige Bedeutung solcher Aufnahmen nicht immer einschätzen können.</p>`,
`<p>Für die Erörterung ist die Formulierung <b>in die Privatsphäre eingreifen</b> besonders wichtig. Sie zeigt präziser als einfache Wörter wie „filmen“ oder „kontrollieren“, dass ein persönlicher Schutzbereich betroffen ist. Auch die Verbindungen <b>das Vertrauensverhältnis beeinträchtigen</b>, <b>einen geschützten Lernraum verändern</b>, <b>unter ständiger Beobachtung stehen</b>, <b>die persönliche Freiheit einschränken</b>, <b>ein Klima des Misstrauens erzeugen</b> und <b>pädagogische Beziehungen schwächen</b> sind für C1/C2-Texte sehr geeignet. Präpositionen spielen dabei eine wichtige Rolle: Man greift <b>in die Privatsphäre</b> ein, man steht <b>unter Beobachtung</b>, man spricht <b>von einem Vertrauensverlust</b>, man wägt Sicherheit <b>mit</b> persönlicher Freiheit ab und man entscheidet sich <b>gegen</b> eine unverhältnismäßige Maßnahme.</p>`,
`<p>Dieser Nachteil lässt sich im alten Erörterungsstil besonders gut erklären, wenn man die Wirkung Schritt für Schritt beschreibt. Dauerhafte Beobachtung führt dazu, dass Schülerinnen und Schüler weniger Privatsphäre empfinden. Weniger Privatsphäre kann das Vertrauen in die Schule schwächen. Ein schwaches Vertrauensverhältnis wiederum belastet das Schulklima. Wenn Jugendliche den Eindruck bekommen, dass die Schule ihnen grundsätzlich misstraut, kann Offenheit zurückgehen. Sie sprechen vorsichtiger, ziehen sich eher zurück oder vermeiden bestimmte Orte. Die Kamera erzeugt dann nicht nur Sicherheit, sondern auch Distanz.</p>`,
`<p>Ein weiterer wichtiger Punkt ist die Verhältnismäßigkeit. Sicherheit ist ein berechtigtes Ziel, aber sie rechtfertigt nicht automatisch jede Form der Kontrolle. Wenn Konflikte auch durch Aufsichtspersonal, Schulsozialarbeit, klare Regeln oder persönliche Gespräche bearbeitet werden können, erscheint eine flächendeckende Videoüberwachung schnell übertrieben. Eine Kamera kann einen Vorfall dokumentieren, aber kein Vertrauen schaffen, kein Gespräch ersetzen und keine pädagogische Beziehung aufbauen. Deshalb sollte dieser Nachteil so formuliert werden: Videoüberwachung kann den Charakter der Schule als geschützten Lernraum verändern, weil technische Kontrolle an die Stelle von Vertrauen und pädagogischer Nähe tritt.</p>`,
`<p>Ein prüfungsnaher Beispielgedanke lautet: Ein wichtiger Nachteil der Videoüberwachung in der Schule liegt im Eingriff in die Privatsphäre der Schülerinnen und Schüler. Die Schule ist ein sozialer Raum, in dem Jugendliche nicht nur Fachwissen erwerben, sondern auch persönliche Erfahrungen sammeln. Wenn sie auf Fluren, im Pausenhof oder in Aufenthaltsräumen ständig von Kameras erfasst werden, entsteht leicht ein Gefühl permanenter Kontrolle. Dadurch kann das Vertrauensverhältnis zwischen Schule und Lernenden belastet werden. Zwar ist Sicherheit ein legitimes Ziel, doch darf sie nicht dazu führen, dass junge Menschen ihren Schulalltag wie in einem überwachten Raum erleben.</p>`,
`<h4>Nachteil 2: Psychischer Druck, Anpassungszwang und gestörte persönliche Entwicklung</h4>`,
`<p>Ein weiterer Nachteil besteht darin, dass Videoüberwachung psychischen Druck erzeugen kann. Dieser Druck muss nicht offen ausgesprochen werden. Schon das Wissen, dass eine Kamera vorhanden ist, kann ausreichen, damit Schülerinnen und Schüler ihr Verhalten verändern. Sie fragen sich, wer die Aufnahmen sieht, ob ihr Verhalten später bewertet wird oder ob eine peinliche Situation gegen sie verwendet werden könnte. Gerade Jugendliche achten ohnehin stark darauf, wie sie von anderen wahrgenommen werden. Wenn zu Mitschülern, Lehrkräften und Eltern zusätzlich eine technische Beobachtung hinzukommt, kann das Gefühl der Bewertung deutlich stärker werden.</p>`,
`<p>Jugendliche befinden sich in einer Lebensphase, in der Selbstwahrnehmung, Anerkennung, Unsicherheit und Zugehörigkeit eine große Rolle spielen. Sie müssen lernen, Fehler auszuhalten, Konflikte zu lösen, Verantwortung zu übernehmen und selbstbewusster zu werden. Diese Entwicklung braucht Freiräume. Wenn jedoch jeder Schritt beobachtet wird, entsteht ein Anpassungszwang. Schülerinnen und Schüler verhalten sich dann möglicherweise ruhiger, vorsichtiger oder unauffälliger, aber nicht unbedingt aus innerer Überzeugung. Sie handeln aus Angst vor Kontrolle. Dadurch wirkt das Verhalten äußerlich korrekt, bleibt pädagogisch aber wenig nachhaltig.</p>`,
`<p>Für diesen Nachteil sind die Verbindungen <b>psychischen Druck ausüben</b>, <b>sich beobachtet fühlen</b>, <b>das Verhalten anpassen</b>, <b>Unsicherheit verstärken</b>, <b>spontanes Verhalten hemmen</b>, <b>aus Angst vor Kontrolle handeln</b>, <b>Konflikte verdrängen</b>, <b>innere Einsicht fördern</b> und <b>soziale Entwicklung beeinträchtigen</b> besonders wichtig. Diese Formulierungen passen genau zum C1/C2-Niveau, weil sie nicht nur eine Meinung ausdrücken, sondern eine Wirkung beschreiben. Auch hier müssen Präpositionen sicher verwendet werden: Druck wird <b>auf</b> Jugendliche ausgeübt, man handelt <b>aus Angst vor</b> Kontrolle, man fühlt sich <b>von</b> Kameras beobachtet, Konflikte werden <b>in</b> unbeobachtete Bereiche verlagert und die Entwicklung wird <b>durch</b> ständige Beobachtung beeinträchtigt.</p>`,
`<p>Der Kern dieses Nachteils liegt im Unterschied zwischen äußerer Disziplin und echter pädagogischer Einsicht. Kameras können dazu führen, dass sich Jugendliche oberflächlich regelkonform verhalten. Das bedeutet aber nicht automatisch, dass sie Rücksichtnahme, Respekt oder Verantwortungsbewusstsein gelernt haben. Wer nur wegen einer Kamera Regeln beachtet, hat den Sinn der Regeln noch nicht unbedingt verstanden. Eine Schule sollte junge Menschen nicht nur kontrollieren, sondern ihnen erklären, warum bestimmte Regeln notwendig sind. Reine Überwachung kann deshalb Probleme verdecken, statt sie zu lösen.</p>`,
`<p>Besonders problematisch ist, dass Konflikte durch Videoüberwachung nicht verschwinden müssen. Sie können lediglich in Bereiche verlagert werden, die nicht von Kameras erfasst werden. Jugendliche lernen dann nicht, Streit offen und verantwortungsvoll zu klären, sondern sie lernen, Kontrolle zu umgehen. Dadurch verliert die Schule eine wichtige pädagogische Möglichkeit. Konflikte sind im Schulalltag nicht nur Störungen, sondern auch Lerngelegenheiten. Wenn sie nur technisch registriert oder verdrängt werden, entsteht keine echte soziale Entwicklung.</p>`,
`<p>Auch das Schulklima kann darunter leiden. Pausen, Aufenthaltsräume und Flure sind Orte der Entspannung, der spontanen Begegnung und der sozialen Erfahrung. Wenn sich Schülerinnen und Schüler dort dauerhaft beobachtet fühlen, nimmt die Natürlichkeit des Miteinanders ab. Manche sprechen vorsichtiger, lachen weniger ungezwungen, vermeiden bestimmte Bewegungen oder ziehen sich zurück. Besonders schüchterne oder sensible Jugendliche können eine Kamera als zusätzliche Belastung empfinden. Langfristig entsteht dadurch eine Atmosphäre, in der Vorsicht wichtiger wird als Offenheit. Dieser Nachteil sollte deshalb nicht nur als kurzfristiger Stress beschrieben werden, sondern als Gefahr für Selbstständigkeit, Selbstbewusstsein und eine lebendige Schulkultur.</p>`,
`<p>Ein prüfungsnaher Beispielgedanke lautet: Ein weiterer Nachteil der Videoüberwachung besteht darin, dass sie psychischen Druck auf Schülerinnen und Schüler ausüben kann. Jugendliche befinden sich in einer Phase, in der sie lernen müssen, selbstständig zu handeln, Konflikte auszutragen und Verantwortung zu übernehmen. Wenn sie jedoch ständig das Gefühl haben, von Kameras beobachtet zu werden, passen sie ihr Verhalten möglicherweise nur äußerlich an. Sie verhalten sich dann nicht unbedingt aus Überzeugung richtig, sondern aus Angst vor Kontrolle. Dadurch bleibt der pädagogische Nutzen der Maßnahme begrenzt und die persönliche Entwicklung kann beeinträchtigt werden.</p>`,
`<h4>Nachteil 3: Datenschutzrisiken, Missbrauchsmöglichkeiten und zusätzlicher Kontrollaufwand</h4>`,
`<p>Ein dritter wichtiger Nachteil betrifft den Datenschutz. Videoüberwachung bedeutet nicht nur, dass Kameras Bilder aufnehmen. Es entstehen Bilddaten, die gespeichert, geschützt, ausgewertet und rechtlich korrekt behandelt werden müssen. Gerade in Schulen ist dies besonders sensibel, weil die meisten betroffenen Personen minderjährig sind. Bildaufnahmen von Kindern und Jugendlichen dürfen nicht leichtfertig behandelt werden. Die Schule muss genau klären, wer Zugriff auf die Aufnahmen hat, wie lange sie gespeichert werden, wann sie gelöscht werden und wie unbefugter Zugriff verhindert wird.</p>`,
`<p>Dieser Nachteil ist deshalb so wichtig, weil jede Kamera neue Verantwortung schafft. Die Schule muss technische Systeme warten, Zuständigkeiten festlegen, Zugriffsrechte beschränken, Löschfristen kontrollieren und Eltern transparent informieren. Dadurch entsteht ein zusätzlicher organisatorischer Kontrollaufwand. Eine Schule, die eigentlich Bildung, Beratung und pädagogische Begleitung leisten soll, muss plötzlich auch Aufgaben übernehmen, die mit Datenschutz, Technik und Verwaltung zusammenhängen. Wenn Personal, Zeit oder Fachwissen fehlen, können Fehler entstehen. Videoüberwachung wird dann selbst zu einem Risiko.</p>`,
`<p>Für diesen Abschnitt sind C1/C2-Formulierungen wie <b>sensible Bilddaten speichern</b>, <b>Aufnahmen auswerten</b>, <b>Zugriff auf Aufnahmen gewähren</b>, <b>Zugriff beschränken</b>, <b>Löschfristen festlegen</b>, <b>Missbrauch verhindern</b>, <b>Kosten verursachen</b>, <b>Verantwortung tragen</b>, <b>Ressourcen binden</b>, <b>eine Situation aus dem Zusammenhang reißen</b> und <b>Vertrauen beschädigen</b> sehr wichtig. Auch die Präpositionen müssen sauber sein: Zugriff besteht <b>auf</b> Aufnahmen, Daten werden <b>von</b> Minderjährigen gespeichert, eine Aufnahme wird <b>aus</b> dem Zusammenhang gerissen, Verantwortung liegt <b>bei</b> der Schule, und Zweifel entstehen <b>an</b> der sicheren Nutzung der Daten.</p>`,
`<p>Ein besonderes Risiko liegt in der Fehlinterpretation von Aufnahmen. Ein Video zeigt häufig nur einen Ausschnitt, nicht den vollständigen Zusammenhang. Es kann die Reaktion eines Schülers zeigen, aber nicht die vorherige Provokation. Es kann eine emotionale Szene zeigen, aber nicht erklären, warum sie entstanden ist. Wenn solche Ausschnitte ohne Kontext bewertet werden, können Schülerinnen und Schüler ungerecht beurteilt werden. Dadurch kann die Videoüberwachung genau das Gegenteil von Sicherheit erzeugen: Sie schafft Unsicherheit, weil einzelne Situationen technisch festgehalten, aber menschlich nicht ausreichend verstanden werden.</p>`,
`<p>Hinzu kommt die Möglichkeit des Missbrauchs. Selbst wenn die Schule gute Absichten hat, können Aufnahmen falsch verwendet, zu lange gespeichert oder von Personen gesehen werden, die keinen berechtigten Zugriff haben. Eine peinliche Szene muss nicht öffentlich verbreitet werden, um Schaden anzurichten; es reicht bereits, wenn mehrere Personen sie sehen oder darüber sprechen. Gerade bei Minderjährigen kann ein solcher Umgang mit Bilddaten das Vertrauen von Eltern und Schülern nachhaltig beschädigen. Datenschutz ist daher kein Nebenthema, sondern ein zentrales Argument gegen unkritische Videoüberwachung.</p>`,
`<p>Auch der finanzielle und organisatorische Aufwand darf nicht unterschätzt werden. Kameras müssen angeschafft, installiert, gewartet und technisch geschützt werden. Externe Dienstleister können beteiligt sein, wodurch zusätzliche Datenschutzfragen entstehen. Geld, Zeit und Aufmerksamkeit, die in Überwachungstechnik fließen, fehlen möglicherweise für Schulsozialarbeit, Präventionsprojekte, mehr Aufsichtspersonal oder pädagogische Gespräche. Dadurch entsteht die Gefahr, dass technische Kontrolle pädagogische Maßnahmen verdrängt. Mehr Kameras bedeuten nicht automatisch mehr Sicherheit; sie bedeuten auch mehr Daten, mehr Verantwortung und mehr Risiken.</p>`,
`<p>Ein prüfungsnaher Beispielgedanke lautet: Ein dritter Nachteil der Videoüberwachung in der Schule liegt in den Datenschutzrisiken und im zusätzlichen Kontrollaufwand. Kameras erzeugen sensible Bilddaten, und gerade bei Minderjährigen muss sehr genau geregelt werden, wer diese Aufnahmen sehen darf und wann sie gelöscht werden. Wenn Zuständigkeiten unklar sind oder technische Systeme nicht ausreichend geschützt werden, kann das Vertrauen von Eltern und Schülern schnell beschädigt werden. Außerdem zeigt ein Video häufig nur einen Ausschnitt einer Situation. Ohne den gesamten Zusammenhang kann ein Verhalten falsch interpretiert werden. Hinzu kommen Kosten für Anschaffung, Wartung und Verwaltung, wodurch pädagogische Ressourcen gebunden werden.</p>`
].join('');
var P=[
['in die Privatsphäre eingreifen','in + Akkusativ','Videoüberwachung kann ___ die Privatsphäre der Lernenden eingreifen.','in','einen persönlichen Schutzraum verletzen'],
['das Vertrauensverhältnis beeinträchtigen','NVV','Ständige Beobachtung kann das Vertrauensverhältnis ___.','beeinträchtigen','Vertrauen schwächen'],
['einen geschützten Lernraum verändern','NVV','Kameras können einen geschützten Lernraum ___.','verändern','Schulraum anders wirken lassen'],
['unter ständiger Beobachtung stehen','unter + Dativ','Viele Jugendliche haben das Gefühl, ___ ständiger Beobachtung zu stehen.','unter','beobachtet werden'],
['ein Klima des Misstrauens erzeugen','NVV','Dauerhafte Kontrolle kann ein Klima des Misstrauens ___.','erzeugen','Misstrauen schaffen'],
['psychischen Druck ausüben','NVV','Kameras können psychischen Druck auf Jugendliche ___.','ausüben','Belastung erzeugen'],
['das Verhalten anpassen','Kollokation','Schüler passen ihr Verhalten aus Angst vor Kontrolle ___.','an','kontrollierter handeln'],
['spontanes Verhalten hemmen','Kollokation','Ständige Beobachtung kann spontanes Verhalten ___.','hemmen','Spontaneität verringern'],
['soziale Entwicklung beeinträchtigen','NVV','Überwachung kann die soziale Entwicklung ___.','beeinträchtigen','Entwicklung schwächen'],
['sensible Bilddaten speichern','Kollokation','Kameras können sensible Bilddaten von Minderjährigen ___.','speichern','Aufnahmen sichern'],
['Zugriff auf Aufnahmen beschränken','auf + Akkusativ','Die Schule muss den Zugriff ___ Aufnahmen beschränken.','auf','Datenzugang begrenzen'],
['Löschfristen festlegen','NVV','Für Videoaufnahmen müssen klare Löschfristen ___.','festgelegt','Speicherdauer regeln'],
['Missbrauch verhindern','Kollokation','Strenge Regeln sollen Missbrauch ___.','verhindern','falsche Nutzung vermeiden'],
['Ressourcen binden','NVV','Kameras können finanzielle und organisatorische Ressourcen ___.','binden','Mittel beanspruchen'],
['aus dem Zusammenhang reißen','feste Wendung','Ein kurzer Videoausschnitt kann eine Situation ___ dem Zusammenhang reißen.','aus','Kontext verlieren']
];
var MC=[
['Welche Aussage passt ausschließlich zur Nachteilsseite?',['Videoüberwachung kann Privatsphäre einschränken, Druck erzeugen und Datenschutzrisiken schaffen.','Videoüberwachung hat nur Vorteile für Schulen.','Kameras lösen automatisch alle pädagogischen Probleme.','Videoüberwachung ersetzt Vertrauen vollständig.'],0,'Nachteilsfokus'],
['Welche Formulierung ist C1/C2-gerecht?',['in die Privatsphäre eingreifen','Privatsphäre kaputt machen','Schüler filmen ist schlecht','Kameras machen Schule böse'],0,'Register'],
['Welche Folge passt zu dauerhafter Beobachtung?',['Das Vertrauensverhältnis kann geschwächt werden.','Alle Schüler lernen automatisch besser.','Datenschutz wird überflüssig.','Konflikte verschwinden endgültig.'],0,'Folge'],
['Welche Formulierung beschreibt psychischen Druck?',['Jugendliche passen ihr Verhalten aus Angst vor Kontrolle an.','Jugendliche haben immer mehr Spaß.','Kameras ersetzen Selbstständigkeit positiv.','Alle Konflikte werden pädagogisch gelöst.'],0,'Nachteil 2'],
['Welche Datenschutzformulierung ist korrekt?',['Zugriff auf Aufnahmen beschränken','Zugriff an Aufnahmen machen','Aufnahmen ohne Kontext als Lösung beurteilen','Daten ewig speichern'],0,'Datenschutz'],
['Welche Aussage ist prüfungsstark?',['Ein Video zeigt oft nur einen Ausschnitt, nicht den vollständigen Zusammenhang.','Ein Video ist immer die ganze Wahrheit.','Bilddaten von Minderjährigen sind unwichtig.','Löschfristen braucht man nicht.'],0,'Fehlinterpretation'],
['Welche NVV passt?',['Ressourcen binden','Ressourcen machen','Ressourcen stehen','Ressourcen filmen'],0,'NVV'],
['Welche Alternative bleibt im Nachteilskontext sinnvoll?',['Schulsozialarbeit, klare Regeln und Aufsicht als mildere Mittel prüfen','noch mehr Kameras ohne Datenschutz einsetzen','alle Pausenräume dauerhaft filmen','Aufnahmen beliebig weitergeben'],0,'mildere Mittel']
];
var TF=[
['Das Modul behandelt ausschließlich Nachteile der Videoüberwachung in der Schule.',true,'Fokus'],
['Videoüberwachung kann in die Privatsphäre der Schülerinnen und Schüler eingreifen.',true,'Nachteil 1'],
['Kameras können Vertrauen automatisch und immer stärken.',false,'Bewertung'],
['Psychischer Druck kann entstehen, wenn Jugendliche sich dauerhaft beobachtet fühlen.',true,'Nachteil 2'],
['Konflikte werden durch Kameras immer pädagogisch gelöst.',false,'Pädagogik'],
['Bilddaten von Minderjährigen sind besonders sensibel.',true,'Datenschutz'],
['Ein kurzer Videoausschnitt kann ohne Kontext falsch interpretiert werden.',true,'Fehlinterpretation'],
['Mehr Überwachung bedeutet auch mehr Verantwortung.',true,'Kontrollaufwand']
];
window.DEUTSCH_TESTS[key]={category:'Bevor Schreiben',slug:'videoueberwachung_in_der_schule_nachteile_c1_c2',title:'Videoüberwachung in der Schule – Nachteile · C1/C2 Nachteilsabsatz',topic:'Erörterung · Nachteile · Schule · Privatsphäre · Datenschutz',source:source,words:P.map(function(x){return x[0];}),fill:P.map(function(x){return [x[2],x[3],x[1]];}),mc:MC,tf:TF,wordMatch:P.map(function(x){return [x[0],x[4]];}),phraseMatch:[['Privatsphäre','einschränken'],['Vertrauensverhältnis','beeinträchtigen'],['psychischen Druck','ausüben'],['Verhalten','anpassen'],['Bilddaten','speichern'],['Zugriff','beschränken'],['Ressourcen','binden'],['mildere Mittel','in Betracht ziehen']],prep:P.map(function(x){return [x[2],x[3],x[1]];}),hang:P.map(function(x){return x[0];})};
window.DEUTSCH_LESSONS[key]={source:source,longSourceVerified:true,short:'<h3>Videoüberwachung in der Schule – Nachteile</h3><p>Dieses Modul behandelt ausschließlich drei Nachteile: Eingriff in die Privatsphäre, psychischer Druck durch ständige Beobachtung und Datenschutzrisiken durch sensible Bilddaten von Minderjährigen.</p>',medium:'<h3>Videoüberwachung in der Schule – Nachteile</h3><p>Videoüberwachung kann den Charakter der Schule als geschützten Lern- und Lebensraum verändern. Sie kann das Vertrauensverhältnis beeinträchtigen, Jugendliche zu äußerlich angepasstem Verhalten drängen und neue Verantwortung beim Umgang mit Bilddaten schaffen. Zentrale Muster sind <b>in die Privatsphäre eingreifen</b>, <b>psychischen Druck ausüben</b>, <b>das Verhalten anpassen</b>, <b>Zugriff auf Aufnahmen beschränken</b> und <b>Ressourcen binden</b>.</p>',long:LONG};
function active(){var t=(document.getElementById('lessonTitle')||{}).textContent||'';return t.indexOf('Videoüberwachung in der Schule')>-1||t.indexOf('videoueberwachung_in_der_schule_nachteile')>-1;}
function visible(){var x=document.getElementById('lesson');return !x||!/(^|\s)hide(\s|$)/.test(x.className||'');}
function render(){if(!visible()||!active())return;var title=document.getElementById('lessonTitle'),meta=document.getElementById('lessonMeta'),content=document.getElementById('lessonContent');if(title)title.textContent='Lektion: Videoüberwachung in der Schule – Nachteile';if(meta)meta.textContent='Niveau: C1/C2 · Erörterung · Nachteile';if(content&&content.innerHTML!==LONG)content.innerHTML=LONG;}
render();setTimeout(render,250);setTimeout(render,900);document.addEventListener('click',function(){setTimeout(render,80);setTimeout(render,300);},true);
window.AAYS_BEFORE_VIDEO_SCHULE_NACHTEILE_ONLY3_HEADINGS_OK=true;
})();