(function(){
'use strict';
window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};
window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};
var key='t50';
window.DEUTSCH_TESTS[key]={
 category:'Bevor Schreiben',
 slug:'maschinen_ersetzen_menschen_vorteile_c1_c2',
 title:'Maschinen ersetzen Menschen – Vorteile · C1/C2 Vorteilsabsatz',
 topic:'Erörterung · Vorteile · Maschinen ersetzen Menschen · Entlastung · Effizienz · Produktivität · Präzision · Qualität',
 source:'Maschinen_ersetzen_Menschen_Vorteile_3_C1_C2_15_20_pruefungsnah(2).docx',
 words:['die Automatisierung','die technische Unterstützung','die Entlastung','die körperliche Belastung','die gefährliche Arbeit','die monotone Arbeit','der Arbeitsschutz','die Sicherheit am Arbeitsplatz','das Unfallrisiko','die Arbeitsbedingung','die Effizienz','die Produktivität','die Zeitersparnis','der Arbeitsprozess','die Planbarkeit','die Wettbewerbsfähigkeit','die Lieferzeit','die Kostenreduzierung','die Arbeitsorganisation','die Prozessoptimierung','die Genauigkeit','die Fehlerreduzierung','die Qualität','die Zuverlässigkeit','die Präzision','die Qualitätskontrolle','die gleichbleibende Leistung','die Datenauswertung','der Qualitätsstandard','die Entscheidungshilfe'],
 fill:[['Maschinen können Menschen bei schweren und gefährlichen Arbeiten ____.','entlasten','Vorteil 1'],['Wenn Maschinen schwere Lasten heben, wird die körperliche ____ verringert.','Belastung','Vorteil 1'],['In gefährlichen Bereichen kann Technik das Unfallrisiko ____.','senken','Vorteil 1'],['Monotone Tätigkeiten können durch automatische Systeme ____ werden.','reduziert','Vorteil 1'],['Ein weiterer Vorteil besteht in der höheren ____.','Effizienz','Vorteil 2'],['Maschinen können wiederholbare Aufgaben schneller und gleichmäßiger ____.','erledigen','Vorteil 2'],['Durch Automatisierung lassen sich Lieferzeiten ____.','verkürzen','Vorteil 2'],['Unternehmen können Zeit sparen und Produktivität ____.','steigern','Vorteil 2'],['Darüber hinaus können Maschinen Fehler ____.','reduzieren','Vorteil 3'],['Bei klar definierten Aufgaben arbeiten Maschinen konstant und ____.','präzise','Vorteil 3'],['Automatische Kontrollen können Qualitätsstandards besser ____.','sichern','Vorteil 3'],['Technische Systeme können menschliche Entscheidungen ____.','unterstützen','Vorteil 3']],
 mc:[['Welche Hauptthese passt?',['Maschinen können Menschen bei schweren oder gefährlichen Aufgaben entlasten, Produktivität erhöhen und Qualität verbessern.','Maschinen haben nur Nachteile.','Technik betrifft keine Arbeitswelt.','Maschinen arbeiten immer ungenau.'],0,'Hauptthese'],['Was gehört zum ersten Vorteil?',['Entlastung bei schweren, monotonen und gefährlichen Arbeiten','mehr körperliche Belastung','weniger Arbeitsschutz','mehr Unfallrisiko'],0,'Entlastung'],['Welche Kette ist logisch?',['gefährliche Arbeit → Maschine übernimmt Aufgabe → Mensch wird entlastet → weniger Unfälle','Maschine → mehr Müdigkeit → mehr Risiko','Technik → keine Kontrolle → keine Qualität','Roboter → weniger Sicherheit'],0,'Argumentation'],['Was beschreibt Effizienz?',['schnellere Abläufe, höhere Produktivität und bessere Planbarkeit','mehr Wartezeit','weniger Organisation','mehr Zufall'],0,'Effizienz'],['Welche Folge kann Automatisierung haben?',['Zeitersparnis, geringere Kosten und stärkere Wettbewerbsfähigkeit','immer längere Lieferzeiten','weniger Produktivität','weniger Planbarkeit'],0,'Wirtschaft'],['Was gehört zum dritten Vorteil?',['weniger Fehler, gleichbleibende Qualität und bessere Unterstützung','weniger Kontrolle','mehr Ungenauigkeit','weniger Qualitätsstandards'],0,'Qualität'],['Welche Aussage ist C1/C2-gerecht?',['Bei klar definierten Aufgaben können Maschinen konstant und präzise arbeiten.','Maschinen sind gut, weil sie modern sind.','Roboter machen alles besser.','Technik ist immer perfekt.'],0,'Stil'],['Welche Rolle bleibt beim Menschen?',['Er kontrolliert, bewertet und übernimmt Verantwortung.','Er spielt überhaupt keine Rolle mehr.','Er darf keine Entscheidungen treffen.','Er kann keine Technik nutzen.'],0,'Rolle des Menschen']],
 tf:[['Die Quelle behandelt ausschließlich Vorteile.',true,'Fokus'],['Maschinen können schwere oder gefährliche Tätigkeiten übernehmen.',true,'Vorteil 1'],['Technik erhöht laut Quelle immer die körperliche Belastung.',false,'Fehler'],['Automatisierung kann zu sichereren Arbeitsbedingungen beitragen.',true,'Arbeitsschutz'],['Höhere Effizienz bedeutet schnellere und planbarere Abläufe.',true,'Vorteil 2'],['Maschinen brauchen bei Routineaufgaben grundsätzlich mehr Pausen als Menschen.',false,'Fehler'],['Kürzere Lieferzeiten können Kunden zugutekommen.',true,'Alltag'],['Maschinen können bei klar programmierten Aufgaben gleichbleibende Qualität liefern.',true,'Vorteil 3'],['In Medizin, Verkehr und Technik kann Genauigkeit wichtig sein.',true,'Präzision'],['Die Quelle sagt, dass Menschen keine Rolle mehr spielen.',false,'Fehler']],
 wordMatch:[['die Entlastung','Verringerung einer körperlichen, zeitlichen oder mentalen Belastung'],['der Arbeitsschutz','Maßnahmen zum Schutz der Beschäftigten'],['das Unfallrisiko','Wahrscheinlichkeit eines Unfalls'],['die Effizienz','gutes Verhältnis zwischen Aufwand, Zeit und Ergebnis'],['die Produktivität','Leistung in einer bestimmten Zeit'],['die Planbarkeit','Möglichkeit, Abläufe zuverlässig zu organisieren'],['die Präzision','sehr genaue Ausführung'],['die Qualitätskontrolle','Prüfung von Produkten oder Prozessen'],['die Fehlerreduzierung','Verringerung von Fehlern'],['die Entscheidungshilfe','Unterstützung bei einer Entscheidung']],
 phraseMatch:[['Menschen','entlasten'],['körperliche Belastung','verringern'],['gefährliche Aufgaben','übernehmen'],['das Unfallrisiko','senken'],['Arbeitsbedingungen','verbessern'],['Arbeitsprozesse','beschleunigen'],['Produktivität','steigern'],['Lieferzeiten','verkürzen'],['Kosten','senken'],['Wettbewerbsfähigkeit','stärken'],['Fehler','reduzieren'],['Qualität','sichern'],['Daten','auswerten'],['Entscheidungen','unterstützen']],
 prep:[['Ein Vorteil liegt ___ der Entlastung bei schweren Arbeiten.','in','liegen in + Dativ'],['Maschinen können Menschen ___ gefährlichen Aufgaben entlasten.','bei','entlasten bei + Dativ'],['Automatisierung kann ___ sichereren Arbeitsplätzen beitragen.','zu','beitragen zu + Dativ'],['Ein weiterer Vorteil besteht ___ der höheren Effizienz.','in','bestehen in + Dativ'],['Maschinen sind ___ wiederholbare Aufgaben geeignet.','für','geeignet für + Akkusativ'],['Unternehmen profitieren ___ kürzeren Lieferzeiten.','von','profitieren von + Dativ'],['Technische Systeme können ___ Fehlerreduzierung beitragen.','zur','beitragen zu + Dativ'],['Menschen bleiben ___ Kontrolle und Bewertung wichtig.','für','wichtig für + Akkusativ']],
 hang:['Menschen entlasten','körperliche Belastung verringern','gefährliche Aufgaben übernehmen','das Unfallrisiko senken','Arbeitsbedingungen verbessern','monotone Arbeit reduzieren','Arbeitsprozesse beschleunigen','Produktivität steigern','Zeit sparen','Lieferzeiten verkürzen','Kosten senken','Wettbewerbsfähigkeit stärken','Fehler reduzieren','präzise arbeiten','Qualität sichern','gleichbleibende Ergebnisse liefern','Daten genau auswerten','Entscheidungen unterstützen']
};
window.DEUTSCH_LESSONS[key]={source:'Maschinen_ersetzen_Menschen_Vorteile_3_C1_C2_15_20_pruefungsnah(2).docx',longSourceVerified:true,short:'<h3>Maschinen ersetzen Menschen – Vorteile · Kurz</h3><p>Dieses Thema behandelt nur Vorteile. Maschinen können Menschen bei schweren, monotonen und gefährlichen Arbeiten entlasten, Arbeitsprozesse effizienter machen und durch präzise Arbeit Fehler reduzieren.</p>',medium:'<h3>Maschinen ersetzen Menschen – Vorteile · Mittel</h3><p>Ein erster Vorteil besteht darin, dass Maschinen Menschen bei schweren, monotonen oder gefährlichen Arbeiten entlasten können. Dadurch sinkt das Unfallrisiko und Arbeitsbedingungen werden sicherer.</p><p>Ein zweiter Vorteil liegt in der höheren Effizienz. Maschinen erledigen wiederholbare Aufgaben schneller und gleichmäßiger. Dadurch werden Produktionsprozesse planbarer, Lieferzeiten kürzer und Unternehmen produktiver.</p><p>Ein dritter Vorteil betrifft Genauigkeit und Qualität. Maschinen arbeiten bei klar definierten Aufgaben konstant und präzise. Dadurch werden Fehler reduziert und Menschen bei komplexen Entscheidungen unterstützt.</p>',long:'<h3>Maschinen ersetzen Menschen – Vorteile · ausführliche C1/C2-Konu anlatımı</h3><p>Diese lange Fassung wird durch die Word-Quelle gesteuert und behandelt ausschließlich Vorteile: Entlastung, Effizienz und Präzision. Sie wird im nächsten Loader-Schritt mit einer ausführlichen 2000+ Wörter Fassung überschrieben.</p>'};
function forceVisible(){try{var list=document.getElementById('testList');var txt=String(list&&list.textContent||'');var isBefore=(window.selectedCategory==='Bevor Schreiben')||txt.indexOf('Bevor Schreiben')>-1;if(isBefore&&txt.indexOf('Maschinen ersetzen Menschen – Vorteile')===-1){if(typeof window.renderTests==='function')window.renderTests('Bevor Schreiben');else if(typeof renderTests==='function')renderTests('Bevor Schreiben');}}catch(e){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',forceVisible);else forceVisible();
[100,400,900,1800,3200].forEach(function(ms){setTimeout(forceVisible,ms);});
window.AAYS_MASCHINEN_VORTEILE_T50_OK=true;
window.AAYS_MASCHINEN_VORTEILE_SOURCE_WORD_OK=true;
window.AAYS_MASCHINEN_VORTEILE_ONLY_VORTEILE_OK=true;
window.AAYS_MASCHINEN_VORTEILE_VISIBLE_BUTTON_FIX_OK=true;
})();
