(function(){
'use strict';
var key='sf2_11';
var source='11. Sprach Fehlern.docx';
window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};
window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};
var LONG=[
`<h3>Schreiben_fehler_11 · Freizeitplanung, Haustierhaltung, Hilfsprogramme und KI-basierte Arbeitssysteme</h3>`,
`<p><b>Niveau:</b> C1/C2 · Präpositionen · Rektion · Verbvalenz · Nominalstil · Nomen-Verb-Verbindungen · Funktionsverbgefüge</p>`,
`<h4>1. Lernziel und Fehlerprofil</h4>`,
`<p>Dieses Kapitel trainiert typische Fehler, die in argumentativen Texten zu Freizeitplanung, Haustierhaltung, Hilfsprogrammen, ehrenamtlicher Arbeit und KI-basierten Arbeitssystemen auftreten. Der Schwerpunkt liegt auf festen Ausdrucksmustern: Verben verlangen bestimmte Ergänzungen, Präpositionen steuern bestimmte Kasus, abstrakte Nomen brauchen passende Kollokationen und technische Themen erfordern fachsprachliche Präzision. Auf C1/C2-Niveau reicht es nicht, eine Aussage ungefähr verständlich zu formulieren. Ein prüfungstauglicher Satz muss präzise, idiomatisch, kohärent und stilistisch kontrolliert sein.</p>`,
`<p>Die wichtigsten Muster dieses Kapitels sind <b>sich um jemanden kümmern</b>, <b>an einem Programm teilnehmen</b>, <b>unter Druck stehen</b>, <b>auf einem Niveau liegen</b>, <b>aus Erfahrungen lernen</b>, <b>mit anderen kommunizieren</b>, <b>auf Kundenfragen antworten</b>, <b>Verantwortung übernehmen</b>, <b>Tätigkeiten ausführen</b>, <b>Prozesse optimieren</b>, <b>Risiken bergen</b> und <b>Unsicherheit empfinden</b>. Diese Einheiten sollten nicht als einzelne Vokabeln, sondern als komplette syntaktische Bausteine gelernt werden.</p>`,
`<h4>2. Präpositionen mit Kasus: die zentralen Muster</h4>`,
`<p>Präpositionen bestimmen im Deutschen nicht nur die grammatische Form, sondern auch die argumentative Funktion. <b>Aufgrund + Genitiv</b> nennt in formeller Sprache einen Grund: <i>Aufgrund wirtschaftlicher Schwierigkeiten verzichten manche Familien auf die Haltung eines Haustiers.</i> <b>Wegen</b> kann ebenfalls einen Grund ausdrücken, wirkt aber oft weniger gehoben: <i>Wegen anhaltenden Stresses planen manche Studierende ihre Freizeit übermäßig streng.</i> Wichtig ist, Ursache, Bereich und Richtung nicht zu vermischen.</p>`,
`<p>Für Sorge und Pflege verwendet man <b>sich kümmern um + Akkusativ</b>: <i>Wer ein Haustier hält, muss sich dauerhaft um dessen Pflege kümmern.</i> Für Teilnahme gilt <b>teilnehmen an + Dativ</b>: <i>Viele Jugendliche nehmen an Hilfsprogrammen teil, um soziale Verantwortung zu übernehmen.</i> Für Lernquellen ist <b>aus + Dativ</b> erforderlich: <i>Teilnehmende können aus den Erfahrungen anderer lernen.</i> Für Kommunikation mit Personen steht <b>mit + Dativ</b>: <i>Indem sie mit anderen kommunizieren, entwickeln sie soziale Kompetenzen.</i></p>`,
`<p>Weitere wichtige Muster sind <b>zu + Dativ</b> bei Richtung: <i>Kranke Haustiere müssen rechtzeitig zum Tierarzt gebracht werden.</i> Bei abstrakten Standards steht <b>auf + Dativ</b>: <i>Wenn Sicherheitsstandards nicht auf einem ausreichenden Niveau liegen, entstehen Risiken.</i> Bei Wirkungsrichtung steht <b>Auswirkungen auf + Akkusativ</b>: <i>KI-basierte Maschinen können positive Auswirkungen auf eine geringere körperliche Belastung haben.</i> Das Verb <b>antworten</b> verlangt <b>auf + Akkusativ</b>: <i>Chatbots können auf zahlreiche Kundenfragen automatisch antworten.</i></p>`,
`<h4>3. Rektion und Verbvalenz</h4>`,
`<p>Viele Fehler entstehen, weil ein deutsches Verb eine feste Ergänzung verlangt. Das Verb <b>kümmern</b> ist reflexiv: <i>Familien müssen sich um die Pflege ihrer Haustiere kümmern.</i> Ohne Reflexivpronomen ist der Satz falsch oder unvollständig. Das Verb <b>teilnehmen</b> steht mit <b>an + Dativ</b>: <i>Ich habe an einem Unterstützungsprogramm im Sportverein teilgenommen.</i> Ein Programm wird nicht geteilt, sondern besucht oder man nimmt daran teil.</p>`,
`<p>Bei Hilfsprogrammen ist die Verbwahl besonders wichtig. Taktiken werden nicht einfach gegeben, sondern <b>vermittelt</b>, <b>erklärt</b> oder <b>beigebracht</b>. Fähigkeiten werden im gehobenen Stil <b>erworben</b> oder <b>entwickelt</b>. Probleme werden <b>eigenständig bewältigt</b> oder <b>selbstständig gelöst</b>. Verantwortung wird <b>übernommen</b>, in allgemeiner Bedeutung häufig ohne Artikel: <i>Durch ehrenamtliches Engagement lernen Jugendliche, Verantwortung zu übernehmen.</i></p>`,
`<p>Im technischen Kontext sind andere Verben erforderlich. Maschinen machen keine Arbeiten, sondern <b>führen Tätigkeiten aus</b> oder <b>übernehmen monotone Aufgaben</b>. Digitale Systeme <b>antworten auf Fragen</b>, nicht <i>an Fragen</i>. Beschäftigte <b>empfinden Unsicherheit</b> oder <b>geraten unter Druck</b>, statt Unsicherheit einfach zu fühlen. Diese präzisen Verbvalenzen machen den Unterschied zwischen alltagssprachlicher Verständlichkeit und C1/C2-Prüfungssprache.</p>`,
`<h4>4. Nomen-Verb-Verbindungen und Funktionsverbgefüge</h4>`,
`<p>Nomen-Verb-Verbindungen helfen dabei, komplexe Gedanken sachlich und strukturiert auszudrücken. Besonders wichtig sind <b>Verantwortung übernehmen</b>, <b>unter Druck stehen</b>, <b>Zeit aufwenden</b>, <b>Betreuung leisten</b>, <b>Kosten tragen</b>, <b>einen Beitrag leisten</b>, <b>Einfluss auf etwas nehmen</b>, <b>in Anspruch nehmen</b>, <b>Risiken bergen</b>, <b>Arbeitsplätze gefährden</b>, <b>Prozesse optimieren</b> und <b>Unsicherheit auslösen</b>. Diese Verbindungen sind präziser als einfache, vage Verben.</p>`,
`<p>Ein schwacher Satz lautet: <i>Hilfsprogramme helfen Jugendlichen.</i> Präziser ist: <i>Hilfsprogramme leisten einen wichtigen Beitrag zur sozialen Entwicklung Jugendlicher, weil sie Verantwortung, Kommunikation und eigenständiges Problemlösen fördern.</i> Ein einfacher KI-Satz lautet: <i>KI macht Arbeiten.</i> C1/C2-gerecht ist: <i>KI-basierte Maschinen können monotone Tätigkeiten ausführen und Produktionsprozesse optimieren, sofern technische Standards auf einem ausreichenden Niveau liegen.</i></p>`,
`<h4>5. Themenblock Freizeitplanung, Stress und persönliche Freiheit</h4>`,
`<p>Beim Thema Freizeitplanung muss zwischen Organisation, Erholung und Belastung klar unterschieden werden. Das Adjektiv <i>planmäßig</i> beschreibt eher Abläufe, nicht Personen. Für Personen schreibt man <b>gut organisierte Studierende</b> oder <b>Studierende mit guter Freizeitplanung</b>. Ein C1/C2-Satz lautet: <i>Gut organisierte Studierende beginnen mit ihren Aufgaben rechtzeitig und können dadurch Stress reduzieren.</i></p>`,
`<p>Freizeit soll normalerweise zur Erholung beitragen. Deshalb sagt man <b>sich in der Freizeit erholen</b>, <b>in der Freizeit entspannen</b> oder <b>Hobbys als Ausgleich nutzen</b>. Wenn Freizeit zu stark strukturiert wird, kann sie ihren entlastenden Charakter verlieren: <i>Ein unflexibler Zeitplan kann dazu führen, dass Freizeit nicht mehr als Erholung wahrgenommen wird.</i> Besonders stark ist die Formulierung: <i>Hobbys werden als Pflicht empfunden</i>. Sie zeigt, dass ein eigentlich freier Bereich in Leistungsdruck umschlägt.</p>`,
`<p>Für eine differenzierte Argumentation ist der Gegensatz wichtig: Planung kann entlasten, aber Überplanung kann belasten. Ein Modell lautet: <i>Eine sinnvolle Freizeitplanung kann zur Stressreduktion beitragen, weil Aufgaben rechtzeitig erledigt werden. Eine zu strenge Planung verringert jedoch die persönliche Freiheit und kann dazu führen, dass Erholung nicht mehr möglich ist.</i></p>`,
`<h4>6. Themenblock Haustierhaltung, Pflegekosten und Verantwortung</h4>`,
`<p>Bei Haustieren sind Nominalisierung und Verbstruktur entscheidend. Man spricht von <b>Pflegekosten</b>, <b>Kosten für die Pflege</b>, <b>Tierarztkosten</b> und <b>langfristigen Verpflichtungen</b>. Das Verb <b>sich kümmern</b> verlangt <b>um + Akkusativ</b>: <i>Haustierhalter müssen sich täglich um ihre Haustiere kümmern.</i> Ebenso wichtig ist <b>Verantwortung für ein Tier übernehmen</b>: <i>Wer ein Haustier hält, übernimmt Verantwortung für ein Lebewesen.</i></p>`,
`<p>Wenn ein Tier krank ist, wird es <b>zum Tierarzt gebracht</b>. Man schreibt nicht, dass das Tier <i>nach Tierarztbesuche mitkommt</i>. Ein gehobener Satz lautet: <i>Wenn ein Haustier krank wird, können regelmäßige Tierarztbesuche notwendig werden, wodurch zusätzliche Kosten entstehen.</i> Für finanzielle Gründe eignet sich <b>aufgrund + Genitiv</b>: <i>Manche Familien können sich aufgrund ihrer wirtschaftlichen Situation kein Haustier leisten.</i></p>`,
`<p>Auch räumliche Bedingungen müssen idiomatisch formuliert werden. Bei kleinen Wohnungen schreibt man <b>auf engem Raum</b>: <i>In kleinen Wohnungen kann es schwierig sein, sich auf engem Raum angemessen um Haustiere zu kümmern.</i> Dadurch wird nicht nur der Ort genannt, sondern ein Problem der Haltung beschrieben.</p>`,
`<h4>7. Themenblock Hilfsprogramme und soziale Fähigkeiten</h4>`,
`<p>Programme werden nicht geteilt, sondern man <b>nimmt an ihnen teil</b>. Korrekt ist: <i>Jugendliche können an einem Hilfsprogramm teilnehmen, um Verantwortung zu übernehmen.</i> Wenn ein Programm Inhalte vermittelt, verwendet man <b>vermitteln</b>: <i>Trainerinnen und Trainer vermitteln den Kindern grundlegende Spieltaktiken.</i> Diese Form ist wesentlich präziser als <i>Taktiken geben</i>.</p>`,
`<p>Fähigkeiten werden im Prüfungskontext <b>erworben</b>, <b>entwickelt</b> oder <b>gestärkt</b>. Ein Satz lautet: <i>Durch die Mitarbeit erwerben Teilnehmende soziale und organisatorische Fähigkeiten.</i> Die Struktur <b>aus Fehlern und Erfahrungen anderer lernen</b> betont die Quelle eines Lernprozesses. <i>Sie lernen aus den Fehlern und Erfahrungen anderer</i> ist idiomatischer als eine direkte Übertragung mit <i>von anderen Fehlern</i>.</p>`,
`<p>Hilfsprogramme können zur Persönlichkeitsentwicklung beitragen, weil sie soziale Interaktion, Verantwortung und Problemlösekompetenz verbinden. Ein Modell lautet: <i>Indem Jugendliche mit anderen kommunizieren, lernen sie, Probleme eigenständig zu bewältigen und Verantwortung für gemeinsame Aufgaben zu übernehmen.</i></p>`,
`<h4>8. Themenblock Zeitaufwand, Personalmangel und Betreuungsarbeit</h4>`,
`<p>Bei einer kritischen Betrachtung von Hilfsprogrammen müssen Zeit, Personal und Betreuung voneinander getrennt werden. Ein Programm <b>erfordert einen hohen Zeitaufwand</b>, weil regelmäßige Betreuung notwendig ist. Wenn nicht genügend Helferinnen und Helfer vorhanden sind, spricht man von <b>Personalmangel</b> oder einem <b>Mangel an freiwilligen Helferinnen und Helfern</b>. Der Ausdruck <i>Arbeiterknappheit</i> ist in diesem Kontext weniger passend.</p>`,
`<p>Bei Kindern, Sportvereinen oder sozialen Programmen ist <b>Betreuungszeit</b> angemessener als <i>Behandlungszeit</i>, weil es nicht um medizinische Behandlung geht. Freiwillige Helferinnen und Helfer <b>wenden Zeit auf</b>, <b>leisten Betreuung</b> und <b>unterstützen Kinder</b>. Ein C1/C2-Satz lautet: <i>Hilfsprogramme erfordern einen hohen Zeitaufwand und ausreichend freiwillige Helferinnen und Helfer, damit eine zuverlässige Betreuung geleistet werden kann.</i></p>`,
`<h4>9. Themenblock KI-basierte Arbeitssysteme</h4>`,
`<p>Beim Thema KI und Automatisierung ist fachsprachliche Genauigkeit besonders wichtig. Man schreibt <b>KI-basierte Maschinen</b> oder <b>Maschinen, die auf KI basieren</b>. Die Form <i>KI-basierende Maschinen</i> wirkt weniger idiomatisch. Maschinen produzieren keine Dinge, sondern <b>stellen Produkte her</b>, <b>produzieren Waren</b>, <b>führen Tätigkeiten aus</b> oder <b>optimieren Produktionsprozesse</b>.</p>`,
`<p>Die Präposition bei Tätigkeiten lautet <b>bei + Dativ</b>: <i>Technische Systeme können Menschen bei ihrer Arbeit unterstützen.</i> Mit Niveau steht <b>auf + Dativ</b>: <i>Wenn Sicherheitsstandards nicht auf einem ausreichenden Niveau liegen, können Risiken entstehen.</i> Das Nomen <b>Risiko</b> hat im Plural <b>Risiken</b>. Ein fachsprachlicher Satz lautet: <i>Diese Risiken müssen vor dem Einsatz neuer Systeme sorgfältig geprüft werden.</i></p>`,
`<p>Für Arbeitsplatzunsicherheit sind die Kollokationen <b>berufliche Unsicherheit empfinden</b>, <b>aus Angst vor einem Arbeitsplatzverlust unter Druck geraten</b> und <b>Arbeitsplätze gefährden</b> wichtig. Ein ausgewogener Satz lautet: <i>KI-basierte Maschinen können Produktionsprozesse optimieren, bergen jedoch soziale Risiken, wenn Beschäftigte aus Angst vor einem Arbeitsplatzverlust unter Druck geraten.</i></p>`,
`<h4>10. Akademische Satzbausteine</h4>`,
`<p>Für Prüfungstexte eignen sich folgende Strukturen: <i>Ein zentrales Problem besteht darin, dass eine zu strenge Freizeitplanung den Erholungswert der Freizeit verringern kann.</i> <i>Ein weiterer Aspekt liegt in den Pflegekosten, die Haustierhalter langfristig tragen müssen.</i> <i>Hilfsprogramme leisten einen wichtigen Beitrag zur sozialen Entwicklung, da Teilnehmende lernen, Verantwortung zu übernehmen.</i> <i>KI-basierte Maschinen können Produktionsprozesse optimieren, indem sie monotone Tätigkeiten übernehmen und menschliche Arbeit entlasten.</i></p>`,
`<p>Solche Satzbausteine verbinden Grammatik und Argumentation. Sie ermöglichen es, Ursachen, Folgen, Gegenargumente und Bewertungen klar zu formulieren. Besonders wichtig sind <b>dies ist darauf zurückzuführen, dass</b>, <b>daraus lässt sich ableiten, dass</b>, <b>gleichzeitig muss berücksichtigt werden, dass</b> und <b>sofern technische Standards auf einem ausreichenden Niveau liegen</b>.</p>`,
`<h4>11. Modellabsätze</h4>`,
`<p><b>Freizeitplanung:</b> Eine zu strenge Freizeitplanung kann problematisch sein, weil sie den Erholungswert der Freizeit verringert. Wer seine Hobbys nicht mehr als Ausgleich, sondern als Pflicht empfindet, steht auch außerhalb des Berufsalltags unter Druck. Schließlich sind viele Menschen bereits bei der Arbeit gezwungen, feste Termine einzuhalten und ihre Zeit genau einzuteilen.</p>`,
`<p><b>Haustierhaltung:</b> Haustierhaltung bringt nicht nur emotionale Vorteile mit sich, sondern auch langfristige Verpflichtungen. Haustierhalter müssen Pflegekosten tragen, Tiere bei Krankheiten zum Tierarzt bringen und sich täglich um deren Versorgung kümmern. Besonders für Menschen mit begrenzten finanziellen Mitteln kann dies aufgrund ihrer wirtschaftlichen Situation eine erhebliche Belastung darstellen.</p>`,
`<p><b>Hilfsprogramme:</b> Hilfsprogramme können die Persönlichkeitsentwicklung junger Menschen fördern, da Teilnehmende lernen, Verantwortung zu übernehmen, mit anderen zu kommunizieren und Probleme eigenständig zu bewältigen. Zugleich erfordern solche Programme jedoch einen hohen Zeitaufwand und ausreichend freiwillige Helferinnen und Helfer, damit eine zuverlässige Betreuung geleistet werden kann.</p>`,
`<p><b>KI-basierte Arbeitssysteme:</b> KI-basierte Maschinen können Unternehmen dabei unterstützen, Produktionsprozesse zu optimieren und monotone Tätigkeiten effizienter auszuführen. Dennoch bergen sie Risiken, wenn Sicherheitsstandards nicht auf einem ausreichenden Niveau liegen oder Beschäftigte aus Angst vor einem Arbeitsplatzverlust unter Druck geraten.</p>`,
`<h4>12. Schreibkontrolle</h4>`,
`<p>Vor dem Schreiben sollte jede zentrale Formulierung geprüft werden: Verlangt das Verb eine feste Präposition? Steht nach der Präposition der richtige Kasus? Ist das Verb reflexiv? Ist das Nomen idiomatisch? Ist die Aussage fachlich präzise? Besonders wichtig sind <b>teilnehmen an + Dativ</b>, <b>antworten auf + Akkusativ</b>, <b>sich kümmern um + Akkusativ</b>, <b>aufgrund + Genitiv</b>, <b>mit + Dativ</b>, <b>auf + Dativ bei Niveau</b>, <b>Risiken bergen</b>, <b>Verantwortung übernehmen</b>, <b>Prozesse optimieren</b> und <b>Unsicherheit empfinden</b>.</p>`
].join('');
var P=[
['aufgrund wirtschaftlicher Schwierigkeiten','aufgrund + Genitiv','___ wirtschaftlicher Schwierigkeiten verzichten manche Familien auf Haustiere.','Aufgrund','formeller Grund'],
['sich um ein Haustier kümmern','um + Akkusativ','Wer ein Haustier hält, muss sich ___ dessen Pflege kümmern.','um','Sorge und Verantwortung'],
['an einem Hilfsprogramm teilnehmen','an + Dativ','Viele Jugendliche nehmen ___ einem Hilfsprogramm teil.','an','Teilnahme'],
['aus Erfahrungen lernen','aus + Dativ','Teilnehmende können ___ den Erfahrungen anderer lernen.','aus','Lernquelle'],
['mit anderen kommunizieren','mit + Dativ','Indem sie ___ anderen kommunizieren, entwickeln sie soziale Kompetenzen.','mit','Interaktion'],
['zum Tierarzt bringen','zu + Dativ','Kranke Haustiere müssen rechtzeitig ___ Tierarzt gebracht werden.','zum','Richtung zu Institution'],
['auf einem ausreichenden Niveau liegen','auf + Dativ','Sicherheitsstandards müssen ___ einem ausreichenden Niveau liegen.','auf','Qualitätsstand'],
['Auswirkungen auf körperliche Belastung haben','auf + Akkusativ','KI kann Auswirkungen ___ eine geringere körperliche Belastung haben.','auf','Wirkungsrichtung'],
['auf Kundenfragen antworten','auf + Akkusativ','Chatbots können ___ zahlreiche Kundenfragen antworten.','auf','Reaktion'],
['auf KI basieren','auf + Dativ','Moderne Produktionssysteme basieren zunehmend ___ KI.','auf','Grundlage'],
['Verantwortung übernehmen','NVV','Jugendliche lernen, Verantwortung zu ___.','übernehmen','verantwortlich handeln'],
['Tätigkeiten ausführen','Kollokation','KI-basierte Maschinen können monotone Tätigkeiten ___.','ausführen','technische Tätigkeit'],
['Prozesse optimieren','Kollokation','Unternehmen können Produktionsprozesse ___.','optimieren','Abläufe verbessern'],
['Unsicherheit empfinden','Kollokation','Beschäftigte können berufliche Unsicherheit ___.','empfinden','abstrakten Zustand wahrnehmen'],
['unter Druck geraten','unter + Dativ','Viele Beschäftigte geraten ___ Druck.','unter','Belastung'],
['Pflegekosten tragen','NVV','Haustierhalter müssen langfristig Pflegekosten ___.','tragen','Kosten übernehmen']
];
var MC=[
['Welche Form ist korrekt?',['sich um ein Haustier kümmern','ein Haustier kümmern','um ein Haustier teilnehmen','Haustier kümmern müssen'],0,'reflexiv + um'],
['Welche Präposition passt zu teilnehmen?',['an einem Programm teilnehmen','auf ein Programm teilnehmen','ein Programm teilnehmen','bei ein Programm teilnehmen'],0,'an + Dativ'],
['Welche Kollokation ist C1/C2-gerecht?',['Tätigkeiten ausführen','Arbeiten machen','Dinge machen','Maschinen arbeiten machen'],0,'technische Kollokation'],
['Welche Form ist korrekt?',['auf einem ausreichenden Niveau','im ausreichenden Niveau','bei ausreichendem Niveau','an ausreichendes Niveau'],0,'auf + Dativ'],
['Welche Form passt bei Fragen?',['auf Kundenfragen antworten','an Kundenfragen antworten','bei Kundenfragen antworten','zu Kundenfragen antworten'],0,'antworten auf + Akkusativ'],
['Welche Form ist fachsprachlich?',['KI-basierte Maschinen','KI-basierende Maschinen','KI-machende Maschinen','Maschinen mit KI machend'],0,'attributive Form'],
['Welche NVV ist idiomatisch?',['Verantwortung übernehmen','Verantwortung lernen übernehmen','die Verantwortung nehmen','Verantwortung machen'],0,'NVV'],
['Welche Form passt zu Haustierkosten?',['Pflegekosten tragen','Ausgaben der Kümmern machen','Kümmerkosten tun','Pflegeausgaben erledigen'],0,'Kosten tragen']
];
var TF=[
['Sich kümmern verlangt um + Akkusativ.',true,'Rektion'],
['Teilnehmen steht mit an + Dativ.',true,'Rektion'],
['Antworten regiert in diesem Muster auf + Akkusativ.',true,'Rektion'],
['Mit Niveau steht im Deutschen normalerweise im + Dativ.',false,'auf + Dativ'],
['Risiko hat im Plural Risiken.',true,'Plural'],
['Maschinen führen Tätigkeiten aus; Arbeiten machen ist weniger fachsprachlich.',true,'Kollokation'],
['Unsicherheit empfinden ist idiomatischer als Unsicherheit fühlen.',true,'Kollokation'],
['Kommunizieren steht mit an + Dativ.',false,'mit + Dativ']
];
window.DEUTSCH_TESTS[key]={category:'Schreiben Fehler 2',slug:'schreiben_fehler_11_freizeit_haustiere_hilfsprogramme_ki',title:'Schreiben_fehler_11 · Freizeitplanung, Haustierhaltung, Hilfsprogramme und KI-basierte Arbeitssysteme',topic:'C1/C2 · Präpositionen · Rektion · Verbvalenz · Nominalstil · NVV/FVG',source:source,words:P.map(function(x){return x[0];}),fill:P.map(function(x){return [x[2],x[3],x[1]];}),mc:MC,tf:TF,wordMatch:P.map(function(x){return [x[0],x[4]];}),phraseMatch:[['Freizeitplanung','zur Entspannung beitragen'],['Haustierhaltung','Pflegekosten tragen'],['Hilfsprogramme','Verantwortung übernehmen'],['Betreuung','Zeit aufwenden'],['KI-Systeme','Prozesse optimieren'],['Arbeitsplatzunsicherheit','unter Druck geraten']],prep:P.map(function(x){return [x[2],x[3],x[1]];}),hang:P.map(function(x){return x[0];})};
window.DEUTSCH_LESSONS[key]={source:source,longSourceVerified:true,short:'<h3>Schreiben_fehler_11 · Kurzüberblick</h3><p>Dieses Modul behandelt Freizeitplanung, Haustierhaltung, Hilfsprogramme und KI-basierte Arbeitssysteme. Trainiert werden Präpositionen mit Kasus, Rektion, Verbvalenz, Nominalstil und Nomen-Verb-Verbindungen auf C1/C2-Niveau.</p>',medium:'<h3>Schreiben_fehler_11 · Erweiterte Erklärung</h3><p>Zentrale Muster sind <b>sich um ein Haustier kümmern</b>, <b>an einem Hilfsprogramm teilnehmen</b>, <b>aus Erfahrungen lernen</b>, <b>mit anderen kommunizieren</b>, <b>auf Kundenfragen antworten</b>, <b>auf einem ausreichenden Niveau liegen</b>, <b>Tätigkeiten ausführen</b>, <b>Prozesse optimieren</b>, <b>Risiken bergen</b>, <b>Unsicherheit empfinden</b> und <b>unter Druck geraten</b>.</p>',long:LONG};
function active(){var t=(document.getElementById('lessonTitle')||{}).textContent||'';return t.indexOf('Schreiben_fehler_11')>-1||t.indexOf('Schreibfehler 11')>-1||t.indexOf('Freizeitplanung, Haustierhaltung')>-1;}
function visible(){var x=document.getElementById('lesson');return !x||!/(^|\s)hide(\s|$)/.test(x.className||'');}
function render(){if(!visible()||!active())return;var title=document.getElementById('lessonTitle'),meta=document.getElementById('lessonMeta'),content=document.getElementById('lessonContent');if(title)title.textContent='Lektion: Schreiben_fehler_11 · Freizeitplanung, Haustierhaltung, Hilfsprogramme und KI-basierte Arbeitssysteme';if(meta)meta.textContent='Niveau: C1/C2 · Deutsch';if(content&&content.innerHTML!==LONG)content.innerHTML=LONG;}
render();setTimeout(render,200);setTimeout(render,900);setInterval(render,200);document.addEventListener('click',function(){setTimeout(render,80);setTimeout(render,300);setTimeout(render,900);},true);try{new MutationObserver(function(){setTimeout(render,30);}).observe(document.documentElement,{childList:true,subtree:true,characterData:true});}catch(e){}
window.AAYS_SF2_11_SOURCE_WORD_OK=true;
})();