(function(){
'use strict';
var key='t_video_schule_nachteile';
var source='Videoueberwachung_in_der_Schule_Nachteile_C1C2(3).docx';
window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};
window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};
var LONG=[
`<h3>Videoüberwachung in der Schule – Nachteile · C1/C2-Erörterungstraining</h3>`,
`<h4>1. Grundidee des Themas</h4>`,
`<p>Videoüberwachung in der Schule ist ein prüfungsnahes Thema, weil es unmittelbar den Alltag von Jugendlichen, Lehrkräften und Eltern betrifft. In einer Schule geht es nicht nur um Ordnung und Sicherheit, sondern auch um Vertrauen, persönliche Entwicklung, soziale Begegnung und pädagogische Beziehung. Genau deshalb darf eine Kamera nicht nur als technisches Hilfsmittel betrachtet werden. Sie verändert die Atmosphäre eines Ortes, an dem Schülerinnen und Schüler lernen, Fehler machen, Freundschaften aufbauen, Konflikte austragen und allmählich Verantwortung übernehmen sollen.</p>`,
`<p>Für einen C1/C2-Text ist entscheidend, die Nachteile nicht allgemein oder moralisch zu behaupten, sondern mit klaren Erklärungsketten zu entfalten. Man schreibt also nicht einfach, Kameras seien schlecht. Man erklärt, dass dauerhafte Beobachtung zu weniger Privatsphäre führen kann, dass weniger Privatsphäre das Vertrauen schwächt und dass ein schwächeres Vertrauen ein offenes Schulklima belastet. Ebenso lässt sich zeigen, dass ständige Kontrolle psychischen Druck erzeugt, Verhalten äußerlich anpasst und die Entwicklung echter Eigenverantwortung behindert. Schließlich muss der Umgang mit Bilddaten als eigenständiger Nachteil betrachtet werden, weil in Schulen besonders viele Minderjährige betroffen sind.</p>`,
`<p>Die Argumentation bleibt dadurch nah am Schulalltag. Kameras können im Eingangsbereich, auf Fluren, im Pausenhof, in der Mensa oder in Aufenthaltsräumen installiert werden. Genau an diesen Orten finden nicht nur sicherheitsrelevante Vorfälle statt, sondern auch private Gespräche, spontane Reaktionen, Unsicherheiten und persönliche Momente. Ein starker Nachteilsaufsatz zeigt daher, dass eine Sicherheitsmaßnahme nicht automatisch pädagogisch sinnvoll ist. Sicherheit ist wichtig, aber sie darf nicht zur dauerhaften Beobachtung des gesamten Schulalltags werden.</p>`,
`<h4>2. Nachteil 1: Eingriff in die Privatsphäre und Verlust eines geschützten Lernraums</h4>`,
`<p>Ein wesentlicher Nachteil der Videoüberwachung besteht darin, dass sie in die Privatsphäre der Schülerinnen und Schüler eingreifen kann. Privatsphäre bedeutet in der Schule nicht, dass Jugendliche außerhalb jeder Regel stehen. Sie bedeutet vielmehr, dass sie einen geschützten Bereich brauchen, in dem sie sich natürlich verhalten, miteinander sprechen, Fehler machen und soziale Erfahrungen sammeln können. Die Schule ist kein reiner Kontrollraum, sondern ein Lern- und Lebensraum. Wenn Kameras dauerhaft präsent sind, verschiebt sich dieser Charakter. Der Schulraum wirkt weniger wie ein Ort des Vertrauens und stärker wie ein Bereich, in dem jede Bewegung potenziell dokumentiert wird.</p>`,
`<p>Besonders problematisch ist, dass Kameras nicht zwischen sicherheitsrelevanten Vorfällen und normalen privaten Momenten unterscheiden. Eine Kamera auf dem Pausenhof erfasst nicht nur einen möglichen Streit, sondern auch vertrauliche Gespräche, Freundschaften, Unsicherheiten oder peinliche Situationen. Eine Kamera im Flur filmt nicht nur Regelverstöße, sondern auch den verspäteten Schüler, die weinende Schülerin oder Jugendliche, die sich nach einem Konflikt zurückziehen. Dadurch werden alltägliche und persönliche Situationen Teil eines technischen Systems. Für Minderjährige ist das besonders heikel, weil sie die langfristige Bedeutung gespeicherter Aufnahmen oft nicht vollständig einschätzen können.</p>`,
`<p>Aus pädagogischer Sicht kann eine solche Beobachtung das Vertrauensverhältnis zwischen Schule und Lernenden schwächen. Wenn Schülerinnen und Schüler das Gefühl bekommen, grundsätzlich unter Verdacht zu stehen, verändert sich ihre Beziehung zur Institution Schule. Sie erleben die Schule dann nicht mehr in erster Linie als unterstützenden Lernort, sondern als kontrollierenden Raum. Auch Lehrkräfte können dadurch in eine schwierige Rolle geraten, weil pädagogische Nähe durch technische Kontrolle überlagert wird. Eine Kamera kann einen Vorfall dokumentieren, aber sie kann kein Vertrauen aufbauen, kein Gespräch führen und keine Konflikte pädagogisch lösen.</p>`,
`<p>Für eine Erörterung ist der Begriff der Verhältnismäßigkeit besonders wichtig. Eine Maßnahme ist nur dann überzeugend, wenn sie notwendig und angemessen ist. Wenn Konflikte auch durch Aufsichtspersonal, Schulsozialarbeit, klare Regeln oder persönliche Gespräche bearbeitet werden können, wirkt flächendeckende Videoüberwachung schnell übertrieben. Der Schutz vor Gefahren muss mit dem Schutz der Privatsphäre abgewogen werden. Ein C1/C2-Text sollte daher betonen, dass Sicherheit nicht zur Dauerbeobachtung werden darf.</p>`,
`<h4>3. Sprachliche Mittel zu Nachteil 1</h4>`,
`<p>Für diesen Nachteil sind präzise Ausdrucksmuster wichtig: <b>in die Privatsphäre eingreifen</b>, <b>das Vertrauensverhältnis beeinträchtigen</b>, <b>einen geschützten Lernraum verändern</b>, <b>unter ständiger Beobachtung stehen</b>, <b>die persönliche Freiheit einschränken</b>, <b>ein Klima des Misstrauens erzeugen</b>, <b>mildere Mittel in Betracht ziehen</b> und <b>pädagogische Beziehungen schwächen</b>. Diese Verbindungen sind für C1/C2-Texte deutlich stärker als einfache Formulierungen. Sie benennen konkrete Folgen und machen die Argumentation prüfungsnah.</p>`,
`<p>Ein passender Beispielabsatz lautet: Ein wichtiger Nachteil der Videoüberwachung in der Schule liegt im Eingriff in die Privatsphäre der Schülerinnen und Schüler. Die Schule ist nicht nur ein Ort der Wissensvermittlung, sondern auch ein sozialer Raum, in dem Jugendliche Fehler machen, Freundschaften aufbauen und persönliche Erfahrungen sammeln. Wenn sie jedoch auf Fluren, im Pausenhof oder in Aufenthaltsräumen ständig von Kameras erfasst werden, kann ein Gefühl permanenter Kontrolle entstehen. Dadurch wird das Vertrauensverhältnis zwischen Schule und Lernenden belastet. Zwar ist Sicherheit ein legitimes Ziel, doch darf sie nicht dazu führen, dass junge Menschen ihren Schulalltag wie in einem überwachten Raum erleben.</p>`,
`<h4>4. Nachteil 2: Psychischer Druck, Anpassungszwang und gestörte persönliche Entwicklung</h4>`,
`<p>Ein zweiter Nachteil besteht darin, dass Videoüberwachung psychischen Druck erzeugen kann. Dieser Druck muss nicht sichtbar oder ausdrücklich ausgesprochen sein. Bereits das Wissen, dass eine Kamera vorhanden ist, kann das Verhalten verändern. Schülerinnen und Schüler fragen sich, wer die Aufnahmen sieht, ob ihr Verhalten später bewertet wird oder ob eine peinliche Situation gegen sie verwendet werden könnte. Solche Gedanken können den Schulalltag belasten, besonders weil Jugendliche ohnehin stark darauf achten, wie sie von anderen wahrgenommen werden.</p>`,
`<p>Jugendliche befinden sich in einer Lebensphase, in der Selbstwahrnehmung, Anerkennung, Unsicherheit und soziale Zugehörigkeit eine große Rolle spielen. Sie müssen lernen, mit Fehlern umzugehen, Konflikte auszuhalten, Verantwortung zu übernehmen und selbstbewusster zu werden. Diese Entwicklung braucht Freiräume. Wenn jeder Schritt beobachtet wird, entsteht ein Anpassungszwang. Schülerinnen und Schüler verhalten sich dann möglicherweise ruhiger oder vorsichtiger, aber nicht unbedingt aus innerer Einsicht. Sie handeln aus Angst vor Kontrolle, nicht aus verstandenem Verantwortungsbewusstsein.</p>`,
`<p>Gerade in der Schule ist dieser Unterschied zentral. Kameras können äußerlich Disziplin erzeugen, aber sie ersetzen keine pädagogische Einsicht. Wenn Jugendliche Regeln nur beachten, weil sie gefilmt werden, haben sie den Sinn der Regeln noch nicht unbedingt verstanden. Eine Schule sollte jedoch nicht nur regelkonformes Verhalten erzwingen, sondern erklären, warum Rücksichtnahme, Respekt und Konfliktfähigkeit wichtig sind. Reine Überwachung kann dazu führen, dass Probleme nicht gelöst, sondern lediglich in unbeobachtete Bereiche verlagert werden.</p>`,
`<p>Auch das Schulklima kann darunter leiden. Pausen, Flure und Aufenthaltsräume sind Orte, an denen Jugendliche entspannen, miteinander reden und soziale Sicherheit entwickeln. Wenn sie sich dort beobachtet fühlen, nimmt spontanes Verhalten ab. Manche Jugendliche sprechen vorsichtiger, meiden bestimmte Bereiche oder ziehen sich zurück. Besonders schüchterne, sensible oder bereits belastete Schülerinnen und Schüler können Kameras als zusätzliche Bewertung erleben. Langfristig kann dadurch eine Kultur entstehen, in der Vorsicht wichtiger wird als Offenheit.</p>`,
`<h4>5. Sprachliche Mittel zu Nachteil 2</h4>`,
`<p>Für diesen Nachteil eignen sich folgende C1/C2-Verbindungen: <b>psychischen Druck ausüben</b>, <b>sich beobachtet fühlen</b>, <b>das Verhalten anpassen</b>, <b>Unsicherheit verstärken</b>, <b>spontanes Verhalten hemmen</b>, <b>aus Angst vor Kontrolle handeln</b>, <b>Konflikte verdrängen</b>, <b>Verantwortungsbewusstsein fördern</b>, <b>innere Einsicht entwickeln</b> und <b>soziale Entwicklung beeinträchtigen</b>. Besonders stark ist die Aussage: Kontrolle ersetzt keine pädagogische Einsicht.</p>`,
`<p>Ein prüfungsnaher Absatz lautet: Ein weiterer Nachteil der Videoüberwachung besteht darin, dass sie psychischen Druck auf Schülerinnen und Schüler ausüben kann. Jugendliche befinden sich in einer Lebensphase, in der sie lernen müssen, selbstständig zu handeln, Konflikte auszutragen und Verantwortung zu übernehmen. Wenn sie jedoch ständig das Gefühl haben, von Kameras beobachtet zu werden, passen sie ihr Verhalten möglicherweise nur äußerlich an. Sie verhalten sich dann nicht unbedingt aus Überzeugung richtig, sondern aus Angst vor Kontrolle. Dadurch bleibt der pädagogische Nutzen der Maßnahme begrenzt. Langfristig kann ein solches Klima die persönliche Entwicklung beeinträchtigen und die Schule weniger offen erscheinen lassen.</p>`,
`<h4>6. Nachteil 3: Datenschutzrisiken, Missbrauchsmöglichkeiten und zusätzlicher Kontrollaufwand</h4>`,
`<p>Ein dritter Nachteil betrifft den Datenschutz. Videoüberwachung bedeutet nicht nur, dass Kameras Bilder aufnehmen. Es entstehen Bilddaten, die gespeichert, geschützt, ausgewertet und rechtlich korrekt behandelt werden müssen. Gerade in Schulen ist dies besonders sensibel, weil die meisten betroffenen Personen minderjährig sind. Bildaufnahmen von Minderjährigen dürfen nicht leichtfertig behandelt werden. Die Schule muss genau festlegen, wer Zugriff auf die Aufnahmen erhält, wie lange sie gespeichert werden, wann sie gelöscht werden und wie unbefugter Zugriff verhindert wird.</p>`,
`<p>Jede Kamera schafft neue Verantwortung. Die Schule muss technische Systeme warten, Zuständigkeiten klären, Zugriffsrechte beschränken, Löschfristen festlegen und Eltern transparent informieren. Dadurch entsteht ein erheblicher organisatorischer Kontrollaufwand. Eine Schule, die eigentlich Bildung, Beratung und pädagogische Begleitung leisten soll, muss zusätzliche Verwaltungs- und Kontrollaufgaben übernehmen. Wenn Personal, Zeit oder technisches Fachwissen fehlen, können Datenschutzprobleme entstehen. Videoüberwachung ist deshalb nicht nur eine Sicherheitsmaßnahme, sondern auch eine organisatorische Belastung.</p>`,
`<p>Ein weiteres Risiko liegt in der Fehlinterpretation von Aufnahmen. Ein Video zeigt häufig nur einen Ausschnitt, nicht den vollständigen Zusammenhang. Es kann die Reaktion eines Schülers zeigen, aber nicht die vorherige Provokation. Es kann eine emotionale Szene zeigen, aber nicht erklären, warum sie entstanden ist. Wenn solche Ausschnitte ohne Kontext bewertet werden, können Schülerinnen und Schüler ungerecht beurteilt werden. Besonders problematisch wäre es, wenn Aufnahmen intern weitergegeben, zu lange gespeichert oder von unbefugten Personen gesehen werden.</p>`,
`<p>Hinzu kommt der finanzielle Aufwand. Kameras müssen angeschafft, installiert, gewartet und technisch geschützt werden. Externe Dienstleister können beteiligt sein, wodurch zusätzliche Datenschutzfragen entstehen. Geld und Aufmerksamkeit, die in Überwachungstechnik fließen, fehlen möglicherweise für Schulsozialarbeit, mehr Aufsichtspersonal, Präventionsprojekte oder pädagogische Gespräche. Damit entsteht die Gefahr, dass technische Kontrolle pädagogische Lösungen verdrängt. Mehr Kameras bedeuten also nicht automatisch mehr Sicherheit, sondern auch mehr Daten, mehr Verantwortung und mehr Risiken.</p>`,
`<h4>7. Sprachliche Mittel zu Nachteil 3</h4>`,
`<p>Für den Datenschutzteil sind folgende Begriffe und Nomen-Verb-Verbindungen besonders wichtig: <b>sensible Bilddaten speichern</b>, <b>Aufnahmen auswerten</b>, <b>Zugriff auf Aufnahmen gewähren</b>, <b>Zugriff beschränken</b>, <b>Löschfristen festlegen</b>, <b>Missbrauch verhindern</b>, <b>Kosten verursachen</b>, <b>Verantwortung tragen</b>, <b>Ressourcen binden</b>, <b>eine Situation aus dem Zusammenhang reißen</b> und <b>Vertrauen beschädigen</b>. Diese Muster helfen, den Datenschutz nicht nur als Nebenpunkt, sondern als zentrales Gegenargument zu behandeln.</p>`,
`<p>Ein starker Absatz lautet: Ein dritter Nachteil der Videoüberwachung in der Schule liegt in den Datenschutzrisiken und im zusätzlichen Kontrollaufwand. Kameras erzeugen sensible Bilddaten, und gerade bei Minderjährigen muss sehr genau geregelt werden, wer diese Aufnahmen sehen darf und wann sie gelöscht werden. Wenn Zuständigkeiten unklar sind oder technische Systeme nicht ausreichend geschützt werden, kann das Vertrauen von Eltern und Schülern schnell beschädigt werden. Außerdem zeigt ein Video häufig nur einen Ausschnitt einer Situation. Ohne den gesamten Zusammenhang kann ein Verhalten falsch interpretiert werden. Hinzu kommen Kosten für Anschaffung, Wartung und Verwaltung.</p>`,
`<h4>8. Vollständige Muster-Erörterung: nur Nachteile</h4>`,
`<p>In vielen Schulen wird darüber nachgedacht, ob Videoüberwachung zu mehr Sicherheit beitragen kann. Auf den ersten Blick wirkt diese Maßnahme praktisch, weil Konflikte, Diebstähle oder fremde Personen schneller erkannt werden könnten. Trotzdem sollte man sehr sorgfältig prüfen, ob Kameras in einem schulischen Umfeld wirklich angemessen sind. Schulen sind nicht nur Orte der Ordnung, sondern auch Räume des Lernens, der persönlichen Entwicklung und des Vertrauens. Aus diesem Grund bringt Videoüberwachung mehrere Nachteile mit sich.</p>`,
`<p>Ein erster wichtiger Nachteil besteht darin, dass Videoüberwachung in die Privatsphäre der Schülerinnen und Schüler eingreifen kann. Jugendliche verbringen einen großen Teil ihres Alltags in der Schule. Sie sprechen in Pausen mit Freunden, lösen Konflikte, machen Fehler und erleben persönliche Situationen. Wenn diese Momente durch Kameras erfasst werden, verändert sich der Charakter des Schulraums. Die Schule wirkt dann weniger wie ein geschützter Lernort und stärker wie ein kontrollierter Bereich. Zwar ist Sicherheit ein berechtigtes Ziel, doch darf sie nicht dazu führen, dass junge Menschen sich ständig beobachtet fühlen. Langfristig kann dadurch das Vertrauen zwischen Schule und Lernenden geschwächt werden.</p>`,
`<p>Darüber hinaus kann Videoüberwachung psychischen Druck erzeugen. Viele Schülerinnen und Schüler achten ohnehin darauf, wie sie von anderen wahrgenommen werden. Wenn zusätzlich Kameras installiert sind, kann dieses Gefühl der Bewertung noch stärker werden. Jugendliche passen ihr Verhalten dann möglicherweise nur äußerlich an, weil sie Angst vor Kontrolle haben. Das bedeutet jedoch nicht, dass sie Verantwortung übernehmen oder Regeln wirklich verstehen. Eine Schule sollte nicht nur Disziplin erzwingen, sondern die Entwicklung von Selbstständigkeit fördern. Wenn Konflikte lediglich in unbeobachtete Bereiche verschoben werden, ist pädagogisch wenig gewonnen.</p>`,
`<p>Ein weiterer problematischer Punkt betrifft den Datenschutz. Kameras erzeugen sensible Bilddaten, und gerade bei Minderjährigen muss sehr genau geregelt werden, wer Zugriff auf diese Aufnahmen hat. Auch Löschfristen, technische Sicherheit und Zuständigkeiten müssen klar sein. Wenn Aufnahmen falsch verwendet oder ohne vollständigen Zusammenhang betrachtet werden, können Schülerinnen und Schüler ungerecht beurteilt werden. Hinzu kommt, dass Kameras Kosten verursachen und organisatorische Ressourcen binden. Dieses Geld und diese Aufmerksamkeit könnten stattdessen in Schulsozialarbeit, mehr Aufsichtspersonal oder Präventionsprojekte investiert werden.</p>`,
`<p>Zusammenfassend lässt sich sagen, dass Videoüberwachung in der Schule zwar Sicherheit versprechen kann, aber erhebliche Nachteile mit sich bringt. Sie kann die Privatsphäre einschränken, psychischen Druck erzeugen und neue Datenschutzprobleme schaffen. Aus meiner Sicht sollte eine Schule daher zuerst auf Vertrauen, klare Regeln, persönliche Gespräche und pädagogische Prävention setzen. Eine sichere Schule entsteht nicht allein durch Kameras, sondern vor allem durch ein respektvolles und verantwortungsbewusstes Miteinander.</p>`
].join('');
var P=[
['in die Privatsphäre eingreifen','in + Akkusativ','Videoüberwachung kann ___ die Privatsphäre der Lernenden eingreifen.','in','einen persönlichen Schutzraum verletzen'],
['das Vertrauensverhältnis beeinträchtigen','NVV','Ständige Beobachtung kann das Vertrauensverhältnis ___.','beeinträchtigen','Vertrauen schwächen'],
['einen geschützten Lernraum verändern','NVV','Kameras können einen geschützten Lernraum ___.','verändern','Schulraum anders wirken lassen'],
['unter ständiger Beobachtung stehen','unter + Dativ','Viele Jugendliche haben das Gefühl, ___ ständiger Beobachtung zu stehen.','unter','beobachtet werden'],
['ein Klima des Misstrauens erzeugen','NVV','Dauerhafte Kontrolle kann ein Klima des Misstrauens ___.','erzeugen','Misstrauen schaffen'],
['psychischen Druck ausüben','NVV','Kameras können psychischen Druck auf Jugendliche ___.','ausüben','Belastung erzeugen'],
['das Verhalten anpassen','Kollokation','Schüler passen ihr Verhalten aus Angst vor Kontrolle ___.','an','kontrollierter handeln'],
['spontanes Verhalten hemmen','Kollokation','Ständige Beobachtung kann spontanes Verhalten ___.','hemmen','Spontaneität verringern'],
['soziale Entwicklung beeinträchtigen','NVV','Überwachung kann die soziale Entwicklung ___.','beeinträchtigen','Entwicklung schwächen'],
['sensible Bilddaten speichern','Kollokation','Kameras können sensible Bilddaten von Minderjährigen ___.','speichern','Aufnahmen sichern'],
['Zugriff auf Aufnahmen beschränken','auf + Akkusativ','Die Schule muss den Zugriff ___ Aufnahmen beschränken.','auf','Datenzugang begrenzen'],
['Löschfristen festlegen','NVV','Für Videoaufnahmen müssen klare Löschfristen ___.','festgelegt','Speicherdauer regeln'],
['Missbrauch verhindern','Kollokation','Strenge Regeln sollen Missbrauch ___.','verhindern','falsche Nutzung vermeiden'],
['Ressourcen binden','NVV','Kameras können finanzielle und organisatorische Ressourcen ___.','binden','Mittel beanspruchen'],
['aus dem Zusammenhang reißen','feste Wendung','Ein kurzer Videoausschnitt kann eine Situation ___ dem Zusammenhang reißen.','aus','Kontext verlieren']
];
var MC=[
['Welche Aussage passt ausschließlich zur Nachteilsseite?',['Videoüberwachung kann Privatsphäre einschränken, Druck erzeugen und Datenschutzrisiken schaffen.','Videoüberwachung hat nur Vorteile für Schulen.','Kameras lösen automatisch alle pädagogischen Probleme.','Videoüberwachung ersetzt Vertrauen vollständig.'],0,'Nachteilsfokus'],
['Welche Formulierung ist C1/C2-gerecht?',['in die Privatsphäre eingreifen','Privatsphäre kaputt machen','Schüler filmen ist schlecht','Kameras machen Schule böse'],0,'Register'],
['Welche Folge passt zu dauerhafter Beobachtung?',['Das Vertrauensverhältnis kann geschwächt werden.','Alle Schüler lernen automatisch besser.','Datenschutz wird überflüssig.','Konflikte verschwinden endgültig.'],0,'Folge'],
['Welche Formulierung beschreibt psychischen Druck?',['Jugendliche passen ihr Verhalten aus Angst vor Kontrolle an.','Jugendliche haben immer mehr Spaß.','Kameras ersetzen Selbstständigkeit positiv.','Alle Konflikte werden pädagogisch gelöst.'],0,'Nachteil 2'],
['Welche Datenschutzformulierung ist korrekt?',['Zugriff auf Aufnahmen beschränken','Zugriff an Aufnahmen machen','Aufnahmen ohne Kontext als Lösung beurteilen','Daten ewig speichern'],0,'Datenschutz'],
['Welche Aussage ist prüfungsstark?',['Ein Video zeigt oft nur einen Ausschnitt, nicht den vollständigen Zusammenhang.','Ein Video ist immer die ganze Wahrheit.','Bilddaten von Minderjährigen sind unwichtig.','Löschfristen braucht man nicht.'],0,'Fehlinterpretation'],
['Welche NVV passt?',['Ressourcen binden','Ressourcen machen','Ressourcen stehen','Ressourcen filmen'],0,'NVV'],
['Welche Alternative bleibt im Nachteilskontext sinnvoll?',['Schulsozialarbeit, klare Regeln und Aufsicht als mildere Mittel prüfen','noch mehr Kameras ohne Datenschutz einsetzen','alle Pausenräume dauerhaft filmen','Aufnahmen beliebig weitergeben'],0,'mildere Mittel']
];
var TF=[
['Das Modul behandelt ausschließlich Nachteile der Videoüberwachung in der Schule.',true,'Fokus'],
['Videoüberwachung kann in die Privatsphäre der Schülerinnen und Schüler eingreifen.',true,'Nachteil 1'],
['Kameras können Vertrauen automatisch und immer stärken.',false,'Bewertung'],
['Psychischer Druck kann entstehen, wenn Jugendliche sich dauerhaft beobachtet fühlen.',true,'Nachteil 2'],
['Konflikte werden durch Kameras immer pädagogisch gelöst.',false,'Pädagogik'],
['Bilddaten von Minderjährigen sind besonders sensibel.',true,'Datenschutz'],
['Ein kurzer Videoausschnitt kann ohne Kontext falsch interpretiert werden.',true,'Fehlinterpretation'],
['Mehr Überwachung bedeutet auch mehr Verantwortung.',true,'Kontrollaufwand']
];
window.DEUTSCH_TESTS[key]={category:'Bevor Schreiben',slug:'videoueberwachung_in_der_schule_nachteile_c1_c2',title:'Videoüberwachung in der Schule – Nachteile · C1/C2 Nachteilsabsatz',topic:'Erörterung · Nachteile · Schule · Privatsphäre · Datenschutz',source:source,words:P.map(function(x){return x[0];}),fill:P.map(function(x){return [x[2],x[3],x[1]];}),mc:MC,tf:TF,wordMatch:P.map(function(x){return [x[0],x[4]];}),phraseMatch:[['Privatsphäre','einschränken'],['Vertrauensverhältnis','beeinträchtigen'],['psychischen Druck','ausüben'],['Verhalten','anpassen'],['Bilddaten','speichern'],['Zugriff','beschränken'],['Ressourcen','binden'],['mildere Mittel','in Betracht ziehen']],prep:P.map(function(x){return [x[2],x[3],x[1]];}),hang:P.map(function(x){return x[0];})};
window.DEUTSCH_LESSONS[key]={source:source,longSourceVerified:true,short:'<h3>Videoüberwachung in der Schule – Nachteile · Kurzüberblick</h3><p>Dieses Modul behandelt ausschließlich Nachteile: Eingriff in die Privatsphäre, psychischer Druck durch ständige Beobachtung und Datenschutzrisiken durch sensible Bilddaten von Minderjährigen.</p>',medium:'<h3>Videoüberwachung in der Schule – Nachteile · Erweiterte Erklärung</h3><p>Videoüberwachung kann den Charakter der Schule als geschützten Lern- und Lebensraum verändern. Sie kann das Vertrauensverhältnis beeinträchtigen, Jugendliche zu äußerlich angepasstem Verhalten drängen und neue Verantwortung beim Umgang mit Bilddaten schaffen. Zentrale Muster sind <b>in die Privatsphäre eingreifen</b>, <b>psychischen Druck ausüben</b>, <b>das Verhalten anpassen</b>, <b>Zugriff auf Aufnahmen beschränken</b> und <b>Ressourcen binden</b>.</p>',long:LONG};
function active(){var t=(document.getElementById('lessonTitle')||{}).textContent||'';return t.indexOf('Videoüberwachung in der Schule')>-1||t.indexOf('videoueberwachung_in_der_schule_nachteile')>-1;}
function visible(){var x=document.getElementById('lesson');return !x||!/(^|\s)hide(\s|$)/.test(x.className||'');}
function render(){if(!visible()||!active())return;var title=document.getElementById('lessonTitle'),meta=document.getElementById('lessonMeta'),content=document.getElementById('lessonContent');if(title)title.textContent='Lektion: Videoüberwachung in der Schule – Nachteile';if(meta)meta.textContent='Niveau: C1/C2 · Erörterung · Nachteile';if(content&&content.innerHTML!==LONG)content.innerHTML=LONG;}
render();setTimeout(render,250);setTimeout(render,900);document.addEventListener('click',function(){setTimeout(render,80);setTimeout(render,300);},true);
window.AAYS_BEFORE_VIDEO_SCHULE_NACHTEILE_SOURCE3_CLEAN_OK=true;
})();