window.DEUTSCH_TESTS = window.DEUTSCH_TESTS || {};
window.DEUTSCH_TESTS.t13 = {
  slug: "allgemeine_mehrzweck_c1_c2_strukturen",
  title: "13. Genel Tema: Eşleşmeyen / Çok Amaçlı Kalıplar",
  topic: "Mehrzweck-Kollokationen · präzise Verben · Wirkung · Entwicklung · Praxis · akademische Strukturen",
  words: [
    "Feste Wendungen", "nützliche Ausdrücke", "Fokus auf etwas", "Einsatz von etwas", "wissenschaftlicher Ausdruck",
    "präzise Verben für C1/C2", "Verben für Entwicklung und Veränderung", "präzise und idiomatische Formulierungen",
    "logisch richtige Aussagen", "Standards und Regelungen", "präzise Fachlexik", "Verdrängung", "Standardisierung",
    "zentrale Akteure", "die Verhaltensänderung", "die Abwendung", "der finanzielle Erfolg", "die Weiterentwicklung",
    "das Instrument", "die Perspektive", "das Verständnis", "der soziale Fortschritt", "die vorhandenen Mittel",
    "die Belastung", "der regionale Handel", "die Ausdruckssicherheit", "Orientierung und Zukunft"
  ],
  fill: [
    ["Bekannte Persönlichkeiten können Jugendliche ____ Sportaktivitäten motivieren.", "zu", "motivieren zu + Dativ"],
    ["Ein klarer Fokus ____ praktische Anwendung erhöht den Lerneffekt.", "auf", "Fokus auf"],
    ["Der gezielte Einsatz ____ Lehrvideos kann Lernprozesse unterstützen.", "von", "Einsatz von"],
    ["Solche Projekte können einen Beitrag dazu leisten, Bildungschancen zu ____.", "verbessern", "Beitrag dazu leisten"],
    ["Digitale Medien prägen die Art und Weise, ____ Jugendliche politische Ereignisse wahrnehmen.", "wie", "prägen, wie"],
    ["Plattformen können genutzt werden, ____ Informationen schneller zu verbreiten.", "um", "um … zu"],
    ["Ein neues Verfahren kann in der Praxis Anwendung ____.", "finden", "Anwendung finden"],
    ["Langfristig kann diese Maßnahme dazu beitragen, dass soziale Teilhabe ____ wird.", "gestärkt", "Passiv"],
    ["Neue Technologien schaffen neue Möglichkeiten ____ individuelle Entwicklung.", "für", "Möglichkeiten für"],
    ["Diese Methode kann zur Verbesserung ____ Kommunikationsfähigkeit beitragen.", "der", "Genitiv"],
    ["Eine digitale Anwendung kann schneller und effektiver umgesetzt ____.", "werden", "Passiv"],
    ["Wer systematisch übt, kann messbare Fortschritte ____.", "erzielen", "Fortschritte erzielen"],
    ["Unternehmen müssen Standards, Regeln und Vorschriften ____.", "einhalten", "Standards einhalten"],
    ["Viele Menschen können von transparenten Regelungen ____.", "profitieren", "profitieren von"],
    ["Mediale Bilder können Einfluss ____ die Wahrnehmung gesellschaftlicher Gruppen ausüben.", "auf", "Einfluss auf"],
    ["Eine solche Entwicklung kann zu einer tiefgreifenden Veränderung ____.", "führen", "zu einer Entwicklung führen"],
    ["Automatisierte Verfahren können die Effizienz deutlich ____.", "steigern", "Effizienz steigern"],
    ["Übermäßiger Leistungsdruck kann eine erhebliche Belastung ____.", "darstellen", "Belastung darstellen"],
    ["Eine präzise Formulierung kann eine starke Wirkung ____.", "entfalten", "Wirkung entfalten"],
    ["Die Produktionsgeschwindigkeit kann durch technische Innovation deutlich ____.", "steigen", "Entwicklung"],
    ["Die Nachfrage kann im Laufe der Zeit ____.", "zunehmen", "Veränderung"],
    ["Die Anforderungen können sich in kurzer Zeit ____.", "erhöhen", "sich erhöhen"],
    ["Der Wandel kann sich durch digitale Prozesse ____.", "beschleunigen", "sich beschleunigen"],
    ["Durch direkten Austausch kann man an ____ gewinnen.", "Ausdruckssicherheit", "gewinnen an"],
    ["Interkulturalität kann zur sozialen Entwicklung ____.", "beitragen", "beitragen zu"],
    ["Der Wert einer Methode liegt häufig ____ ihrer praktischen Anwendbarkeit.", "in", "liegen in"],
    ["Eine bessere Orientierung kann sich positiv auf Zukunftschancen ____.", "auswirken", "sich auswirken auf"]
  ],
  mc: [
    ["Welche Formulierung ist C1/C2-gerecht?", ["Ein gezielter Einsatz digitaler Medien kann zur Verbesserung der Kommunikationsfähigkeit beitragen.", "Digitale Medien machen Kommunikation besser.", "Medien helfen gut beim Sprechen.", "Kommunikation wird irgendwie gut.", "Der Einsatz von Medien ist gut."], 0, "Akademischer Stil"],
    ["Welche Kollokation ist korrekt?", ["jemanden zu gesellschaftlichem Engagement motivieren", "jemanden an Engagement motivieren", "jemanden auf Engagement motivieren", "jemanden mit Engagement motivieren", "jemanden für zu Engagement motivieren"], 0, "motivieren zu"],
    ["Welche Struktur ist idiomatisch?", ["einen Beitrag dazu leisten, soziale Teilhabe zu stärken", "einen Beitrag leisten dazu soziale Teilhabe stärken", "einen Beitrag für Teilhabe machen", "beitragen dazu, Teilhabe stärkt", "einen Beitrag an Teilhabe leisten"], 0, "Beitrag dazu leisten"],
    ["Welche Wendung beschreibt Praxisbezug korrekt?", ["in der Praxis Anwendung finden", "in Praxis Anwendung haben", "bei der Praxis Anwendung haben", "in der Praxis angewendet finden", "auf Praxis Anwendung kommen"], 0, "Anwendung finden"],
    ["Welche Aussage ist differenziert?", ["Standardisierung kann Effizienz steigern, zugleich aber Vielfalt einschränken.", "Standardisierung ist immer nur positiv.", "Effizienz hat mit Standardisierung nichts zu tun.", "Vielfalt verhindert grundsätzlich Entwicklung.", "Regeln sind nur symbolisch."], 0, "Abwägung"],
    ["Welche Verbindung passt zu Regelungen?", ["Standards, Regeln und Vorschriften einhalten", "Regeln ausüben", "Vorschriften profitieren", "Standards beschleunigen", "Regelungen besitzen"], 0, "Standards"],
    ["Welche Formulierung ist im C1/C2-Stil präzise?", ["Eine solche Entwicklung kann eine erhebliche Belastung darstellen.", "Das ist sehr viel Stress.", "Eine Entwicklung macht Leute belastet.", "Belastung ist da.", "Das wird schwer für viele."], 0, "präzise Lexik"],
    ["Welche Struktur beschreibt Wirkung korrekt?", ["eine Wirkung entfalten", "eine Wirkung machen", "eine Wirkung besitzen", "eine Wirkung verfügen", "eine Wirkung stehen"], 0, "Wirkung"],
    ["Welche Aussage verwendet ein präzises Verb statt Nominalstil?", ["Die Maßnahme stärkt die Teilhabe.", "Die Maßnahme macht eine Stärkung der Teilhabe.", "Die Teilhabe wird stark gemacht.", "Es gibt eine Stärkung durch Maßnahme.", "Teilhabe bekommt Stärkung."], 0, "präzise Verben"],
    ["Welche Formulierung ist logisch korrekt?", ["Vorhandene Mittel müssen zielgerichtet eingesetzt werden, damit sie Wirkung entfalten.", "Mittel wirken automatisch, sobald sie existieren.", "Je mehr Mittel existieren, desto weniger Umsetzung braucht man.", "Vorhandene Mittel verhindern Wirkung.", "Mittel brauchen keine Anwendung."], 0, "Logik"],
    ["Welche Verbindung ist korrekt?", ["an Ausdruckssicherheit gewinnen", "auf Ausdruckssicherheit gewinnen", "mit Ausdruckssicherheit gewinnen", "für Ausdruckssicherheit gewinnen", "durch Ausdruckssicherheit gewinnen"], 0, "gewinnen an + Dativ"]
  ],
  tf: [
    ["„Jemanden zu etwas motivieren“ verlangt die Präposition zu mit Dativ.", true, "Rektion"],
    ["„Einen Beitrag dazu leisten, … zu …“ ist eine produktive C1/C2-Struktur.", true, "Struktur"],
    ["„Die Art und Weise prägen, wie …“ beschreibt Einfluss auf Wahrnehmungs- oder Verhaltensmuster.", true, "prägen"],
    ["„In der Praxis Anwendung finden“ ist eine unidiomatische Formulierung.", false, "Anwendung finden"],
    ["„Langfristig kann … dazu beitragen, dass …“ verbindet zeitliche Perspektive und Wirkung.", true, "Argumentation"],
    ["„Fortschritte erzielen“ ist im formellen Stil eine idiomatische Kollokation.", true, "Kollokation"],
    ["Standards, Regeln und Vorschriften kann man im Standarddeutschen einhalten.", true, "Regelungen"],
    ["„Einfluss auf etwas ausüben“ verlangt gewöhnlich den Dativ nach auf.", false, "Akkusativ"],
    ["„Eine erhebliche Belastung darstellen“ ist präziser als eine vage Aussage wie „sehr schwer sein“.", true, "C1/C2"],
    ["„Eine Wirkung entfalten“ ist eine feste und gehobene Verbindung.", true, "Wirkung"],
    ["„Wachsen“, „zunehmen“, „steigen“ und „sich erhöhen“ können Entwicklung oder Veränderung ausdrücken.", true, "Entwicklung"],
    ["„Sich beschleunigen“ bedeutet, dass ein Prozess langsamer wird.", false, "Bedeutung"],
    ["Präzise Verbwahl kann Nominalstil vermeiden und argumentative Klarheit erhöhen.", true, "Stil"],
    ["Vorhandene Mittel führen automatisch zu Wirkung, auch wenn sie nicht eingesetzt werden.", false, "Logik"],
    ["„An Ausdruckssicherheit gewinnen“ verlangt an + Dativ.", true, "Kasus"]
  ],
  wordMatch: [
    ["Präzise Verben für C1/C2", "Verben, die komplexe Sachverhalte genauer und idiomatischer ausdrücken als vage Alltagsverben"],
    ["Verben für Entwicklung und Veränderung", "Verben wie wachsen, zunehmen, steigen, sich erhöhen und sich beschleunigen"],
    ["präzise und idiomatische Formulierungen", "sprachlich korrekte und natürlich wirkende Ausdrücke auf gehobenem Niveau"],
    ["logisch richtige Aussagen", "Aussagen, deren sprachliche Form und inhaltliche Beziehung stimmig sind"],
    ["Standards und Regelungen", "Normen, Regeln oder Vorschriften, die Verhalten oder Verfahren strukturieren"],
    ["präzise Fachlexik", "genauer Fachwortschatz zur sachlichen Beschreibung komplexer Themen"],
    ["Verdrängung", "Prozess, bei dem eine Struktur, Gruppe oder Praxis durch eine andere zurückgedrängt wird"],
    ["Standardisierung", "Vereinheitlichung von Formen, Verfahren oder Angeboten"],
    ["zentrale Akteure", "wichtige handelnde Personen, Gruppen oder Institutionen in einem Prozess"],
    ["die Verhaltensänderung", "Änderung von Gewohnheiten, Entscheidungen oder sozialen Praktiken"],
    ["die Abwendung", "bewusste Distanzierung von bisherigen Mustern oder Gewohnheiten"],
    ["der finanzielle Erfolg", "wirtschaftlich messbarer Erfolg oder Gewinn"],
    ["die Weiterentwicklung", "fortlaufende Verbesserung, Veränderung oder Differenzierung"],
    ["das Instrument", "Mittel oder Werkzeug zur Erreichung eines bestimmten Ziels"],
    ["die Perspektive", "Sichtweise oder Betrachtungsrichtung auf ein Problem"],
    ["das Verständnis", "gedankliche Erfassung und Einordnung eines Sachverhalts"],
    ["der soziale Fortschritt", "Verbesserung gesellschaftlicher Bedingungen, Chancen oder Teilhabe"],
    ["die vorhandenen Mittel", "Ressourcen, Instrumente oder Möglichkeiten, die bereits zur Verfügung stehen"],
    ["die Belastung", "psychische, soziale, wirtschaftliche oder ökologische Beanspruchung"],
    ["die Ausdruckssicherheit", "Fähigkeit, sich sprachlich sicher, treffend und angemessen auszudrücken"]
  ],
  phraseMatch: [
    ["jemanden zu etwas", "motivieren"],
    ["Interesse am Sport", "wecken"],
    ["einen Beitrag dazu leisten", "… zu …"],
    ["Fokus", "auf …"],
    ["Einsatz", "von …"],
    ["Einfluss auf …", "ausüben"],
    ["eine wichtige Rolle", "spielen"],
    ["eine Rolle bei", "… spielen"],
    ["die Art und Weise prägen", "wie …"],
    ["genutzt werden", "um … zu …"],
    ["in der Praxis Anwendung", "finden"],
    ["Langfristig kann … dazu beitragen", "dass …"],
    ["neue Möglichkeiten", "für … schaffen"],
    ["zur Verbesserung von …", "beitragen"],
    ["schneller und effektiver", "umgesetzt werden"],
    ["Fortschritte", "erzielen"],
    ["Standards / Regeln / Vorschriften", "einhalten"],
    ["von etwas", "profitieren"],
    ["zu einer Entwicklung", "führen"],
    ["die Effizienz deutlich", "steigern"],
    ["eine erhebliche Belastung", "darstellen"],
    ["eine Wirkung", "entfalten"],
    ["sich", "beschleunigen"],
    ["an Ausdruckssicherheit", "gewinnen"],
    ["sich positiv auf Zukunftschancen", "auswirken"]
  ],
  prep: [
    ["Bekannte Persönlichkeiten können Jugendliche ___ Sportaktivitäten motivieren.", "zu", "motivieren zu"],
    ["Ein Fokus ___ praktische Anwendung erleichtert nachhaltiges Lernen.", "auf", "Fokus auf"],
    ["Der Einsatz ___ Lehrvideos kann individuelle Lernprozesse unterstützen.", "von", "Einsatz von"],
    ["Einfluss ___ gesellschaftliche Wahrnehmungen auszuüben, erfordert mediale Reichweite.", "auf", "Akkusativ"],
    ["Interesse ___ Sport kann durch Vorbilder geweckt werden.", "am", "an + Dativ"],
    ["Die Art und Weise, ___ Menschen kommunizieren, wird durch digitale Medien geprägt.", "wie", "Struktur"],
    ["Plattformen werden genutzt, ___ Informationen schneller zu verbreiten.", "um", "um … zu"],
    ["Ein Verfahren kann ___ der Praxis Anwendung finden.", "in", "in der Praxis"],
    ["Langfristig kann Bildung dazu beitragen, ___ soziale Teilhabe gestärkt wird.", "dass", "dazu beitragen, dass"],
    ["Neue Angebote schaffen Möglichkeiten ___ persönliche Weiterentwicklung.", "für", "Möglichkeiten für"],
    ["Diese Maßnahme trägt zur Verbesserung ___ Kommunikation bei.", "der", "Genitiv"],
    ["Wer regelmäßig übt, kann ___ Ausdruckssicherheit gewinnen.", "an", "gewinnen an + Dativ"],
    ["Menschen können ___ transparenten Regelungen profitieren.", "von", "profitieren von"],
    ["Technische Innovation kann ___ einer Entwicklung führen.", "zu", "zu + Dativ"],
    ["Eine Wirkung kann sich erst ___ Laufe der Zeit entfalten.", "im", "im Laufe der Zeit"],
    ["Die Anforderungen können sich ___ kurzer Zeit erhöhen.", "in", "Zeitangabe"],
    ["Interkulturalität kann ___ sozialen Entwicklung beitragen.", "zur", "zu + Dativ"],
    ["Der Wert einer Methode liegt häufig ___ ihrer praktischen Anwendbarkeit.", "in", "liegen in"],
    ["Eine bessere Orientierung kann sich positiv ___ Zukunftschancen auswirken.", "auf", "sich auswirken auf"]
  ],
  hang: [
    "jemanden zu etwas motivieren", "Interesse am Sport wecken", "einen Beitrag dazu leisten etwas zu verbessern",
    "Fokus auf praktische Anwendung", "Einsatz von digitalen Medien", "Einfluss auf etwas ausüben",
    "eine wichtige Rolle spielen", "eine Rolle bei etwas spielen", "die Art und Weise prägen wie",
    "genutzt werden um etwas zu tun", "in der Praxis Anwendung finden", "Langfristig kann etwas dazu beitragen dass",
    "neue Möglichkeiten für etwas schaffen", "zur Verbesserung von etwas beitragen", "schneller und effektiver umgesetzt werden",
    "Fortschritte erzielen", "Standards Regeln und Vorschriften einhalten", "von etwas profitieren",
    "zu einer Entwicklung führen", "die Effizienz deutlich steigern", "eine erhebliche Belastung darstellen",
    "eine Wirkung entfalten", "an Ausdruckssicherheit gewinnen", "sich positiv auf Zukunftschancen auswirken"
  ]
};
