window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};
window.DEUTSCH_TESTS.t19={
  category:"Bevor Schreiben",
  slug:"selbstfahrende_autos_vorteilsabsatz_c1_c2",
  title:"Selbstfahrende Autos · C1/C2 Vorteilsabsatz",
  topic:"Erörterung · Vorteile selbstfahrender Autos · Verkehrssicherheit · Verkehrsfluss · Mobilität · Teilhabe · NVV · Konnektoren",
  words:[
    "selbstfahrende Autos","selbstfahrende Fahrzeuge","autonomes Fahren","die Verkehrssicherheit","menschliches Versagen","die Reaktionsfähigkeit","die Unfallrate","der Verkehrsfluss","die Straßeninfrastruktur","der Energieverbrauch","die Mobilitätsbarrieren","die gesellschaftliche Teilhabe","die Akzeptanz autonomer Fahrzeuge","die Voraussetzung","die Vernetzung","vernetzte Fahrzeuge","langfristig betrachtet","unter bestimmten Voraussetzungen","sofern die Technik zuverlässig funktioniert","ressourcenschonender gestalten","eine vielversprechende Technologie","ein sichereres Verkehrssystem","ein effizienteres Verkehrssystem","ein inklusiveres Verkehrssystem","die Fahrzeit sinnvoll nutzen","eine deutliche Entlastung darstellen","die vorhandene Straßeninfrastruktur besser nutzbar machen","die Technik als sicher und zuverlässig wahrnehmen","Argumentationskette","Vorteilsabsatz"
  ],
  fill:[
    ["Selbstfahrende Autos sind Fahrzeuge, die nicht dauerhaft von einem Menschen ____ werden müssen.","gesteuert","Grundverständnis"],
    ["Sie erfassen ihre Umgebung mithilfe von Kameras, Sensoren, Radarsystemen, digitalen Karten und künstlicher ____.","Intelligenz","Grundverständnis"],
    ["In einer Erörterung sollte man diese Technik nicht nur beschreiben, sondern ihre gesellschaftliche Bedeutung ____.","erklären","Schreibziel"],
    ["Ein Vorteilsabsatz muss zeigen, worin der konkrete Nutzen besteht, wodurch dieser Nutzen entsteht und welche Folgen er für Menschen und Gesellschaft ____ könnte.","haben","Argumentationslogik"],
    ["Selbstfahrende Autos könnten langfristig zu einem sichereren, effizienteren und inklusiveren Verkehrssystem ____.","beitragen","Leitgedanke"],
    ["Ein Vorteilsabsatz beginnt mit einem Hauptargument, erklärt dieses Argument, begründet es logisch und zeigt anschließend eine positive ____.","Folge","Absatzaufbau"],
    ["Der stärkste Vorteil selbstfahrender Autos liegt in der möglichen Erhöhung der ____.","Verkehrssicherheit","zentraler Vorteil"],
    ["Zahlreiche Unfälle entstehen nicht durch technische Defekte, sondern durch menschliches ____.","Fehlverhalten","Sicherheit"],
    ["Autonome Fahrzeuge könnten Risikofaktoren verringern, weil sie ihre Umgebung dauerhaft ____.","analysieren","Erklärung"],
    ["Man sollte nicht schreiben, dass selbstfahrende Autos garantiert alle Unfälle ____.","verhindern","vorsichtige Formulierung"],
    ["Besser ist: Sie könnten die Unfallrate senken, sofern die technischen Systeme zuverlässig ____.","funktionieren","Bedingung"],
    ["Ein weiterer Vorteil besteht darin, dass autonome Fahrzeuge den Verkehrsfluss ____ könnten.","verbessern","Verkehrsfluss"],
    ["Wenn Fahrzeuge miteinander vernetzt sind, können sie Geschwindigkeiten besser aufeinander ____.","abstimmen","Vernetzung"],
    ["Weniger plötzliches Bremsen kann Staus reduzieren, Energie sparen und die Straßeninfrastruktur besser ____ machen.","nutzbar","Folge"],
    ["Selbstfahrende Autos könnten dazu beitragen, Mobilitätsbarrieren ____.","abzubauen","Teilhabe"],
    ["Für ältere Menschen oder Menschen mit Behinderung bedeutet Mobilität nicht nur Fortbewegung, sondern auch Selbstständigkeit, Freiheit und gesellschaftliche ____.","Teilhabe","Mobilität"],
    ["Wenn Menschen nicht mehr dauerhaft selbst fahren müssen, könnten sie die Fahrzeit anders ____.","nutzen","Komfort"],
    ["Für Pendlerinnen und Pendler könnte dies eine deutliche Entlastung ____.","darstellen","Komfort"],
    ["Eine schnelle und präzise Reaktionsfähigkeit ist besonders in unübersichtlichen Verkehrssituationen ____.","entscheidend","Wortschatz"],
    ["Die gesellschaftliche Akzeptanz autonomer Fahrzeuge hängt davon ab, ob die Technik als sicher und zuverlässig ____ wird.","wahrgenommen","Akzeptanz"],
    ["Die zuverlässige Funktion der Systeme ist eine zentrale Voraussetzung dafür, dass selbstfahrende Autos tatsächlich Vorteile ____.","bringen","Voraussetzung"],
    ["Autonome Fahrzeuge könnten einen wichtigen Beitrag zur Erhöhung der Verkehrssicherheit ____.","leisten","NVV"],
    ["Durch präzisere Reaktionen ließe sich die Unfallrate langfristig ____.","senken","NVV"],
    ["Autonomes Fahren könnte in zukünftigen Mobilitätskonzepten eine zentrale Rolle ____.","spielen","NVV"],
    ["Vernetzte Fahrzeuge könnten die Voraussetzung für einen effizienteren Straßenverkehr ____.","schaffen","NVV"],
    ["Ein überzeugender Vorteilsabsatz kombiniert nicht nur Vorteile, sondern erklärt logisch, warum diese Vorteile ____.","entstehen","Merksatz"],
    ["Ein C1/C2-Satz erklärt Ursache, Wirkung und Bedingung in einem logischen ____.","Zusammenhang","Stil"],
    ["Unter der Voraussetzung, dass die Systeme zuverlässig funktionieren, könnten selbstfahrende Autos zu einem sichereren und inklusiveren Verkehrssystem ____.","beitragen","Musterabsatz"]
  ],
  mc:[
    ["Welche Grundthese entspricht dem hochgeladenen Vorteilsabsatz-Thema am genauesten?",["Selbstfahrende Autos könnten langfristig zu einem sichereren, effizienteren und inklusiveren Verkehrssystem beitragen.","Selbstfahrende Autos sind gut, weil sie modern sind und viele Menschen sie interessant finden.","Autonome Fahrzeuge beschreiben vor allem eine technische Neuerung ohne gesellschaftliche Bedeutung.","Selbstfahrende Autos sollten in einer Erörterung hauptsächlich definiert und nicht bewertet werden.","Der wichtigste Punkt ist, dass Menschen beim Fahren weniger arbeiten müssen."],0,"Leitgedanke"],
    ["Welche Formulierung erklärt den Nutzen eines Vorteilsabsatzes am besten?",["Der Absatz muss zeigen, worin der konkrete Nutzen besteht, wodurch er entsteht und welche Folgen er haben könnte.","Der Absatz soll möglichst viele Vorteile aufzählen, auch wenn sie nicht begründet werden.","Der Absatz muss nur erklären, was selbstfahrende Autos technisch sind.","Der Absatz sollte beweisen, dass selbstfahrende Autos alle Probleme lösen.","Der Absatz beginnt am besten mit einer persönlichen Meinung ohne Begründung."],0,"Absatzlogik"],
    ["Welche Aussage formuliert den Sicherheitsvorteil C1/C2-gerecht?",["Da zahlreiche Unfälle auf menschliches Versagen zurückzuführen sind, könnten autonome Fahrzeuge langfristig zur Senkung der Unfallrate beitragen.","Selbstfahrende Autos sind sicherer, weil Menschen oft schlecht fahren und Computer besser sind.","Es gibt weniger Unfälle, wenn Autos allein fahren, deshalb ist die Technik gut.","Autonome Fahrzeuge verhindern alle Unfälle, weil technische Systeme keine Fehler machen.","Die Sicherheit wird automatisch besser, sobald Menschen nicht mehr lenken."],0,"Verkehrssicherheit"],
    ["Welche vorsichtige Formulierung ist angemessen?",["Selbstfahrende Autos könnten unter bestimmten Voraussetzungen dazu beitragen, die Zahl der Unfälle zu verringern.","Selbstfahrende Autos verhindern alle Unfälle.","Autonome Fahrzeuge lösen jedes Sicherheitsproblem vollständig.","Die Technik ist immer sicher und deshalb eindeutig überlegen.","Alle Verkehrsteilnehmer werden automatisch geschützt."],0,"Vorsichtiger Stil"],
    ["Welche Aussage beschreibt den Zusammenhang zwischen Vernetzung und Verkehrsfluss am präzisesten?",["Wenn Fahrzeuge miteinander kommunizieren, lassen sich Geschwindigkeit und Abstand genauer abstimmen, wodurch der Verkehrsfluss stabiler werden könnte.","Vernetzte Fahrzeuge machen den Verkehr besser, weil alle Autos Informationen haben.","Staus verschwinden sofort, sobald selbstfahrende Autos miteinander verbunden sind.","Der Verkehrsfluss hat mit digitaler Vernetzung nur wenig zu tun.","Autos fahren schneller, wenn sie miteinander reden, deshalb gibt es keine Staus mehr."],0,"Verkehrsfluss"],
    ["Welche Formulierung passt zu Mobilität und Teilhabe?",["Selbstfahrende Autos könnten älteren Menschen, die im Alltag häufig auf Hilfe angewiesen sind, mehr Mobilität ermöglichen und dadurch ihre gesellschaftliche Teilhabe stärken.","Alte Menschen können dann endlich fahren und haben keine Probleme mehr.","Menschen mit Behinderung brauchen selbstfahrende Autos, weil normale Autos schwer sind.","Mobilität bedeutet nur, dass man von einem Ort zu einem anderen kommt.","Autonome Fahrzeuge sind vor allem praktisch, weil niemand mehr einen Führerschein braucht."],0,"Teilhabe"],
    ["Welche Nomen-Verb-Verbindung ersetzt eine einfache Aussage wie „Die Technik hilft der Sicherheit“ am besten?",["einen Beitrag zur Erhöhung der Verkehrssicherheit leisten","die Sicherheit gut machen","Sicherheit benutzen für Verkehr","einen Vorteil gegen Sicherheit tun","der Sicherheit eine Hilfe geben"],0,"NVV"],
    ["Welche Konnektorformel gibt eine Begründung?",["Dies lässt sich damit begründen, dass …","Darüber hinaus …","Langfristig betrachtet …","Somit …","Zunächst lässt sich festhalten, dass …"],0,"Konnektoren"],
    ["Welche Konnektorformel formuliert eine Folge?",["Dies hätte zur Folge, dass …","Dies ist vor allem darauf zurückzuführen, dass …","Ein wesentliches Argument dafür ist, dass …","Unter der Voraussetzung, dass …","Nicht zu unterschätzen ist außerdem …"],0,"Konnektoren"],
    ["Welche Umformulierung ist gehoben?",["Autonome Fahrzeuge hätten das Potenzial, die Unfallrate langfristig zu senken.","Es gibt vielleicht weniger Unfälle.","Wahrscheinlich passieren nicht mehr so viele Unfälle.","Die Autos machen weniger Unfälle.","Unfälle werden weniger, weil das Auto fährt."],0,"Stilkorrektur"],
    ["Welche Satzstruktur ist am überzeugendsten?",["Da autonome Fahrzeuge die Steuerung übernehmen, könnten Pendler die bisher oft als Belastung empfundene Fahrzeit sinnvoller nutzen.","Pendler haben Fahrzeit und Autos fahren dann allein, was gut ist.","Die Fahrzeit ist eine Belastung, aber autonome Autos sind bequem.","Wenn Autos fahren, können Leute etwas anderes machen und das ist besser.","Pendler fahren nicht mehr und haben dadurch Zeit."],0,"Komplexer Satzbau"],
    ["Welche Struktur entspricht der idealen Denkstruktur eines Vorteilsabsatzes?",["Hauptargument → Begründung → Erklärung → Folge → Erweiterung → Schlussgedanke","Definition → persönliche Meinung → Beispiel → Wiederholung → Ende","Nachteil → Risiko → Gegenargument → persönlicher Wunsch → Schluss","Wortliste → Zitat → Beispiel → neues Thema → Ergebnis","Beschreibung der Technik → Behauptung → andere Meinung → offene Frage"],0,"Argumentationskette"],
    ["Welche Formulierung beschreibt Komfort überzeugend und nicht isoliert?",["Wenn Pendler die Fahrzeit sinnvoller nutzen könnten, würde dies im Alltag eine deutliche Entlastung darstellen.","Selbstfahrende Autos sind bequem, weil man nichts machen muss.","Komfort ist gut, weil Fahren nervt.","Man kann lesen, schlafen und arbeiten, deshalb sind autonome Autos perfekt.","Die Fahrzeit wird lustiger, wenn das Auto allein fährt."],0,"Komfort"],
    ["Welche Schlussfolgerung passt zum Vorteilsabsatz?",["Insgesamt wird deutlich, dass autonomes Fahren unter bestimmten Voraussetzungen einen Beitrag zu einem sichereren und inklusiveren Verkehrssystem leisten könnte.","Alles in allem sind selbstfahrende Autos gut und sollten benutzt werden.","Zusammenfassend kann man sagen, dass neue Autos interessant sind.","Am Ende hat das Thema viele Vorteile und vielleicht auch Nachteile.","Daraus ergibt sich, dass Technik immer die beste Lösung ist."],0,"Schlussfolgerung"]
  ],
  tf:[
    ["In einer Erörterung sollte man selbstfahrende Autos nicht nur beschreiben, sondern ihre gesellschaftliche Bedeutung erklären.",true,"Theorie"],
    ["Ein Vorteilsabsatz darf auf C1/C2-Niveau aus einer bloßen Aufzählung einzelner Vorteile bestehen.",false,"Absatzaufbau"],
    ["Ein starker Vorteilsabsatz erklärt Argument, Begründung, Zusammenhang und positive Folge.",true,"Argumentationslogik"],
    ["Selbstfahrende Autos sollten in einem akademischen Text als garantiert unfallfrei dargestellt werden.",false,"vorsichtige Formulierung"],
    ["Menschliches Versagen kann Müdigkeit, Ablenkung, Stress oder Selbstüberschätzung umfassen.",true,"Wortschatz"],
    ["Die Formulierung ‚die Unfallrate senken‘ ist eine passende Nomen-Verb-Verbindung.",true,"NVV"],
    ["Die Verbesserung des Verkehrsflusses lässt sich mit digitaler Vernetzung und genauer Abstimmung von Geschwindigkeit und Abstand erklären.",true,"Verkehrsfluss"],
    ["Gesellschaftliche Teilhabe bedeutet ausschließlich, dass Menschen schneller zur Arbeit fahren können.",false,"Teilhabe"],
    ["Mobilitätsbarrieren abzubauen ist ein gesellschaftlich argumentierbarer Vorteil selbstfahrender Autos.",true,"Inklusion"],
    ["Konnektoren wie ‚Dies lässt sich damit begründen, dass …‘ helfen, eine Begründung klar einzuleiten.",true,"Konnektoren"],
    ["Formulierungen wie ‚könnte‘, ‚hätte das Potenzial‘ und ‚unter bestimmten Voraussetzungen‘ schwächen einen C1/C2-Text grundsätzlich und sollten vermieden werden.",false,"Stil"],
    ["Ein Musterabsatz sollte mindestens eine NVV, einen Konnektor und eine vorsichtige Formulierung enthalten.",true,"Schreibtraining"],
    ["Komfort wirkt überzeugender, wenn er mit Lebensqualität oder Entlastung verbunden wird.",true,"Komfort"],
    ["Die Akzeptanz autonomer Fahrzeuge hängt auch davon ab, ob die Technik als sicher und zuverlässig wahrgenommen wird.",true,"Akzeptanz"]
  ],
  wordMatch:[
    ["autonomes Fahren","Oberbegriff für das selbstständige Fahren ohne dauerhafte menschliche Steuerung"],
    ["menschliches Versagen","Fehler, die durch Unaufmerksamkeit, Müdigkeit oder falsche Entscheidungen entstehen"],
    ["Verkehrssicherheit","Sicherheit aller Beteiligten im Straßenverkehr"],
    ["Unfallrate","Häufigkeit von Verkehrsunfällen"],
    ["Verkehrsfluss","gleichmäßige Bewegung des Verkehrs ohne häufiges Stoppen"],
    ["Mobilitätsbarrieren","Hindernisse, die Menschen in ihrer Bewegungsfreiheit einschränken"],
    ["gesellschaftliche Teilhabe","aktive Teilnahme am sozialen und öffentlichen Leben"],
    ["Vernetzung","digitale Verbindung zwischen Fahrzeugen oder Verkehrssystemen"],
    ["langfristig betrachtet","mit Blick auf zukünftige Entwicklungen"],
    ["unter bestimmten Voraussetzungen","vorsichtige Formulierung, die Bedingungen einbezieht"],
    ["Reaktionsfähigkeit","Fähigkeit, schnell und angemessen auf eine Situation zu reagieren"],
    ["Straßeninfrastruktur","vorhandenes System aus Straßen, Verkehrswegen und technischer Ausstattung"],
    ["Akzeptanz","Bereitschaft, eine Technologie gesellschaftlich anzunehmen"],
    ["Vorteilsabsatz","argumentativer Absatz, der einen Vorteil logisch erklärt und bewertet"],
    ["Argumentationskette","geordnete Abfolge von Argument, Begründung, Erklärung, Folge und Bewertung"]
  ],
  phraseMatch:[
    ["einen Beitrag leisten","zu + Dativ"],
    ["zur Verbesserung","beitragen"],
    ["eine Verbesserung","bewirken"],
    ["die Unfallrate","senken"],
    ["mehr Selbstständigkeit","ermöglichen"],
    ["zur Reduzierung von Staus","beitragen"],
    ["eine zentrale Rolle","spielen"],
    ["von großer Bedeutung","sein"],
    ["positive Auswirkungen haben","auf + Akkusativ"],
    ["die Voraussetzung schaffen","für + Akkusativ"],
    ["Mobilitätsbarrieren","abbauen"],
    ["die Verkehrssicherheit","erhöhen"],
    ["menschliches Versagen","verringern"],
    ["den Verkehrsfluss","stabilisieren"],
    ["Geschwindigkeit und Abstand","genauer abstimmen"],
    ["die Fahrzeit","sinnvoller nutzen"],
    ["eine deutliche Entlastung","darstellen"],
    ["gesellschaftliche Teilhabe","stärken"],
    ["einen übergeordneten Schlussgedanken","formulieren"],
    ["eine logische Argumentationskette","entwickeln"]
  ],
  prep:[
    ["Selbstfahrende Autos könnten einen wichtigen Beitrag ___ Erhöhung der Verkehrssicherheit leisten.","zur","zu + Dativ"],
    ["Viele Unfälle sind ___ menschliches Versagen zurückzuführen.","auf","zurückzuführen auf"],
    ["Autonome Fahrzeuge könnten ___ Verbesserung des Verkehrsflusses beitragen.","zur","beitragen zu + Dativ"],
    ["Autonomes Fahren könnte positive Auswirkungen ___ die Organisation des Verkehrs haben.","auf","Auswirkungen auf + Akkusativ"],
    ["Vernetzte Fahrzeuge könnten die Voraussetzung ___ einen effizienteren Straßenverkehr schaffen.","für","Voraussetzung für + Akkusativ"],
    ["Für Menschen ___ eingeschränkter Mobilität könnte diese Technologie von großer Bedeutung sein.","mit","mit + Dativ"],
    ["Der Grund dafür liegt ____ , dass viele Unfälle durch Ablenkung entstehen.","darin","liegen darin"],
    ["Dies lässt sich damit begründen, ____ autonome Systeme ihre Umgebung dauerhaft analysieren.","dass","Nebensatz"],
    ["Weniger plötzliches Bremsen kann ___ einer Reduzierung von Staus beitragen.","zu","beitragen zu"],
    ["Unter der Voraussetzung, ____ die Systeme zuverlässig funktionieren, könnten selbstfahrende Autos Vorteile bringen.","dass","Bedingung"],
    ["Mobilität ist eng ___ Selbstständigkeit und gesellschaftlicher Teilhabe verbunden.","mit","verbunden mit"],
    ["Die Akzeptanz hängt davon ab, ob die Technik ___ sicher und zuverlässig wahrgenommen wird.","als","wahrnehmen als"],
    ["Infolgedessen wäre es möglich, den Verkehr ressourcenschonender ___ gestalten.","zu","zu-Infinitiv"],
    ["Im Gegensatz ___ menschlichen Fahrern werden technische Systeme nicht müde.","zu","im Gegensatz zu"],
    ["Daraus ergibt sich, ____ autonomes Fahren ein wichtiger Bestandteil moderner Mobilität sein könnte.","dass","Folgesatz"]
  ],
  hang:[
    "selbstfahrende Autos","autonomes Fahren","menschliches Versagen","die Verkehrssicherheit erhöhen","die Unfallrate langfristig senken","den Verkehrsfluss stabilisieren","Mobilitätsbarrieren abbauen","gesellschaftliche Teilhabe stärken","einen Beitrag zur Verkehrssicherheit leisten","zur Verbesserung des Verkehrsflusses beitragen","eine Verbesserung bewirken","mehr Selbstständigkeit ermöglichen","zur Reduzierung von Staus beitragen","eine zentrale Rolle spielen","von großer Bedeutung sein","positive Auswirkungen auf die Organisation des Verkehrs haben","die Voraussetzung für einen effizienteren Straßenverkehr schaffen","Geschwindigkeit und Abstand genauer abstimmen","die Fahrzeit sinnvoller nutzen","eine deutliche Entlastung darstellen","unter bestimmten Voraussetzungen","langfristig betrachtet","sofern die Technik zuverlässig funktioniert","Dies lässt sich damit begründen dass","Der Grund dafür liegt darin dass","Daraus ergibt sich dass","Ein wesentliches Argument dafür ist dass","Nicht zu unterschätzen ist außerdem","eine logische Argumentationskette entwickeln","einen übergeordneten Schlussgedanken formulieren","ressourcenschonender gestalten","die vorhandene Straßeninfrastruktur besser nutzbar machen"
  ]
};
