window.AAYS_VIDEO_SCHULE_NACHTEILE_LONG_PARTS=window.AAYS_VIDEO_SCHULE_NACHTEILE_LONG_PARTS||[];
window.AAYS_VIDEO_SCHULE_NACHTEILE_LONG_PARTS[2]=`<h4>Nachteil 2: Psychischer Druck, Anpassungszwang und gestörte persönliche Entwicklung</h4>
<h5>Grundidee dieses Nachteils</h5>
<p>Kameras verändern nicht nur die äußere Ordnung, sondern auch das innere Erleben der Schülerinnen und Schüler. Wer sich dauerhaft beobachtet fühlt, verhält sich häufig weniger spontan, weniger offen und stärker angepasst. Gerade Jugendliche achten ohnehin sehr darauf, wie sie von anderen wahrgenommen werden. Eine zusätzliche technische Beobachtung kann dieses Gefühl der Bewertung verstärken.</p>
<h5>Beobachtungen aus dem Alltag</h5>
<ul><li>Viele Jugendliche überlegen schon ohne Kameras, wie Mitschüler und Lehrkräfte ihr Verhalten beurteilen.</li><li>Auf Pausenhöfen, Fluren und in Aufenthaltsräumen möchten Lernende sich erholen und frei miteinander sprechen.</li><li>Schüchterne oder sensible Schülerinnen und Schüler können sichtbare Kameras als zusätzliche Belastung erleben.</li><li>Nach einem Streit kann die Sorge entstehen, dass eine emotionale Reaktion später erneut angesehen und bewertet wird.</li><li>Private Gespräche werden möglicherweise in unbeobachtete Bereiche verlagert.</li></ul>
<h5>Detaillierte Erklärung</h5>
<p>Psychischer Druck muss nicht durch eine direkte Drohung entstehen. Schon das Wissen, dass eine Kamera vorhanden ist, kann genügen, damit Jugendliche jede Bewegung kontrollieren. Sie fragen sich, wer die Aufnahme sehen darf, ob ein peinlicher Moment gespeichert wird oder ob eine unklare Situation später gegen sie verwendet werden könnte. Dadurch wird der Schulalltag nicht automatisch sicherer, sondern möglicherweise angespannter.</p>
<p>Schule ist ein Raum persönlicher Entwicklung. Jugendliche müssen lernen, Fehler auszuhalten, Konflikte zu lösen, Verantwortung zu übernehmen und selbstständig zu handeln. Diese Entwicklung braucht Freiräume. Wenn Lernende Regeln nur deshalb beachten, weil sie Angst vor Aufzeichnungen oder Sanktionen haben, entsteht zwar äußerlich angepasstes Verhalten, aber keine sichere innere Einsicht. Pädagogisch ist dieser Unterschied entscheidend: Kontrolle kann Verhalten kurzfristig beeinflussen, aber sie erklärt nicht, warum Rücksichtnahme, Respekt und Verantwortung notwendig sind.</p>
<p>Außerdem verschwinden Konflikte durch Kameras nicht zwingend. Sie können in nicht überwachte Bereiche verlagert werden. Schülerinnen und Schüler lernen dann eher, Kontrolle zu umgehen, als Streit offen und verantwortungsvoll zu bearbeiten. Dadurch verliert die Schule eine wichtige pädagogische Möglichkeit. Konflikte sind nicht nur Störungen, sondern auch Lerngelegenheiten, in denen Kommunikation, Wiedergutmachung und soziale Verantwortung geübt werden können.</p>
<h5>Konkrete Beispiele</h5>
<ul><li>Ein Schüler hält sich beim ausgelassenen Gespräch mit Freunden zurück, weil er nicht gefilmt werden möchte.</li><li>Eine Schülerin vermeidet nach einem Streit einen bestimmten Flur, weil sie sich dort besonders beobachtet fühlt.</li><li>Jugendliche verlagern persönliche Gespräche in schlecht einsehbare Bereiche, wodurch neue Aufsichtsprobleme entstehen.</li><li>Ein bereits häufig ermahnter Schüler erlebt die Kameras als Zeichen dauerhaften Misstrauens und entwickelt noch mehr Distanz zur Schule.</li></ul>
<h5>Ergebnisse und Risiken</h5>
<ul><li>Spontanes Verhalten und offene Kommunikation können abnehmen.</li><li>Jugendliche handeln aus Angst vor Kontrolle statt aus Verantwortungsbewusstsein.</li><li>Schüchterne oder sensible Lernende können stärker belastet werden.</li><li>Konflikte werden versteckt, anstatt pädagogisch bearbeitet zu werden.</li><li>Das Schulklima wirkt kontrollierter und weniger lebendig.</li></ul>
<h5>Kurz- und Langzeitwirkungen</h5>
<p><b>Kurzfristig:</b> Schülerinnen und Schüler verhalten sich vorsichtiger, vermeiden bestimmte Reaktionen und erleben Pausen weniger entspannt. Konflikte können weniger sichtbar werden, ohne tatsächlich gelöst zu sein.</p>
<p><b>Langfristig:</b> Ein dauerhaftes Beobachtungsgefühl kann Selbstständigkeit, Eigenverantwortung und Vertrauen beeinträchtigen. Jugendliche gewöhnen sich möglicherweise daran, Regeln nur unter Kontrolle einzuhalten, statt deren Sinn zu verstehen.</p>
<h5>C1/C2-Kopiervorlage</h5>
<p><b>Wörter:</b> der psychische Druck, der Anpassungszwang, die Selbstwahrnehmung, die Unsicherheit, die persönliche Entwicklung, das Verantwortungsbewusstsein, die Verhaltensänderung, die Fehlerkultur, die innere Einsicht, die Sanktion.</p>
<p><b>Verben und NVV:</b> Druck ausüben, sich beobachtet fühlen, das Verhalten anpassen, Unsicherheit verstärken, spontanes Verhalten hemmen, Konflikte verdrängen, aus Angst handeln, innere Einsicht fördern, soziale Entwicklung beeinträchtigen.</p>
<p><b>Argumentationskette:</b> Kameras → Beobachtungsgefühl → psychischer Druck → äußerlich angepasstes Verhalten → weniger Selbstständigkeit und schwächere persönliche Entwicklung.</p>
<p><b>Prüfungsnaher Musterabsatz:</b> Ein weiterer Nachteil der Videoüberwachung besteht darin, dass sie psychischen Druck auf Schülerinnen und Schüler ausüben kann. Jugendliche befinden sich in einer Lebensphase, in der sie lernen müssen, selbstständig zu handeln und Verantwortung zu übernehmen. Wenn sie jedoch ständig das Gefühl haben, beobachtet zu werden, passen sie ihr Verhalten möglicherweise nur aus Angst vor Kontrolle an. Dadurch entsteht zwar äußerliche Disziplin, aber nicht unbedingt innere Einsicht. Besonders problematisch ist, dass Konflikte in unbeobachtete Bereiche verlagert werden können. Langfristig kann ein solches Klima die persönliche Entwicklung und die Offenheit im Schulalltag beeinträchtigen.</p>
<p><b>Gegenargument entkräften:</b> Befürworter können darauf hinweisen, dass Kameras disziplinierend wirken. Kurzfristig kann das stimmen. Eine Schule soll jedoch nicht nur ruhiges Verhalten erzwingen, sondern jungen Menschen vermitteln, warum Regeln gelten. Kontrolle ersetzt deshalb keine pädagogische Begleitung.</p>`;
window.AAYS_VIDEO_SCHULE_NACHTEILE_LONG_PARTS[3]=`<h4>Nachteil 3: Datenschutzrisiken, Missbrauchsmöglichkeiten und zusätzlicher Kontrollaufwand</h4>
<h5>Grundidee dieses Nachteils</h5>
<p>Videoüberwachung erzeugt Bilddaten. Da es sich in Schulen überwiegend um Minderjährige handelt, sind diese Daten besonders sensibel. Jede Kamera schafft deshalb neue Verantwortung: Die Schule muss bestimmen, wer Zugriff erhält, wie lange Aufnahmen gespeichert werden, wann sie gelöscht werden und wie unbefugte Nutzung verhindert wird.</p>
<h5>Beobachtungen aus dem Alltag</h5>
<ul><li>In Schulen arbeiten Lehrkräfte, Verwaltung, technische Dienstleister und weitere externe Personen mit unterschiedlichen Zuständigkeiten.</li><li>Je mehr Kameras installiert werden, desto aufwendiger wird die sichere Verwaltung der Aufnahmen.</li><li>Ein kurzer Videoausschnitt zeigt häufig nur eine Reaktion, nicht die vorausgegangene Provokation.</li><li>Technische Systeme verursachen Kosten für Anschaffung, Wartung, Schutz und Kontrolle.</li><li>Eltern erwarten klare Informationen darüber, wie Bilddaten ihrer Kinder behandelt werden.</li></ul>
<h5>Detaillierte Erklärung</h5>
<p>Datenschutz ist kein Nebenthema. Aufnahmen müssen gespeichert, geschützt, ausgewertet und rechtlich korrekt gelöscht werden. Die Schule muss Zugriffsrechte begrenzen, Löschfristen festlegen, technische Sicherheitsmaßnahmen organisieren und nachvollziehbar dokumentieren, warum eine Aufnahme angesehen wurde. Fehlen Personal, Zeit oder Fachwissen, können Fehler entstehen. Eine Maßnahme, die Sicherheit verspricht, wird dann selbst zu einem organisatorischen Risiko.</p>
<p>Ein besonderes Problem ist die Fehlinterpretation. Ein Video zeigt einen begrenzten Bildausschnitt und enthält nicht automatisch alle Ursachen eines Konflikts. Es kann beispielsweise zeigen, wie ein Schüler laut reagiert, ohne die vorherige Beleidigung zu erfassen. Wird eine solche Szene aus dem Zusammenhang gerissen, kann eine ungerechte Bewertung entstehen. Aufnahmen ersetzen deshalb weder Zeugenaussagen noch Gespräche und müssen immer im Kontext geprüft werden.</p>
<p>Auch Missbrauchsmöglichkeiten dürfen nicht unterschätzt werden. Eine peinliche Szene muss nicht öffentlich im Internet erscheinen, um Schaden anzurichten. Schon eine unangemessene interne Weitergabe oder der Zugriff einer nicht berechtigten Person kann das Vertrauen von Lernenden und Eltern beschädigen. Gerade Minderjährige können sich gegen solche Folgen nur begrenzt schützen.</p>
<p>Hinzu kommt der finanzielle und organisatorische Aufwand. Kameras müssen angeschafft, installiert, gewartet und vor unbefugtem Zugriff geschützt werden. Externe Dienstleister können zusätzliche Datenschutzfragen erzeugen. Geld und Personal, die für Technik und Verwaltung eingesetzt werden, fehlen möglicherweise bei Schulsozialarbeit, Präventionsprojekten, Aufsichtspersonal oder Beratungsangeboten.</p>
<h5>Konkrete Beispiele</h5>
<ul><li>Eine Aufnahme zeigt nur die Reaktion eines Lernenden und nicht die vorherige Provokation.</li><li>Eine Datei wird länger als notwendig gespeichert, weil keine klare Löschfrist umgesetzt wurde.</li><li>Ein technischer Dienstleister erhält Zugang zum System, ohne dass alle Zuständigkeiten transparent erklärt sind.</li><li>Mehrere Personen sehen eine peinliche Szene und sprechen später darüber, obwohl keine Veröffentlichung stattgefunden hat.</li><li>Die Schule investiert in Kameras, besitzt aber zu wenig Personal für Prävention und persönliche Gespräche.</li></ul>
<h5>Ergebnisse und Risiken</h5>
<ul><li>Der organisatorische Kontrollaufwand steigt.</li><li>Unbefugter Zugriff oder unangemessene Weitergabe können Vertrauen zerstören.</li><li>Aufnahmen können ohne Kontext falsch bewertet werden.</li><li>Technik, Wartung und Verwaltung binden finanzielle Ressourcen.</li><li>Ein falsches Sicherheitsgefühl kann entstehen, obwohl pädagogische Ursachen ungelöst bleiben.</li></ul>
<h5>Kurz- und Langzeitwirkungen</h5>
<p><b>Kurzfristig:</b> Zugriffsrechte, Speicherfristen, Zuständigkeiten und technische Sicherheit müssen sofort geklärt werden. Fehler oder unvollständige Informationen können Konflikte mit Eltern und Lernenden auslösen.</p>
<p><b>Langfristig:</b> Datenschutzverstöße können das Vertrauen nachhaltig beschädigen. Die Schule wird organisatorisch belastet, während Mittel für pädagogische Alternativen fehlen. Eine technische Sicherheitslogik kann dadurch schrittweise persönliche und präventive Lösungen verdrängen.</p>
<h5>C1/C2-Kopiervorlage</h5>
<p><b>Wörter:</b> der Datenschutz, die Bilddaten, der Zugriff, die Speicherung, die Löschfrist, die Zuständigkeit, der Kontrollaufwand, die Missbrauchsgefahr, die Fehlinterpretation, der technische Dienstleister, die Wartung, die Anschaffungskosten.</p>
<p><b>Verben und NVV:</b> Daten speichern, Aufnahmen auswerten, Zugriff gewähren, Zugriff beschränken, Löschfristen festlegen, Missbrauch verhindern, Kosten verursachen, Verantwortung tragen, eine Situation aus dem Zusammenhang reißen, Vertrauen beschädigen, Ressourcen binden.</p>
<p><b>Argumentationskette:</b> Kameras → sensible Bilddaten → Zugriff und Speicherung → Datenschutz- und Missbrauchsrisiken → organisatorischer Aufwand und möglicher Vertrauensverlust.</p>
<p><b>Prüfungsnaher Musterabsatz:</b> Ein dritter Nachteil liegt in den Datenschutzrisiken und im zusätzlichen Kontrollaufwand. Kameras erzeugen sensible Bilddaten, und gerade bei Minderjährigen muss genau geregelt werden, wer diese Aufnahmen sehen darf und wann sie gelöscht werden. Wenn Zuständigkeiten unklar sind oder das System nicht ausreichend geschützt wird, kann das Vertrauen von Eltern und Lernenden beschädigt werden. Außerdem zeigt ein Video häufig nur einen Ausschnitt. Ohne den vollständigen Zusammenhang kann ein Verhalten falsch interpretiert werden. Hinzu kommen Kosten für Anschaffung, Wartung und Verwaltung. Videoüberwachung ist deshalb nicht nur eine Sicherheitsmaßnahme, sondern auch eine organisatorische Belastung.</p>
<p><b>Gegenargument entkräften:</b> Aufnahmen können bei einzelnen Vorfällen helfen. Trotzdem muss geprüft werden, ob dieser Nutzen den dauerhaften Umgang mit sensiblen Daten rechtfertigt. Aufklärung, Datenschutz, Kontext und Verhältnismäßigkeit müssen gleich ernst genommen werden.</p>`;
window.AAYS_VIDEO_SCHULE_NACHTEILE_LONG_PARTS[4]=`<h4>Allgemeine C1/C2-Kopiervorlage und Erörterungshilfe</h4>
<p><b>Zentrale Wörter:</b> die Privatsphäre, das Vertrauensverhältnis, der geschützte Lernraum, die Verhältnismäßigkeit, der psychische Druck, der Anpassungszwang, die persönliche Entwicklung, die Fehlerkultur, der Datenschutz, die Bilddaten, der unbefugte Zugriff, die Löschfrist, der Kontrollaufwand, das Schulklima, die pädagogische Verantwortung, die Missbrauchsgefahr.</p>
<p><b>Starke Verbindungen:</b> in die Privatsphäre eingreifen, das Vertrauen beeinträchtigen, psychischen Druck ausüben, das Verhalten anpassen, spontane Reaktionen hemmen, Verantwortung übernehmen, Datenschutz gewährleisten, Aufnahmen speichern, Zugriff beschränken, Kosten verursachen, Ressourcen binden, Konflikte pädagogisch bearbeiten, eine Maßnahme kritisch hinterfragen.</p>
<h5>Einleitungssätze</h5>
<ul><li>In den letzten Jahren wird immer häufiger darüber diskutiert, ob Schulen durch Videoüberwachung sicherer gemacht werden sollten.</li><li>Da Schulen nicht nur Lernorte, sondern auch soziale Lebensräume sind, ist der Einsatz von Kameras besonders umstritten.</li><li>Auf den ersten Blick scheint Videoüberwachung eine einfache Lösung zu sein; bei genauerer Betrachtung zeigt sich jedoch, dass sie erhebliche Nachteile mit sich bringen kann.</li><li>Die Streitfrage berührt nicht nur Sicherheit, sondern auch Privatsphäre, Vertrauen und pädagogische Verantwortung.</li></ul>
<h5>Übergänge</h5>
<ul><li>Neben dem Eingriff in die Privatsphäre spielt auch der psychische Druck eine wichtige Rolle.</li><li>Darüber hinaus darf nicht übersehen werden, dass Videoüberwachung neue Datenschutzfragen aufwirft.</li><li>Ein weiterer häufig unterschätzter Aspekt betrifft die langfristige Wirkung auf das Schulklima.</li><li>Damit verbunden ist die Frage, ob technische Kontrolle pädagogische Arbeit ersetzen kann.</li></ul>
<h5>Schlussbausteine</h5>
<ul><li>Zusammenfassend lässt sich sagen, dass Videoüberwachung zwar Sicherheit versprechen kann, aber zugleich erhebliche Nachteile mit sich bringt.</li><li>Besonders problematisch sind der Eingriff in die Privatsphäre, der psychische Druck und der Umgang mit sensiblen Bilddaten.</li><li>Eine Schule sollte zuerst mildere Mittel wie mehr Aufsicht, klare Kommunikation und Schulsozialarbeit prüfen.</li><li>Eine sichere Schule entsteht nicht nur durch Kameras, sondern vor allem durch Vertrauen, Verantwortung und ein gutes Miteinander.</li></ul>
<h5>Absatzbau</h5>
<ol><li><b>Behauptung:</b> Nachteil klar nennen.</li><li><b>Erklärung:</b> Bedeutung für den Schulalltag erläutern.</li><li><b>Beispiel:</b> Einen konkreten Ort oder Vorfall nennen.</li><li><b>Folge:</b> Kurz- oder langfristige Wirkung beschreiben.</li><li><b>Bewertung:</b> Pädagogische oder gesellschaftliche Bedeutung herausstellen.</li></ol>
<p><b>Prüfungsstarke Kurzsätze:</b> Sicherheit darf nicht zur Dauerbeobachtung werden. · Eine Kamera kann dokumentieren, aber keine pädagogische Beziehung ersetzen. · Schülerinnen und Schüler brauchen Vertrauen, nicht nur Kontrolle. · Mehr Überwachung bedeutet auch mehr Verantwortung. · Ein gutes Schulklima entsteht durch Kommunikation, nicht durch ständige Aufzeichnung.</p>`;
window.AAYS_VIDEO_SCHULE_NACHTEILE_LONG_PARTS[5]=`<h4>Vollständige Muster-Erörterung: nur Nachteile</h4>
<p>In vielen Schulen wird darüber nachgedacht, ob Videoüberwachung zu mehr Sicherheit beitragen kann. Auf den ersten Blick wirkt diese Maßnahme praktisch, weil Konflikte, Diebstähle oder fremde Personen möglicherweise schneller erkannt werden. Trotzdem muss sorgfältig geprüft werden, ob Kameras in einem pädagogischen Umfeld wirklich angemessen sind. Schulen sind nicht nur Orte der Ordnung, sondern auch Räume des Lernens, der persönlichen Entwicklung und des Vertrauens. Aus diesem Grund bringt Videoüberwachung mehrere ernst zu nehmende Nachteile mit sich.</p>
<p>Ein erster wichtiger Nachteil besteht darin, dass Videoüberwachung in die Privatsphäre der Schülerinnen und Schüler eingreifen kann. Jugendliche verbringen einen großen Teil ihres Alltags in der Schule. Sie sprechen in Pausen mit Freunden, lösen Konflikte, machen Fehler und erleben persönliche Situationen. Wenn diese Momente durch Kameras erfasst werden, verändert sich der Charakter des Schulraums. Die Schule wirkt dann weniger wie ein geschützter Lernort und stärker wie ein kontrollierter Bereich. Zwar ist Sicherheit ein berechtigtes Ziel, doch darf sie nicht dazu führen, dass junge Menschen sich ständig beobachtet oder grundsätzlich verdächtigt fühlen. Langfristig kann dadurch das Vertrauen zwischen Schule und Lernenden geschwächt werden.</p>
<p>Darüber hinaus kann Videoüberwachung psychischen Druck erzeugen. Viele Schülerinnen und Schüler achten ohnehin stark darauf, wie andere sie wahrnehmen. Wenn zusätzlich Kameras installiert sind, kann dieses Gefühl der Bewertung noch stärker werden. Jugendliche passen ihr Verhalten dann möglicherweise nur äußerlich an, weil sie Angst vor Kontrolle haben. Das bedeutet jedoch nicht, dass sie Verantwortung übernehmen oder Regeln wirklich verstehen. Eine Schule sollte nicht nur Disziplin erzwingen, sondern Selbstständigkeit und innere Einsicht fördern. Wenn Konflikte lediglich in unbeobachtete Bereiche verschoben werden, ist pädagogisch wenig gewonnen.</p>
<p>Ein weiterer problematischer Punkt betrifft den Datenschutz. Kameras erzeugen sensible Bilddaten, und gerade bei Minderjährigen muss sehr genau geregelt werden, wer Zugriff auf diese Aufnahmen hat. Auch Löschfristen, technische Sicherheit und Zuständigkeiten müssen klar sein. Wenn Aufnahmen falsch verwendet oder ohne vollständigen Zusammenhang betrachtet werden, können Schülerinnen und Schüler ungerecht beurteilt werden. Ein Video kann eine Reaktion zeigen, ohne die vorherige Provokation zu erfassen. Deshalb darf eine Aufnahme niemals automatisch als vollständige Wahrheit behandelt werden.</p>
<p>Hinzu kommt, dass Kameras Kosten verursachen und organisatorische Ressourcen binden. Die Systeme müssen angeschafft, gewartet und geschützt werden. Mitarbeitende müssen Zugriffe dokumentieren und Speicherfristen kontrollieren. Dieses Geld und diese Aufmerksamkeit könnten stattdessen in Schulsozialarbeit, mehr Aufsichtspersonal, Beratungsangebote oder Präventionsprojekte investiert werden. Technische Kontrolle kann daher pädagogisch sinnvollere Maßnahmen verdrängen.</p>
<p>Zusammenfassend lässt sich sagen, dass Videoüberwachung in der Schule zwar Sicherheit versprechen kann, aber erhebliche Nachteile mit sich bringt. Sie kann die Privatsphäre einschränken, psychischen Druck erzeugen und neue Datenschutzprobleme schaffen. Aus meiner Sicht sollte eine Schule zuerst auf Vertrauen, klare Regeln, persönliche Gespräche, mehr Aufsicht und pädagogische Prävention setzen. Eine sichere Schule entsteht nicht allein durch Kameras, sondern vor allem durch ein respektvolles und verantwortungsbewusstes Miteinander.</p>`;
window.AAYS_VIDEO_SCHULE_NACHTEILE_LONG_PARTS[6]=`<h4>Prüfungsnahe Musterstruktur und letzte Kontrolle</h4>
<ul><li><b>Einleitung:</b> Thema nennen, Aktualität zeigen und die Streitfrage formulieren.</li><li><b>Nachteil 1:</b> Privatsphäre, geschützten Lernraum und Vertrauensverlust erklären.</li><li><b>Nachteil 2:</b> psychischen Druck, Anpassungszwang und pädagogische Wirkung darstellen.</li><li><b>Nachteil 3:</b> Datenschutzrisiken, Fehlinterpretation, Missbrauch und Kontrollaufwand erläutern.</li><li><b>Schluss:</b> abwägend formulieren und eine klare Position einnehmen.</li></ul>
<h5>Letzte Checkliste</h5>
<ul><li>Wurde ausschließlich die Nachteilsseite behandelt?</li><li>Sind Privatsphäre, psychischer Druck und Datenschutz klar voneinander getrennt?</li><li>Enthält jeder Hauptabsatz Erklärung, Beispiel, Folge und Bewertung?</li><li>Wurden absolute Aussagen vermieden und Formulierungen wie „kann“, „möglicherweise“ und „unter bestimmten Bedingungen“ verwendet?</li><li>Wurden mildere pädagogische Mittel genannt, ohne Vorteile und Nachteile im selben Button zu vermischen?</li></ul>
<p><b>Abschließender Merksatz:</b> Eine sichere Schule braucht nicht nur Schutz, sondern auch Privatsphäre, Vertrauen, pädagogische Nähe und einen verantwortungsvollen Umgang mit sensiblen Daten.</p>`;
if(window.AAYS_VIDEO_SCHULE_NACHTEILE_BUILD)window.AAYS_VIDEO_SCHULE_NACHTEILE_BUILD();
if(window.DEUTSCH_LESSONS&&window.DEUTSCH_LESSONS.t_video_schule_nachteile){window.DEUTSCH_LESSONS.t_video_schule_nachteile.minimumWords='2000+';window.DEUTSCH_LESSONS.t_video_schule_nachteile.longSourceVerified=true;window.DEUTSCH_LESSONS.t_video_schule_nachteile.source='Videoueberwachung_in_der_Schule_Nachteile_C1C2(6).docx';window.DEUTSCH_LESSONS.t_video_schule_nachteile.formatVerified='Genel bakış / Öncelikli kavramlar / Konu açıklaması / Nachteile';}
if(window.DEUTSCH_TESTS&&window.DEUTSCH_TESTS.t_video_schule_nachteile){window.DEUTSCH_TESTS.t_video_schule_nachteile.source='Videoueberwachung_in_der_Schule_Nachteile_C1C2(6).docx';}
window.AAYS_VIDEO_SCHULE_NACHTEILE_TEMPLATE_FORM_V6_OK=true;
