(function(){
'use strict';
var key='sf2_8';
var source='8. Sprach Fehlern.docx';
window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};
window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};
var LONG=[
`<h3>Schreiben_fehler_8 · E-Books, Massentourismus und Alltagserleichterung</h3>`,
`<p><b>Niveau:</b> C1/C2 · Präpositionen · Rektion · Nominalstil · Nomen-Verb-Verbindungen · prüfungstaugliche Formulierungen</p>`,
`<h4>1. Ziel des Kapitels</h4>`,
`<p>Dieses Kapitel trainiert typische Fehler, die in argumentativen Texten zu E-Books, Massentourismus, Umweltbelastung und Alltagserleichterung auftreten. Der Schwerpunkt liegt nicht auf isolierten Einzelkorrekturen, sondern auf übertragbaren Ausdrucksmustern, die in Prüfungsaufsätzen mehrfach verwendet werden können. Besonders wichtig sind präzise Präpositionen, feste Rektion, idiomatische Nomen-Verb-Verbindungen, kontrollierter Nominalstil und die Vermeidung unnötiger Wiederholungen.</p>`,
`<p>Auf C1/C2-Niveau muss ein Text nicht nur verständlich, sondern auch strukturell sauber und stilistisch angemessen sein. Ein Satz wie <i>Massentourismus beeinflusst die Umweltbelastung</i> bleibt zu ungenau, weil nicht klar wird, ob die Belastung steigt, sinkt oder sich verlagert. Präziser ist: <i>Massentourismus kann die Umwelt erheblich belasten</i> oder <i>Die Umweltbelastung nimmt durch Massentourismus zu</i>. Genau diese Art der sprachlichen Präzisierung steht im Zentrum dieses Moduls.</p>`,
`<h4>2. Ursachen, Mittel und Wirkungen: durch, bei, aufgrund, zu</h4>`,
`<p>Viele Fehler entstehen, weil im Deutschen sorgfältig zwischen Ursache, Mittel, Begleitumstand und Folge unterschieden wird. <b>Durch + Akkusativ</b> markiert häufig ein Mittel oder eine Ursache: <i>Durch Tourismuseinnahmen können Kommunen ihre Infrastruktur ausbauen.</i> Ebenso: <i>Durch günstigere Reisemöglichkeiten können auch Menschen mit begrenzten finanziellen Möglichkeiten andere Länder besuchen.</i> Wenn eine verkürzte Zubereitungszeit als Ursache einer Entlastung gemeint ist, lautet die Struktur: <i>Durch die verkürzte Zubereitungszeit kann der zeitliche Aufwand verringert werden.</i></p>`,
`<p><b>Bei + Dativ</b> bezeichnet dagegen eher eine Situation, eine Tätigkeit oder einen Begleitumstand: <i>Bei längerem Lesen am Bildschirm können Augenbeschwerden auftreten.</i> <i>Bei intensiver Bildschirmnutzung kann die Konzentration nachlassen.</i> <i>Bei steigender Nachfrage geraten lokale Ressourcen stärker unter Druck.</i> Der Unterschied zwischen <b>durch</b> und <b>bei</b> ist zentral: <b>durch</b> erklärt, wodurch etwas geschieht; <b>bei</b> beschreibt, in welchem Kontext etwas geschieht.</p>`,
`<p>Für Folgen eignet sich häufig <b>zu + Dativ führen</b>: <i>Massentourismus kann zu höheren CO2-Emissionen führen.</i> <i>Lange Bildschirmzeiten können zu gesundheitlichen Beschwerden führen.</i> Für positive Beiträge verwendet man <b>zu + Dativ beitragen</b>: <i>Die verkürzte Zubereitungszeit kann zu einer geringeren Alltagsbelastung beitragen.</i> Diese Strukturen sind präzise, prüfungstauglich und deutlich idiomatischer als direkte Übersetzungen mit allgemeinen Verben.</p>`,
`<h4>3. E-Books und gesundheitliche Belastungen</h4>`,
`<p>Ein typischer Fehler besteht darin, den Oberbegriff zu wiederholen: <i>negative Auswirkungen auf die Gesundheit haben, weil es negative Auswirkungen auf die Gesundheit hat</i>. C1/C2-Stil verlangt eine Konkretisierung. Man schreibt besser: <i>Ein wesentlicher Nachteil digitaler Lektüre besteht in möglichen gesundheitlichen Belastungen.</i> Danach muss die Wirkung konkretisiert werden: <i>Langes Schauen auf den Bildschirm kann trockene und brennende Augen, Konzentrationsprobleme und Ermüdungserscheinungen verursachen.</i></p>`,
`<p>Wichtig ist auch die Unterscheidung zwischen <b>Lesen</b> und <b>Lesung</b>. <b>Lesung</b> bezeichnet meist eine öffentliche Buchvorlesung, während <b>Lesen</b> die Tätigkeit meint. Korrekt ist also: <i>Bei längerem Lesen auf digitalen Geräten können trockene Augen auftreten.</i> Nach <b>verursachen</b> steht ein Akkusativobjekt: <i>Langes Lesen kann trockene und brennende Augen verursachen.</i> Nicht korrekt wäre eine Form mit falsch gebeugtem Adjektiv oder unklarem Objekt.</p>`,
`<p>Für die Wirkungsanalyse ist <b>sich auf + Akkusativ auswirken</b> besonders wichtig: <i>Eine dauerhaft hohe Bildschirmzeit kann sich negativ auf die Sehkraft auswirken.</i> Das Verb ist reflexiv und trennbar. In einem Hauptsatz steht die Verbpartikel am Ende: <i>Die Bildschirmnutzung wirkt sich auf die Konzentration aus.</i> Diese Struktur ist präziser als ein allgemeines <i>beeinflussen</i>, wenn eine konkrete Wirkung auf einen Bereich beschrieben wird.</p>`,
`<h4>4. Massentourismus und wirtschaftliche Vorteile</h4>`,
`<p>Im wirtschaftlichen Kontext des Massentourismus ist <b>Tourismuseinnahmen generieren</b> eine zentrale Nomen-Verb-Verbindung. Ein C1/C2-Satz lautet: <i>Ein zentrales Argument zugunsten des Massentourismus besteht darin, dass er erhebliche Tourismuseinnahmen generieren kann.</i> Diese Einnahmen können Kommunen in die Lage versetzen, Infrastruktur auszubauen, öffentliche Dienstleistungen zu verbessern und lokale Betriebe zu stärken.</p>`,
`<p>Bei Infrastruktur verwendet man im Deutschen meistens <b>ausbauen</b>, <b>modernisieren</b>, <b>verbessern</b> oder <b>finanzieren</b>. Die Formulierung <i>Verkehrsinfrastruktur entwickeln</i> wirkt weniger idiomatisch, wenn es um konkrete Straßen, öffentliche Verkehrsmittel oder touristische Einrichtungen geht. Korrekt ist: <i>Durch Tourismuseinnahmen können Städte ihre Verkehrsinfrastruktur ausbauen.</i> Ebenso: <i>Diese Mittel können in den Ausbau öffentlicher Verkehrssysteme investiert werden.</i></p>`,
`<p>Für Nutznießer verwendet man <b>profitieren von + Dativ</b>: <i>Von dieser Einnahmequelle profitieren nicht nur Hotelketten, sondern auch lokale Betriebe.</i> Die Struktur <b>nicht nur ..., sondern auch ...</b> verlangt Parallelität. Beide Teile müssen dieselbe syntaktische Funktion erfüllen. Besonders flüssig ist die Variante mit vorangestelltem Prädikat: <i>Von dieser Einnahmequelle profitieren nicht nur große Hotelketten, sondern auch Restaurants, Cafes und Souvenirläden.</i></p>`,
`<h4>5. Massentourismus und ökologische Belastung</h4>`,
`<p>Für ökologische Nachteile sind präzise Folge- und Belastungsstrukturen notwendig. Man schreibt nicht: <i>das Niveau der CO2-Emissionen erhöhen</i>, sondern idiomatischer: <i>zu höheren CO2-Emissionen führen</i> oder <i>zusätzliche CO2-Emissionen verursachen</i>. Beispiel: <i>Massentourismus kann langfristig zu höheren CO2-Emissionen führen, insbesondere wenn Flugreisen, Hotelanlagen und lokale Verkehrswege stark zunehmen.</i></p>`,
`<p>Wenn räumliche Verdichtung gemeint ist, lautet die feste Wendung <b>auf engem Raum</b>: <i>Wenn viele Hotels auf engem Raum entstehen, steigt der Ressourcenverbrauch erheblich.</i> Nicht idiomatisch ist <i>in einem kleinen Raum</i>, wenn kein einzelner Innenraum gemeint ist. Im touristischen Kontext beschreibt <b>auf engem Raum</b> die Verdichtung von Hotels, Verkehrswegen, Restaurants und touristischen Einrichtungen in einer begrenzten Region.</p>`,
`<p>Unklare Formulierungen wie <i>die Umweltbelastung wird beeinflusst</i> sollten durch konkrete Verben ersetzt werden: <b>zunehmen</b>, <b>steigen</b>, <b>die Umwelt belasten</b>, <b>den Ressourcenverbrauch erhöhen</b>, <b>ein Problem verschärfen</b>. Ein Musterabsatz lautet: <i>Dies ist problematisch, weil Massentourismus auf engem Raum ähnliche Folgen wie eine Fabrik haben kann: Er führt zu hohem Ressourcenverbrauch, steigert den Wasser- und Energiebedarf und kann dadurch zu höheren CO2-Emissionen beitragen.</i></p>`,
`<h4>6. Fertiggerichte, Mikrowelle und Alltagserleichterung</h4>`,
`<p>Beim Thema schnelle Mahlzeiten und Alltagserleichterung sind Zeitangaben und Gerätepräpositionen wichtig. Man schreibt <b>in zehn Minuten</b> oder <b>innerhalb von zehn Minuten</b>, nicht <i>im zehn Minuten</i>. Bei Geräten als Ort der Zubereitung verwendet man <b>in der Mikrowelle</b>, <b>im Ofen</b> oder <b>auf dem Herd</b>. Ein korrekter Satz lautet: <i>Viele Fertiggerichte lassen sich innerhalb von zehn Minuten in der Mikrowelle erwärmen.</i></p>`,
`<p>Der Vorteil solcher Mahlzeiten besteht häufig <b>in der verkürzten Zubereitungszeit</b>. Das Muster <b>bestehen in + Dativ</b> beschreibt den Kern eines Vorteils oder Nachteils: <i>Ein praktischer Vorteil schnell zubereiteter Mahlzeiten besteht in der verkürzten Zubereitungszeit.</i> Die Folge kann mit <b>zu + Dativ beitragen</b> formuliert werden: <i>Dies kann zu einer geringeren zeitlichen Belastung im Alltag beitragen.</i></p>`,
`<p>Gleichzeitig sollte die Entlastung nicht isoliert betrachtet werden. Ein C1/C2-Satz lautet: <i>Dennoch sollte diese Entlastung nicht isoliert betrachtet werden, weil auch die Qualität und Ausgewogenheit der Ernährung eine zentrale Rolle spielt.</i> Dadurch wird der Vorteil sprachlich anerkannt, aber argumentativ eingeordnet.</p>`,
`<h4>7. Nomen-Verb-Verbindungen und Funktionsverbgefüge</h4>`,
`<p>Nomen-Verb-Verbindungen machen einen Text nicht automatisch besser. Sie sind nur dann sinnvoll, wenn sie präziser, wissenschaftlicher oder strukturell klarer sind als ein einfaches Verb. Wichtige Muster sind <b>Beschwerden verursachen</b>, <b>Auswirkungen auf etwas haben</b>, <b>zu Beschwerden führen</b>, <b>eine Belastung verringern</b>, <b>zu einer Entlastung beitragen</b>, <b>Einnahmen generieren</b>, <b>Infrastruktur ausbauen</b>, <b>von einer Einnahmequelle profitieren</b>, <b>Investitionen ermöglichen</b>, <b>die Lebensqualität beeinträchtigen</b>, <b>den Ressourcenverbrauch erhöhen</b>, <b>die Umwelt erheblich belasten</b>, <b>CO2-Emissionen verursachen</b> und <b>ein Problem verschärfen</b>.</p>`,
`<p>Besonders nützlich sind auch <b>in den Vordergrund rücken</b>, <b>unter Druck geraten</b>, <b>eine zentrale Rolle spielen</b>, <b>eine Entwicklung begünstigen</b>, <b>einen Beitrag leisten</b> und <b>eine Alternative darstellen</b>. Beispiele: <i>Die Frage der Nachhaltigkeit rückt im Tourismus zunehmend in den Vordergrund.</i> <i>Lokale Ressourcen können durch hohe Besucherzahlen unter Druck geraten.</i> <i>E-Books stellen eine Alternative zu gedruckten Büchern dar.</i></p>`,
`<h4>8. Satzbau für C1/C2</h4>`,
`<p>Ein häufiger Fehler besteht darin, einen weil-Satz allein stehen zu lassen. Korrekt ist entweder: <i>Dies ist problematisch, weil Massentourismus zu einem steigenden Ressourcenverbrauch führen kann.</i> Oder: <i>Weil Massentourismus zu einem steigenden Ressourcenverbrauch führen kann, sollte er kritisch bewertet werden.</i> Der Nebensatz braucht eine Verbindung zum Hauptsatz, und das finite Verb steht im Nebensatz am Ende.</p>`,
`<p>Weitere sichere Muster sind: <b>Ein wesentlicher Vorteil/Nachteil besteht in + Dativ</b>, <b>Kurzfristig kann ... dazu führen, dass ...</b>, <b>Durch + Akkusativ können ...</b>, <b>Bei + Dativ können ... auftreten</b>, <b>Von ... profitieren nicht nur ..., sondern auch ...</b>, <b>Daraus lässt sich ableiten, dass ...</b>, <b>Infolgedessen kann es zu + Dativ kommen</b> und <b>Aus dieser Entwicklung ergeben sich ...</b>. Diese Strukturen ordnen Argumente klar und verhindern bruchstückhafte Sätze.</p>`,
`<h4>9. Musterabsätze</h4>`,
`<p><b>E-Books:</b> Ein wesentlicher Nachteil von E-Books besteht in möglichen gesundheitlichen Belastungen, die vor allem bei längerer Bildschirmnutzung auftreten können. Da Lesende über längere Zeit auf ein Display schauen, können trockene und brennende Augen, Konzentrationsprobleme sowie Ermüdungserscheinungen entstehen. Entscheidend ist dabei, die allgemeinen Auswirkungen auf die Gesundheit durch konkrete Beschwerden zu präzisieren.</p>`,
`<p><b>Massentourismus und Wirtschaft:</b> Ein zentrales Argument zugunsten des Massentourismus besteht darin, dass er erhebliche Tourismuseinnahmen generieren kann. Durch diese Einnahmen sind Städte in der Lage, ihre Verkehrsinfrastruktur auszubauen, öffentliche Dienstleistungen zu verbessern und lokale Betriebe wirtschaftlich zu stärken. Von dieser Einnahmequelle profitieren nicht nur große Hotelketten, sondern auch Restaurants, Cafes und Souvenirläden.</p>`,
`<p><b>Massentourismus und Umwelt:</b> Dies ist problematisch, weil Massentourismus auf engem Raum ähnliche Folgen wie eine Fabrik haben kann. Er führt zu hohem Ressourcenverbrauch, steigert den Wasser- und Energiebedarf und kann dadurch zu höheren CO2-Emissionen beitragen. Daher sollte Massentourismus nicht nur unter wirtschaftlichen, sondern auch unter ökologischen Gesichtspunkten bewertet werden.</p>`,
`<p><b>Alltagserleichterung:</b> Ein praktischer Vorteil schnell zubereiteter Mahlzeiten liegt in der verkürzten Zubereitungszeit. Viele Gerichte lassen sich innerhalb von zehn Minuten in der Mikrowelle erwärmen, wodurch der zeitliche Aufwand im Alltag erheblich verringert werden kann. Dennoch sollte diese Entlastung im Zusammenhang mit Ernährungsqualität und langfristiger Gesundheit betrachtet werden.</p>`,
`<h4>10. Schreibkontrolle</h4>`,
`<p>Vor der Abgabe sollte geprüft werden: Wurde bei Ursachen und Mitteln <b>durch + Akkusativ</b> verwendet? Steht bei Situationen und Tätigkeiten <b>bei + Dativ</b>? Wurden Folgen mit <b>zu + Dativ führen</b> oder <b>zu + Dativ beitragen</b> korrekt formuliert? Wurde <b>sich auf + Akkusativ auswirken</b> richtig eingesetzt? Wurden unklare Verben wie <i>beeinflussen</i> durch präzisere Verben ersetzt? Ist die Struktur <b>nicht nur ..., sondern auch ...</b> parallel? Sind Zeitangaben wie <b>in zehn Minuten</b> und Geräteangaben wie <b>in der Mikrowelle</b> korrekt?</p>`
].join('');
var P=[
['durch Tourismuseinnahmen','durch + Akkusativ','___ Tourismuseinnahmen können Städte ihre Infrastruktur ausbauen.','Durch','Mittel oder Ursache'],
['bei längerem Lesen','bei + Dativ','___ längerem Lesen am Bildschirm können Augenbeschwerden auftreten.','Bei','Tätigkeit oder Situation'],
['zu höheren CO2-Emissionen führen','führen zu + Dativ','Massentourismus kann ___ höheren CO2-Emissionen führen.','zu','Folge'],
['auf engem Raum','feste Wendung','Viele Hotels entstehen ___ engem Raum.','auf','räumliche Verdichtung'],
['in der Mikrowelle','in + Dativ','Das Essen wird ___ der Mikrowelle erwärmt.','in','Gerät als Ort'],
['innerhalb von zehn Minuten','innerhalb von + Dativ','Eine Mahlzeit lässt sich ___ zehn Minuten zubereiten.','innerhalb von','zeitlicher Rahmen'],
['von dieser Einnahmequelle profitieren','profitieren von + Dativ','Lokale Betriebe profitieren ___ dieser Einnahmequelle.','von','Nutzen'],
['sich auf die Lebensqualität auswirken','sich auf + Akkusativ auswirken','Der Tourismus wirkt sich ___ die Lebensqualität aus.','auf','Wirkungsbereich'],
['auf digitale Inhalte zugreifen','zugreifen auf + Akkusativ','Lesende können jederzeit ___ digitale Inhalte zugreifen.','auf','digitaler Zugriff'],
['Beschwerden verursachen','verursachen + Akkusativ','Langes Lesen kann trockene und brennende Augen ___.','verursachen','direkte Wirkung'],
['Infrastruktur ausbauen','ausbauen + Akkusativ','Städte können ihre Verkehrsinfrastruktur ___.','ausbauen','idiomatische Kollokation'],
['eine Belastung verringern','verringern + Akkusativ','Schnelle Mahlzeiten können die zeitliche Belastung ___.','verringern','Reduktion'],
['Einnahmen generieren','NVV','Tourismus kann erhebliche Einnahmen ___.','generieren','wirtschaftliche Wirkung'],
['eine Alternative darstellen','NVV','E-Books können eine Alternative zu gedruckten Büchern ___.','darstellen','Definition'],
['in den Vordergrund rücken','NVV','Die Frage der Nachhaltigkeit rückt zunehmend ___ den Vordergrund.','in','Fokusstruktur'],
['unter Druck geraten','feste Verbindung','Lokale Ressourcen können durch hohe Besucherzahlen unter Druck ___.','geraten','Belastung']
];
var MC=[
['Welche Form ist korrekt?',['Bei längerem Lesen können Augenbeschwerden auftreten.','Bei der langedauernden Lesung können Beschwerden auftreten.','In der langen Lesung treten Beschwerden auf.','Durch Lesung entstehen Augen trocken.'],0,'Lesen statt Lesung'],
['Welche Präposition markiert Ursache oder Mittel?',['durch Tourismuseinnahmen','bei Tourismuseinnahmen','auf Tourismuseinnahmen','in Tourismuseinnahmen'],0,'durch + Akkusativ'],
['Welche Kollokation ist idiomatisch?',['die Verkehrsinfrastruktur ausbauen','die Verkehrsinfrastruktur entwickeln','die Verkehrsinfrastruktur machen','die Verkehrsinfrastruktur einstellen'],0,'Infrastruktur'],
['Welche Folgekonstruktion passt?',['zu höheren CO2-Emissionen führen','auf höhere CO2-Emissionen machen','höhere CO2-Emissionen entwickeln','bei höheren CO2-Emissionen verursachen'],0,'führen zu + Dativ'],
['Welche Wendung ist korrekt?',['auf engem Raum','in einem kleinen Raum','bei engem Raum','durch engen Raum'],0,'räumliche Verdichtung'],
['Welche Geräteangabe ist korrekt?',['in der Mikrowelle','durch Mikrowelle','bei Mikrowelle','auf der Mikrowelle'],0,'Ort der Zubereitung'],
['Welche Struktur ist korrekt?',['sich auf die Lebensqualität auswirken','die Lebensqualität auswirken auf','auf der Lebensqualität auswirken','sich bei die Lebensqualität auswirken'],0,'reflexives Verb'],
['Welche NVV ist C1/C2-gerecht?',['Einnahmen generieren','Geld machen','Einnahmen bauen','Geld entwickeln'],0,'wirtschaftlicher Stil'],
['Welche Form vermeidet Wiederholung?',['gesundheitliche Beschwerden verursachen','negative Auswirkungen auf die Gesundheit negativ machen','Gesundheit Auswirkungen machen','Gesundheit negativ wiederholen'],0,'Konkretisierung'],
['Welche Parallelität ist korrekt?',['nicht nur Hotelketten, sondern auch lokale Betriebe','nicht nur Hotelketten, sondern auch profitieren lokale Betriebe','nicht nur Hotelketten profitieren, sondern auch lokale Betriebe profitieren von','nicht nur bei Hotelketten, sondern lokale Betriebe'],0,'nicht nur ... sondern auch'],
['Welche Zeitangabe passt?',['in zehn Minuten','im zehn Minuten','bei zehn Minuten','durch zehn Minuten'],0,'Zeitangabe'],
['Welche Form ist idiomatisch?',['zu einer geringeren Belastung beitragen','Auswirkungen auf eine geringere Belastung haben','eine geringere Belastung machen','Belastung kleiner entwickeln'],0,'beitragen zu + Dativ']
];
var TF=[
['Durch + Akkusativ markiert häufig Ursache, Mittel oder Vermittlung.',true,'Präposition'],
['Bei + Dativ bezeichnet häufig eine Situation oder Tätigkeit.',true,'Präposition'],
['Lesung ist die beste Bezeichnung für die allgemeine Tätigkeit des Lesens.',false,'Lexik'],
['Verursachen verlangt ein Akkusativobjekt.',true,'Valenz'],
['Infrastruktur wird häufig ausgebaut oder modernisiert.',true,'Kollokation'],
['Sich auswirken auf ist reflexiv und trennbar.',true,'Rektion'],
['Zeit benutzt man in der Regel wie ein technisches Gerät.',false,'Kollokation'],
['In der Mikrowelle ist eine korrekte Ortsangabe.',true,'Präposition'],
['Auf engem Raum ist eine feste Wendung für räumliche Verdichtung.',true,'Wendung'],
['Nicht nur ... sondern auch verlangt grammatische Parallelität.',true,'Satzbau'],
['Umweltbelastung beeinflusst wird ist präziser als die Umweltbelastung nimmt zu.',false,'Präzision'],
['E-Books können eine Alternative zu gedruckten Büchern darstellen.',true,'NVV']
];
window.DEUTSCH_TESTS[key]={category:'Schreiben Fehler 2',slug:'schreiben_fehler_8_ebooks_massentourismus_alltag',title:'Schreiben_fehler_8 · E-Books, Massentourismus und Alltagserleichterung',topic:'C1/C2 · Präpositionen · Rektion · Nominalstil · NVV/FVG',source:source,words:P.map(function(x){return x[0];}),fill:P.map(function(x){return [x[2],x[3],x[1]];}),mc:MC,tf:TF,wordMatch:P.map(function(x){return [x[0],x[4]];}),phraseMatch:[['E-Books','gesundheitliche Beschwerden verursachen'],['Massentourismus','Tourismuseinnahmen generieren'],['Kommunen','Verkehrsinfrastruktur ausbauen'],['Hotels','auf engem Raum entstehen'],['Fertiggerichte','in der Mikrowelle erwärmt werden'],['Nachhaltigkeit','in den Vordergrund rücken'],['Lokale Betriebe','von Tourismuseinnahmen profitieren'],['Bildschirmzeit','sich auf die Sehkraft auswirken']],prep:P.map(function(x){return [x[2],x[3],x[1]];}),hang:['durch Tourismuseinnahmen','bei längerem Lesen','zu höheren CO2-Emissionen führen','auf engem Raum','in der Mikrowelle','innerhalb von zehn Minuten','von dieser Einnahmequelle profitieren','sich auf die Lebensqualität auswirken','auf digitale Inhalte zugreifen','Beschwerden verursachen','Infrastruktur ausbauen','eine Belastung verringern','Einnahmen generieren','eine Alternative darstellen','in den Vordergrund rücken','unter Druck geraten']};
window.DEUTSCH_LESSONS[key]={source:source,longSourceVerified:true,short:'<h3>Schreiben_fehler_8 · Kurzüberblick</h3><p>Dieses Modul behandelt E-Books, Massentourismus und Alltagserleichterung. Trainiert werden Präpositionen, Rektion, Nominalstil, präzise Verbwahl und Nomen-Verb-Verbindungen auf C1/C2-Niveau.</p>',medium:'<h3>Schreiben_fehler_8 · Erweiterte Erklärung</h3><p>Die wichtigsten Muster sind <b>durch + Akkusativ</b>, <b>bei + Dativ</b>, <b>zu + Dativ führen</b>, <b>sich auf + Akkusativ auswirken</b>, <b>profitieren von + Dativ</b>, <b>auf etwas zugreifen</b>, <b>Infrastruktur ausbauen</b>, <b>Beschwerden verursachen</b>, <b>Einnahmen generieren</b> und <b>zu einer Entlastung beitragen</b>. Entscheidend ist, Ursache, Mittel, Situation und Folge sprachlich sauber zu unterscheiden.</p>',long:LONG};
function active(){var t=(document.getElementById('lessonTitle')||{}).textContent||'';var c=(document.getElementById('lessonContent')||{}).textContent||'';return t.indexOf('Schreiben_fehler_8')>-1||t.indexOf('Schreibfehler 8')>-1||c.indexOf('Massentourismus')>-1&&c.indexOf('Alltagserleichterung')>-1;}
function visible(){var x=document.getElementById('lesson');return !x||!/(^|\s)hide(\s|$)/.test(x.className||'');}
function render(){if(!visible()||!active())return;var title=document.getElementById('lessonTitle'),meta=document.getElementById('lessonMeta'),content=document.getElementById('lessonContent');if(title)title.textContent='Lektion: Schreiben_fehler_8 · E-Books, Massentourismus und Alltagserleichterung';if(meta)meta.textContent='Niveau: C1/C2 · Deutsch';if(content&&content.innerHTML!==LONG)content.innerHTML=LONG;}
render();setTimeout(render,200);setTimeout(render,900);setInterval(render,180);document.addEventListener('click',function(){setTimeout(render,60);setTimeout(render,240);setTimeout(render,800);},true);try{new MutationObserver(function(){setTimeout(render,30);}).observe(document.documentElement,{childList:true,subtree:true,characterData:true});}catch(e){}
window.AAYS_SF2_8_1500_DE_ONLY_OK=true;
})();