(function(){
'use strict';
window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};
var L=window.DEUTSCH_LESSONS.t51;if(!L||L.__aaysMaschinenNachteileExtraExpanded)return;
var extra=[];
extra.push('<h4>Zusätzliche 2000+ Erweiterung: Nachteile ausführlicher erklärt</h4>');
extra.push('<p><b>Nachteil 1 ausführlicher:</b> Arbeitsplatzverlust ist bei diesem Thema der wichtigste soziale Punkt. Wenn Maschinen menschliche Arbeit übernehmen, verändert sich nicht nur ein einzelner Arbeitsplatz, sondern oft die gesamte Sicherheit einer Person. Arbeit bedeutet Einkommen, Tagesstruktur, Anerkennung und Zukunftsplanung. Wenn einfache, körperliche oder wiederholende Tätigkeiten automatisiert werden, können Beschäftigte ihre berufliche Stabilität verlieren. Besonders betroffen sind Menschen, deren Aufgaben stark aus Routine bestehen, zum Beispiel in Produktion, Lager, Supermarkt, Verwaltung, Kundenservice oder einfacher Büroarbeit.</p>');
extra.push('<p>Prüfungsnah kann man diesen Gedanken so erklären: Maschinen erledigen bestimmte Aufgaben schneller und gleichmäßiger. Für Unternehmen kann dadurch der Bedarf an Personal sinken. Die Folge ist berufliche Unsicherheit. Betroffene Menschen fragen sich, ob ihre Stelle langfristig erhalten bleibt, ob sie eine neue Arbeit finden und ob ihr Einkommen stabil bleibt. Gerade gering qualifizierte Beschäftigte können stärker unter Druck geraten, weil ein schneller Wechsel in andere Berufe nicht immer möglich ist. Dadurch kann Automatisierung soziale Ungleichheit vergrößern.</p>');
extra.push('<p><b>Nachteil 2 ausführlicher:</b> Der Weiterbildungsdruck entsteht, weil technische Entwicklung viele Berufe ständig verändert. Beschäftigte müssen neue Programme, Maschinen, digitale Abläufe und Bedienoberflächen verstehen. Weiterbildung ist zwar grundsätzlich wichtig, aber sie kann im Alltag zusätzlichen Stress verursachen. Wer bereits Vollzeit arbeitet, Familie hat oder körperlich belastet ist, erlebt ständige technische Anpassung schnell als Überforderung. Besonders schwierig wird es, wenn Unternehmen neue Systeme einführen, ohne genügend Zeit, Erklärung und Unterstützung anzubieten.</p>');
extra.push('<p>Für den Aufsatz ist wichtig, die Folgen zu nennen. Ältere Beschäftigte oder Menschen mit geringer technischer Erfahrung können sich ausgeschlossen fühlen. Wer neue Programme nicht schnell genug beherrscht, hat Angst, beruflich zurückzufallen. Dadurch entsteht Anpassungsdruck. Langfristig können Unterschiede zwischen gut qualifizierten und weniger qualifizierten Menschen größer werden. Eine starke C1/C2-Formulierung lautet: Automatisierung erhöht nicht nur die Effizienz, sondern auch die Anforderungen an Beschäftigte, wodurch Lernstress, Unsicherheit und berufliche Benachteiligung entstehen können.</p>');
extra.push('<p><b>Nachteil 3 ausführlicher:</b> Technikabhängigkeit ist problematisch, weil viele Abläufe ohne funktionierende Systeme kaum noch möglich sind. Wenn Kassen, Automaten, Buchungssysteme, Verwaltungsportale oder Maschinen ausfallen, fehlen oft schnelle Alternativen. Menschen gewöhnen sich daran, dass Technik Wege zeigt, Antworten gibt, Aufgaben sortiert oder Entscheidungen vorbereitet. Dadurch kann Selbstständigkeit schwächer werden. Gleichzeitig nimmt persönlicher Kontakt ab, wenn Automaten, Chatbots und Online-Formulare direkte Gespräche ersetzen.</p>');
extra.push('<p>Gerade in Beratung, Pflege, Bildung, Verwaltung und Kundenservice ist menschlicher Kontakt wichtig. Maschinen können Informationen liefern, aber sie können Empathie, Geduld, Zwischenfragen und persönliche Einschätzung nur begrenzt ersetzen. Ein Chatbot kann eine Standardantwort geben, aber er erkennt nicht immer die besondere Situation eines Menschen. Deshalb kann eine stark technisierte Arbeitswelt schneller, aber auch unpersönlicher wirken. Prüfungsnah formuliert: Maschinen können Prozesse erleichtern, dürfen aber menschliche Kommunikation und Verantwortung nicht vollständig verdrängen.</p>');
extra.push('<p><b>Gesamtschluss 2000+:</b> Insgesamt zeigt das Thema, dass der Ersatz menschlicher Arbeit durch Maschinen nicht nur wirtschaftlich bewertet werden darf. Erstens können Arbeitsplätze verloren gehen und berufliche Sicherheit geschwächt werden. Zweitens entsteht ein dauerhafter Druck zur Weiterbildung, der besonders ältere oder weniger qualifizierte Beschäftigte belasten kann. Drittens wächst die Abhängigkeit von Technik, während persönliche Beratung und menschlicher Kontakt abnehmen können. Deshalb sollte Automatisierung sozial begleitet werden: mit fairer Weiterbildung, klarer Verantwortung und Schutz für Menschen, deren Arbeit sich durch Maschinen stark verändert.</p>');
L.long=(L.long||'')+extra.join('');
L.__aaysMaschinenNachteileExtraExpanded=true;
window.AAYS_MASCHINEN_NACHTEILE_EXTRA_EXPAND_OK=true;
window.AAYS_MASCHINEN_NACHTEILE_LONG_2000_REAL_OK=true;
})();