(function(){
  var KEY='t41';
  window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};
  window.LESSONS=window.LESSONS||{};
  var long=String.raw`
<h3>Selbstoptimierung durch Vorbilder – Nachteile · ausführlich, tabellarisch und prüfungsnah</h3>
<p><b>Quelle:</b> Selbstoptimierung_durch_Vorbilder_Nachteile_4_C1_C2_15_20(1).docx. Diese ausführliche Fassung folgt der Struktur des Word-Dokuments: kurze Orientierung, Grundthese, allgemeines Wortfeld, vier Nachteile, Satzbausteine, Musterabsätze, Kopiervorlage und Übungen. Der Text bleibt prüfungsnah und vermeidet allgemeine Füllabschnitte.</p>
<h4>1. Kurze Orientierung zum Thema</h4>
<table>
<tr><th>Begriff</th><td>Selbstoptimierung durch Vorbilder bedeutet, dass Menschen sich an Personen orientieren, die sie als erfolgreich, diszipliniert, schön, sportlich, produktiv oder bewundernswert wahrnehmen. Diese Vorbilder können aus dem persönlichen Umfeld stammen, zum Beispiel Eltern, Lehrer, ältere Geschwister, Freunde, Trainer oder Kollegen. Sie können aber auch durch soziale Medien, Werbung, Sport, Musik, Politik oder Karriereplattformen sichtbar werden.</td></tr>
<tr><th>Problem im Nachteilsaufsatz</th><td>In einem Nachteilsaufsatz geht es nicht darum, Vorbilder pauschal schlecht darzustellen. Der zentrale Punkt ist, dass Vorbilder problematisch werden, wenn Menschen sie unkritisch zum Maßstab machen. Dann entsteht nicht Orientierung, sondern Druck. Besonders Jugendliche und junge Erwachsene vergleichen ihr normales Leben mit idealisierten Bildern anderer Personen.</td></tr>
<tr><th>Grundthese</th><td>Selbstoptimierung durch Vorbilder kann zwar motivierend wirken, führt jedoch häufig zu Vergleichsdruck, unrealistischen Erwartungen, Verlust der eigenen Individualität und einer Abhängigkeit von äußerer Anerkennung.</td></tr>
<tr><th>Prüfungsformel</th><td>Beobachtung → Erklärung → Beispiel → Ergebnis → Risiko → kurz- und langfristige Wirkung → Bewertung. Diese Reihenfolge eignet sich für jeden Nachteilsabsatz, weil sie klar, logisch und prüfungsnah ist.</td></tr>
</table>
<h4>2. Allgemeines Wortfeld und direkt verwendbare Ausdrücke</h4>
<table>
<tr><th>Nomen</th><td>der Vergleichsdruck, das Selbstwertgefühl, die Unsicherheit, die Selbstzweifel, der Leistungsdruck, die Selbstoptimierung, die Zielorientierung, das Vorbild, die Nachahmung, die Anerkennungssuche, die psychische Belastung, die Individualität, die Authentizität, die Fremdbestimmung, der Perfektionsdruck, die Überforderung, die Erschöpfung, die Burnout-Gefahr, der Produktivitätsdruck, die Fehlerangst, die Selbstdarstellung, der Konsumdruck, die äußere Bestätigung, die finanzielle Belastung, die Selbstinszenierung.</td></tr>
<tr><th>Verben und NVV</th><td>sich an Vorbildern orientieren, sich ständig vergleichen, unter Druck geraten, das Selbstwertgefühl schwächen, unrealistische Erwartungen wecken, eigene Ziele aus den Augen verlieren, fremde Maßstäbe übernehmen, nach Anerkennung streben, psychische Belastung verursachen, Authentizität verlieren, Perfektionsdruck erzeugen, Erholung vernachlässigen, die eigene Belastungsgrenze überschreiten, Konsumdruck ausüben, Erfolg an Konsum knüpfen.</td></tr>
<tr><th>Adjektive</th><td>idealisiert, unrealistisch, oberflächlich, leistungsorientiert, belastend, unsicher, überfordert, selbstkritisch, abhängig, authentisch, langfristig, problematisch, verzerrt, kommerzialisiert, fremdbestimmt.</td></tr>
<tr><th>Satzanfänge</th><td>Ein zentraler Nachteil liegt darin, dass ... / Besonders problematisch ist, dass ... / Dies lässt sich damit begründen, dass ... / Ein typisches Beispiel dafür ist ... / Daraus ergibt sich, dass ... / Langfristig kann dies dazu führen, dass ... / Aus meiner Sicht sollte man Vorbilder kritisch betrachten.</td></tr>
</table>
<h4>3. Nachteil 1: Vergleichsdruck und geringeres Selbstwertgefühl</h4>
<table>
<tr><th>Kurze Idee</th><td>Der erste große Nachteil besteht darin, dass Vorbilder starken Vergleichsdruck erzeugen können. Menschen sehen die Erfolge anderer und fragen sich, warum sie selbst nicht genauso diszipliniert, attraktiv, sportlich, produktiv oder erfolgreich sind. Besonders soziale Medien verstärken diesen Effekt, weil dort oft nur ausgewählte, schöne und erfolgreiche Momente gezeigt werden.</td></tr>
<tr><th>Beobachtungen aus dem Alltag</th><td>• Jugendliche vergleichen ihren Körper mit Fitness-Influencern.<br>• Studierende vergleichen ihre Lernleistung mit produktiven Lernvideos.<br>• Berufseinsteiger sehen Karriereerfolge anderer und fühlen sich zurückgeblieben.<br>• Likes und Kommentare wirken wie eine öffentliche Bewertung.<br>• Der Alltag anderer erscheint attraktiver als das eigene normale Leben.<br>• Rückschläge und Fehler werden selten gezeigt.</td></tr>
<tr><th>Detaillierte Erklärung</th><td>Vorbilder können Orientierung geben, aber sie können auch zu einem unfairen Maßstab werden. Problematisch ist, dass Menschen ihr vollständiges Leben mit einer ausgewählten Darstellung anderer Personen vergleichen. Man sieht den Erfolg, aber selten die Müdigkeit, die Fehler, die Zweifel, die Pausen oder die schwierigen Bedingungen dahinter. Dadurch entsteht ein verzerrtes Bild. Wer diesem Bild zu lange folgt, bewertet die eigenen Fortschritte nicht mehr realistisch. Statt kleine Verbesserungen wahrzunehmen, sieht man nur, was noch fehlt. So wird Selbstoptimierung zu einem dauerhaften Gefühl von Mangel.</td></tr>
<tr><th>Konkrete Beispiele</th><td>Ein Jugendlicher vergleicht seinen Körper mit professionell inszenierten Fitnessbildern. Eine Studentin sieht täglich Lernroutinen im Internet und glaubt, sie arbeite nicht genug. Ein Schüler vergleicht seine Noten mit besonders erfolgreichen Mitschülern und verliert die Freude an eigenen Fortschritten. Eine Person sieht auf LinkedIn frühe Karriereerfolge anderer und hat das Gefühl, beruflich zu langsam zu sein. Jemand betrachtet perfekte Urlaubsbilder und wird unzufrieden mit dem eigenen Alltag.</td></tr>
<tr><th>Folgen und Risiken</th><td>Die Folgen sind Unsicherheit, Selbstzweifel, Minderwertigkeitsgefühle, Neid, Frustration und psychische Belastung. Kurzfristig entsteht Druck, sich sofort verbessern zu müssen. Langfristig kann das Selbstwertgefühl geschwächt werden. In der Erörterung sollte klar werden: Nicht jede Orientierung ist problematisch, aber ein ständiger Vergleich mit idealisierten Bildern kann Selbstabwertung fördern.</td></tr>
<tr><th>C1/C2-Wörter und NVV</th><td>der Vergleichsdruck, das Selbstwertgefühl, die Selbstabwertung, die Minderwertigkeitsgefühle, die Anerkennungssuche, die Körperwahrnehmung; Vergleichsdruck erzeugen, das Selbstwertgefühl beeinträchtigen, Unsicherheit verstärken, nach Anerkennung streben, sich an unrealistischen Bildern orientieren, das eigene Leben abwerten.</td></tr>
<tr><th>Musterabsatz</th><td>Ein wesentlicher Nachteil der Selbstoptimierung durch Vorbilder liegt im Vergleichsdruck. Viele Menschen orientieren sich an erfolgreichen Personen und vergleichen das eigene Leben mit deren Leistungen. Besonders in sozialen Medien werden jedoch häufig nur perfekte Ergebnisse, schöne Körper oder produktive Tagesabläufe gezeigt. Schwierigkeiten, Rückschläge und normale Alltagsprobleme bleiben meist unsichtbar. Dadurch entsteht der Eindruck, selbst nicht gut genug zu sein. Langfristig kann dieser Vergleich das Selbstwertgefühl schwächen und psychische Belastungen verstärken.</td></tr>
</table>
<h4>4. Nachteil 2: Unrealistische Erwartungen und Perfektionsdruck</h4>
<table>
<tr><th>Kurze Idee</th><td>Ein weiterer Nachteil besteht darin, dass Vorbilder unrealistische Erwartungen wecken können. Viele Vorbilder wirken dauerhaft diszipliniert, kontrolliert, attraktiv, leistungsfähig und produktiv. Dadurch glauben manche Menschen, sie müssten ebenfalls immer funktionieren und dürften keine Schwächen zeigen.</td></tr>
<tr><th>Beobachtungen aus dem Alltag</th><td>• perfekte Morgenroutinen werden als Normalität gezeigt.<br>• Pausen wirken wie Zeitverlust.<br>• Fehler und Rückschläge werden versteckt.<br>• Menschen versuchen, Sport, Ernährung, Schlaf, Arbeit und Lernen gleichzeitig zu optimieren.<br>• Erholung wird weniger wichtig genommen.<br>• Selbstoptimierung wird mit Perfektion verwechselt.</td></tr>
<tr><th>Detaillierte Erklärung</th><td>Vorbilder zeigen oft Ergebnisse, aber nicht den langen Weg dorthin. Man sieht Erfolg, aber selten die Unterstützung, die Zeit, die finanziellen Möglichkeiten, die Übung oder die Misserfolge dahinter. Dadurch entsteht der Eindruck, Erfolg sei nur eine Frage von Disziplin. Wer diesem Eindruck folgt, setzt sich leicht selbst unter Druck. Besonders problematisch ist, dass persönliche Entwicklung dann nicht mehr freiwillig wirkt, sondern wie eine Pflicht. Menschen glauben, sie müssten jeden Tag produktiver, gesünder, erfolgreicher und kontrollierter sein. Wenn sie das nicht schaffen, entstehen Schuldgefühle.</td></tr>
<tr><th>Konkrete Beispiele</th><td>Eine Studentin fühlt sich schuldig, wenn sie eine Pause macht. Ein Schüler lernt bis spät in die Nacht, weil seine Vorbilder extrem fleißig wirken. Eine Person versucht, Ernährung, Sport, Schlaf und Arbeit vollständig zu kontrollieren. Ein Berufstätiger glaubt, ständig erreichbar sein zu müssen. Jugendliche glauben, sie müssten früh Karrierepläne haben und immer souverän auftreten.</td></tr>
<tr><th>Folgen und Risiken</th><td>Perfektionsdruck kann zu Überforderung, Fehlerangst, Erschöpfung, dauerhafter Selbstkritik und Burnout-Gefahr führen. Kurzfristig steigt die Leistungsbereitschaft vielleicht, aber langfristig kann die Belastungsgrenze überschritten werden. Aus einem sinnvollen Wunsch nach Verbesserung wird ein innerer Zwang. Genau diese Entwicklung ist für einen Nachteilsaufsatz besonders stark.</td></tr>
<tr><th>C1/C2-Wörter und NVV</th><td>der Perfektionsdruck, die unrealistische Erwartung, der Leistungsdruck, die Selbstkontrolle, die Überforderung, die Erschöpfung, die Burnout-Gefahr, die Fehlerangst; unrealistische Erwartungen wecken, unter Leistungsdruck geraten, Erholung vernachlässigen, die Belastungsgrenze überschreiten, Schuldgefühle entwickeln.</td></tr>
<tr><th>Musterabsatz</th><td>Ein weiterer negativer Aspekt ist der Perfektionsdruck. Vorbilder zeigen häufig Disziplin, Erfolg und produktive Routinen. Das kann zwar motivierend wirken, aber auch unrealistische Erwartungen erzeugen. Manche Menschen glauben dann, sie müssten jeden Tag perfekt funktionieren, ständig lernen, Sport treiben oder beruflich erfolgreich sein. Pausen und Erholung werden als Schwäche empfunden, obwohl sie für die Gesundheit wichtig sind. Langfristig kann Selbstoptimierung dadurch zu Stress, Überforderung und psychischer Erschöpfung führen.</td></tr>
</table>
<h4>5. Nachteil 3: Verlust der eigenen Individualität und fremde Ziele</h4>
<table>
<tr><th>Kurze Idee</th><td>Der dritte Nachteil betrifft die eigene Individualität. Wer sich zu stark an Vorbildern orientiert, kann den Kontakt zu den eigenen Wünschen, Interessen und Bedürfnissen verlieren. Nicht jedes Ziel passt zu jedem Menschen. Wenn fremde Lebensmodelle unkritisch übernommen werden, entsteht keine echte Entwicklung, sondern Nachahmung.</td></tr>
<tr><th>Beobachtungen aus dem Alltag</th><td>• Menschen kopieren Verhalten, Sprache, Kleidung oder Routinen anderer.<br>• Trends werden schnell übernommen.<br>• Eigene Interessen geraten in den Hintergrund.<br>• Vorbilder bestimmen Lebensstil und Ziele.<br>• Erfolg wird nach fremden Maßstäben bewertet.<br>• Jugendliche imitieren Influencer.<br>• Authentizität geht verloren.</td></tr>
<tr><th>Detaillierte Erklärung</th><td>Vorbilder können hilfreiche Orientierung geben, aber sie dürfen die eigene Entscheidung nicht ersetzen. Jeder Mensch hat andere Voraussetzungen, Werte, Fähigkeiten, Grenzen und Lebensumstände. Was für ein Vorbild sinnvoll ist, kann für die eigene Person unpassend sein. Wer fremde Ziele übernimmt, prüft möglicherweise nicht mehr, ob diese Ziele zu den eigenen Interessen passen. Besonders bei jungen Menschen ist das problematisch, weil sie ihre Identität noch entwickeln. Selbstoptimierung sollte eigentlich helfen, die eigene Persönlichkeit zu stärken. Wird jedoch nur ein fremdes Ideal kopiert, schwächt sie die Authentizität.</td></tr>
<tr><th>Konkrete Beispiele</th><td>Jemand wählt einen Beruf nur, weil ein Vorbild in diesem Bereich erfolgreich ist. Ein Jugendlicher kopiert Kleidung und Sprache eines Influencers. Eine Person übernimmt eine Fitnessroutine, die nicht zum eigenen Körper passt. Jemand studiert ein angesehenes Fach, obwohl es nicht den eigenen Interessen entspricht. Eine Person verliert Freude an Hobbys, weil sie nur noch Leistung zeigen möchte.</td></tr>
<tr><th>Folgen und Risiken</th><td>Die Folgen können Identitätsverlust, Fremdbestimmung, falsche Lebensentscheidungen, Unzufriedenheit und Abhängigkeit von fremden Maßstäben sein. Kurzfristig gibt Nachahmung vielleicht Sicherheit. Langfristig kann sie aber dazu führen, dass man den eigenen Weg verlässt. In einer Erörterung sollte man deshalb betonen, dass Vorbilder Orientierung geben dürfen, aber nicht zur Aufgabe der eigenen Persönlichkeit führen sollten.</td></tr>
<tr><th>C1/C2-Wörter und NVV</th><td>die Individualität, die Authentizität, die eigene Identität, die Nachahmung, die Fremdbestimmung, die Lebensentscheidung, der Identitätsverlust; die eigene Individualität verlieren, fremde Lebensmodelle übernehmen, eigene Bedürfnisse vernachlässigen, fremde Maßstäbe übernehmen, den eigenen Weg verlassen.</td></tr>
<tr><th>Musterabsatz</th><td>Auch der Verlust der eigenen Individualität kann ein Nachteil sein. Wer sich zu stark an Vorbildern orientiert, übernimmt möglicherweise Ziele und Lebensweisen, die gar nicht zu den eigenen Bedürfnissen passen. Statt eigene Interessen zu entwickeln, versucht man, eine andere Person zu imitieren. Dies kann besonders bei Jugendlichen problematisch sein, da sie sich noch in der Phase der Identitätsbildung befinden. Langfristig kann unkritische Nachahmung zu Unzufriedenheit und falschen Lebensentscheidungen führen.</td></tr>
</table>
<h4>6. Nachteil 4: Oberflächliche Selbstoptimierung, Konsumdruck und Abhängigkeit von Anerkennung</h4>
<table>
<tr><th>Kurze Idee</th><td>Der vierte Nachteil besteht darin, dass Selbstoptimierung durch Vorbilder oberflächlich und kommerzialisiert werden kann. Besonders in sozialen Medien sind Vorbilder oft mit Produkten, Marken, Fitnessprogrammen, Apps, Kursen oder Coaching-Angeboten verbunden. Dadurch entsteht der Eindruck, persönliche Entwicklung hänge vom Kauf bestimmter Dinge ab.</td></tr>
<tr><th>Beobachtungen aus dem Alltag</th><td>• Influencer verkaufen Produkte und Kurse.<br>• Selbstoptimierung wird mit Konsum verbunden.<br>• Likes und Kommentare wirken wie Anerkennung.<br>• Fortschritte werden öffentlich gezeigt.<br>• Erfolg wird über Aussehen, Besitz und Statussymbole definiert.<br>• Teure Programme versprechen schnelle Veränderung.<br>• Menschen vergleichen ihre Fortschritte öffentlich.</td></tr>
<tr><th>Detaillierte Erklärung</th><td>Vorbilder in sozialen Medien sind nicht immer neutral. Viele verdienen Geld mit Werbung, Fitnessplänen, Produktplatzierungen oder Onlinekursen. Dadurch kann Selbstoptimierung zu einem Markt werden. Menschen glauben dann, sie müssten bestimmte Kleidung, Nahrungsergänzungsmittel, Apps oder Kurse kaufen, um sich wirklich zu verbessern. Gleichzeitig entsteht eine Abhängigkeit von äußerer Anerkennung. Wenn Fortschritte nur wertvoll erscheinen, wenn sie gesehen und gelobt werden, verliert Selbstentwicklung ihre innere Bedeutung. Man arbeitet dann nicht mehr nur an sich selbst, sondern an einem Bild, das nach außen wirken soll.</td></tr>
<tr><th>Konkrete Beispiele</th><td>Ein Influencer verkauft einen teuren Fitnessplan. Eine Person kauft ständig neue Produkte, um einem Vorbild ähnlicher zu werden. Jemand postet jeden Fortschritt und wartet auf Likes. Online-Kurse versprechen schnelle Karriere oder perfekte Produktivität. Jugendliche orientieren sich an Marken, Statussymbolen und äußeren Reaktionen. Eine Person fühlt sich nur erfolgreich, wenn andere ihre Fortschritte sehen.</td></tr>
<tr><th>Folgen und Risiken</th><td>Diese Entwicklung kann Konsumdruck, finanzielle Belastung, Manipulation durch Werbung, oberflächliche Werte und Anerkennungsabhängigkeit verursachen. Kurzfristig entsteht der Wunsch, Produkte zu kaufen oder Fortschritte zu zeigen. Langfristig kann Selbstwert immer stärker von Reaktionen anderer abhängen. In der Prüfung kann man diesen Punkt gut als Verbindung von sozialen Medien, Konsumkultur und Selbstbild darstellen.</td></tr>
<tr><th>C1/C2-Wörter und NVV</th><td>der Konsumdruck, die Selbstdarstellung, die Anerkennungssuche, die äußere Bestätigung, die oberflächliche Selbstoptimierung, die Kaufentscheidung, die finanzielle Belastung, die Selbstinszenierung; Konsumdruck ausüben, Anerkennung suchen, sich über Likes definieren, innere Motivation schwächen, Erfolg an Konsum knüpfen.</td></tr>
<tr><th>Musterabsatz</th><td>Ein weiterer Nachteil besteht darin, dass Selbstoptimierung durch Vorbilder leicht oberflächlich werden kann. Besonders in sozialen Medien sind Vorbilder häufig mit Werbung, Produkten oder kostenpflichtigen Programmen verbunden. Dadurch entsteht der Eindruck, dass man bestimmte Kleidung, Apps, Fitnesspläne oder Kurse braucht, um sich wirklich zu verbessern. Gleichzeitig wird Anerkennung durch Likes, Kommentare und Lob immer wichtiger. Langfristig kann dies zu Konsumdruck, finanzieller Belastung und Abhängigkeit von äußerer Anerkennung führen.</td></tr>
</table>
<h4>7. Satzbausteine für Einleitung, Hauptteil und Schluss</h4>
<table>
<tr><th>Einleitungssätze</th><td>In der heutigen Gesellschaft orientieren sich viele Menschen an Vorbildern, um sich persönlich weiterzuentwickeln. Besonders durch soziale Medien sind erfolgreiche, disziplinierte oder attraktive Personen ständig sichtbar. Das Thema Selbstoptimierung durch Vorbilder gewinnt zunehmend an Bedeutung, weil viele Menschen ihr Verhalten verbessern möchten. Im Folgenden soll untersucht werden, welche Nachteile diese Form der Selbstoptimierung mit sich bringen kann.</td></tr>
<tr><th>Argument einführen</th><td>Ein wesentlicher Nachteil besteht darin, dass ... / Ein zentraler Aspekt dieses Problems ist, dass ... / Besonders problematisch ist vor allem, dass ... / Ein nicht zu unterschätzender Punkt ist, dass ...</td></tr>
<tr><th>Begründung und Folge</th><td>Dies lässt sich damit begründen, dass Vorbilder häufig nur ihre positiven Seiten zeigen. Daraus ergibt sich, dass Menschen ihr eigenes Leben als weniger erfolgreich wahrnehmen können. Infolgedessen kann es dazu kommen, dass Selbstoptimierung als Druck empfunden wird. Langfristig betrachtet kann dies zu psychischer Belastung und Unzufriedenheit führen.</td></tr>
<tr><th>Beispiele formulieren</th><td>Dies lässt sich am Beispiel von Fitness-Influencern verdeutlichen. Ein typisches Beispiel dafür ist die Darstellung perfekter Tagesroutinen in sozialen Medien. Besonders bei Jugendlichen wird deutlich, dass Vorbilder das Selbstbild stark beeinflussen können. Auch im Studium oder Beruf kann dieser Druck entstehen, wenn Erfolgsgeschichten als Maßstab dienen.</td></tr>
<tr><th>Schluss</th><td>Abschließend lässt sich festhalten, dass Selbstoptimierung durch Vorbilder nicht nur positive Seiten hat. Aus den genannten Gründen komme ich zu dem Schluss, dass Vorbilder kritisch betrachtet werden sollten. Vorbilder können hilfreich sein, solange sie nicht zu Druck, Vergleich und Selbstabwertung führen. Deshalb sollte Selbstoptimierung realistisch, freiwillig und an den eigenen Bedürfnissen orientiert bleiben.</td></tr>
</table>
<h4>8. Mustertexte und Kopiervorlage</h4>
<table>
<tr><th>Mustertext 1</th><td>Ein wesentlicher Nachteil der Selbstoptimierung durch Vorbilder liegt darin, dass sie starken Vergleichsdruck erzeugen kann. Viele Menschen orientieren sich an erfolgreichen Personen und vergleichen das eigene Leben mit deren Leistungen. Besonders in sozialen Medien werden jedoch häufig nur perfekte Ergebnisse, schöne Körper oder produktive Tagesabläufe gezeigt. Schwierigkeiten und Rückschläge bleiben meist unsichtbar. Dadurch entsteht ein verzerrtes Bild von Erfolg. Wer sich ständig mit solchen Idealen vergleicht, kann schnell das Gefühl bekommen, nicht gut genug zu sein. Langfristig kann dies das Selbstwertgefühl schwächen und zu psychischer Belastung führen.</td></tr>
<tr><th>Mustertext 2</th><td>Ein weiterer problematischer Aspekt ist der mögliche Verlust der eigenen Individualität. Vorbilder können zwar Orientierung geben, aber nicht jedes Ziel passt zu jeder Person. Wenn Menschen fremde Lebensmodelle unkritisch übernehmen, entfernen sie sich möglicherweise von ihren eigenen Bedürfnissen. Statt sich selbst zu entwickeln, versucht man dann, jemand anderes zu imitieren. Langfristig kann dies zu Unzufriedenheit und falschen Lebensentscheidungen führen.</td></tr>
<tr><th>Mustertext 3</th><td>Auch die Verbindung von Vorbildern und Konsum kann problematisch sein. Viele Vorbilder in sozialen Medien empfehlen Produkte, Kurse, Fitnesspläne oder Apps. Dadurch entsteht leicht der Eindruck, dass persönliche Entwicklung nur durch bestimmte Käufe möglich ist. Hinzu kommt, dass Fortschritte häufig öffentlich gezeigt werden und Anerkennung durch Likes oder Kommentare gesucht wird. Wenn Selbstwert vor allem von äußerer Bestätigung abhängt, entsteht eine problematische Abhängigkeit.</td></tr>
<tr><th>Kopiervorlage</th><td>Ein zentraler Nachteil der Selbstoptimierung durch Vorbilder liegt darin, dass ... Dies lässt sich damit begründen, dass ... Ein typisches Beispiel dafür ist ... Dadurch entsteht ... Langfristig kann dies dazu führen, dass ... Aus meiner Sicht sollte man Vorbilder deshalb kritisch betrachten und nicht blind übernehmen.</td></tr>
</table>
<h4>9. Übungen für die eigene Anwendung</h4>
<table>
<tr><th>Lücken</th><td>Vorbilder können Vergleichsdruck erzeugen, wenn Menschen sich ständig mit ihnen vergleichen. Das Selbstwertgefühl kann leiden, wenn man sich nicht gut genug fühlt. Unrealistische Ideale führen oft zu Perfektionsdruck. Wer fremde Ziele unkritisch übernimmt, kann seine Individualität verlieren. Influencer-Marketing kann Konsumdruck auslösen.</td></tr>
<tr><th>Sätze verbinden</th><td>Vorbilder zeigen oft nur Erfolge; dadurch bekommen Menschen ein verzerrtes Bild. Menschen vergleichen sich ständig; infolgedessen kann das Selbstwertgefühl geschwächt werden. Perfekte Routinen wirken normal; besonders problematisch ist, dass viele sich selbst unter Druck setzen. Influencer verkaufen Produkte; langfristig betrachtet wird Selbstoptimierung mit Konsum verbunden.</td></tr>
<tr><th>Eigener Absatz</th><td>Schreibe einen Absatz mit acht bis zehn Sätzen zum Thema: Warum kann Selbstoptimierung durch Vorbilder zu Perfektionsdruck führen? Nutze mindestens fünf Wörter aus der Wortliste und zwei Satzbausteine aus dem Baukasten.</td></tr>
</table>`;
  function apply(){
    var lesson=window.DEUTSCH_LESSONS[KEY]||window.LESSONS[KEY]||{};
    lesson.long=long;
    lesson.longSource='WORD_SOURCE_DETAILED_2000_PLUS';
    lesson.wordSource='Selbstoptimierung_durch_Vorbilder_Nachteile_4_C1_C2_15_20(1).docx';
    window.DEUTSCH_LESSONS[KEY]=lesson;
    window.LESSONS[KEY]=lesson;
  }
  apply();
  setTimeout(apply,400);setTimeout(apply,1200);setTimeout(apply,2600);
})();