(function(){
  window.DEUTSCH_LESSONS = window.DEUTSCH_LESSONS || {};
  window.LESSONS = window.LESSONS || {};

  function esc(s){return String(s).replace(/[&<>]/g,function(c){return c==='&'?'&amp;':c==='<'?'&lt;':'&gt;';});}
  function p(s){return '<p>'+esc(s)+'</p>';}
  function li(a){return '<ul>'+a.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ul>';}
  function section(s){
    var h='<h4>'+esc(s.name)+'</h4>';
    h += p('Beobachtung: '+s.obs.join(' '));
    h += p('Detaillierte Erklärung: '+s.exp.join(' '));
    h += p('Konkrete Beispiele: '+s.ex.join(' '));
    h += p('Ergebnisse und Folgen: '+s.res.join(' '));
    h += p('Kurzfristig zeigt sich der Nachteil vor allem daran, dass '+s.short+'. Langfristig kann daraus entstehen, dass '+s.long+'.');
    h += p('Prüfungslogik: '+s.logic);
    return h;
  }
  function build(title, sourceFile, thesis, intro, sections, vocab, nvv, sentenceBlocks, modelParas, exercises){
    var h='<h3>'+esc(title)+'</h3>';
    h += '<p><b>Quelle:</b> Fortail.net / voreile,nachteile.rar – Word-Datei: <code>'+esc(sourceFile)+'</code></p>';
    h += p('Diese lange Konu anlatımı ist aus der zugeordneten Word-Datei aufgebaut. Sie ist für den Modus Uzun konu anlatımı bestimmt und enthält die prüfungsrelevanten Argumentationslinien, Beispiele, Folgen, C1/C2-Wortschatz, Satzbausteine, Musterabsätze und Übungen.');
    h += '<h4>Grundidee und Prüfungsziel</h4>'+p(intro)+p('Mögliche Grundthese: '+thesis);
    h += '<h4>Wie du den Absatz in der Prüfung aufbaust</h4>';
    h += li(['Alltagsbeobachtung nennen, damit das Argument konkret wirkt.','Problem oder Vorteil erklären und nicht nur behaupten.','Ein passendes Beispiel aus Schule, Studium, Beruf, Familie oder Alltag nennen.','Die Folge erklären: Wie verändert sich Verhalten, Gesundheit, Umwelt, Effizienz oder Selbstständigkeit?','Langfristige Wirkung formulieren und den Gedanken mit einem C1/C2-Satz abrunden.']);
    sections.forEach(function(s){h+=section(s);});
    h += '<h4>C1/C2-Wortschatz</h4>'+li(vocab);
    h += '<h4>Nomen-Verb-Verbindungen und starke Verben</h4>'+li(nvv);
    h += '<h4>Satzbausteine für die Erörterung</h4>'+li(sentenceBlocks);
    h += '<h4>Musterabsätze</h4>'+modelParas.map(function(x){return p(x);}).join('');
    h += '<h4>Kopya kağıdı / Spickzettel</h4>';
    h += li(sections.map(function(s){return s.name+': '+s.logic;}));
    h += '<h4>Übungen zur Aktivierung</h4>'+li(exercises);
    h += p('Abschlussstrategie: Verwende nicht nur einfache Bewertungen wie gut, schlecht, praktisch oder problematisch. Entscheidend ist, dass du Beobachtung, Ursache, Beispiel, Folge und Langzeitwirkung miteinander verbindest. Dadurch entsteht ein langer, differenzierter C1/C2-Absatz, der direkt aus dem Quellenmaterial entwickelt ist.');
    return h;
  }
  function applyLong(key, html){
    window.DEUTSCH_LESSONS[key]=window.DEUTSCH_LESSONS[key]||{};
    window.DEUTSCH_LESSONS[key].long=html;
    window.LESSONS[key]=window.LESSONS[key]||window.DEUTSCH_LESSONS[key];
    window.LESSONS[key].long=html;
  }

  applyLong('t28', build('Teamarbeit – Nachteile · C1/C2 Nachteilsabsatz','Teamarbeit_Nachteile_4_C1_C2_Konuanlatimi.docx','Teamarbeit kann zwar kreative Prozesse fördern, führt jedoch häufig zu Konflikten, Zeitverlust, ungleicher Arbeitsverteilung und einer verwässerten Verantwortlichkeit.','Teamarbeit wird in Schule, Studium und Beruf oft als moderne Arbeitsform betrachtet. Die Quelle zeigt aber, dass Teamarbeit nicht automatisch produktiv ist. Problematisch wird sie besonders dann, wenn unterschiedliche Arbeitsstile aufeinandertreffen, Zuständigkeiten unklar bleiben, einige Mitglieder weniger beitragen oder Entscheidungen zu lange dauern. Für eine C1/C2-Erörterung ist deshalb wichtig, nicht pauschal gegen Teamarbeit zu schreiben, sondern genau zu zeigen, unter welchen Bedingungen die Zusammenarbeit zur Belastung wird.',[
    {name:'Nachteil 1: Konflikte und schwierige Abstimmung', obs:['unterschiedliche Meinungen in Gruppenarbeiten','lange Diskussionen über kleine Entscheidungen','Missverständnisse zwischen Gruppenmitgliedern','dominante Personen setzen sich durch','ruhigere Mitglieder ziehen sich zurück','verschiedene Arbeitsstile prallen aufeinander'], exp:['mehrere Personen bringen verschiedene Erwartungen, Ziele und Qualitätsansprüche mit','ohne Moderation entstehen Spannungen','unklare Kommunikation blockiert die Arbeit','Vielfalt kann kreativ sein, aber auch Konflikte auslösen'], ex:['Streit über Aufbau und Design einer Präsentation','ein dominantes Mitglied entscheidet fast alles allein','Kritik wird persönlich genommen','mündliche Absprachen werden missverstanden'], res:['Zeitverlust','schlechtere Arbeitsatmosphäre','sinkende Motivation','verlangsamter Arbeitsprozess','geringere Effizienz','schwächeres Endergebnis'], short:'Diskussionen länger werden, Entscheidungen verschoben werden und die Stimmung im Team leidet', long:'Vertrauen verloren geht, Kommunikationsprobleme dauerhaft bestehen und die Teamleistung insgesamt schwächer wird', logic:'verschiedene Meinungen und Arbeitsstile -> Konflikte -> Zeitverlust -> Motivationsverlust'},
    {name:'Nachteil 2: Ungleiche Arbeitsverteilung und Trittbrettfahrer-Problem', obs:['einige Gruppenmitglieder arbeiten deutlich mehr','Aufgaben werden ungleich verteilt','einzelne verlassen sich auf die Gruppe','Abgaben kommen verspätet oder unvollständig','engagierte Mitglieder fühlen sich ausgenutzt'], exp:['Verantwortung wird in Gruppen nicht immer klar zugeordnet','passive Mitglieder profitieren vom Ergebnis ohne angemessenen Beitrag','leistungsstarke Personen übernehmen Zusatzaufgaben','Gerechtigkeit, Motivation und Bewertung werden problematisch'], ex:['eine Person erstellt fast die gesamte Präsentation','ein Gruppenmitglied liefert seinen Teil kurz vor der Abgabe','andere erscheinen unvorbereitet','alle erhalten dieselbe Note trotz unterschiedlicher Leistung'], res:['Gefühl von Ungerechtigkeit','zusätzlicher Leistungsdruck','Frustration','Demotivation','schlechtere Qualität','Konflikte über Anerkennung'], short:'zuverlässige Mitglieder mehr Arbeit übernehmen und vor der Abgabe Stress entsteht', long:'Teamarbeit vermieden wird, Vertrauen sinkt und eine schwache Teamkultur entsteht', logic:'ungleiche Beteiligung -> Trittbrettfahrer-Problem -> Frustration -> schwächere Teamleistung'},
    {name:'Nachteil 3: Zeitverlust und ineffiziente Entscheidungsprozesse', obs:['Termine müssen koordiniert werden','Besprechungen dauern länger als geplant','kleine Entscheidungen werden ausführlich diskutiert','Aufgaben hängen voneinander ab','Online-Kommunikation verursacht Verzögerungen'], exp:['Teamarbeit braucht Planung, Kommunikation und Abstimmung','eine Einzelperson kann oft schneller entscheiden','Teams müssen Kompromisse finden','wenn Koordination mehr Zeit kostet als die Aufgabe, sinkt Effizienz'], ex:['Treffen wird mehrfach verschoben','eine Folie wird lange diskutiert','Entscheidungen werden neu geöffnet','eine Person wartet auf den Beitrag einer anderen'], res:['mehr Organisationsaufwand','langsamerer Arbeitsprozess','Verzögerungen','sinkende Produktivität','weniger Zeit für Qualität'], short:'mehr Abstimmung, Terminprobleme und Zeitdruck entstehen', long:'ineffiziente Arbeitskulturen, Projektverzögerungen und Motivationsverlust entstehen', logic:'viele Absprachen -> hoher Koordinationsaufwand -> langsame Entscheidungen -> geringere Effizienz'},
    {name:'Nachteil 4: Verlust individueller Verantwortung und Abhängigkeit', obs:['einzelne fühlen sich nicht direkt verantwortlich','Fehler werden auf die Gruppe geschoben','eigene Leistung ist schwer erkennbar','das Ergebnis hängt von anderen ab','manche verstecken sich hinter der Gruppe'], exp:['Verantwortung verwässert, wenn mehrere Personen gemeinsam zuständig sind','es bleibt unklar, wer Fehler verursacht hat','zuverlässige Mitglieder hängen von unpünktlichen oder schwachen Beiträgen anderer ab','faire Leistungsbewertung wird erschwert'], ex:['bei einer schlechten Note ist die Ursache unklar','eine Person kann ohne fremden Beitrag nicht weiterarbeiten','niemand übernimmt Endkontrolle','Fehler in einer gemeinsamen Datei bleiben unbemerkt'], res:['unklare Verantwortlichkeit','geringere Eigeninitiative','Abhängigkeit von anderen','schwierige Leistungsbewertung','weniger Kontrolle über das Endprodukt'], short:'Zuständigkeiten unklar bleiben und einzelne weniger Kontrolle über das Ergebnis haben', long:'Eigenverantwortung, Qualitätssicherung und Vertrauen in Teamprozesse geschwächt werden', logic:'unklare Zuständigkeit -> Verantwortungsdiffusion -> Abhängigkeit -> schwierige Bewertung'}
  ], ['die Meinungsverschiedenheit','der Abstimmungsbedarf','die Konfliktsituation','die Arbeitsatmosphäre','das Trittbrettfahrer-Problem','die Verantwortungsübernahme','der Koordinationsaufwand','die Entscheidungsfindung','die Projektverzögerung','die Verantwortungsdiffusion','die Eigenverantwortung','die Leistungstransparenz'], ['die Arbeitsatmosphäre belasten','die Effizienz beeinträchtigen','Verantwortung übernehmen','unter zusätzlichem Druck stehen','das Gesamtergebnis beeinträchtigen','die Produktivität mindern','in Anspruch nehmen','Verantwortung verschieben','die Eigenverantwortung schwächen'], ['Ein zentraler Nachteil der Teamarbeit liegt im hohen Abstimmungsbedarf.','Unterschiedliche Meinungen und Arbeitsweisen können die Zusammenarbeit erheblich erschweren.','Problematisch ist vor allem die ungleiche Verteilung der Aufgaben.','Ein hoher Koordinationsaufwand kann die Effizienz des Arbeitsprozesses beeinträchtigen.','Zudem besteht die Gefahr, dass individuelle Verantwortung innerhalb der Gruppe verwässert wird.'], ['Ein wesentlicher Nachteil der Teamarbeit liegt in möglichen Konflikten innerhalb der Gruppe. Da verschiedene Persönlichkeiten, Meinungen und Arbeitsweisen aufeinandertreffen, kann die Abstimmung viel Zeit in Anspruch nehmen. Besonders problematisch wird dies, wenn keine klaren Regeln für Kommunikation und Entscheidungsfindung bestehen. In solchen Fällen entstehen Missverständnisse, Frustration und eine angespannte Arbeitsatmosphäre. Somit kann Teamarbeit trotz gemeinsamer Zielsetzung zu Ineffizienz und Motivationsverlust führen.','Ein weiterer Nachteil besteht in der häufig ungleichen Arbeitsverteilung. Während einige Gruppenmitglieder sehr engagiert arbeiten, beteiligen sich andere nur oberflächlich oder gar nicht. Dadurch entsteht für zuverlässige Personen eine zusätzliche Belastung, weil sie fehlende Beiträge ausgleichen müssen. Besonders problematisch ist dies, wenn am Ende alle Mitglieder gleich bewertet werden. Infolgedessen kann Teamarbeit ein Gefühl von Ungerechtigkeit hervorrufen und die Motivation leistungsbereiter Personen deutlich senken.','Ein dritter Nachteil der Teamarbeit liegt im hohen Zeit- und Koordinationsaufwand. Da mehrere Personen beteiligt sind, müssen Termine abgestimmt, Aufgaben verteilt und Entscheidungen gemeinsam getroffen werden. Dieser Prozess nimmt oft mehr Zeit in Anspruch als die eigentliche Bearbeitung. Wenn zu viel Energie in Organisation und Diskussionen fließt, bleibt weniger Zeit für eine sorgfältige Ausarbeitung.'], ['Setze passende Ausdrücke ein: Koordinationsaufwand, Verantwortungsdiffusion, Arbeitsatmosphäre, Trittbrettfahrer-Problem, Abstimmungsbedarf.','Formuliere: Teamarbeit kostet viel Zeit, manche arbeiten weniger, es gibt Streit, niemand fühlt sich verantwortlich.','Schreibe einen Nachteilsabsatz mit Beobachtung, Erklärung, Beispiel, Folge und Bewertung.']));

  applyLong('t29', build('Individualität – Nachteile · C1/C2 Nachteilsabsatz','Individualitaet_Nachteile_C1_C2_Konuanlatimi.docx','Individualität ist zwar ein wichtiger Bestandteil persönlicher Freiheit, kann aber auch Egoismus, sozialen Druck, Abgrenzung und weniger Gemeinsinn fördern.','Die Quelle beschreibt Individualität differenziert: Sie bedeutet Selbstverwirklichung, Eigenständigkeit und persönliche Freiheit, kann aber problematisch werden, wenn sie zu stark betont wird. In modernen Gesellschaften soll jeder einzigartig sein, einen eigenen Stil entwickeln und sich ständig von anderen unterscheiden. Dadurch entstehen Leistungsdruck, Selbstdarstellung und eine Schwächung gemeinschaftlicher Werte.',[
    {name:'Nachteil 1: Übersteigerter Individualismus und Egoismus', obs:['eigene Wünsche stehen im Mittelpunkt','gemeinsame Interessen verlieren an Bedeutung','Menschen grenzen sich bewusst ab','soziale Rücksichtnahme wird schwächer','persönliche Selbstverwirklichung wird zum Hauptziel'], exp:['Individualität kann in Egoismus umschlagen','Freiheit wird einseitig verstanden','soziale Verantwortung tritt zurück','Gemeinschaft braucht jedoch Rücksicht und Kompromissfähigkeit'], ex:['jemand lehnt Teamregeln ab','persönliche Wünsche werden über Familienpflichten gestellt','gesellschaftliche Regeln werden nur als Einschränkung gesehen'], res:['weniger Solidarität','mehr Konflikte','schwächerer Zusammenhalt','geringere Kompromissbereitschaft'], short:'eigene Interessen stärker zählen als gemeinsame Ziele', long:'Gemeinsinn, Verantwortung und soziale Bindungen geschwächt werden', logic:'starke Selbstbezogenheit -> weniger Rücksicht -> Konflikte -> schwächerer Zusammenhalt'},
    {name:'Nachteil 2: Druck zur Selbstoptimierung und Selbstdarstellung', obs:['jeder soll besonders sein','soziale Medien fördern Vergleich','Aussehen, Karriere und Lebensstil werden inszeniert','Menschen präsentieren ihr Leben ständig','Individualität wird zur Pflicht'], exp:['wenn Einzigartigkeit erwartet wird, entsteht neuer Konformitätsdruck','Menschen vergleichen sich mit idealisierten Bildern','Selbstverwirklichung wird mit Leistung und Sichtbarkeit verbunden'], ex:['Influencer-Lebensstile als Vorbild','ständige Selbstpräsentation in sozialen Netzwerken','Druck, originell, erfolgreich und attraktiv zu wirken'], res:['Stress','Unsicherheit','Selbstzweifel','Vergleichsdruck','oberflächliche Selbstdarstellung'], short:'Menschen sich ständig vergleichen und darstellen müssen', long:'psychischer Druck, Unsicherheit und eine oberflächliche Vorstellung von Persönlichkeit entstehen', logic:'Zwang zur Einzigartigkeit -> Selbstinszenierung -> Vergleichsdruck -> psychische Belastung'},
    {name:'Nachteil 3: Soziale Abgrenzung und weniger Gemeinschaft', obs:['Menschen betonen Unterschiede','Lebensstile entfernen sich voneinander','gemeinsame Normen verlieren Bedeutung','Gruppen bilden sich nach Interessen oder Status','Dialog wird schwieriger'], exp:['Individualität kann Abgrenzung fördern','wenn jeder nur seine eigene Identität betont, sinkt Bereitschaft zu gemeinsamen Lösungen','Gesellschaft braucht jedoch gemeinsame Werte'], ex:['starke Abgrenzung über Kleidung, Konsum oder politische Haltung','weniger gemeinsame Familienrituale','geringere Bereitschaft, sich anzupassen'], res:['soziale Distanz','weniger Zusammenhalt','mehr Fragmentierung','schwierigere Kommunikation'], short:'Unterschiede stärker betont werden als Gemeinsamkeiten', long:'eine fragmentierte Gesellschaft mit weniger Solidarität entstehen kann', logic:'Betonung eigener Identität -> Abgrenzung -> weniger Gemeinsamkeit -> gesellschaftliche Spaltung'},
    {name:'Nachteil 4: Konsumorientierte Pseudo-Individualität', obs:['Individualität wird über Produkte verkauft','Marken versprechen Einzigartigkeit','Konsum ersetzt echte Persönlichkeit','Trends wirken wie Individualität','Werbung nutzt Selbstverwirklichung als Verkaufsargument'], exp:['Menschen glauben, durch Produkte einzigartig zu werden','tatsächlich folgen sie oft Markttrends','Individualität wird kommerzialisiert','persönliche Freiheit wird mit Konsumentscheidungen verwechselt'], ex:['Mode, Technik, Kosmetik oder Lifestyle-Produkte als Ausdruck der Persönlichkeit','Werbung mit Slogans wie sei du selbst','teure Produkte als Identitätszeichen'], res:['materielle Orientierung','Abhängigkeit von Marken','oberflächliche Selbstdefinition','weniger echte Selbstreflexion'], short:'Individualität über Konsum dargestellt wird', long:'Persönlichkeit zunehmend von Marktlogik und Statussymbolen abhängig wird', logic:'Werbung verkauft Einzigartigkeit -> Konsumdruck -> Pseudo-Individualität -> weniger echte Selbstbestimmung'}
  ], ['der Individualismus','die Selbstverwirklichung','die Selbstinszenierung','der Vergleichsdruck','die soziale Abgrenzung','der Gemeinsinn','die Solidarität','die Kompromissbereitschaft','die Pseudo-Individualität','die Kommerzialisierung','die Identitätsbildung','die Selbstoptimierung'], ['Gemeinsinn schwächen','sozialen Druck erzeugen','Selbstzweifel verstärken','Unterschiede betonen','Solidarität verringern','Individualität kommerzialisieren','Konsumdruck erzeugen','soziale Bindungen schwächen'], ['Ein möglicher Nachteil übersteigerter Individualität liegt darin, dass gemeinsame Werte an Bedeutung verlieren.','Problematisch wird Individualität, wenn sie mit permanenter Selbstoptimierung verwechselt wird.','Hinzu kommt, dass soziale Medien den Druck zur Selbstdarstellung verstärken können.','Langfristig kann eine starke Fixierung auf das eigene Ich den gesellschaftlichen Zusammenhalt schwächen.'], ['Ein zentraler Nachteil übersteigerter Individualität besteht darin, dass sie soziale Rücksichtnahme schwächen kann. Wenn Menschen vor allem ihre eigenen Wünsche und Lebensentwürfe betonen, geraten gemeinsame Interessen leichter in den Hintergrund. Dadurch können Konflikte entstehen, weil Kompromisse als Einschränkung der persönlichen Freiheit wahrgenommen werden. Langfristig kann dies den Gemeinsinn und die Solidarität innerhalb einer Gesellschaft verringern.','Ein weiterer problematischer Aspekt liegt im Druck zur Selbstoptimierung. Moderne Individualität bedeutet häufig nicht nur Freiheit, sondern auch die Erwartung, besonders, erfolgreich und sichtbar zu sein. Vor allem soziale Medien verstärken diesen Vergleichsdruck. Menschen präsentieren dort ideale Versionen ihres Lebens und messen sich mit anderen. Infolgedessen kann Individualität zu Stress, Unsicherheit und Selbstzweifeln führen.'], ['Formuliere einen Absatz zum Unterschied zwischen echter Selbstbestimmung und Pseudo-Individualität.','Erkläre, warum soziale Medien Individualität auch in Leistungsdruck verwandeln können.','Nutze die Wörter Gemeinsinn, Selbstinszenierung und Kommerzialisierung in einem C1/C2-Absatz.']));

  applyLong('t30', build('Lebenslanges Lernen – Nachteile · C1/C2 Nachteilsabsatz','Lebenslanges_Lernen_Nachteile_C1_C2_Konuanlatimi.docx','Lebenslanges Lernen kann zwar berufliche Anpassungsfähigkeit fördern, aber auch dauerhaften Leistungsdruck, soziale Ungleichheit, Überforderung und eine Entwertung vorhandener Qualifikationen verursachen.','Lebenslanges Lernen gilt in modernen Wissensgesellschaften als Voraussetzung für berufliche Sicherheit. Die Quelle zeigt jedoch, dass diese Idee nicht nur positiv ist. Wenn Menschen ständig neue Kompetenzen erwerben müssen, kann daraus ein permanenter Druck entstehen. Außerdem profitieren nicht alle gleichermaßen, weil Zeit, Geld, Bildungsvoraussetzungen und digitale Zugänge ungleich verteilt sind.',[
    {name:'Nachteil 1: Dauerhafter Leistungs- und Anpassungsdruck', obs:['Arbeitsmärkte verändern sich schnell','Beschäftigte müssen ständig neue Fähigkeiten erwerben','Weiterbildungen werden erwartet','Stillstand gilt als Rückschritt','Karrieren werden unsicherer'], exp:['lebenslanges Lernen wird zur Pflicht','Menschen fühlen sich dauerhaft bewertet','Anpassungsfähigkeit wird wichtiger als Erholung','Beruf und Freizeit verschwimmen'], ex:['neue Software im Beruf','ständige Zertifikate','Kurse nach Feierabend','Druck, digital kompetent zu bleiben'], res:['Stress','Erschöpfung','Angst vor beruflichem Abstieg','weniger Freizeit','permanente Selbstoptimierung'], short:'Menschen sich ständig weiterbilden müssen und Erholung zurücktritt', long:'dauerhafte Überlastung, Unsicherheit und psychischer Druck entstehen', logic:'schneller Wandel -> Lernpflicht -> Leistungsdruck -> Überforderung'},
    {name:'Nachteil 2: Soziale Ungleichheit beim Zugang zu Bildung', obs:['Weiterbildungen kosten Geld','nicht alle haben Zeit','digitale Kompetenzen sind ungleich verteilt','Familienpflichten erschweren Lernen','höhere Bildung erleichtert neue Bildung'], exp:['lebenslanges Lernen setzt Ressourcen voraus','wer wenig Geld oder Zeit hat, wird benachteiligt','Bildungsstarke profitieren stärker','soziale Unterschiede können wachsen'], ex:['teure Sprach- oder IT-Kurse','fehlende Kinderbetreuung','schlechte Internetverbindung','Arbeitende mit mehreren Jobs haben keine Kurszeit'], res:['ungleiche Chancen','Benachteiligung bildungsferner Gruppen','mehr Druck auf sozial Schwächere','Verstärkung bestehender Ungleichheit'], short:'nicht alle Menschen gleiche Lernmöglichkeiten haben', long:'Bildungsschere und soziale Ungerechtigkeit größer werden', logic:'ungleiche Ressourcen -> ungleicher Zugang -> weniger Chancen -> soziale Ungleichheit'},
    {name:'Nachteil 3: Überforderung durch Informationsflut', obs:['Kurse, Plattformen und Lernangebote nehmen zu','neue Trends entstehen ständig','Menschen wissen nicht, was relevant ist','digitale Lernformen verlangen Selbstorganisation'], exp:['zu viele Informationen erschweren Orientierung','Lernen wird unübersichtlich','Selbststeuerung kann überfordern','nicht jede Weiterbildung ist qualitativ wertvoll'], ex:['unzählige Online-Kurse','wechselnde berufliche Anforderungen','Zertifikate ohne klare Anerkennung','Lernen neben Beruf und Familie'], res:['Orientierungsverlust','Motivationsprobleme','oberflächliches Lernen','Zeitverschwendung','Frustration'], short:'Menschen zwischen vielen Angeboten wählen müssen', long:'Lernmotivation sinkt und Bildung nur noch als Pflicht empfunden wird', logic:'Informationsflut -> Orientierungsprobleme -> Überforderung -> geringere Lernqualität'},
    {name:'Nachteil 4: Entwertung vorhandener Qualifikationen', obs:['Abschlüsse verlieren schneller an Wert','Berufserfahrung reicht oft nicht mehr','neue Zertifikate werden verlangt','ältere Arbeitnehmer geraten unter Druck'], exp:['wenn ständig neue Kompetenzen gefordert werden, gelten frühere Leistungen als veraltet','Menschen müssen ihre Qualifikation immer wieder beweisen','Erfahrung wird weniger anerkannt'], ex:['ältere Beschäftigte müssen digitale Tools lernen','ein Abschluss genügt nicht mehr für Karriere','Bewerbungen verlangen aktuelle Zertifikate'], res:['Unsicherheit','Statusverlust','Druck auf ältere Arbeitnehmer','Abwertung praktischer Erfahrung'], short:'vorhandene Qualifikationen schneller infrage gestellt werden', long:'berufliche Identität, Selbstwert und Sicherheit geschwächt werden', logic:'neue Anforderungen -> alte Qualifikationen verlieren Wert -> Unsicherheit -> ständiger Rechtfertigungsdruck'}
  ], ['der Anpassungsdruck','die Weiterbildungspflicht','die Bildungsungleichheit','die Informationsflut','die Selbstoptimierung','die Qualifikationsentwertung','die Bildungsschere','die Überforderung','die berufliche Unsicherheit','die digitale Kompetenz','die Lernmotivation','die Ressourcenfrage'], ['Druck erzeugen','Chancen ungleich verteilen','Menschen überfordern','Qualifikationen entwerten','Bildungsungleichheit verstärken','Lernmotivation schwächen','berufliche Sicherheit infrage stellen','Ressourcen voraussetzen'], ['Ein Nachteil lebenslangen Lernens liegt im permanenten Anpassungsdruck.','Problematisch ist, dass Weiterbildung Zeit, Geld und digitale Zugänge voraussetzt.','Nicht alle Menschen verfügen über dieselben Ressourcen, um neue Kompetenzen zu erwerben.','Langfristig kann lebenslanges Lernen soziale Ungleichheiten verstärken.'], ['Ein wesentlicher Nachteil des lebenslangen Lernens besteht im dauerhaften Leistungsdruck. In einer sich schnell verändernden Arbeitswelt müssen Beschäftigte immer wieder neue Fähigkeiten erwerben. Was zunächst sinnvoll erscheint, kann langfristig zu Überforderung führen, weil Lernen nicht mehr als freie Entwicklung, sondern als berufliche Pflicht erlebt wird. Dadurch verschwimmen Arbeit, Freizeit und Weiterbildung.','Ein weiterer Nachteil betrifft die soziale Ungleichheit. Weiterbildung setzt Zeit, Geld und Zugang zu digitalen Lernangeboten voraus. Menschen mit stabiler finanzieller Lage und guter Vorbildung können diese Angebote leichter nutzen. Wer jedoch familiäre Verpflichtungen, wenig Geld oder geringe digitale Kompetenzen hat, wird benachteiligt. Somit kann lebenslanges Lernen bestehende soziale Unterschiede sogar verstärken.'], ['Erkläre, warum lebenslanges Lernen nicht für alle dieselben Chancen bietet.','Formuliere einen Absatz zum Unterschied zwischen freiwilliger Weiterbildung und Anpassungsdruck.','Nutze die Wörter Bildungsungleichheit, Informationsflut und Qualifikationsentwertung.']));
})();