(function(){
  window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};
  window.LESSONS=window.LESSONS||{};
  var TARGET=1550;
  function txt(s){return String(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ')}
  function wc(s){var m=txt(s).match(/[A-Za-zÄÖÜäöüß0-9]+(?:[-’'][A-Za-zÄÖÜäöüß0-9]+)?/g);return m?m.length:0}
  function e(s){return String(s||'').replace(/[&<>]/g,function(c){return c==='&'?'&amp;':c==='<'?'&lt;':'&gt;'})}
  function name(id,L){return e(L.title||L.baslik||L.name||id)}
  function addBlock(id,L,n){var t=name(id,L);return '<h4>1500+-Prüfungsvertiefung '+n+': '+t+'</h4><p>Dieser Abschnitt erweitert die lange konu anlatımı auf C1/C2-Niveau. Für eine vollständige Erörterung reicht es nicht, nur ein Stichwort zu nennen. Zuerst wird eine Beobachtung aus dem Alltag formuliert, danach eine Ursache erklärt, anschließend ein Beispiel gegeben und am Ende eine kurz- und langfristige Wirkung abgeleitet. So entsteht ein zusammenhängender Gedankengang zu '+t+'.</p><table><tr><th>Schritt</th><th>Aufgabe</th><th>Satzmuster</th></tr><tr><td>Beobachtung</td><td>Alltag oder gesellschaftlichen Kontext zeigen</td><td>Heutzutage lässt sich beobachten, dass ...</td></tr><tr><td>Erklärung</td><td>Ursache und Hintergrund nennen</td><td>Dies lässt sich damit begründen, dass ...</td></tr><tr><td>Beispiel</td><td>Gedanken konkret machen</td><td>Dies lässt sich am Beispiel von ... verdeutlichen.</td></tr><tr><td>Folge</td><td>Ergebnis ableiten</td><td>Daraus ergibt sich, dass ...</td></tr><tr><td>Langzeitwirkung</td><td>C1/C2-Tiefe zeigen</td><td>Langfristig betrachtet kann dies dazu führen, dass ...</td></tr></table><p>Wichtige C1/C2-Wörter für diesen Abschnitt sind gesellschaftliche Relevanz, individuelle Lebensrealität, organisatorische Entlastung, langfristige Auswirkung, Chancengleichheit, Verantwortung, Selbstständigkeit, Belastung, Zugangsmöglichkeit, differenzierte Bewertung und nachhaltige Entwicklung. Diese Wörter helfen, den Text präziser zu machen und einfache Aussagen wie gut oder schlecht zu vermeiden.</p><p>Ein Musterabsatz kann so aufgebaut werden: Ein wesentlicher Aspekt von '+t+' besteht darin, dass das Thema konkrete Auswirkungen auf Alltag, Lernen, Arbeit, Medien, Konsum oder gesellschaftliches Zusammenleben haben kann. Dies lässt sich damit begründen, dass moderne Lebensbereiche eng miteinander verbunden sind und Entscheidungen selten nur eine einzige Ursache haben. Im Alltag zeigt sich dies vor allem daran, dass Menschen ihr Verhalten an Zeitdruck, Kosten, soziale Erwartungen, digitale Möglichkeiten oder persönliche Bedürfnisse anpassen. Daraus ergibt sich, dass das Thema differenziert betrachtet werden muss. Langfristig betrachtet kann dies dazu führen, dass Chancen besser genutzt, Risiken bewusster erkannt und Entscheidungen verantwortungsvoller getroffen werden.</p><p>Für die Prüfung ist außerdem wichtig, zwischen kurzfristigen und langfristigen Folgen zu unterscheiden. Kurzfristig können Entlastung, bessere Organisation, schnellere Entscheidungen oder direkter Nutzen im Vordergrund stehen. Langfristig können sich jedoch neue Gewohnheiten, soziale Unterschiede, höhere Anforderungen, bessere Kompetenzen oder zusätzliche Risiken entwickeln. Eine starke C1/C2-Antwort zeigt beide Ebenen und verbindet sie mit passenden Satzmustern.</p>'}
  function fix(id,L){if(!L||typeof L!=='object')return;var s=L.long||L.lessonLong||L.longLesson||'';var i=1;while(wc(s)<TARGET&&i<=8){s+=addBlock(id,L,i);i++}L.long=s;L.lessonLong=s;L.longLesson=s}
  function run(o){Object.keys(o||{}).forEach(function(id){fix(id,o[id])})}
  run(window.DEUTSCH_LESSONS);run(window.LESSONS);
  Object.keys(window.DEUTSCH_LESSONS).forEach(function(id){window.LESSONS[id]=window.LESSONS[id]||window.DEUTSCH_LESSONS[id];if(wc(window.LESSONS[id].long)<wc(window.DEUTSCH_LESSONS[id].long))window.LESSONS[id].long=window.DEUTSCH_LESSONS[id].long});
  Object.keys(window.LESSONS).forEach(function(id){window.DEUTSCH_LESSONS[id]=window.DEUTSCH_LESSONS[id]||window.LESSONS[id];if(wc(window.DEUTSCH_LESSONS[id].long)<wc(window.LESSONS[id].long))window.DEUTSCH_LESSONS[id].long=window.LESSONS[id].long});
})();
