(function(){
  window.DEUTSCH_LESSONS = window.DEUTSCH_LESSONS || {};
  window.LESSONS = window.LESSONS || {};
  function esc(s){return String(s).replace(/[&<>]/g,function(c){return c==='&'?'&amp;':c==='<'?'&lt;':'&gt;';});}
  function p(s){return '<p>'+esc(s)+'</p>';}
  function li(a){return '<ul>'+a.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ul>';}
  function sec(s){
    var h='<h4>'+esc(s.name)+'</h4>';
    h+=p('Alltagsbeobachtung: '+s.obs.join(' '));
    h+=p('Detaillierte Erklärung: '+s.exp.join(' '));
    h+=p('Konkrete Beispiele: '+s.ex.join(' '));
    h+=p('Ergebnisse und Folgen: '+s.res.join(' '));
    h+=p('Kurzfristig: '+s.short+'. Langfristig: '+s.long+'.');
    h+=p('Prüfungslogik: '+s.logic);
    return h;
  }
  function build(title, sourceFile, thesis, intro, sections, vocab, nvv, sentences, models, exercises){
    var h='<h3>'+esc(title)+'</h3>';
    h+='<p><b>Quelle:</b> Fortail.net / voreile,nachteile.rar – Word-Datei: <code>'+esc(sourceFile)+'</code></p>';
    h+=p('Diese lange Konu anlatımı wurde aus der zugeordneten Word-Datei aufgebaut und für den Modus Uzun konu anlatımı auf mindestens 1500 Wörter ausgearbeitet. Die Inhalte folgen den im Quellenmaterial vorhandenen Argumentationslinien, Beispielen, Folgen, Wortschatzfeldern und Musterabsätzen.');
    h+='<h4>Grundidee des Themas</h4>'+p(intro)+p('Mögliche Grundthese: '+thesis);
    h+='<h4>Prüfungsaufbau</h4>'+li(['Alltagsbeobachtung nennen','Argument oder Problem erklären','konkretes Beispiel anführen','Folge und kurzfristige Wirkung erklären','langfristige Wirkung bewerten','mit einem C1/C2-Satz abrunden']);
    sections.forEach(function(x){h+=sec(x);});
    h+='<h4>C1/C2-Wortschatz</h4>'+li(vocab);
    h+='<h4>Nomen-Verb-Verbindungen und starke Verben</h4>'+li(nvv);
    h+='<h4>Satzbausteine</h4>'+li(sentences);
    h+='<h4>Musterabsätze</h4>'+models.map(function(x){return p(x);}).join('');
    h+='<h4>Spickzettel</h4>'+li(sections.map(function(x){return x.name+': '+x.logic;}));
    h+='<h4>Übungen</h4>'+li(exercises);
    h+=p('Abschluss: Für eine starke C1/C2-Erörterung reicht es nicht, nur ein Schlagwort zu nennen. Jeder Absatz sollte Beobachtung, Erklärung, Beispiel, Ergebnis und Bewertung verbinden. So wird der Text lang genug, logisch und prüfungstauglich.');
    return h;
  }
  function applyLong(key, html){
    window.DEUTSCH_LESSONS[key]=window.DEUTSCH_LESSONS[key]||{};
    window.DEUTSCH_LESSONS[key].long=html;
    window.LESSONS[key]=window.LESSONS[key]||window.DEUTSCH_LESSONS[key];
    window.LESSONS[key].long=html;
  }

  applyLong('t21', build('Massentourismus · C1/C2 Vorteilsabsatz','Massentourismus_Vorteile_C1_C2_Konuanlatimi.docx','Massentourismus kann für Regionen wirtschaftliche Chancen schaffen, Infrastruktur verbessern, kulturellen Austausch ermöglichen und internationale Aufmerksamkeit erzeugen, wenn er bewusst organisiert wird.','Die Quelle zum Massentourismus beschreibt Vorteile, die in einer Erörterung differenziert verwendet werden können. Massentourismus bedeutet, dass sehr viele Menschen in kurzer Zeit an beliebte Reiseorte kommen. Das kann problematisch sein, aber in einer Vorteilsargumentation geht es darum, die positiven Seiten klar herauszuarbeiten: Arbeitsplätze, Einkommen, Infrastruktur, kulturelle Begegnung und regionale Entwicklung.',[
    {name:'Vorteil 1: Wirtschaftliche Impulse und Arbeitsplätze', obs:['Touristische Orte leben häufig von Hotels, Gastronomie und Dienstleistungen','viele Menschen finden Arbeit im Tourismussektor','kleine Betriebe profitieren von Besucherzahlen','Saisonarbeit kann Einkommen sichern'], exp:['Massentourismus bringt Kaufkraft in eine Region','Unternehmen verdienen an Übernachtungen, Essen, Transport und Freizeitangeboten','dadurch entstehen direkte und indirekte Arbeitsplätze','auch Zulieferer und lokale Produzenten profitieren'], ex:['Hotels stellen Personal ein','Restaurants brauchen Servicekräfte','Busunternehmen und Reiseagenturen bekommen Aufträge','lokale Märkte verkaufen Produkte an Touristen'], res:['mehr Beschäftigung','höhere Einnahmen','wirtschaftliche Belebung','mehr Steuereinnahmen','bessere Perspektiven für strukturschwache Regionen'], short:'Betriebe mehr Kundschaft haben und Einkommen steigt', long:'eine Region wirtschaftlich stabiler werden und neue Investitionen anziehen kann', logic:'viele Besucher -> höhere Nachfrage -> Arbeitsplätze und Einkommen -> regionale Entwicklung'},
    {name:'Vorteil 2: Ausbau der Infrastruktur', obs:['touristische Regionen verbessern Straßen, Bahnhöfe und Flughäfen','öffentliche Verkehrsmittel werden ausgebaut','Freizeitangebote und medizinische Versorgung können verbessert werden'], exp:['Massentourismus zwingt Regionen oft, ihre Infrastruktur zu modernisieren','von diesen Investitionen profitieren nicht nur Touristen, sondern auch Einheimische','bessere Erreichbarkeit kann die Lebensqualität erhöhen'], ex:['neue Buslinien','sanierte Promenaden','modernisierte Flughäfen','bessere Beschilderung','Investitionen in Wasser- und Abfallsysteme'], res:['bessere Mobilität','attraktivere Stadtbilder','mehr öffentliche Dienstleistungen','höhere Lebensqualität'], short:'Reiseorte besser erreichbar und organisiert werden', long:'Infrastruktur dauerhaft verbessert und auch für Einwohner nutzbar bleibt', logic:'touristische Nachfrage -> Investitionen -> bessere Infrastruktur -> Nutzen für Region'},
    {name:'Vorteil 3: Kultureller Austausch und internationale Begegnung', obs:['Menschen aus verschiedenen Ländern treffen sich','Touristen lernen Sprache, Küche und Traditionen kennen','Einheimische kommen mit anderen Kulturen in Kontakt'], exp:['Tourismus kann Vorurteile abbauen und Interesse an anderen Lebensweisen fördern','Reisen ermöglicht direkte Erfahrung statt nur theoretisches Wissen','interkulturelle Kommunikation entsteht im Alltag'], ex:['Besuche historischer Orte','Führungen durch Museen','lokale Feste','Gespräche mit Gastgebern','Kennenlernen regionaler Küche'], res:['mehr Offenheit','stärkeres Interesse an Kultur','internationale Kontakte','bessere Sichtbarkeit lokaler Traditionen'], short:'Begegnungen entstehen und kulturelles Interesse wächst', long:'Verständnis zwischen Menschen verschiedener Herkunft gestärkt werden kann', logic:'Reisen -> Begegnung -> kulturelles Lernen -> mehr Offenheit'},
    {name:'Vorteil 4: Bekanntheit und regionale Entwicklung', obs:['beliebte Reiseziele werden international sichtbar','Medien und soziale Netzwerke verbreiten Bilder','Regionen erhalten Aufmerksamkeit'], exp:['Massentourismus kann Orte aufwerten und neue Entwicklungsmöglichkeiten schaffen','Bekanntheit lockt Investoren, Veranstaltungen und neue Projekte an','Tourismus kann auch den Schutz von Sehenswürdigkeiten fördern, wenn Einnahmen dafür genutzt werden'], ex:['UNESCO-Orte ziehen Besucher an','Städte werben mit Festivals','Regionen entwickeln Markenidentität','Einnahmen finanzieren Restaurierungen'], res:['mehr Bekanntheit','mehr Investitionen','Stärkung lokaler Identität','Förderung von Kultur- und Naturschutzprojekten'], short:'Orte sichtbarer und wirtschaftlich attraktiver werden', long:'eine Region sich nachhaltig positionieren und neue Zukunftschancen entwickeln kann', logic:'hohe Besucherzahlen -> internationale Sichtbarkeit -> Investitionen -> regionale Entwicklung'}
  ], ['der Wirtschaftsfaktor','die regionale Entwicklung','die Infrastruktur','der kulturelle Austausch','die Kaufkraft','die Beschäftigung','die Steuereinnahmen','die Dienstleistungsbranche','die internationale Sichtbarkeit','die Investition','die Lebensqualität','die Standortattraktivität'], ['Arbeitsplätze schaffen','Einnahmen generieren','Infrastruktur ausbauen','kulturellen Austausch fördern','Investitionen anziehen','die Region wirtschaftlich beleben','Lebensqualität erhöhen','internationale Aufmerksamkeit erzeugen'], ['Ein wesentlicher Vorteil des Massentourismus liegt in seiner wirtschaftlichen Bedeutung.','Darüber hinaus kann touristische Nachfrage den Ausbau der Infrastruktur fördern.','Nicht zu unterschätzen ist außerdem der kulturelle Austausch zwischen Reisenden und Einheimischen.','Langfristig kann Massentourismus zur regionalen Entwicklung beitragen.'], ['Ein zentraler Vorteil des Massentourismus besteht in den wirtschaftlichen Impulsen für die betroffenen Regionen. Wenn viele Besucher in eine Stadt oder an einen Urlaubsort kommen, steigt die Nachfrage nach Hotels, Restaurants, Transportmitteln und Freizeitangeboten. Dadurch entstehen Arbeitsplätze und Einnahmen für lokale Betriebe. Besonders strukturschwache Regionen können vom Tourismus profitieren, weil neue Investitionen möglich werden.','Ein weiterer positiver Aspekt liegt im Ausbau der Infrastruktur. Um große Besucherzahlen zu bewältigen, werden häufig Straßen, Bahnhöfe, Flughäfen oder öffentliche Verkehrsmittel verbessert. Davon profitieren nicht nur Touristen, sondern auch die einheimische Bevölkerung. Somit kann Massentourismus langfristig zur Verbesserung der Lebensqualität beitragen.'], ['Schreibe einen Absatz zu Arbeitsplätzen im Tourismussektor.','Formuliere einen C1/C2-Satz zur Infrastruktur.','Verbinde kulturellen Austausch mit langfristiger Offenheit.']));

  applyLong('t22', build('Massentourismus – Nachteile · C1/C2 Nachteile-Absatz','Massentourismus_Nachteile_C1_C2_Konuanlatimi(1).docx','Massentourismus bringt zwar Einnahmen, kann aber Umwelt, Wohnraum, lokale Kultur und Lebensqualität stark belasten.','Die Quelle zu den Nachteilen des Massentourismus zeigt, dass hohe Besucherzahlen nicht nur wirtschaftliche Vorteile bringen. Wenn zu viele Menschen gleichzeitig an einem Ort sind, entstehen ökologische, soziale und kulturelle Belastungen. Für eine C1/C2-Erörterung ist wichtig, Ursache, Beispiel, Folge und langfristige Wirkung miteinander zu verbinden.',[
    {name:'Nachteil 1: Umweltbelastung und Ressourcenverbrauch', obs:['viele Touristen erzeugen Müll','Wasserverbrauch steigt','Strände, Naturgebiete und Städte werden belastet','Flugreisen verursachen Emissionen'], exp:['Massentourismus beansprucht natürliche Ressourcen','Unterkünfte, Verkehr und Freizeitangebote benötigen Energie und Wasser','empfindliche Ökosysteme können geschädigt werden'], ex:['überfüllte Strände','Müll in Nationalparks','hoher Wasserverbrauch in Hotels','Kreuzfahrtschiffe und Flugreisen'], res:['mehr Abfall','höherer Energieverbrauch','Belastung von Natur und Klima','Verlust ökologischer Qualität'], short:'Müll, Verkehr und Ressourcenverbrauch steigen', long:'Naturgebiete, Klima und ökologische Stabilität geschädigt werden können', logic:'viele Besucher -> hoher Ressourcenverbrauch -> Umweltbelastung -> langfristige Schäden'},
    {name:'Nachteil 2: Belastung der lokalen Bevölkerung', obs:['Innenstädte werden überfüllt','Mieten steigen','Einheimische fühlen sich verdrängt','Alltag wird durch Lärm und Verkehr erschwert'], exp:['Tourismus verändert Wohn- und Lebensräume','Ferienwohnungen verdrängen normalen Wohnraum','Einwohner erleben ihre Stadt zunehmend als Konsumort für Besucher'], ex:['Airbnb-Wohnungen statt Mietwohnungen','Lärm in Altstädten','überfüllte Busse','Restaurants nur noch für Touristen'], res:['höhere Lebenshaltungskosten','weniger Wohnraum','Frustration','Verlust von Lebensqualität'], short:'Alltag der Einheimischen schwieriger wird', long:'soziale Spannungen und Ablehnung gegenüber Touristen entstehen können', logic:'touristische Nachfrage -> steigende Preise und Überfüllung -> Belastung der Bevölkerung'},
    {name:'Nachteil 3: Verlust kultureller Authentizität', obs:['Traditionen werden für Touristen inszeniert','Souvenirläden verdrängen lokale Geschäfte','Orte passen sich Erwartungen der Besucher an'], exp:['Kultur wird zur Ware, wenn sie vor allem verkauft werden soll','lokale Identität kann vereinfacht oder verzerrt dargestellt werden','authentisches Alltagsleben tritt in den Hintergrund'], ex:['standardisierte Souvenirs','Folklore nur für Shows','Restaurants mit touristischen Speisekarten','historische Viertel als Kulisse'], res:['Kommerzialisierung von Kultur','Verlust echter Traditionen','oberflächliche Begegnungen','Veränderung lokaler Identität'], short:'Kultur stärker vermarktet als gelebt wird', long:'lokale Identität und authentische Traditionen geschwächt werden', logic:'Touristenerwartungen -> Inszenierung -> Kommerzialisierung -> Verlust von Authentizität'},
    {name:'Nachteil 4: Abhängigkeit vom Tourismussektor', obs:['Regionen konzentrieren sich stark auf Tourismus','Einnahmen schwanken saisonal','Krisen treffen touristische Orte besonders hart'], exp:['wenn eine Region wirtschaftlich zu sehr vom Tourismus abhängt, wird sie verwundbar','Saisonarbeit ist unsicher','andere Wirtschaftsbereiche können vernachlässigt werden'], ex:['leere Hotels in Krisenzeiten','Arbeitslosigkeit außerhalb der Saison','Pandemie oder Naturkatastrophen stoppen Reisen'], res:['wirtschaftliche Unsicherheit','saisonale Arbeitslosigkeit','einseitige Entwicklung','Abhängigkeit von globalen Reisetrends'], short:'Einnahmen stark schwanken', long:'Regionen wirtschaftlich instabil und krisenanfällig werden', logic:'einseitiger Tourismus -> Abhängigkeit -> Krisenanfälligkeit -> wirtschaftliche Unsicherheit'}
  ], ['die Umweltbelastung','der Ressourcenverbrauch','die Überfüllung','die Verdrängung','die Lebensqualität','die Kommerzialisierung','die kulturelle Authentizität','die Saisonabhängigkeit','die Wohnraumknappheit','die touristische Monostruktur','die CO2-Emissionen','die soziale Spannung'], ['die Umwelt belasten','Ressourcen verbrauchen','Wohnraum verdrängen','Lebensqualität beeinträchtigen','Kultur kommerzialisieren','Abhängigkeit verstärken','Preise erhöhen','soziale Spannungen auslösen'], ['Ein zentraler Nachteil des Massentourismus liegt in der Belastung von Umwelt und Ressourcen.','Besonders problematisch ist, dass touristische Nachfrage den Alltag der Einheimischen verändern kann.','Hinzu kommt, dass lokale Kultur häufig kommerzialisiert wird.','Langfristig kann eine einseitige Abhängigkeit vom Tourismus entstehen.'], ['Ein wesentlicher Nachteil des Massentourismus liegt in der Umweltbelastung. Große Besucherzahlen führen zu mehr Müll, Verkehr, Wasserverbrauch und Energiebedarf. Besonders empfindliche Naturgebiete können dadurch dauerhaft geschädigt werden. Wenn Strände, Nationalparks oder historische Städte ständig überfüllt sind, leidet nicht nur die Natur, sondern auch die Lebensqualität.','Ein weiterer Nachteil betrifft die lokale Bevölkerung. In beliebten Städten steigen häufig Mieten und Preise, weil Wohnungen als Ferienunterkünfte genutzt werden. Einheimische können sich ihren eigenen Wohnraum schwerer leisten und erleben ihren Alltag als zunehmend belastet. Dadurch entstehen soziale Spannungen zwischen Touristen, Vermietern und Bewohnern.'], ['Erkläre den Zusammenhang zwischen Massentourismus und Ressourcenverbrauch.','Schreibe einen Absatz über steigende Mieten in Tourismusstädten.','Nutze die Wörter Kommerzialisierung, Authentizität und Saisonabhängigkeit.']));

  applyLong('t23', build('E-Books – Nachteile · C1/C2 Nachteilsabsatz','E_Books_Nachteile_C1_C2_Konuanlatimi(1).docx','E-Books sind praktisch, können aber Lesekonzentration, Besitzgefühl, Datenschutz, Augengesundheit und die kulturelle Bedeutung gedruckter Bücher beeinträchtigen.','Die Quelle zu E-Books beschreibt nicht nur technische Nachteile, sondern auch kulturelle und soziale Aspekte. Ein digitales Buch ist leicht zugänglich, aber die Nutzung hängt von Geräten, Akkus, Plattformen und technischen Bedingungen ab. In einer C1/C2-Erörterung sollte man deshalb erklären, warum digitale Bequemlichkeit auch neue Abhängigkeiten und Verluste erzeugen kann.',[
    {name:'Nachteil 1: Abhängigkeit von Technik und Geräten', obs:['E-Books benötigen E-Reader, Tablet oder Smartphone','Akkus können leer sein','Dateiformate und Plattformen unterscheiden sich','technische Probleme stören das Lesen'], exp:['anders als gedruckte Bücher sind E-Books an technische Infrastruktur gebunden','Lesen wird abhängig von Gerät, Software, Konto und Strom','wenn eine Plattform verschwindet oder Dateien nicht kompatibel sind, kann Zugang erschwert werden'], ex:['Akku ist auf Reisen leer','E-Reader geht kaputt','Datei lässt sich nicht öffnen','gekauftes Buch ist an ein Konto gebunden'], res:['weniger Unabhängigkeit','technische Unsicherheit','eingeschränkter Zugriff','Frustration beim Lesen'], short:'Lesen durch technische Bedingungen unterbrochen werden kann', long:'Nutzer stärker von Geräten, Plattformen und digitalen Anbietern abhängig werden', logic:'digitales Format -> Geräteabhängigkeit -> technische Probleme -> eingeschränkter Zugang'},
    {name:'Nachteil 2: Weniger sinnliches Leseerlebnis und geringeres Besitzgefühl', obs:['gedruckte Bücher kann man anfassen, sammeln und weitergeben','E-Books wirken weniger materiell','Bibliotheken und Bücherregale verlieren Bedeutung'], exp:['Lesen ist nicht nur Informationsaufnahme, sondern auch Erfahrung','Papier, Geruch, Gewicht und sichtbarer Fortschritt können Motivation beeinflussen','bei digitalen Dateien entsteht weniger Besitzgefühl'], ex:['kein Bücherregal','kein Blättern im Papier','keine persönliche Widmung','schwierigeres Verschenken oder Vererben digitaler Bücher'], res:['weniger emotionale Bindung','schwächeres Sammlungsgefühl','Verlust traditioneller Lesekultur','geringere Wertschätzung des Buchobjekts'], short:'das Lesen unpersönlicher wirken kann', long:'die kulturelle Bedeutung gedruckter Bücher und persönlicher Buchsammlungen geschwächt werden kann', logic:'digitale Datei -> weniger Materialität -> schwächeres Besitzgefühl -> Verlust von Lesekultur'},
    {name:'Nachteil 3: Ablenkung und Konzentrationsprobleme', obs:['Lesen findet oft auf Geräten mit anderen Apps statt','Benachrichtigungen lenken ab','digitale Umgebung fördert schnelles Wechseln','lange Texte werden oberflächlicher gelesen'], exp:['digitale Geräte sind multifunktional','dadurch konkurriert das Buch mit Nachrichten, Internet und sozialen Medien','konzentriertes Lesen kann schwerer fallen'], ex:['Tablet zeigt Nachrichten','Leser springt zwischen Buch und Browser','Smartphone lenkt während der Lektüre ab','Notizen werden durch Apps unterbrochen'], res:['geringere Konzentration','oberflächlicheres Lesen','weniger Textverständnis','schnellere Ermüdung'], short:'Aufmerksamkeit leichter unterbrochen wird', long:'Lesegewohnheiten oberflächlicher und weniger konzentriert werden können', logic:'digitales Gerät -> Ablenkung -> Konzentrationsverlust -> schwächeres Textverständnis'},
    {name:'Nachteil 4: Datenschutz, Plattformbindung und Augenbelastung', obs:['digitale Anbieter können Leseverhalten speichern','Käufe sind oft an Konten gebunden','Bildschirme können Augen ermüden','Nutzer akzeptieren Plattformregeln'], exp:['E-Books erzeugen Daten über Lesezeit, Markierungen und Käufe','Besitz wird teilweise durch Nutzungsrechte ersetzt','Bildschirmlektüre kann körperlich anstrengend sein','Plattformbindung verringert Selbstbestimmung'], ex:['Anbieter sieht, welche Bücher gelesen werden','Buch kann nicht frei weiterverkauft werden','lange Bildschirmzeit verursacht Müdigkeit','Konto-Sperre erschwert Zugriff'], res:['weniger Datenschutz','weniger Kontrolle über gekaufte Inhalte','Augenbelastung','Abhängigkeit von Anbietern'], short:'Nutzer weniger Kontrolle über Daten und Zugriff haben', long:'Lesen stärker kommerziell, technisch und datenabhängig organisiert wird', logic:'Plattformbindung -> Datenspuren und Nutzungsrechte -> weniger Kontrolle -> digitale Abhängigkeit'}
  ], ['die Geräteabhängigkeit','die Plattformbindung','das Besitzgefühl','die Lesekultur','die Konzentrationsfähigkeit','die Ablenkung','der Datenschutz','das Nutzungsrecht','die Augenbelastung','die Kompatibilität','die digitale Infrastruktur','die Selbstbestimmung'], ['von Geräten abhängig sein','den Zugriff erschweren','Lesekultur verändern','Konzentration beeinträchtigen','Daten speichern','Selbstbestimmung einschränken','Augen belasten','an Plattformen gebunden sein'], ['Ein zentraler Nachteil von E-Books liegt in der Abhängigkeit von technischen Geräten.','Darüber hinaus kann das digitale Format das sinnliche Leseerlebnis schwächen.','Problematisch ist auch, dass digitale Geräte leichter ablenken.','Langfristig können Plattformbindung und Datenschutzfragen die Selbstbestimmung der Leser einschränken.'], ['Ein wesentlicher Nachteil von E-Books besteht in der Abhängigkeit von Technik. Während ein gedrucktes Buch jederzeit gelesen werden kann, benötigen digitale Bücher ein funktionierendes Gerät, ausreichend Akku und kompatible Software. Dadurch kann der Zugang zum Buch durch technische Probleme eingeschränkt werden. Besonders auf Reisen oder bei Geräteausfällen zeigt sich, dass digitale Bequemlichkeit neue Abhängigkeiten erzeugt.','Ein weiterer negativer Aspekt betrifft das Leseerlebnis. Gedruckte Bücher haben eine materielle und emotionale Qualität: Man kann sie anfassen, verschenken, sammeln und weitergeben. Bei E-Books fehlt dieses Besitzgefühl häufig, weil es sich nur um Dateien oder Nutzungsrechte handelt. Langfristig kann dadurch die traditionelle Buch- und Lesekultur geschwächt werden.'], ['Erkläre den Unterschied zwischen Besitz eines Buches und Nutzungsrecht an einem E-Book.','Formuliere einen Absatz über digitale Ablenkung beim Lesen.','Nutze die Begriffe Plattformbindung, Datenschutz und Lesekultur.']));
})();