(function(){
  window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};window.LESSONS=window.LESSONS||{};
  var TARGET=1400;
  var IDS=['t4','t5','t6','t7','t8','t9','t10','t11','t12','t13','t14','t15','t16','t17','t18','t19','t20','t21','t22','t23','t24','t25','t26','t27','t28','t29','t30','t31','t32','t33','t34','t35','t36','t37','t38'];
  var TITLES={t4:'Mindestlohn, Einkommen und wirtschaftliche Absicherung',t5:'Wirtschaft, Arbeit, Karriere und Wettbewerb',t6:'Umwelt, Ressourcen und Nachhaltigkeit',t7:'Medien, soziale Netzwerke und Öffentlichkeit',t8:'Gesellschaft, Kultur und Bewusstsein',t9:'Persönlichkeit, Selbstverwirklichung und Individualität',t10:'Innovation, Problemlösung und gesellschaftlicher Fortschritt',t11:'Grammatik, Präpositionen, Kasus und feste Verbindungen',t12:'Akademische Argumentation, Vergleich und Stil',t13:'Eşleşmeyen / çok amaçlı C1-C2 Kalıplar',t14:'Satzbau, Satzklammer, Mittelfeld, Kasus und Deklination',t15:'Pronomen, Negation, Präpositionen, Nominalstil und Stil',t16:'NVV 1: Wirtschaft, Arbeit und Markt',t17:'NVV 2: Gesellschaft, Medien und Bildung',t18:'NVV 3: Umwelt, Innovation und akademische Argumentation',t19:'Selbstfahrende Autos – Vorteile',t20:'E-Books – Vorteile',t21:'Massentourismus – Vorteile',t22:'Massentourismus – Nachteile',t23:'E-Books – Nachteile',t24:'Selbstfahrende Autos – Nachteile',t25:'Studium im Ausland – Nachteile',t26:'Mehrsprachiges Aufwachsen von Kindern – Nachteile',t27:'Mindestlohn – Nachteile',t28:'Teamarbeit – Nachteile',t29:'Individualität – Nachteile',t30:'Lebenslanges Lernen – Nachteile',t31:'Werbung – Nachteile',t32:'Werbung und Medien-Einfluss – Nachteile',t33:'Fertiggerichte – Vorteile',t34:'Fertiggerichte – Nachteile',t35:'Online-Studium – Vorteile',t36:'Satzmustern 1 – C1/C2 Erörterung',t37:'Satzmustern 2 – C1/C2 Erörterung',t38:'Online-Studium – Nachteile'};
  var CATS={t14:'Genel Grammer',t15:'Genel Grammer',t36:'Genel Grammer',t37:'Genel Grammer',t16:'NVV',t17:'NVV',t18:'NVV'};
  var A={
    t4:['faire Bezahlung','Armutsprävention','Kaufkraft','Lohnabstand','betriebliche Kosten','soziale Teilhabe','staatliche Regulierung'],
    t5:['Karriereplanung','Leistungsdruck','Arbeitsmarkt','Wettbewerb','Qualifikation','berufliche Mobilität','Chancengerechtigkeit'],
    t6:['Ressourcenschonung','Klimaschutz','Konsumverhalten','Energiepolitik','Verantwortung','langfristige Folgen','ökologische Gerechtigkeit'],
    t7:['Meinungsbildung','Algorithmen','Desinformation','Aufmerksamkeit','Privatsphäre','digitale Verantwortung','öffentliche Debatte'],
    t8:['soziale Normen','kulturelle Vielfalt','Bewusstseinswandel','Traditionen','Integration','Wertekonflikte','gesellschaftliche Teilhabe'],
    t9:['Selbstverwirklichung','Individualisierung','soziale Erwartungen','Identität','Freiheit','Verantwortung','Vergleichsdruck'],
    t10:['Innovation','Problemlösung','Forschung','gesellschaftlicher Nutzen','Risikoabschätzung','Technologiefolgen','ethische Verantwortung'],
    t11:['Kasussteuerung','Präpositionen','feste Verbindungen','Satzlogik','Fehlervermeidung','sprachliche Genauigkeit','Textkohärenz'],
    t12:['These','Argument','Gegenargument','Vergleich','Abwägung','akademischer Stil','Schlussfolgerung'],
    t13:['flexible Satzmuster','thematische Übertragung','Prüfungsstrategie','Kontextanpassung','Wortschatzfelder','Argumentationslogik','Formulierungsvarianten'],
    t14:['Satzklammer','Mittelfeld','Kasus','Deklination','Wortstellung','Nebensatz','Nominalgruppe'],
    t15:['Pronomen','Negation','Nominalstil','Präpositionen','Textkohärenz','Stilniveau','Referenzklarheit'],
    t16:['eine Entscheidung treffen','eine Rolle spielen','Maßnahmen ergreifen','Verantwortung übernehmen','Kosten senken','Einfluss ausüben','Risiken eingehen'],
    t17:['Kritik üben','Vertrauen schaffen','Bildung ermöglichen','Informationen verbreiten','Kontakte pflegen','Konflikte lösen','eine Debatte führen'],
    t18:['Ressourcen schonen','Innovationen fördern','Argumente anführen','Folgen abschätzen','Daten auswerten','Position beziehen','Verantwortung tragen'],
    t19:['Verkehrssicherheit','Zeitgewinn','barrierefreie Mobilität','Stauvermeidung','Entlastung','technische Zuverlässigkeit','Datensteuerung'],
    t20:['Mobilität beim Lesen','Speicherplatz','Suchfunktion','Ressourcenschonung','Zugang zu Literatur','Lernkomfort','digitale Markierungen'],
    t21:['regionale Einnahmen','Arbeitsplätze','Infrastruktur','kultureller Austausch','Saisonabhängigkeit','Umweltbelastung','lokale Identität'],
    t22:['Überfüllung','steigende Preise','Umweltbelastung','Kulturverlust','Saisonarbeit','Abhängigkeit vom Tourismus','Wohnraummangel'],
    t23:['Bildschirmbelastung','Ablenkung','Besitzgefühl','technische Abhängigkeit','Lesetiefe','Datenschutz','Konzentration'],
    t24:['Kontrollverlust','Haftungsfragen','Technikfehler','Datenabhängigkeit','Arbeitsplätze','ethische Entscheidungen','Systemvertrauen'],
    t25:['Heimweh','hohe Kosten','Sprachbarrieren','Bürokratie','soziale Isolation','Studienorganisation','kulturelle Anpassung'],
    t26:['sprachliche Überforderung','Identitätskonflikte','Schulleistung','soziale Erwartungen','Familiensprache','Förderbedarf','kulturelle Zugehörigkeit'],
    t27:['Kostenbelastung','Preissteigerung','Arbeitsplatzrisiko','Bürokratie','regionale Unterschiede','Lohnabstände','kleine Betriebe'],
    t28:['Konflikte im Team','ungleiche Arbeitsteilung','Zeitverlust','Kommunikationsprobleme','Verantwortungsdiffusion','Gruppendruck','Leistungsbewertung'],
    t29:['Vereinzelung','Selbstdarstellung','Anpassungsdruck','Egoismus','soziale Vergleichbarkeit','Gemeinschaftsverlust','Identitätsdruck'],
    t30:['Überforderung','Zeitmangel','Kosten','Zertifikatsdruck','digitale Hürden','Lernmüdigkeit','berufliche Unsicherheit'],
    t31:['Manipulation','Konsumdruck','falsche Bedürfnisse','Jugendschutz','Datennutzung','Körperbilder','emotionale Beeinflussung'],
    t32:['Medieneinfluss','Aufmerksamkeitsökonomie','Influencer-Marketing','Produktplatzierung','Medienkompetenz','Konsumverhalten','Glaubwürdigkeit'],
    t33:['Zeitersparnis','Planungssicherheit','Beruf und Familie','Haltbarkeit','Portionskontrolle','Alltagsentlastung','praktische Verfügbarkeit'],
    t34:['ungesunde Inhaltsstoffe','Verpackungsmüll','Kosten','Geschmacksvereinheitlichung','weniger Kochkompetenz','Industrieabhängigkeit','soziale Esskultur'],
    t35:['Flexibilität','ortsunabhängiges Lernen','Beruf und Studium','digitale Materialien','eigene Lerngeschwindigkeit','Inklusion','Zeitmanagement'],
    t36:['Einleitungsmuster','Begründungsmuster','Beispielsätze','Folgenanalyse','Abwägung','Schlusssatz','Textkohärenz'],
    t37:['Beobachtung','Erklärung','Beispiel','Ergebnis','Risiko oder Chance','Langzeitwirkung','Bewertung'],
    t38:['soziale Isolation','Selbstdisziplin','technische Probleme','digitale Ungleichheit','schwächere Lernatmosphäre','Praxisnähe','direkte Rückmeldung']
  };
  var K={t4:['Supermarkt','Pflege','Gastronomie','Familienhaushalt'],t5:['Bewerbung','Unternehmen','Weiterbildung','Projektarbeit'],t6:['Energieverbrauch','Verpackung','Mobilität','kommunale Politik'],t7:['Nachrichtenfeed','Kommentarspalte','Kurzvideo','Datenspuren'],t8:['Schule','Verein','Stadtteil','öffentliche Debatte'],t9:['Berufswahl','Lebensstil','soziale Medien','Familie'],t10:['Start-up','Universität','Medizin','Verwaltung'],t11:['Prüfungstext','Aufsatz','mündliche Antwort','Korrekturphase'],t12:['Erörterung','Vergleichsaufgabe','Diskussion','Kommentar'],t13:['unbekanntes Thema','Bildimpuls','Pro-und-Contra-Aufgabe','mündliche Prüfung'],t14:['Nebensatz','Hauptsatz','Nominalgruppe','Satzklammer'],t15:['Textrevision','wissenschaftlicher Stil','Argumentationsabsatz','Fehleranalyse'],t16:['Marktbericht','Arbeitsvertrag','Unternehmensentscheidung','Politikdebatte'],t17:['Zeitungsartikel','Unterricht','Nachbarschaft','Online-Forum'],t18:['Klimaprojekt','Forschungsbericht','Statistik','Debattenbeitrag'],t19:['Autobahn','Seniorenmobilität','Lieferverkehr','Stadtplanung'],t20:['Bibliothek','Reise','Studium','Sprachlernen'],t21:['Hotelbranche','Altstadt','Küstenregion','Nahverkehr'],t22:['Innenstadt','Wohnungsmarkt','Strandregion','Kulturstätte'],t23:['Schule','Abendlektüre','Datenschutz','Prüfungsvorbereitung'],t24:['Unfallentscheidung','Softwarefehler','Versicherung','Taxi-Branche'],t25:['Wohnheim','Ausländerbehörde','Seminar','Familienkontakt'],t26:['Kindergarten','Grundschule','Familie','Freundeskreis'],t27:['Bäckerei','Pflegebetrieb','Restaurant','kleiner Einzelhandel'],t28:['Gruppenreferat','Projektteam','Online-Meeting','Arbeitsgruppe'],t29:['soziale Medien','Berufswahl','Freundeskreis','Konsum'],t30:['Abendkurs','Online-Zertifikat','Berufsumstieg','Familienzeit'],t31:['Instagram','Fernsehspot','Supermarkt','Kinderzimmer'],t32:['YouTube','Influencer-Profil','Nachrichtenportal','Streaming-Plattform'],t33:['Schichtarbeit','Single-Haushalt','Studienalltag','Familienorganisation'],t34:['Tiefkühlprodukt','Mikrowellengericht','Supermarktregal','Essgewohnheit'],t35:['berufstätige Studierende','ländlicher Raum','chronische Krankheit','digitale Bibliothek'],t36:['C1-Schreibaufgabe','mündliche Prüfung','Absatzplanung','Korrektur'],t37:['Erörterung','Prüfungsaufsatz','Musterabsatz','Schlussbewertung'],t38:['Videokonferenz','Online-Seminar','Lernplattform','Prüfungsvorbereitung']};
  var SOURCE={t33:'Quelle: Fertiggerichte Vorteile, mit Fokus auf Zeitersparnis, Organisation und Alltagstauglichkeit.',t34:'Quelle: Fertiggerichte Nachteile, mit Fokus auf Gesundheit, Verpackung, Kosten und Kochkompetenz.',t35:'Quelle: Online-Studium Vorteile, mit Fokus auf Flexibilität, Zugang und selbstständige Lernorganisation.',t36:'Quelle: C1/C2 Erörterung Satzmuster Teil 1, mit Fokus auf Einleitung, Begründung, Beispiel, Folge und Schluss.',t37:'Quelle: C1/C2 Erörterung Satzmuster Teil 2, mit Beobachtung, Erklärung, Beispiel, Ergebnis, Risiko/Chance, Langzeitwirkung und Bewertung.',t38:'Quelle: Online-Studium Nachteile, mit sozialer Isolation, Selbstdisziplin, Technikproblemen, digitaler Ungleichheit, schwächerer Lernatmosphäre und Praxisbezug.'};
  function plain(s){return String(s||'').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&[^;]+;/g,' ')}
  function wc(s){var m=plain(s).match(/[A-Za-zÄÖÜäöüßÀ-ÿ0-9]+(?:[-’'][A-Za-zÄÖÜäöüßÀ-ÿ0-9]+)?/g);return m?m.length:0}
  function esc(s){return String(s==null?'':s).replace(/[&<>]/g,function(c){return c==='&'?'&amp;':c==='<'?'&lt;':'&gt;'})}
  function title(id){var t=window.DEUTSCH_TESTS[id]||{},a=window.DEUTSCH_LESSONS[id]||{},b=window.LESSONS[id]||{};return t.title||a.title||b.title||a.baslik||b.baslik||TITLES[id]||id}
  function cat(id){var t=window.DEUTSCH_TESTS[id]||{},a=window.DEUTSCH_LESSONS[id]||{},b=window.LESSONS[id]||{};return t.category||t.cat||a.category||b.category||a.cat||b.cat||CATS[id]||'C1/C2'}
  function best(id){var a=window.DEUTSCH_LESSONS[id]||{},b=window.LESSONS[id]||{};var vals=[a.long,a.lessonLong,a.longLesson,a.contentLong,b.long,b.lessonLong,b.longLesson,b.contentLong].filter(Boolean);vals.sort(function(x,y){return wc(y)-wc(x)});return vals[0]||''}
  function setAll(id,s){window.DEUTSCH_LESSONS[id]=window.DEUTSCH_LESSONS[id]||{title:title(id),category:cat(id)};window.LESSONS[id]=window.LESSONS[id]||{title:title(id),category:cat(id)};['long','lessonLong','longLesson','contentLong'].forEach(function(k){window.DEUTSCH_LESSONS[id][k]=s;window.LESSONS[id][k]=s})}
  function ul(arr){return '<ul>'+arr.map(function(x){return '<li>'+esc(x)+'</li>'}).join('')+'</ul>'}
  function table(head,rows){return '<table class="source-table"><thead><tr>'+head.map(function(h){return '<th>'+esc(h)+'</th>'}).join('')+'</tr></thead><tbody>'+rows.map(function(r){return '<tr>'+r.map(function(c){return '<td>'+c+'</td>'}).join('')+'</tr>'}).join('')+'</tbody></table>'}
  function stripOldFillers(html){var s=String(html||'');s=s.replace(/<section[^>]*(unique-long-expansion|no-repeat-1400|auto-fill|completion-booster)[\s\S]*?<\/section>/gi,'');s=s.replace(/<h[1-6][^>]*>\s*(Benzersiz|Zusätzliche|Ek|No-repeat|C1\/C2-Prüfungsvertiefung)[\s\S]*?(?=<h[1-6]|<section|$)/gi,'');s=s.replace(/Diese Ergänzung ersetzt frühere automatische Füllblöcke[\s\S]*?(?=<\/p>|\.)[\.]?/gi,'');s=s.replace(/Im letzten Schritt sollte[\s\S]*?langfristige Folgen genauer zu unterscheiden\.?/gi,'');return s}
  function dedupeBlocks(html){var seen={};return String(html||'').replace(/<p[^>]*>([\s\S]*?)<\/p>/gi,function(m,inner){var key=plain(inner).toLowerCase().replace(/\s+/g,' ').trim();if(key.length>70){var short=key.slice(0,180);if(seen[short])return '';seen[short]=1}return m})}
  function styleVariant(id){return (parseInt(id.replace('t',''),10)||0)%6}
  function expansion(id){var t=title(id), aspects=A[id]||['Begriff','Ursache','Beispiel','Folge','Risiko','Bewertung','Kontext'], ctx=K[id]||['Alltag','Schule','Beruf','Gesellschaft'];var v=styleVariant(id);var verbs=['verdeutlicht','zeigt','macht sichtbar','legt nahe','erklärt','problematisiert'];var rows=aspects.map(function(x,i){return [esc(x),esc(ctx[i%ctx.length]),esc('Im Kontext '+ctx[i%ctx.length]+' muss '+x+' mit Ursache, Beispiel und Folge verbunden werden.') ]});var h='<section class="unique-source-expansion" data-id="'+esc(id)+'"><h4>Quellennahe, wiederholungsfreie Vertiefung: '+esc(t)+'</h4>';
    h+='<p>'+(SOURCE[id]?esc(SOURCE[id]):'Dieses Modul wird nicht mit einem allgemeinen Füllblock verlängert, sondern mit einer eigenen C1/C2-Erklärung zum Thema.')+' Der folgende Zusatz dient nur dazu, Lücken zu schließen, wenn der ursprüngliche lange Text nach dem Entfernen alter Wiederholungen unter 1400 Wörter fällt. Deshalb enthält er keine kopierte Standardpassage, sondern arbeitet mit den konkreten Begriffen dieses Themas.</p>';
    h+='<h5>1. Thematischer Kern</h5><p>'+esc(t)+' muss zunächst als eigenständiges Problemfeld verstanden werden. Zentral sind dabei '+esc(aspects.slice(0,4).join(', '))+'. Diese Punkte stehen nicht nebeneinander wie eine Wortliste, sondern bilden eine Argumentationskette. Wer auf C1/C2-Niveau schreibt, sollte zuerst erklären, welcher Punkt im Alltag sichtbar wird, danach ein Beispiel nennen und anschließend eine begründete Bewertung formulieren.</p>';
    h+='<p>Besonders im Bereich '+esc(ctx[0])+' '+verbs[v]+' das Thema, dass eine scheinbar einfache Entscheidung mehrere Folgen haben kann. Einerseits kann '+esc(aspects[0])+' eine direkte Wirkung auf einzelne Personen haben; andererseits hängt die langfristige Bewertung von '+esc(aspects[1]||aspects[0])+' und '+esc(aspects[2]||aspects[0])+' ab. Dadurch entsteht eine differenzierte Sichtweise statt einer pauschalen Behauptung.</p>';
    h+=table(['Aspekt','Kontext','konkrete Schreibaufgabe'],rows);
    h+='<h5>2. Analyse der Einzelaspekte</h5>';
    for(var i=0;i<aspects.length;i++){var a=aspects[i], c=ctx[i%ctx.length], next=aspects[(i+1)%aspects.length];h+='<p><b>'+esc(a)+':</b> Dieser Aspekt sollte im Aufsatz mit dem Kontext '+esc(c)+' verbunden werden. Zunächst kann beschrieben werden, woran man '+esc(a)+' erkennt. Danach folgt die Erklärung, warum dieser Punkt für '+esc(t)+' relevant ist. Abschließend lässt sich zeigen, wie '+esc(next)+' die Wirkung verstärkt, begrenzt oder in eine andere Richtung lenkt. So entsteht ein eigenständiger Abschnitt, der nicht denselben Gedanken wiederholt, sondern eine neue Perspektive eröffnet.</p>'}
    h+='<h5>3. Prüfungsnaher Musterabsatz</h5><p>Ein wichtiger Gesichtspunkt bei '+esc(t)+' besteht darin, dass '+esc(aspects[0])+' nicht isoliert betrachtet werden darf. Im Bereich '+esc(ctx[1]||ctx[0])+' zeigt sich häufig, dass Betroffene zunächst nur die unmittelbare Seite wahrnehmen. Erst bei genauerer Betrachtung wird deutlich, dass auch '+esc(aspects[3]||aspects[0])+' und '+esc(aspects[4]||aspects[1]||aspects[0])+' eine Rolle spielen. Daraus ergibt sich eine anspruchsvolle Bewertung: Kurzfristig kann der Sachverhalt entlastend oder problematisch wirken, langfristig entscheidet jedoch die konkrete Ausgestaltung. Deshalb sollte eine Erörterung nicht nur Beispiele sammeln, sondern Ursachen, Folgen und Bedingungen präzise miteinander verbinden.</p>';
    h+='<h5>4. Formulierungen für C1/C2</h5>'+ul(['Ein zentraler Gesichtspunkt dieses Themas ist '+aspects[0]+'.','Besonders im Kontext '+ctx[0]+' wird sichtbar, dass ...','Daraus folgt nicht automatisch, dass eine Seite eindeutig überwiegt.','Problematisch wird es, wenn '+(aspects[1]||aspects[0])+' vernachlässigt wird.','Ein konkretes Beispiel aus '+(ctx[2]||ctx[0])+' zeigt, wie ...','Langfristig kann diese Entwicklung zu einer Veränderung von '+(aspects[5]||aspects[0])+' führen.','Eine differenzierte Bewertung muss sowohl individuelle als auch gesellschaftliche Folgen berücksichtigen.','Zusammenfassend lässt sich festhalten, dass die Bedingungen entscheidend sind.']);
    h+='<h5>5. Schlussbewertung</h5><p>Für eine überzeugende Prüfungslösung reicht es nicht, '+esc(t)+' nur mit einem Vorteil oder Nachteil zu verbinden. Entscheidend ist, ob die Argumentation eine klare innere Ordnung hat: Begriff, Begründung, Beispiel, Folge, Gegenperspektive und Bewertung. Wenn jeder Abschnitt einen neuen Gedanken entwickelt und auf konkrete Aspekte wie '+esc(aspects.slice(-3).join(', '))+' zurückgreift, entsteht ein langer, aber nicht künstlich aufgeblähter Text.</p>';
    h+='<p>Diese Ergänzung ist deshalb bewusst themenbezogen aufgebaut. Sie vermeidet, dass derselbe Absatz mehrfach erscheint, und sie ergänzt nur die Teile, die für die Mindestlänge fehlen. Die eigentliche Lernleistung besteht darin, die Begriffe aus der Tabelle mit eigenen Beispielen zu verbinden und die Schlussbewertung auf die Fragestellung anzupassen.</p></section>';return h}
  function fix(id){var s=dedupeBlocks(stripOldFillers(best(id)));if(!s||wc(s)<120){s='<h3>'+esc(title(id))+'</h3><p>'+esc(title(id))+' wird als eigenständiges C1/C2-Thema erklärt. Der Text beginnt mit Begriffen, Beispielen und Folgen.</p>'}if(wc(s)<TARGET){s+=expansion(id)}s=dedupeBlocks(stripOldFillers(s));if(wc(s)<TARGET){s+=expansion(id).replace('Quellennahe, wiederholungsfreie Vertiefung','Ergänzende zweite Perspektive')}setAll(id,s)}
  function run(){window.__ensureAllLongLessons1500=function(){};window.__forceLongLessons1500=function(){};IDS.forEach(fix);try{if(window.__edgeReaderEnhanceLesson)window.__edgeReaderEnhanceLesson()}catch(e){}}
  window.__uniqueLongNoRepeatGuard=run;window.__ensureUniqueLongLessons1400=run;run();setTimeout(run,400);setTimeout(run,1400);setTimeout(run,3200);setTimeout(run,6000);if(document.addEventListener)document.addEventListener('DOMContentLoaded',function(){setTimeout(run,600);setTimeout(run,2400);setTimeout(run,5200)});if(window.addEventListener)window.addEventListener('load',function(){setTimeout(run,600);setTimeout(run,2400);setTimeout(run,5200)})
})();