(function(){
  const M_LONG=`<h3>Mindestlohn – Nachteile · C1/C2-Nachteilsabsatz · Lang</h3>
<h4>1. Ziel und Grundthese</h4>
<p>Dieses Material bereitet gezielt auf einen ausführlichen Nachteilsabsatz zum Thema Mindestlohn vor. Der Mindestlohn soll Arbeitnehmer vor sehr niedrigen Löhnen schützen; in einem kritischen Nachteilsabsatz geht es jedoch darum, mögliche wirtschaftliche Nebenwirkungen differenziert zu erklären. Wichtig ist: Man argumentiert nicht pauschal gegen soziale Gerechtigkeit, sondern zeigt, unter welchen Bedingungen ein gesetzlich festgelegter Mindestlohn problematisch werden kann.</p>
<p><b>Grundthese:</b> Der Mindestlohn kann zwar sozialpolitisch sinnvoll erscheinen, weil er sehr niedrige Löhne begrenzen soll; gleichzeitig kann er wirtschaftliche Nebenwirkungen haben, wenn Unternehmen steigende Personalkosten nicht durch höhere Produktivität, höhere Preise oder größere Einnahmen ausgleichen können.</p>
<p>Auf C1/C2-Niveau sollte man vorsichtig formulieren: <b>kann</b>, <b>könnte</b>, <b>unter Umständen</b>, <b>insbesondere in arbeitsintensiven Branchen</b>, <b>bei kleinen Betrieben</b> und <b>langfristig betrachtet</b> sind geeignete Redemittel.</p>
<h4>2. Nachteil 1: Finanzielle Belastung kleiner Unternehmen</h4>
<p>Der erste zentrale Nachteil betrifft die finanzielle Belastung kleiner Unternehmen. Ein gesetzlicher Mindestlohn erhöht die Personalkosten, wenn Betriebe vorher niedrigere Löhne gezahlt haben. Während große Unternehmen steigende Lohnkosten oft durch höhere Umsätze, effizientere Arbeitsabläufe oder interne Umverteilung ausgleichen können, verfügen kleine Betriebe häufig nur über begrenzte finanzielle Reserven. Besonders betroffen sind arbeitsintensive Branchen mit niedrigen Gewinnspannen, zum Beispiel Gastronomie, Einzelhandel, Reinigung, Lieferdienste, Friseursalons oder kleine Handwerksbetriebe.</p>
<p>Problematisch ist, dass Personalkosten in solchen Betrieben einen großen Teil der Gesamtkosten ausmachen. Wenn der Mindestlohn steigt, steigen nicht nur die Stundenlöhne, sondern häufig auch Lohnnebenkosten, Arbeitgeberbeiträge und organisatorische Kosten. Ein kleines Café kann nicht beliebig mehr Kunden gewinnen, nur weil die Personalkosten steigen. Bleiben die Einnahmen gleich, während die Kosten zunehmen, geraten Gewinnspanne und wirtschaftliche Stabilität unter Druck.</p>
<p>Unternehmen können dann gezwungen sein, Preise anzuheben, Öffnungszeiten zu reduzieren, Investitionen zu verschieben oder auf Neueinstellungen zu verzichten. Dadurch kann auch der Arbeitsdruck für das vorhandene Personal steigen, weil weniger Beschäftigte dieselbe Arbeit erledigen müssen. Gleichzeitig kann die Servicequalität sinken, wenn ein Betrieb mit weniger Personal arbeiten muss.</p>
<p><b>C1/C2-Kernsatz:</b> Ein wesentlicher Nachteil des Mindestlohns liegt darin, dass er insbesondere kleine Unternehmen mit geringen Gewinnspannen finanziell belasten kann, da steigende Personalkosten nicht immer durch höhere Einnahmen ausgeglichen werden können.</p>
<p><b>Musterabsatz:</b> Ein wesentlicher Nachteil des Mindestlohns liegt in der finanziellen Belastung kleiner Unternehmen. Während große Unternehmen steigende Lohnkosten häufig leichter ausgleichen können, verfügen Kleinbetriebe oft nur über begrenzte finanzielle Reserven. Besonders in arbeitsintensiven Branchen mit niedrigen Gewinnspannen, etwa in der Gastronomie, im Einzelhandel oder im Friseurhandwerk, können höhere Personalkosten schnell wirtschaftlichen Druck erzeugen. Die Folge könnte sein, dass Betriebe Preise erhöhen, Öffnungszeiten reduzieren oder auf Neueinstellungen verzichten. Langfristig betrachtet kann dies die Wettbewerbsfähigkeit kleiner Unternehmen schwächen und die Vielfalt der lokalen Wirtschaft gefährden.</p>
<h4>3. Nachteil 2: Weniger Beschäftigungschancen für geringqualifizierte Arbeitnehmer</h4>
<p>Der zweite wichtige Nachteil betrifft die Beschäftigungschancen geringqualifizierter Arbeitnehmer. Ein Mindestlohn legt eine Lohnuntergrenze fest. Für Arbeitnehmer klingt das zunächst positiv, weil Arbeit nicht unter einem bestimmten Betrag bezahlt werden darf. Für Arbeitgeber entsteht jedoch die Frage, ob die erwartete Produktivität eines Bewerbers die höheren Lohnkosten rechtfertigt. Wenn jede Arbeitsstunde mindestens einen bestimmten Betrag kostet, können Betriebe bei Neueinstellungen vorsichtiger werden.</p>
<p>Besonders betroffen sein können Berufsanfänger, Jugendliche, Langzeitarbeitslose, Menschen ohne abgeschlossene Ausbildung oder Personen mit geringen Sprachkenntnissen. Diese Gruppen benötigen häufig zunächst Einarbeitung, Anleitung und Zeit, um produktiver zu werden. Wenn die Einstiegskosten für Arbeitgeber steigen, sinkt möglicherweise die Bereitschaft, genau diesen Gruppen eine Chance zu geben. Dadurch kann der Mindestlohn unbeabsichtigt den Berufseinstieg erschweren.</p>
<p>Ein Beispiel: Ein kleiner Betrieb möchte eine ungelernte Aushilfe einstellen. Wenn der Mindestlohn jedoch relativ hoch ist, entscheidet sich der Betrieb möglicherweise für eine erfahrenere Person oder verzichtet vollständig auf die Stelle. Somit profitieren zwar Beschäftigte, die bereits Arbeit haben, aber Menschen am Rand des Arbeitsmarktes könnten schwerer in Beschäftigung kommen.</p>
<p><b>C1/C2-Kernsatz:</b> Ein weiterer Nachteil besteht darin, dass der Mindestlohn unbeabsichtigt die Beschäftigungschancen geringqualifizierter Arbeitnehmer verringern kann, weil Arbeitgeber bei höheren Lohnkosten stärker auf Qualifikation, Erfahrung und Produktivität achten.</p>
<p><b>Musterabsatz:</b> Ein weiterer Nachteil des Mindestlohns betrifft die Beschäftigungschancen geringqualifizierter Arbeitnehmer. Wenn Arbeitgeber verpflichtet sind, einen höheren Mindestlohn zu zahlen, achten sie möglicherweise stärker darauf, ob Bewerber bereits Erfahrung, Qualifikation und eine hohe Produktivität mitbringen. Dadurch können Berufsanfänger, Jugendliche oder Menschen ohne abgeschlossene Ausbildung benachteiligt werden. Gerade diese Gruppen sind jedoch häufig auf einfache Einstiegsmöglichkeiten angewiesen, um Berufserfahrung zu sammeln. Somit kann der Mindestlohn unbeabsichtigt den Zugang zum Arbeitsmarkt erschweren und soziale Ungleichheit sogar verstärken.</p>
<h4>4. Nachteil 3: Preissteigerungen und begrenzte reale Kaufkraft</h4>
<p>Der dritte Nachteil betrifft Preissteigerungen. Wenn Unternehmen höhere Lohnkosten tragen müssen, können sie versuchen, diese Kosten an Kunden weiterzugeben. Das geschieht vor allem in Branchen, in denen Personalkosten einen großen Anteil der Gesamtkosten ausmachen. Restaurants, Bäckereien, kleine Geschäfte, Reinigungsunternehmen oder Lieferdienste könnten ihre Preise anheben, um die gestiegenen Kosten auszugleichen.</p>
<p>Auf den ersten Blick scheint ein höherer Mindestlohn die Kaufkraft der Beschäftigten zu stärken. Problematisch wird es jedoch, wenn steigende Löhne gleichzeitig zu steigenden Preisen führen. Dann kann ein Teil des finanziellen Vorteils wieder verloren gehen. Besonders Haushalte mit geringem Einkommen geben einen großen Anteil ihres Geldes für alltägliche Güter und Dienstleistungen aus. Wenn diese teurer werden, fällt die reale Entlastung geringer aus als erwartet.</p>
<p>Außerdem können Preissteigerungen die Nachfrage schwächen. Wenn ein kleines Restaurant seine Preise deutlich erhöht, könnten weniger Kunden kommen. Sinkt die Nachfrage, geraten Unternehmen erneut unter Druck. Dadurch entsteht ein negativer Kreislauf: höhere Lohnkosten führen zu höheren Preisen; höhere Preise senken möglicherweise die Nachfrage; sinkende Nachfrage kann wiederum Arbeitsplätze gefährden.</p>
<p>In einer Prüfung sollte man nicht behaupten, der Mindestlohn verursache automatisch Inflation. Präziser ist: Der Mindestlohn <b>kann</b> in bestimmten arbeitsintensiven Branchen zu Preissteigerungen beitragen, wenn Unternehmen die höheren Kosten nicht anders ausgleichen können.</p>
<p><b>C1/C2-Kernsatz:</b> Ein weiterer Nachteil kann darin bestehen, dass Unternehmen steigende Personalkosten teilweise an Verbraucher weitergeben, wodurch Preissteigerungen entstehen und die reale Kaufkraft insbesondere einkommensschwacher Haushalte geschwächt werden kann.</p>
<p><b>Musterabsatz:</b> Darüber hinaus kann der Mindestlohn zu Preissteigerungen beitragen. Wenn Unternehmen höhere Personalkosten nicht durch höhere Produktivität oder größere Umsätze ausgleichen können, geben sie diese Kosten möglicherweise an Verbraucher weiter. Dies betrifft besonders arbeitsintensive Dienstleistungen wie Gastronomie, Reinigung, Einzelhandel oder Lieferdienste. Für Beschäftigte kann ein höherer Lohn zwar zunächst eine Entlastung bedeuten; wenn jedoch gleichzeitig alltägliche Dienstleistungen und Produkte teurer werden, kann ein Teil dieses Vorteils wieder verloren gehen. Langfristig betrachtet besteht daher die Gefahr, dass der Mindestlohn zwar nominale Einkommen erhöht, die reale Kaufkraft aber nur begrenzt verbessert.</p>
<h4>5. Nachteil 4: Automatisierung, Bürokratie und unbeabsichtigte Nebenwirkungen</h4>
<p>Der vierte Nachteil betrifft langfristige Anpassungsreaktionen von Unternehmen. Wenn menschliche Arbeit teurer wird, steigt der Anreiz, einfache Tätigkeiten durch technische Lösungen zu ersetzen. Das betrifft nicht jede Branche gleichermaßen, kann aber in bestimmten Bereichen relevant sein: Selbstbedienungskassen, digitale Bestellsysteme, automatisierte Lagerprozesse oder Apps für einfache Verwaltungsaufgaben können menschliche Arbeit teilweise ersetzen.</p>
<p>Aus unternehmerischer Sicht ist Automatisierung eine Möglichkeit, Personalkosten zu reduzieren. Aus arbeitsmarktpolitischer Sicht kann dies problematisch sein, weil gerade einfache Tätigkeiten häufig Einstiegsmöglichkeiten für geringqualifizierte Personen bieten. Wenn solche Tätigkeiten wegfallen, verlieren manche Arbeitnehmergruppen wichtige Chancen, erste Berufserfahrung zu sammeln.</p>
<p>Hinzu kommt der bürokratische Aufwand. Mindestlohnregelungen müssen kontrolliert, dokumentiert und korrekt umgesetzt werden. Unternehmen müssen Arbeitszeiten erfassen, Lohnabrechnungen anpassen und rechtliche Vorgaben beachten. Für große Unternehmen ist dieser Aufwand meist leichter zu bewältigen. Kleine Betriebe können dadurch jedoch zusätzlich belastet werden, weil sie weniger Personal für Verwaltung und Kontrolle haben.</p>
<p>Ein weiterer Punkt ist die mögliche Marktverzerrung. Betriebe, die Lohnkosten leichter ausgleichen können, gewinnen gegenüber kleinen Unternehmen einen Vorteil. Wenn kleine Betriebe schließen oder weniger Personal einstellen, kann die lokale Wirtschaftsstruktur schwächer werden. Dadurch verliert eine Region möglicherweise Vielfalt: weniger kleine Geschäfte, weniger familiengeführte Betriebe und weniger persönliche Dienstleistungen.</p>
<p><b>C1/C2-Kernsatz:</b> Langfristig kann der Mindestlohn unbeabsichtigte Nebenwirkungen haben, weil höhere Lohnkosten den Anreiz zur Automatisierung erhöhen, bürokratischen Aufwand verursachen und kleine Betriebe gegenüber größeren Unternehmen benachteiligen können.</p>
<p><b>Musterabsatz:</b> Ein vierter Nachteil des Mindestlohns besteht in möglichen langfristigen Nebenwirkungen. Wenn einfache Tätigkeiten durch höhere Lohnkosten teurer werden, kann für Unternehmen der Anreiz steigen, diese Tätigkeiten zu automatisieren. Selbstbedienungskassen, digitale Bestellsysteme oder automatisierte Verwaltungsprozesse können dann menschliche Arbeit teilweise ersetzen. Besonders problematisch ist dies für Menschen, die auf einfache Arbeitsplätze als Einstieg in den Arbeitsmarkt angewiesen sind. Hinzu kommt, dass Mindestlohnregelungen zusätzlichen Kontroll- und Verwaltungsaufwand verursachen können. Für kleine Betriebe stellt dies eine weitere Belastung dar. Langfristig betrachtet kann der Mindestlohn daher nicht nur Löhne erhöhen, sondern auch Anpassungsreaktionen auslösen, die Beschäftigungschancen und lokale Wirtschaftsstrukturen verändern.</p>
<h4>6. Nomen-Verb-Verbindungen für C1/C2</h4>
<ul><li>Personalkosten erhöhen / senken / ausgleichen</li><li>wirtschaftlichen Druck erzeugen</li><li>finanzielle Reserven aufbrauchen</li><li>Gewinnspannen verringern</li><li>Preise anheben</li><li>Kosten an Verbraucher weitergeben</li><li>Neueinstellungen vermeiden</li><li>Einstiegschancen verringern</li><li>geringqualifizierte Arbeitnehmer benachteiligen</li><li>Arbeitsplätze gefährden</li><li>einfache Tätigkeiten automatisieren</li><li>bürokratischen Aufwand verursachen</li><li>die Wettbewerbsfähigkeit schwächen</li><li>unbeabsichtigte Nebenwirkungen haben</li></ul>
<h4>7. Vier Nachteile als Prüfungsschema</h4>
<table style="width:100%;border-collapse:collapse"><tr><td><b>Nachteil 1</b></td><td>Belastung kleiner Unternehmen</td><td>Personalkosten steigen, Gewinnspannen sinken, Preise oder Arbeitszeiten werden angepasst.</td></tr><tr><td><b>Nachteil 2</b></td><td>Weniger Chancen für Geringqualifizierte</td><td>Arbeitgeber achten stärker auf Erfahrung, Qualifikation und Produktivität.</td></tr><tr><td><b>Nachteil 3</b></td><td>Preissteigerungen</td><td>Kosten werden an Verbraucher weitergegeben, reale Kaufkraft kann begrenzt steigen.</td></tr><tr><td><b>Nachteil 4</b></td><td>Automatisierung und Bürokratie</td><td>Einfache Tätigkeiten werden ersetzt, Verwaltungsaufwand steigt, kleine Betriebe werden belastet.</td></tr></table>
<h4>8. Mini-Kopiervorlage</h4>
<ul><li><b>Belastung kleiner Unternehmen:</b> Mindestlohn → höhere Personalkosten → geringere Gewinnspanne → Preiserhöhung, weniger Personal oder geringere Wettbewerbsfähigkeit.</li><li><b>Geringqualifizierte Arbeitnehmer:</b> höherer Lohn → höhere Anforderungen → weniger Einstiegschancen → mögliche Benachteiligung.</li><li><b>Preissteigerungen:</b> höhere Kosten → Weitergabe an Verbraucher → eingeschränkte reale Kaufkraft.</li><li><b>Automatisierung und Bürokratie:</b> höhere Lohnkosten → technische Ersatzlösungen und mehr Verwaltung → unbeabsichtigte Nebenwirkungen.</li></ul>`;
  function isMindestlohn(){
    const checked=document.querySelector('input[name="tc"]:checked');
    if(checked&&checked.value==='t27')return true;
    try{return typeof selected!=='undefined'&&selected==='t27'}catch(e){return false}
  }
  function safe(v){return String(v||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
  function render(){
    const test=(window.DEUTSCH_TESTS||{}).t27||{};
    if(typeof hide==='function')hide();
    document.getElementById('lesson').classList.remove('hide');
    document.getElementById('lessonTitle').textContent='Konu anlatımı: '+(test.title||'Mindestlohn – Nachteile · C1/C2 Nachteilsabsatz');
    document.getElementById('lessonMeta').textContent='Seviye: Uzun · C1/C2 Nachteilsabsatz · 4 ausführliche Nachteile';
    const words=(test.words||[]).slice(0,18).map(w=>'<li>'+safe(w)+'</li>').join('');
    document.getElementById('lessonContent').innerHTML='<section style="padding:14px;border:1px solid #d8d3ca;border-radius:14px;background:#fff;margin-bottom:18px"><h2>1. Genel bakış</h2><p><b>Thema:</b> '+safe(test.topic||'Erörterung · Nachteile des Mindestlohns')+'</p>'+(words?'<h3>Öncelikli kavramlar</h3><ul>'+words+'</ul>':'')+'</section><section style="padding:14px;border:1px solid #d8d3ca;border-radius:14px;background:#fff;margin-bottom:18px"><h2>2. Konu açıklaması</h2>'+M_LONG+'</section>';
    document.getElementById('lesson').scrollIntoView({behavior:'smooth'});
  }
  function bind(){
    const longBtn=document.getElementById('btnLessonLong');
    if(!longBtn)return;
    longBtn.addEventListener('click',function(ev){
      if(isMindestlohn()){
        ev.preventDefault();
        ev.stopImmediatePropagation();
        render();
        return false;
      }
    },true);
  }
  document.addEventListener('DOMContentLoaded',bind);
  setInterval(bind,500);
  window.forceMindestlohnLong=render;
})();
