(function(){
'use strict';
var TITLE='Schreibfehler 1 · Korrekte Ausdrucksmuster, Präpositionen und NVV';
function p(x){return '<p>'+x+'</p>'}
var s=[];
s.push('<h3>Schreibfehler 1 · Korrekte Ausdrucksmuster, Präpositionen und Nomen-Verb-Verbindungen</h3>');
s.push('<p><b>Niveau:</b> C1/C2 · Rektion · Valenz · Kollokationen · Nominalstil · Funktionsverbgefüge</p>');
s.push('<h4>1. Grundprinzip: Wörter als vollständige Muster lernen</h4>');
s.push(p('Auf C1/C2-Niveau reicht es nicht aus, die Bedeutung eines Wortes isoliert zu kennen. Entscheidend ist, in welcher grammatischen Umgebung ein Ausdruck verwendet wird. Viele Fehler entstehen nicht, weil das gewählte Wort inhaltlich falsch wäre, sondern weil Präposition, Kasus, Objekt oder typische Ergänzung nicht zum deutschen Muster passen. Deshalb müssen Ausdrücke wie Einfluss, Bedarf, Beitrag, Druck, Interesse oder Fokus immer als ganze Konstruktionen gelernt werden.'));
s.push(p('Ein Ausdruck besteht aus mehreren Bausteinen: einem Nomen oder Verb, einer festen Präposition, einem bestimmten Kasus und einem typischen Objekt. Wer nur Einfluss als einzelnes Wort speichert, neigt zu fehlerhaften Verbindungen wie Einfluss über. Korrekt ist Einfluss auf + Akkusativ. Noch gehobener ist das Funktionsverbgefüge Einfluss auf etwas ausüben. Ein prüfungstauglicher Satz lautet: Werbekampagnen üben erheblichen Einfluss auf die Kaufentscheidungen junger Zielgruppen aus.'));
s.push(p('Dasselbe Prinzip gilt für Bedarf an + Dativ, Beitrag zu + Dativ, Druck auf + Akkusativ, Interesse an + Dativ, Interesse für + Akkusativ wecken, Aufmerksamkeit auf + Akkusativ lenken und den Fokus auf + Akkusativ legen. Diese Muster sind besonders wichtig, wenn es um Werbung, soziale Medien, Konsumverhalten, Medienkompetenz, berufliche Vernetzung und lebenslanges Lernen geht.'));
s.push('<h4>2. Einfluss, Wirkung, Druck und Motivation</h4>');
s.push(p('Im Themenfeld Werbung und Konsumverhalten sind Einfluss, Wirkung und Druck zentrale Begriffe. Das Nomen Einfluss wird mit auf + Akkusativ verbunden. Man schreibt: Werbung hat Einfluss auf das Kaufverhalten von Kindern. In einem gehobenen Text ist jedoch die Nomen-Verb-Verbindung Einfluss auf etwas ausüben oft präziser: Digitale Plattformen üben erheblichen Einfluss auf Konsumgewohnheiten aus.'));
s.push(p('Auch Wirkung folgt demselben Kasusmuster. Eine Kampagne entfaltet eine Wirkung auf eine Zielgruppe. Diese Formulierung ist analytischer als das einfache Verb wirken, weil sie den Effekt als beobachtbare Größe beschreibt. Ein guter Satz lautet: Emotionale Markenbotschaften entfalten eine starke Wirkung auf sportbegeisterte Jugendliche. Das Verb entfalten passt besonders gut zu abstrakten Nomen wie Wirkung, Potenzial oder Dynamik.'));
s.push(p('Druck wird ebenfalls mit auf + Akkusativ verbunden. Influencer können subtilen Konsumdruck auf ihre Follower ausüben. Diese Formulierung ist genauer als Influencer machen Druck, weil das Funktionsverbgefüge Druck ausüben den sozialen oder psychologischen Mechanismus sachlich beschreibt. Motivation wird dagegen häufig mit zu + Dativ verbunden: Bekannte Athleten motivieren Jugendliche zu mehr sportlicher Aktivität. Nominalisiert lautet die Struktur: Kampagnen können Jugendliche zum Kauf oder zum Sporttreiben anregen.'));
s.push('<h4>3. Bedarf, Interesse, Fokus und Aufmerksamkeit</h4>');
s.push(p('Das Nomen Bedarf verlangt im Standardmuster an + Dativ. Richtig ist: Es besteht ein wachsender Bedarf an kritischer Medienkompetenz. Falsch oder zumindest unidiomatisch wäre Bedarf nach in diesem Zusammenhang. Bedarf wird häufig mit bestehen kombiniert: Es besteht Bedarf an Aufklärung, an Orientierung, an Medienbildung oder an pädagogischer Unterstützung. Diese Struktur eignet sich sehr gut, um eine Problemstellung in einer Erörterung einzuleiten.'));
s.push(p('Interesse hat zwei wichtige Muster. Interesse an + Dativ beschreibt ein bereits vorhandenes Interesse: Viele Jugendliche haben Interesse an Sport und Fitness. Interesse für + Akkusativ wecken beschreibt dagegen, dass Interesse erst entsteht: Nike-Kampagnen können Interesse für sportliche Aktivitäten wecken. Wer diese Unterscheidung beherrscht, kann deutlich präziser schreiben, weil Zustand und Entstehung nicht vermischt werden.'));
s.push(p('Fokus und Aufmerksamkeit sind besonders nützlich für analytische Absätze. Man legt den Fokus auf + Akkusativ und lenkt Aufmerksamkeit auf + Akkusativ. Beispiel: Die Kampagne legt den Fokus auf Motivation und Selbstoptimierung. Oder: Influencer lenken die Aufmerksamkeit auf bestimmte Produkte. Diese Strukturen helfen, den Gegenstand der Analyse klar zu bestimmen und Übergänge zwischen Argumenten logisch zu gestalten.'));
s.push('<h4>4. Beitrag, Förderung, Entwicklung und Folge</h4>');
s.push(p('Bei positiven oder lösungsorientierten Argumenten ist Beitrag zu + Dativ ein sehr wichtiges Muster. Man schreibt: Soziale Netzwerke leisten einen Beitrag zur beruflichen Vernetzung. Ebenso korrekt ist: Bildungsvideos können zur Förderung lebenslangen Lernens beitragen. Dabei verlangt beitragen die Präposition zu + Dativ. Die Form zur ist die Verbindung aus zu und der und gehört zum Dativ Singular feminin.'));
s.push(p('Die Struktur einen Beitrag leisten wirkt sachlicher als das einfache Verb helfen. Sie passt besonders gut zu akademischen Texten, weil sie eine Entwicklung als Teil eines größeren Zusammenhangs beschreibt. Digitale Lernangebote leisten einen Beitrag zur Förderung selbstständiger Lernprozesse. Soziale Netzwerke leisten einen Beitrag zum Austausch von Ideen und Informationen. Berufliche Plattformen können einen Beitrag zur Erweiterung beruflicher Kontakte leisten.'));
s.push(p('Für Folgen verwendet man zu + Dativ führen oder zur Folge haben. Personalisierte Werbung führt häufig zu einer Verstärkung von Konsumimpulsen. Permanente Produktpräsenz kann zur Folge haben, dass Jugendliche Konsum als selbstverständlich wahrnehmen. Zur Folge haben ist besonders geeignet, wenn ein dass-Satz folgt und eine komplexe Konsequenz beschrieben wird.'));
s.push('<h4>5. Soziale Medien, Plattformen und Netzwerke</h4>');
s.push(p('Bei digitalen Themen ist die Wahl der Präposition oft fehleranfällig. Man sagt in sozialen Netzwerken, weil ein Netzwerk als Kommunikationsraum verstanden wird. Man sagt auf Plattformen wie Instagram oder TikTok, weil Plattform ähnlich wie Website oder Oberfläche konzeptualisiert wird. Man verwendet über soziale Netzwerke, wenn der Vermittlungskanal betont wird, und durch soziale Netzwerke, wenn Ursache oder Mittel im Vordergrund steht.'));
s.push(p('Beispiele zeigen den Unterschied: Viele Jugendliche präsentieren sich in sozialen Netzwerken. Auf Plattformen wie Instagram werden Produkte häufig indirekt beworben. Berufliche Kontakte können über soziale Netzwerke hergestellt werden. Durch soziale Netzwerke entstehen neue Formen der Selbstdarstellung. YouTube dient als Plattform für Bildungsvideos und persönliche Einblicke.'));
s.push(p('Das Verb zeigen braucht eine klare Valenz: jemandem etwas zeigen. Noch gehobener ist präsentieren: Nutzer präsentieren einem breiten Publikum ihre Fähigkeiten. Falsch wäre eine wörtliche Struktur wie nach anderen Menschen zeigen. Korrekt sind: einem Publikum etwas zeigen, einem Publikum Fähigkeiten präsentieren oder sich in sozialen Netzwerken darstellen.'));
s.push('<h4>6. Kollokationen: zielsprachliche Wortverbindungen</h4>');
s.push(p('Kollokationen entscheiden darüber, ob ein Satz nur verständlich oder wirklich natürlich klingt. Grammatisch mögliche Formulierungen können fremdsprachlich wirken, wenn sie nicht zur üblichen Wortverbindung passen. Man konzipiert oder entwickelt Werbekampagnen; man erstellt nicht einfach Werbungen. Man trifft Kaufentscheidungen; man macht sie nicht. Man weckt Interesse am Sport oder Interesse für sportliche Aktivitäten; man erreicht kein Sportinteresse.'));
s.push(p('Weitere typische Korrekturen sind: durchdachte Werbestrategien statt kluge Werbungstrategien, Konsumdruck über verschiedene Kanäle erzeugen statt Bedingungen über Kanäle schaffen, die Karriere vorantreiben statt die Karriere steigt, Ideen und Informationen austauschen statt Idee und Information austauschen, lebenslanges Lernen statt lebenslange Ausbildung. Diese Korrekturen verbessern nicht nur die Grammatik, sondern auch Textsorte und Register.'));
s.push(p('Produktive C1/C2-Sätze lauten: Werbung beeinflusst nicht nur einzelne Kaufakte, sondern prägt langfristig Konsummuster. Digitale Plattformen fungieren als Vermittlungsräume, in denen Produkte, Identitäten und Lebensstile miteinander verknüpft werden. Durch die kontinuierliche Präsenz von Marken entsteht ein Wahrnehmungsrahmen, der bestimmte Produkte als besonders attraktiv erscheinen lässt.'));
s.push('<h4>7. Nomen-Verb-Verbindungen und Funktionsverbgefüge</h4>');
s.push(p('Nomen-Verb-Verbindungen bestehen aus einem abstrakten Nomen und einem Funktionsverb. Das Nomen trägt die Hauptbedeutung, während das Verb die grammatische Struktur organisiert. Statt beeinflussen kann man Einfluss ausüben verwenden. Statt wirken kann man eine Wirkung entfalten schreiben. Statt fördern ist einen Beitrag leisten zu + Dativ möglich. Diese Strukturen wirken sachlicher, analytischer und schriftsprachlicher.'));
s.push(p('Wichtige Beispiele sind: Einfluss auf etwas ausüben, eine Wirkung auf etwas entfalten, einen Beitrag zu etwas leisten, Beachtung finden, eine Entscheidung treffen, etwas in den Mittelpunkt stellen, den Fokus auf etwas legen, etwas in Beziehung zu etwas setzen, etwas in Anspruch nehmen, etwas zur Verfügung stellen und eine Rolle bei oder in etwas spielen. Jede dieser Verbindungen bringt eine feste Präposition oder Ergänzung mit.'));
s.push(p('Man sollte Funktionsverbgefüge jedoch nicht mechanisch überall verwenden. Ein guter C1/C2-Text kombiniert einfache Verben und nominale Strukturen. In einer Analyse kann man schreiben: Die Kampagne beeinflusst Jugendliche. Danach kann man variieren: Sie übt Einfluss auf deren Kaufentscheidungen aus. Oder: Sie entfaltet eine starke Wirkung auf das Konsumverhalten. Diese Variation verhindert Wiederholung und erhöht die Ausdruckssicherheit.'));
s.push('<h4>8. Valenz: Ergänzungen kontrollieren</h4>');
s.push(p('Valenz bedeutet, dass ein Ausdruck bestimmte Ergänzungen verlangt. Motivieren verlangt jemanden und eine Handlung: jemanden zu + Dativ motivieren. Athleten motivieren Jugendliche zu sportlichen Aktivitäten. Anregen kann ebenfalls mit zu + Dativ oder zum nominalisierten Infinitiv verwendet werden: Rabattaktionen regen Konsumenten zum spontanen Kauf an.'));
s.push(p('Neigen verlangt die Struktur dazu neigen, zu + Infinitiv oder dazu neigen, dass. Ein korrekter Satz lautet: Konsumenten neigen dazu, bekannte Marken höher zu bewerten. Falsch wäre eine direkte Struktur wie dazu neigen, das ist das beste Produkt. Führen verlangt zu + Dativ: Konsumdruck führt zu impulsiven Kaufentscheidungen. Beitragen verlangt ebenfalls zu + Dativ: Bildungsvideos tragen zur Wissensvermittlung bei.'));
s.push(p('Ermöglichen verlangt entweder ein Akkusativobjekt oder ein Dativobjekt plus Akkusativobjekt: Digitale Plattformen ermöglichen Jugendlichen neue Lernformen. Dienen kann mit als + Nominalgruppe oder zu + Dativ stehen: Instagram dient als Plattform für Selbstdarstellung. Diese Valenzmuster verhindern Satzteile ohne klare grammatische Funktion.'));
s.push('<h4>9. Satzmuster für argumentative Texte</h4>');
s.push(p('Präpositionen und NVV müssen in eine Argumentation eingebettet werden. Für Ursachen eignet sich: Dies ist darauf zurückzuführen, dass ... Für Wirkungen: Dies führt dazu, dass ... Für Beispiele: Ein anschauliches Beispiel hierfür ist ... Für Bezüge: Dies steht in engem Zusammenhang mit ... Für Einschränkungen: Dabei darf jedoch nicht außer Acht gelassen werden, dass ... Für Folgen: Langfristig kann dies zur Folge haben, dass ...'));
s.push(p('Ein Modellabschnitt kann lauten: Werbekampagnen internationaler Unternehmen üben einen erheblichen Einfluss auf das Konsumverhalten junger Zielgruppen aus. Besonders deutlich wird dies bei Kampagnen, die emotionale Nähe, soziale Anerkennung und Produktkonsum miteinander verknüpfen. Dadurch entsteht ein Wahrnehmungsrahmen, in dem bestimmte Produkte nicht lediglich als Waren, sondern als Bestandteile eines erstrebenswerten Lebensstils erscheinen.'));
s.push(p('Ein zweiter Modellabschnitt lautet: Soziale Netzwerke dienen längst nicht mehr nur der privaten Kommunikation, sondern fungieren zunehmend als Räume der Selbstdarstellung, der beruflichen Vernetzung und der informellen Bildung. Nutzer können einem breiten Publikum Fähigkeiten präsentieren und dadurch Anerkennung erfahren. Zugleich leisten Plattformen einen Beitrag zur Verbreitung von Wissen, da sie Bildungsvideos, Erfahrungsberichte und berufliche Kontakte zugänglich machen.'));
s.push('<h4>10. Kontrollliste</h4>');
s.push(p('Vor dem Schreiben sollte jede abstrakte Struktur geprüft werden. Habe ich Einfluss mit auf + Akkusativ verbunden? Habe ich Bedarf mit an + Dativ verwendet? Steht nach Beitrag zu der Dativ? Habe ich Druck auf + Akkusativ korrekt gebildet? Habe ich Interesse an und Interesse für wecken unterschieden? Habe ich wörtliche Übersetzungen vermieden und natürliche Kollokationen gewählt?'));
s.push(p('Die wichtigste Kurzformel lautet: Einfluss auf + Akkusativ ausüben; Bedarf an + Dativ bestehen; Beitrag zu + Dativ leisten; Interesse an + Dativ haben; Interesse für + Akkusativ wecken; Druck auf + Akkusativ ausüben; zu + Dativ führen; zur Förderung von + Dativ beitragen; jemanden zu + Dativ motivieren; dazu neigen, zu + Infinitiv. Wer diese Muster automatisiert, schreibt präziser, idiomatischer und deutlich näher am C1/C2-Niveau.'));
var LONG=s.join('');
function setText(){var T=(window.DEUTSCH_TESTS||{}).sf2_1,L=(window.DEUTSCH_LESSONS||{}).sf2_1;if(!T||!L)return;T.title=TITLE;T.topic='C1/C2 · Präpositionalrektion · Valenz · Kollokationen · Nominalstil · NVV/FVG';T.source='1. Sprach Fehlern.docx';L.source='1. Sprach Fehlern.docx';L.short='<h3>Schreibfehler 1 · Kurzüberblick</h3><p>Dieses Modul trainiert feste Ausdrucksmuster, Präpositionen, Rektion, Valenz, Kollokationen und Nomen-Verb-Verbindungen auf C1/C2-Niveau. Ausdrücke werden als vollständige Muster gelernt: <b>Einfluss auf + Akkusativ</b>, <b>Bedarf an + Dativ</b>, <b>Beitrag zu + Dativ</b>, <b>Druck auf + Akkusativ</b> und <b>Interesse an + Dativ</b>.</p>';L.medium='<h3>Schreibfehler 1 · Erweiterte Erklärung</h3><p>Der Schwerpunkt liegt auf produktiven Mustern für argumentative Texte. Wichtig sind <b>Einfluss auf etwas ausüben</b>, <b>eine Wirkung auf etwas entfalten</b>, <b>einen Beitrag zu etwas leisten</b>, <b>den Fokus auf etwas legen</b>, <b>Aufmerksamkeit auf etwas lenken</b>, <b>in sozialen Netzwerken</b>, <b>auf Plattformen</b> und <b>als Plattform für etwas dienen</b>.</p><p>Für C1/C2 sind außerdem natürliche Kollokationen entscheidend: <b>Werbekampagnen konzipieren</b>, <b>Kaufentscheidungen treffen</b>, <b>Konsummuster prägen</b>, <b>berufliche Netzwerke aufbauen</b> und <b>Ideen und Informationen austauschen</b>. Nomen-Verb-Verbindungen machen den Stil sachlich und analytisch, solange sie gezielt und nicht mechanisch verwendet werden.</p>';L.long=LONG;L.minimumWords='1500+';L.longSourceVerified=true;window.AAYS_SF2_1_SOURCE_DOCX1_OK=true;}
function active(){var t=(document.getElementById('lessonTitle')||{}).textContent||'';return t.indexOf('Schreibfehler 1')>-1||t.indexOf('Schreiben fehlern 1')>-1||t.indexOf('Ausdrucksmuster')>-1;}
function visible(){var x=document.getElementById('lesson');return !x||!/(^|\s)hide(\s|$)/.test(x.className||'');}
function render(){setText();if(!visible()||!active())return;var title=document.getElementById('lessonTitle'),meta=document.getElementById('lessonMeta'),content=document.getElementById('lessonContent');if(title)title.textContent='Lektion: '+TITLE;if(meta)meta.textContent='Niveau: C1/C2 · Quelle: 1. Sprach Fehlern.docx';if(content&&content.innerHTML!==LONG)content.innerHTML=LONG;}
render();setTimeout(render,200);setTimeout(render,900);setInterval(render,160);document.addEventListener('click',function(){setTimeout(render,50);setTimeout(render,200);setTimeout(render,700);},true);try{new MutationObserver(function(){setTimeout(render,30);}).observe(document.documentElement,{childList:true,subtree:true,characterData:true});}catch(e){}
})();