(function(){
'use strict';
var LONG=[
'<h3>Schreibfehler 1 · Ausdrucksmuster, Präpositionen und Nomen-Verb-Verbindungen</h3>',
'<p><b>Niveau:</b> C1/C2 · Präpositionalrektion · Kollokationen · Nominalstil · Funktionsverbgefüge</p>',
'<h4>1. Ziel des Kapitels</h4>',
'<p>Dieses Kapitel trainiert nicht einzelne Wörter, sondern vollständige sprachliche Muster. Auf C1/C2-Niveau entsteht ein überzeugender Text erst dann, wenn Bedeutung, Präposition, Kasus, Kollokation und Satzbau zusammenpassen. Ein Ausdruck wie <b>Einfluss</b> ist daher nur dann sicher verwendbar, wenn zugleich klar ist, dass er im hier behandelten Muster mit <b>auf + Akkusativ</b> verbunden wird. Man schreibt also <i>Einfluss auf das Konsumverhalten ausüben</i> und nicht eine frei übersetzte Verbindung mit einer beliebigen Präposition. Dasselbe gilt für <b>Bedarf an + Dativ</b>, <b>einen Beitrag zu + Dativ leisten</b>, <b>Druck auf + Akkusativ ausüben</b>, <b>Interesse an + Dativ haben</b>, <b>Interesse für + Akkusativ wecken</b> und <b>Aufmerksamkeit auf + Akkusativ lenken</b>.</p>',
'<p>Der wichtigste Grundsatz lautet: Ein korrekter C1/C2-Satz ist nicht nur grammatisch möglich, sondern auch idiomatisch, semantisch präzise und registergerecht. Viele Lernende kennen ein Nomen, wählen aber eine unpassende Ergänzung. Dadurch wirkt der Satz übersetzt oder unnatürlich. Wer dagegen feste Ausdrucksmuster beherrscht, kann in argumentativen Texten genauer erklären, wodurch ein Problem entsteht, welche Wirkung es entfaltet, welcher Bedarf besteht und welchen Beitrag eine Maßnahme leisten kann.</p>',
'<h4>2. Präpositionalrektion als Schreibgrundlage</h4>',
'<p>Präpositionalrektion bedeutet, dass ein Wort eine bestimmte Präposition und häufig auch einen bestimmten Kasus verlangt. Das Muster <b>Einfluss auf + Akkusativ ausüben</b> beschreibt eine gerichtete Wirkung. Der Einfluss richtet sich auf eine Person, eine Gruppe, eine Entscheidung, eine Wahrnehmung oder ein Verhalten. Beispiele: <i>Digitale Plattformen üben Einfluss auf Konsumgewohnheiten aus.</i> <i>Emotionale Kampagnen üben Einfluss auf die Wahrnehmung einer Marke aus.</i> <i>Soziale Netzwerke können Einfluss auf politische Meinungsbildungsprozesse ausüben.</i> In all diesen Sätzen steht nach <b>auf</b> der Akkusativ, weil ein Ziel der Wirkung markiert wird.</p>',
'<p>Eng damit verbunden ist die Struktur <b>eine Wirkung auf + Akkusativ entfalten</b>. Sie klingt in analytischen Texten oft präziser als das einfache Verb <i>wirken</i>. Man kann schreiben: <i>Personalisierte Werbung entfaltet eine starke Wirkung auf spontane Kaufentscheidungen.</i> Oder: <i>Wiederholte Produktplatzierungen entfalten eine langfristige Wirkung auf Konsummuster.</i> Die Verbindung <b>Wirkung entfalten</b> eignet sich besonders, wenn nicht nur behauptet, sondern ein Prozess beschrieben werden soll.</p>',
'<h4>3. Bedarf, Beitrag und Förderung</h4>',
'<p>Das Nomen <b>Bedarf</b> verlangt im hier relevanten Standardmuster <b>an + Dativ</b>. Richtig ist: <i>Es besteht Bedarf an kritischer Medienkompetenz.</i> Ebenfalls korrekt sind: <i>Es besteht Bedarf an transparenter Kennzeichnung.</i> und <i>In Bildungseinrichtungen besteht wachsender Bedarf an reflektierter Konsumerziehung.</i> Der Ausdruck zeigt, dass etwas erforderlich ist. Er eignet sich daher für Problemaufrisse, in denen zunächst eine Lücke oder Notwendigkeit benannt wird.</p>',
'<p>Für Lösungsperspektiven ist das Muster <b>einen Beitrag zu + Dativ leisten</b> besonders nützlich. Beispiele: <i>Aufklärungsprogramme leisten einen Beitrag zur Stärkung der Medienkompetenz.</i> <i>Transparente Regeln leisten einen Beitrag zu faireren Kommunikationsbedingungen.</i> <i>Schulische Projekte können einen Beitrag zur bewussteren Nutzung digitaler Angebote leisten.</i> Das Wort <b>zur</b> ist die Verbindung aus <b>zu der</b> und steht im Dativ. Wer diese Struktur beherrscht, kann Maßnahmen differenziert bewerten, ohne ständig einfache Verben zu wiederholen.</p>',
'<h4>4. Druck, Interesse und Aufmerksamkeit</h4>',
'<p>Das Muster <b>Druck auf + Akkusativ ausüben</b> beschreibt sozialen, wirtschaftlichen oder kommunikativen Druck. Beispiele: <i>Ständige Vergleichsbilder üben Druck auf Nutzer aus.</i> <i>Rabattaktionen können Druck auf Konsumenten ausüben, sofort zu handeln.</i> <i>Gruppennormen üben Druck auf individuelle Entscheidungen aus.</i> Auch hier steht nach <b>auf</b> der Akkusativ. Der Ausdruck ist stärker und analytischer als einfache Formulierungen wie <i>unter Druck setzen</i>, weil er den Druck als abstrakte Wirkung sichtbar macht.</p>',
'<p>Bei <b>Interesse</b> muss man zwischen bestehendem und erzeugtem Interesse unterscheiden. <b>Interesse an + Dativ haben</b> beschreibt ein vorhandenes Interesse: <i>Viele Nutzer haben Interesse an unabhängigen Informationen.</i> <b>Interesse für + Akkusativ wecken</b> beschreibt dagegen die Entstehung eines Interesses: <i>Gut gestaltete Bildungsangebote können Interesse für gesellschaftliche Themen wecken.</i> Diese Unterscheidung ist wichtig, weil sie eine unterschiedliche Perspektive ausdrückt: einmal Zustand, einmal Aktivierung.</p>',
'<p>Das Muster <b>Aufmerksamkeit auf + Akkusativ lenken</b> eignet sich für Texte über Medien, Werbung und öffentliche Debatten. Beispiele: <i>Digitale Kampagnen lenken Aufmerksamkeit auf bestimmte Produkte.</i> <i>Journalistische Beiträge lenken Aufmerksamkeit auf strukturelle Probleme.</i> <i>Plattformen lenken Aufmerksamkeit auf Inhalte, die starke Reaktionen hervorrufen.</i> Die Konstruktion ist präzise, weil sie nicht nur sagt, dass etwas beachtet wird, sondern auch, wohin Wahrnehmung gesteuert wird.</p>',
'<h4>5. Fokusstrukturen im Nominalstil</h4>',
'<p>Sehr häufig werden Fokusstrukturen falsch gebildet. Standardsprachlich korrekt sind <b>den Fokus auf + Akkusativ legen</b>, <b>etwas in den Fokus rücken</b> und <b>etwas in den Mittelpunkt stellen</b>. Beispiele: <i>Der Essay legt den Fokus auf die Wirkung personalisierter Werbung.</i> <i>Die Diskussion rückt die Verantwortung digitaler Plattformen in den Fokus.</i> <i>Die Analyse stellt die langfristigen Folgen kommerzieller Kommunikation in den Mittelpunkt.</i> Diese Strukturen helfen, einen Absatz klar zu organisieren. Sie zeigen, welcher Aspekt zentral behandelt wird.</p>',
'<p>Nicht jede Fokusstruktur ist austauschbar. <b>Den Fokus auf etwas legen</b> betont die bewusste Auswahl eines Themas. <b>Etwas in den Fokus rücken</b> betont, dass ein Thema stärker sichtbar wird. <b>Etwas in den Mittelpunkt stellen</b> klingt besonders geeignet, wenn ein Text, eine Untersuchung oder eine Debatte einen zentralen Gegenstand erhält. Wer diese Unterschiede nutzt, schreibt genauer und vermeidet monotone Wiederholungen.</p>',
'<h4>6. Kollokationen: natürliche Wortverbindungen</h4>',
'<p>Kollokationen sind feste oder besonders typische Wortverbindungen. Man sagt <b>Kaufentscheidungen treffen</b>, nicht <i>Kaufentscheidungen machen</i>. Man sagt <b>Werbekampagnen konzipieren</b>, <b>Konsummuster prägen</b>, <b>Markenwahrnehmung beeinflussen</b>, <b>Zielgruppen ansprechen</b>, <b>Vertrauen schaffen</b> und <b>Erwartungen wecken</b>. Diese Verbindungen sind für C1/C2-Texte entscheidend, weil sie zeigen, dass der Wortschatz nicht isoliert, sondern in seinem natürlichen Umfeld verwendet wird.</p>',
'<p>Ein Satz wie <i>Werbung macht Menschen kaufen</i> wäre unpräzise und nicht idiomatisch. Besser ist: <i>Werbung kann Kaufentscheidungen beeinflussen.</i> Noch gehobener: <i>Werbekampagnen können Einfluss auf Kaufentscheidungen ausüben, indem sie emotionale Bedürfnisse, soziale Anerkennung und Produktwahrnehmung miteinander verknüpfen.</i> Hier wird nicht nur ein einzelnes Wort ersetzt; der gesamte Satz wird argumentativ dichter.</p>',
'<h4>7. Nomen-Verb-Verbindungen und Funktionsverbgefüge</h4>',
'<p>Nomen-Verb-Verbindungen bestehen aus einem bedeutungstragenden Nomen und einem Verb, das die grammatische Struktur trägt. Beispiele sind <b>Einfluss ausüben</b>, <b>eine Wirkung entfalten</b>, <b>einen Beitrag leisten</b>, <b>eine Entscheidung treffen</b>, <b>eine Rolle spielen</b>, <b>zur Verfügung stellen</b> und <b>in Anspruch nehmen</b>. Sie sind im akademischen Register nützlich, weil sie abstrakte Zusammenhänge präzise ausdrücken.</p>',
'<p>Diese Strukturen dürfen jedoch nicht mechanisch eingesetzt werden. Ein Text wird nicht besser, wenn jeder einfache Ausdruck künstlich nominalisiert wird. Entscheidend ist die Funktion im Satz. <b>Einfluss ausüben</b> passt, wenn eine Wirkung auf ein Verhalten beschrieben wird. <b>Einen Beitrag leisten</b> passt, wenn eine Maßnahme positiv zu einer Entwicklung beiträgt. <b>Eine Rolle spielen</b> eignet sich, wenn ein Faktor in einem größeren Zusammenhang eingeordnet wird. <b>Zur Verfügung stellen</b> passt, wenn Ressourcen, Informationen oder Angebote bereitgestellt werden.</p>',
'<h4>8. Satzbau und argumentative Verbindung</h4>',
'<p>Die behandelten Muster entfalten ihren Wert erst im Satzbau. Für Folgen verwendet man <b>dazu führen, dass</b>: <i>Ständige Produktpräsenz kann dazu führen, dass Kaufentscheidungen weniger reflektiert getroffen werden.</i> Für nominale Folgen verwendet man <b>zu + Dativ führen</b>: <i>Kommerzielle Dauerpräsenz führt zu einer Verschiebung individueller Konsumprioritäten.</i> Der Unterschied ist wichtig: Nach <b>dass</b> folgt ein Nebensatz mit finitem Verb am Ende, nach <b>zu</b> folgt eine Nominalgruppe im Dativ.</p>',
'<p>Für Begründungen eignen sich Strukturen wie <b>Dies ist darauf zurückzuführen, dass</b>, <b>Dies lässt sich dadurch erklären, dass</b> und <b>Ein Grund dafür liegt darin, dass</b>. Für Einschränkungen sind <b>gleichzeitig</b>, <b>allerdings</b>, <b>dennoch</b> und <b>nicht außer Acht lassen</b> nützlich. Ein C1/C2-Text besteht nicht nur aus korrekten Einzelstrukturen, sondern aus logisch verbundenen Sätzen.</p>',
'<h4>9. Modellabsatz</h4>',
'<p>Kommerzielle Inhalte in digitalen Medien üben erheblichen Einfluss auf die Wahrnehmung von Produkten aus. Besonders deutlich wird dies bei Kampagnen, die emotionale Nähe, soziale Anerkennung und Konsumempfehlung miteinander verbinden. Dadurch entsteht ein kommunikativer Rahmen, in dem Produkte nicht nur als Waren erscheinen, sondern als Bestandteile eines bestimmten Lebensstils. Gleichzeitig besteht Bedarf an kritischer Medienkompetenz, weil Nutzer kommerzielle Absichten nicht immer unmittelbar erkennen. Bildungseinrichtungen, journalistische Angebote und transparente Kennzeichnungspflichten können daher einen Beitrag dazu leisten, Kaufentscheidungen bewusster und reflektierter zu gestalten.</p>',
'<h4>10. Fehlerdiagnose und Korrekturprinzip</h4>',
'<p>Fehler entstehen häufig durch wörtliche Übertragung, unvollständige Rektion oder schwache Kollokationen. Falsch ist <i>Einfluss über etwas machen</i>; richtig ist <b>Einfluss auf etwas ausüben</b>. Falsch ist <i>Bedarf nach Medienkompetenz besteht</i>; richtig ist <b>Es besteht Bedarf an Medienkompetenz</b>. Falsch ist <i>Kaufentscheidungen machen</i>; richtig ist <b>Kaufentscheidungen treffen</b>. Falsch ist <i>einen Beitrag für Aufklärung machen</i>; richtig ist <b>einen Beitrag zur Aufklärung leisten</b>.</p>',
'<p>Vor dem Schreiben sollte jede zentrale Formulierung geprüft werden. Erstens: Welches Wort trägt die Hauptbedeutung? Zweitens: Welche Präposition gehört zu diesem Wort? Drittens: Welcher Kasus folgt? Viertens: Ist die Verbindung idiomatisch? Fünftens: Passt die Struktur zum Register eines argumentativen Textes? Wer diese Fragen systematisch beantwortet, vermeidet typische Schreibfehler und gewinnt sprachliche Kontrolle.</p>',
'<h4>11. Abschlussregel</h4>',
'<p>C1/C2-Schreiben bedeutet nicht, möglichst kompliziert zu formulieren. Es bedeutet, präzise, natürlich und kontrolliert zu schreiben. Ausdrucksmuster wie <b>Einfluss auf etwas ausüben</b>, <b>eine Wirkung auf etwas entfalten</b>, <b>Bedarf an etwas haben</b>, <b>einen Beitrag zu etwas leisten</b>, <b>Aufmerksamkeit auf etwas lenken</b> und <b>Kaufentscheidungen treffen</b> bilden dafür ein stabiles Fundament. Wer diese Muster sicher beherrscht, kann Argumente differenziert entwickeln, Beispiele sprachlich sauber einbauen und komplexe Zusammenhänge ohne unnötige Wiederholungen darstellen.</p>'
].join('');
function inLesson(){var x=document.getElementById('lesson');return !x||!/(^|\s)hide(\s|$)/.test(x.className||'');}
function isSf1(){var t=(document.getElementById('lessonTitle')||{}).textContent||'';var c=(document.getElementById('lessonContent')||{}).textContent||'';return t.indexOf('Schreibfehler 1')>-1||t.indexOf('Schreiben fehlern 1')>-1||c.indexOf('Einfluss auf')>-1||c.indexOf('Bedarf an')>-1;}
function renderDom(){if(!inLesson()||!isSf1())return;var title=document.getElementById('lessonTitle'),meta=document.getElementById('lessonMeta'),content=document.getElementById('lessonContent');if(title)title.textContent='Lektion: Schreibfehler 1 · Ausdrucksmuster, Präpositionen und Nomen-Verb-Verbindungen';if(meta)meta.textContent='Niveau: C1/C2 · Deutsch';if(content&&content.innerHTML!==LONG)content.innerHTML=LONG;}
function apply(){var T=(window.DEUTSCH_TESTS||{}).sf2_1,L=(window.DEUTSCH_LESSONS||{}).sf2_1;if(!T||!L)return;
T.title='Schreibfehler 1 · Ausdrucksmuster, Präpositionen und Nomen-Verb-Verbindungen';
T.topic='C1/C2 · Präpositionalrektion · Kollokationen · Nominalstil · Funktionsverbgefüge';
T.words=['Einfluss auf + Akkusativ ausüben','eine Wirkung auf + Akkusativ entfalten','Bedarf an + Dativ bestehen','einen Beitrag zu + Dativ leisten','Druck auf + Akkusativ ausüben','Interesse an + Dativ haben','Interesse für + Akkusativ wecken','den Fokus auf + Akkusativ legen','Aufmerksamkeit auf + Akkusativ lenken','zu + Dativ beitragen','dazu führen, dass','Kaufentscheidungen treffen','Werbekampagnen konzipieren','Konsummuster prägen'];
T.fill=[['Kommerzielle Inhalte üben Einfluss ___ die Wahrnehmung aus.','auf','Einfluss auf + Akkusativ'],['Emotionale Bildsprache entfaltet eine Wirkung ___ das Konsumverhalten.','auf','Wirkung auf + Akkusativ'],['Es besteht Bedarf ___ kritischer Medienkompetenz.','an','Bedarf an + Dativ'],['Bildungsangebote leisten einen Beitrag ___ Aufklärung.','zur','Beitrag zu + Dativ'],['Digitale Werbung lenkt Aufmerksamkeit ___ bestimmte Produkte.','auf','Aufmerksamkeit auf + Akkusativ'],['Dies führt ___, dass Kaufentscheidungen weniger reflektiert getroffen werden.','dazu','dazu führen, dass']];
T.mc=[['Welche Form ist korrekt?',['Einfluss auf Kaufentscheidungen ausüben','Einfluss über Kaufentscheidungen machen','Einfluss an Kaufentscheidungen geben','Einfluss mit Kaufentscheidungen bauen'],0,'Rektion'],['Welche Kollokation ist idiomatisch?',['Kaufentscheidungen treffen','Kaufentscheidungen machen','Kaufentscheidungen bauen','Kaufentscheidungen erledigen'],0,'Kollokation'],['Welche Form ist korrekt?',['Bedarf an Medienkompetenz besteht.','Bedarf nach Medienkompetenz besteht.','Bedarf für Medienkompetenz besteht.','Bedarf über Medienkompetenz besteht.'],0,'Bedarf an + Dativ'],['Welche Formulierung ist gehoben?',['eine Wirkung auf Zielgruppen entfalten','eine Wirkung über Zielgruppen machen','Wirkung an Zielgruppen geben','Wirkung mit Zielgruppen bauen'],0,'Funktionsverbgefüge']];
T.tf=[['Einfluss wird hier mit auf + Akkusativ verbunden.',true,'Rektion'],['Bedarf nach ist hier die empfohlene Form.',false,'Bedarf an + Dativ'],['Kaufentscheidungen treffen ist idiomatisch.',true,'Kollokation'],['Funktionsverbgefüge können einen Text sachlicher wirken lassen.',true,'Register']];
T.wordMatch=[['Einfluss ausüben','Wahrnehmung oder Verhalten prägen'],['eine Wirkung entfalten','eine Auswirkung entwickeln'],['Bedarf bestehen','etwas wird als notwendig angesehen'],['einen Beitrag leisten','eine Entwicklung unterstützen'],['Aufmerksamkeit lenken','einen Aspekt sichtbar machen'],['den Fokus legen','einen Aspekt in den Mittelpunkt stellen']];
T.hang=['Einfluss auf Entscheidungen ausüben','eine Wirkung auf Zielgruppen entfalten','Bedarf an Medienkompetenz bestehen','einen Beitrag zur Aufklärung leisten','Aufmerksamkeit auf Strategien lenken','Kaufentscheidungen treffen','Werbekampagnen konzipieren','Konsummuster prägen'];
L.short='<h3>Schreibfehler 1 · Kurzüberblick</h3><p>Dieses Modul trainiert feste Ausdrucksmuster, Präpositionalrektion, Kollokationen und Nomen-Verb-Verbindungen auf C1/C2-Niveau. Zentrale Muster sind <b>Einfluss auf + Akkusativ</b>, <b>Bedarf an + Dativ</b>, <b>Beitrag zu + Dativ</b> und <b>Aufmerksamkeit auf + Akkusativ lenken</b>.</p>';
L.medium='<h3>Schreibfehler 1 · Erweiterte Erklärung</h3><p>Auf C1/C2-Niveau werden Wörter nicht isoliert gelernt, sondern als vollständige grammatische Muster. Man sagt <b>Einfluss auf etwas ausüben</b>, <b>Bedarf an etwas bestehen</b>, <b>einen Beitrag zu etwas leisten</b> und <b>den Fokus auf etwas legen</b>. Diese Strukturen machen argumentative Texte präziser und idiomatischer.</p><p>Beispiele: <i>Digitale Plattformen üben Einfluss auf Konsumgewohnheiten aus.</i> <i>Es besteht Bedarf an transparenter Kennzeichnung.</i> <i>Schulische Projekte leisten einen Beitrag zur Medienkompetenz.</i></p>';
L.long=LONG;window.AAYS_SF2_1_PURE_DE_FINAL_OK=true;window.AAYS_SF2_1_1500_DE_ONLY_OK=true;renderDom();}
apply();setTimeout(apply,200);setTimeout(apply,900);setInterval(apply,160);document.addEventListener('click',function(){setTimeout(apply,60);setTimeout(apply,200);setTimeout(apply,700);},true);
try{new MutationObserver(function(){setTimeout(apply,30);}).observe(document.documentElement,{childList:true,subtree:true,characterData:true});}catch(e){}
})();