(function(){
'use strict';
function apply(){var T=(window.DEUTSCH_TESTS||{}).sf2_1,L=(window.DEUTSCH_LESSONS||{}).sf2_1;if(!T||!L)return;
T.title='Schreibfehler 1 · Ausdrucksmuster, Präpositionen und Nomen-Verb-Verbindungen';
T.topic='C1/C2 · Präpositionalrektion · Kollokationen · Nominalstil · Funktionsverbgefüge';
T.words=['Einfluss auf + Akkusativ ausüben','eine Wirkung auf + Akkusativ entfalten','Bedarf an + Dativ bestehen','einen Beitrag zu + Dativ leisten','Druck auf + Akkusativ ausüben','Interesse an + Dativ haben','Interesse für + Akkusativ wecken','den Fokus auf + Akkusativ legen','Aufmerksamkeit auf + Akkusativ lenken','zu + Dativ beitragen','dazu führen, dass','Kaufentscheidungen treffen','Werbekampagnen konzipieren','Konsummuster prägen'];
T.fill=[['Kommerzielle Inhalte üben Einfluss ___ die Wahrnehmung aus.','auf','Einfluss auf + Akkusativ'],['Emotionale Bildsprache entfaltet eine Wirkung ___ das Konsumverhalten.','auf','Wirkung auf + Akkusativ'],['Es besteht Bedarf ___ kritischer Medienkompetenz.','an','Bedarf an + Dativ'],['Bildungsangebote leisten einen Beitrag ___ Aufklärung.','zur','Beitrag zu + Dativ'],['Digitale Werbung lenkt Aufmerksamkeit ___ bestimmte Produkte.','auf','Aufmerksamkeit auf + Akkusativ'],['Dies führt ___, dass Kaufentscheidungen weniger reflektiert getroffen werden.','dazu','dazu führen, dass']];
T.mc=[['Welche Form ist korrekt?',['Einfluss auf Kaufentscheidungen ausüben','Einfluss über Kaufentscheidungen machen','Einfluss an Kaufentscheidungen geben','Einfluss mit Kaufentscheidungen bauen'],0,'Rektion'],['Welche Kollokation ist idiomatisch?',['Kaufentscheidungen treffen','Kaufentscheidungen machen','Kaufentscheidungen bauen','Kaufentscheidungen erledigen'],0,'Kollokation'],['Welche Form ist korrekt?',['Bedarf an Medienkompetenz besteht.','Bedarf nach Medienkompetenz besteht.','Bedarf für Medienkompetenz besteht.','Bedarf über Medienkompetenz besteht.'],0,'Bedarf an + Dativ'],['Welche Formulierung ist gehoben?',['eine Wirkung auf Zielgruppen entfalten','eine Wirkung über Zielgruppen machen','Wirkung an Zielgruppen geben','Wirkung mit Zielgruppen bauen'],0,'Funktionsverbgefüge']];
T.tf=[['Einfluss wird hier mit auf + Akkusativ verbunden.',true,'Rektion'],['Bedarf nach ist hier die empfohlene Form.',false,'Bedarf an + Dativ'],['Kaufentscheidungen treffen ist idiomatisch.',true,'Kollokation'],['Funktionsverbgefüge können einen Text sachlicher wirken lassen.',true,'Register']];
T.wordMatch=[['Einfluss ausüben','Wahrnehmung oder Verhalten prägen'],['eine Wirkung entfalten','eine Auswirkung entwickeln'],['Bedarf bestehen','etwas wird als notwendig angesehen'],['einen Beitrag leisten','eine Entwicklung unterstützen'],['Aufmerksamkeit lenken','einen Aspekt sichtbar machen'],['den Fokus legen','einen Aspekt in den Mittelpunkt stellen']];
T.hang=['Einfluss auf Entscheidungen ausüben','eine Wirkung auf Zielgruppen entfalten','Bedarf an Medienkompetenz bestehen','einen Beitrag zur Aufklärung leisten','Aufmerksamkeit auf Strategien lenken','Kaufentscheidungen treffen','Werbekampagnen konzipieren','Konsummuster prägen'];
L.short='<h3>Schreibfehler 1 · Kurzüberblick</h3><p>Dieses Modul trainiert feste Ausdrucksmuster, Präpositionalrektion, Kollokationen und Nomen-Verb-Verbindungen auf C1/C2-Niveau. Zentrale Muster sind: <b>Einfluss auf + Akkusativ</b>, <b>Bedarf an + Dativ</b>, <b>Beitrag zu + Dativ</b> und <b>Aufmerksamkeit auf + Akkusativ lenken</b>.</p>';
L.medium='<h3>Schreibfehler 1 · Erweiterte Erklärung</h3><p>Auf C1/C2-Niveau werden Wörter nicht isoliert gelernt, sondern als vollständige grammatische Muster. Man sagt <b>Einfluss auf etwas ausüben</b>, <b>Bedarf an etwas bestehen</b>, <b>einen Beitrag zu etwas leisten</b> und <b>den Fokus auf etwas legen</b>. Diese Strukturen machen argumentative Texte präziser und idiomatischer.</p><p>Beispiele: <i>Digitale Plattformen üben Einfluss auf Konsumgewohnheiten aus.</i> <i>Es besteht Bedarf an transparenter Kennzeichnung.</i> <i>Schulische Projekte leisten einen Beitrag zur Medienkompetenz.</i></p>';
L.long='<h3>Schreibfehler 1 · Ausführliche C1/C2-Erklärung</h3><p><b>Schwerpunkt:</b> Dieses Kapitel behandelt rektionale Sicherheit, Kollokationen und Funktionsverbgefüge für gehobene argumentative Texte.</p><h4>1. Rektion</h4><p>Das Nomen <b>Einfluss</b> wird mit <b>auf + Akkusativ</b> verbunden: <i>Werbekampagnen üben Einfluss auf das Konsumverhalten aus.</i> Das Nomen <b>Bedarf</b> verlangt <b>an + Dativ</b>: <i>Es besteht Bedarf an kritischer Medienkompetenz.</i></p><h4>2. Kollokationen</h4><p>Man schreibt <b>Kaufentscheidungen treffen</b>, <b>Werbekampagnen konzipieren</b>, <b>Konsummuster prägen</b> und <b>eine Wirkung entfalten</b>. Solche Verbindungen wirken idiomatisch und registergerecht.</p><h4>3. Modellabsatz</h4><p>Kommerzielle Inhalte in digitalen Medien üben erheblichen Einfluss auf die Wahrnehmung aus. Besonders problematisch ist, dass Empfehlungen häufig in persönliche Erzählungen eingebettet werden. Dadurch kann der Eindruck entstehen, es handle sich nicht um Werbung, sondern um authentische Erfahrung. Dies kann dazu führen, dass Kaufentscheidungen weniger reflektiert getroffen werden.</p><h4>4. Fehlerdiagnose</h4><p>Falsch: <i>Einfluss über etwas machen.</i> Richtig: <b>Einfluss auf etwas ausüben.</b> Falsch: <i>Bedarf nach etwas besteht.</i> Richtig: <b>Bedarf an etwas besteht.</b></p>';window.AAYS_SF2_1_PURE_DE_FINAL_OK=true;}
apply();setTimeout(apply,200);setTimeout(apply,900);document.addEventListener('click',function(){setTimeout(apply,200);},true);
})();