/* Stable strict main menu with guaranteed Schreiben Fehler 2 data loading. */
(function(){
'use strict';
var cards=[
{id:'catTest',kind:'link',href:'./erorterung_tests.html?v=erorterung-8a3d0618c',title:'Test',desc:'C1/C2 Erörterung test sistemini aç.'},
{id:'catGrammar',cat:'Genel Grammer',title:'Genel Grammar',desc:'Satzbau, Kasus, Artikel, Pronomen, Negation ve doğru gramerle yazma.'},
{id:'catWrite',cat:'Schreiben Fehlern',title:'Schreiben Fehler',desc:'Kelime, kalıp, Präposition ve C1/C2 yazma hatası testleri.'},
{id:'catWrite2',cat:'Schreiben Fehler 2',title:'Schreiben Fehler 2',desc:'Schreiben fehlern 1/2/3/4/5/6/7/8/10: Kalıplar, Präpositionen, Rektion, Satzbau, Meinungsfreiheit, Anonymität, Vorbilder, Zeitmanagement ve NVV.'},
{id:'catNVV',cat:'NVV',title:'NVV',desc:'Nomen-Verb-Verbindungen ve akademik yazma kalıpları.'},
{id:'catBefore',cat:'Bevor Schreiben',title:'Bevor Schreiben / Bewerbungsschreiben',desc:'Vorteile/Nachteile konu anlatımları ve yazma hazırlığı.'}
];
function E(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;'}[c]})}
function style(){if(E('aays-strict-six-menu-style'))return;var st=document.createElement('style');st.id='aays-strict-six-menu-style';st.textContent='#testList{min-height:260px}#strictMainGrid .opt,#strictMainGrid b,#strictMainGrid strong{color:#111827!important;text-shadow:none!important}#strictMainGrid .muted{color:#4b5563!important}';document.head.appendChild(st)}
function load(src,flag,cb){if(window[flag]){if(cb)cb();return}window[flag]=true;var s=document.createElement('script');s.src=src;s.async=false;s.onload=function(){if(cb)cb()};(document.head||document.documentElement).appendChild(s)}
function loadWrite2(cb){var left=17;function done(){left--;if(left<=0&&cb)cb()}load('data_schreiben_fehler2_kaliplar_praep_nvv.js?v=2','AAYS_SF2_T1_CORE_DIRECT_OK',done);load('data_schreiben_fehler2_kaliplar_praep_nvv_long.js?v=2','AAYS_SF2_T1_LONG_DIRECT_OK',done);load('data_schreiben_fehler2_medien_wirtschaft_praep_nvv.js?v=6','AAYS_SF2_T2_CORE_DIRECT_OK',done);load('data_schreiben_fehler2_medien_wirtschaft_praep_nvv_long.js?v=2','AAYS_SF2_T2_LONG_DIRECT_OK',done);load('data_schreiben_fehler3_sprachfehler_praep_nvv.js?v=1','AAYS_SF2_3_SOURCE_DIRECT_OK',done);load('sf2_4_pure_de_1500_final.js?v=2','AAYS_SF2_4_PURE_DE_DIRECT_OK',done);load('data_schreiben_fehler5_core.js?v=1','AAYS_SF2_5_CORE_DIRECT_OK',done);load('data_schreiben_fehler5_long1.js?v=1','AAYS_SF2_5_LONG1_DIRECT_OK',done);load('data_schreiben_fehler5_long2.js?v=1','AAYS_SF2_5_LONG2_DIRECT_OK',done);load('data_schreiben_fehler5_long3.js?v=1','AAYS_SF2_5_LONG3_DIRECT_OK',done);load('data_schreiben_fehler5_long4.js?v=1','AAYS_SF2_5_LONG4_DIRECT_OK',done);load('data_schreiben_fehler5_mindestlohn_mehrsprachigkeit.js?v=1','AAYS_SF2_5_MIND_MEHR_DIRECT_OK',done);load('data_schreiben_fehler6_schulsprache_auslandsstudium_autonome_fahrzeuge.js?v=1','AAYS_SF2_6_SOURCE_DIRECT_OK',done);load('data_schreiben_fehler7_autonome_fahrzeuge_recherche_ebooks_praep_nvv.js?v=1','AAYS_SF2_7_SOURCE_DIRECT_OK',done);load('data_schreiben_fehler7_docx1_source_marker.js?v=1','AAYS_SF2_7_DOCX1_MARKER_DIRECT_OK',done);load('data_schreiben_fehler8_ebooks_massentourismus_alltag.js?v=1','AAYS_SF2_8_SOURCE_DIRECT_OK',done);load('data_schreiben_fehler10_meinungsfreiheit_anonymitaet_vorbilder_zeitmanagement.js?v=1','AAYS_SF2_10_SOURCE_DIRECT_OK',done)}
function loadBevorExtras(){load('data_bevor_ki_arbeitsplatz_nachteile.js?v=1','AAYS_KI_ARBEITSPLATZ_NACHTEILE_STRICT_LOADER_OK');load('data_bevor_ki_arbeitsplatz_nachteile_expand.js?v=3','AAYS_KI_ARBEITSPLATZ_NACHTEILE_EXPAND_STRICT_LOADER_V3_OK');load('data_bevor_videoueberwachung_schule_nachteile.js?v=6','AAYS_VIDEO_SCHULE_NACHTEILE_SOURCE6_CORE_LOAD_V6_OK');load('data_bevor_video_schule_nachteile_long1.js?v=6','AAYS_VIDEO_SCHULE_NACHTEILE_LONG1_SOURCE6_LOAD_OK');load('data_bevor_video_schule_nachteile_long2.js?v=6','AAYS_VIDEO_SCHULE_NACHTEILE_LONG2_SOURCE6_LOAD_OK');load('data_bevor_video_schule_nachteile_long3.js?v=6','AAYS_VIDEO_SCHULE_NACHTEILE_LONG3_SOURCE6_LOAD_OK');load('data_bevor_videoueberwachung_schule_vorteile_core.js?v=4','AAYS_VIDEO_SCHULE_VORTEILE_SOURCE4_CORE_LOAD_V4_OK');load('data_bevor_video_schule_vorteile_long1.js?v=4','AAYS_VIDEO_SCHULE_VORTEILE_LONG1_TEMPLATE_V4_LOAD_OK');load('data_bevor_video_schule_vorteile_long2.js?v=4','AAYS_VIDEO_SCHULE_VORTEILE_LONG2_TEMPLATE_V4_LOAD_OK');load('data_bevor_video_schule_vorteile_long3.js?v=4','AAYS_VIDEO_SCHULE_VORTEILE_LONG3_TEMPLATE_V4_LOAD_OK');load('data_bevor_video_schule_vorteile_long4.js?v=4','AAYS_VIDEO_SCHULE_VORTEILE_LONG4_TEMPLATE_V4_LOAD_OK');load('data_bevor_video_schule_vorteile_long5.js?v=4','AAYS_VIDEO_SCHULE_VORTEILE_LONG5_TEMPLATE_V4_LOAD_OK');load('data_bevor_video_schule_vorteile_long6.js?v=4','AAYS_VIDEO_SCHULE_VORTEILE_LONG6_TEMPLATE_V4_LOAD_OK');load('data_bevor_video_schule_vorteile_long7.js?v=4','AAYS_VIDEO_SCHULE_VORTEILE_LONG7_TEMPLATE_V4_LOAD_OK')}
function openCat(cat){window.__strictMainMenuActive=false;if(cat==='Schreiben Fehler 2'){loadWrite2(function(){setTimeout(function(){if(typeof window.renderTests==='function')window.renderTests(cat);else if(typeof renderTests==='function')renderTests(cat)},60)});return}if(cat==='Bevor Schreiben')loadBevorExtras();if(typeof window.renderTests==='function')window.renderTests(cat);else if(typeof renderTests==='function')renderTests(cat)}
function card(c){var inner='<b>'+esc(c.title)+'</b><br><span class="muted">'+esc(c.desc)+'</span>';if(c.kind==='link')return '<a class="opt" id="'+c.id+'" href="'+c.href+'" style="text-align:left;display:block;text-decoration:none">'+inner+'</a>';return '<button class="opt" id="'+c.id+'" style="text-align:left">'+inner+'</button>'}
function bind(){cards.forEach(function(c){if(!c.cat)return;var b=E(c.id);if(b)b.onclick=function(){openCat(c.cat)}})}
function menu(force){style();var list=E('testList');if(!list)return;if(!force&&E('strictMainGrid')){bind();return}try{if(typeof window.setControls==='function')window.setControls(false);else if(typeof setControls==='function')setControls(false)}catch(e){}var artikel=E('artikelMenuCard');list.innerHTML='<h2 style="color:#111827!important">İlk olarak ana başlığı seç</h2><p class="muted">Ana menüde sadece ana başlıklar gösterilir. Alt konu başlıkları kendi bölümüne girince görünür.</p><div id="strictMainGrid" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px;margin-top:12px">'+cards.map(card).join('')+'</div>';if(artikel)list.appendChild(artikel);bind();window.__strictMainMenuActive=true;window.AAYS_SCHREIBEN_FEHLER2_MENU_FIXED_OK=true}
window.renderCategoryChoice=function(){menu(true)};document.addEventListener('DOMContentLoaded',function(){menu(false);loadWrite2(function(){window.AAYS_SF2_PRELOADED_OK=true});loadBevorExtras()},{once:true});if(document.readyState!=='loading'){menu(false);loadWrite2(function(){window.AAYS_SF2_PRELOADED_OK=true});loadBevorExtras()}
window.AAYS_NO_FLICKER_STRICT_MENU_OK=true;window.AAYS_SCHREIBEN_FEHLER2_DIRECT_LOAD_OK=true;window.AAYS_SCHREIBEN_FEHLER4_MENU_LOADER_OK=true;window.AAYS_SCHREIBEN_FEHLER5_MENU_LOADER_OK=true;window.AAYS_SCHREIBEN_FEHLER6_MENU_LOADER_OK=true;window.AAYS_SCHREIBEN_FEHLER7_MENU_LOADER_OK=true;window.AAYS_SCHREIBEN_FEHLER7_DOCX1_MARKER_LOADER_OK=true;window.AAYS_SCHREIBEN_FEHLER8_MENU_LOADER_OK=true;window.AAYS_SCHREIBEN_FEHLER10_MENU_LOADER_OK=true;window.AAYS_VIDEO_SCHULE_VORTEILE_MENU_LOADER_V4_OK=true;window.AAYS_VIDEO_SCHULE_NACHTEILE_MENU_LOADER_V6_OK=true;
})();
