(function(){
var ID='t37',TITLE='Satzmustern 2 · C1/C2 Erörterung Satzmuster',TARGET=1450;
window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};window.LESSONS=window.LESSONS||{};
function wc(s){var m=String(s||'').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&[^;]+;/g,' ').match(/[A-Za-zÄÖÜäöüßÀ-ÿ0-9]+(?:[-’'][A-Za-zÄÖÜäöüßÀ-ÿ0-9]+)?/g);return m?m.length:0}
function best(){var a=window.DEUTSCH_LESSONS[ID]||{},b=window.LESSONS[ID]||{};var v=[a.long,a.lessonLong,a.longLesson,a.contentLong,b.long,b.lessonLong,b.longLesson,b.contentLong].filter(Boolean);v.sort(function(x,y){return wc(y)-wc(x)});return v[0]||''}
function setAll(s){var a=window.DEUTSCH_LESSONS[ID]=window.DEUTSCH_LESSONS[ID]||{},b=window.LESSONS[ID]=window.LESSONS[ID]||{};['long','lessonLong','longLesson','contentLong'].forEach(function(k){a[k]=s;b[k]=s});a.title=b.title=TITLE;a.category=b.category='Genel Grammer';a.cat=b.cat='Genel Grammer'}
function installTest(){window.DEUTSCH_TESTS[ID]=window.DEUTSCH_TESTS[ID]||{title:TITLE,category:'Genel Grammer',cat:'Genel Grammer',slug:'satzmuster_2_c1_c2_eroerterung',topic:'Einleitung · Begründung · Beispiel · Folge · Risiko · Bewertung',fill:[['Das Thema gewinnt zunehmend ___ Bedeutung.','an','Einleitung'],['Dies lässt sich damit erklären, ___ ...','dass','Erklärung'],['Daraus ergibt ___, dass ...','sich','Folge'],['Die Gefahr besteht ___, dass ...','darin','Risiko']],mc:[['Welche Formulierung nennt eine Ursache?',['Dies lässt sich damit erklären, dass ...','Abschließend lässt sich festhalten, dass ...'],0,'Quelle']],tf:[['Langfristig betrachtet kann dies dazu führen, dass ... zeigt eine Langzeitwirkung.',true,'Formel']],hang:['Das Thema gewinnt an Bedeutung','Dies lässt sich damit erklären dass','Daraus ergibt sich dass','Die Gefahr besteht darin dass','Aus meiner Sicht ist entscheidend']};}
function block(){return '<h4>Quellen-Erweiterung: Satzmuster 2</h4><p>Diese Ergänzung folgt der Quelle C1_C2_Eroerterung_Satzmuster_Teil2_Zusatz. Entscheidend ist die Sieben-Schritt-Formel: Beobachtung, Erklärung, Beispiel, Ergebnis, Risiko oder Chance, Langzeitwirkung und Bewertung. Der Lernende soll nicht nur einzelne Sätze auswendig lernen, sondern die Funktion jedes Satzmusters erkennen. Heutzutage lässt sich beobachten, dass ein Thema zuerst in einen aktuellen gesellschaftlichen Zusammenhang gestellt werden muss. Dies lässt sich damit erklären, dass eine C1/C2-Erörterung nicht mit einer einfachen Meinung beginnt, sondern mit einer nachvollziehbaren Situation. Dies lässt sich am Beispiel von Online-Studium, Werbung, Fertiggerichten oder Medien verdeutlichen. Daraus ergibt sich, dass Satzmuster wie Das Thema gewinnt zunehmend an Bedeutung, Dies lässt sich damit erklären, dass und Langfristig betrachtet kann dies dazu führen, dass als sicheres Gerüst dienen.</p><p>Besonders wichtig ist außerdem die Verbindung von Argument, Beispiel und Bewertung. Ein wesentlicher Vorteil oder Nachteil wird zuerst genannt, danach begründet und anschließend durch ein konkretes Beispiel erklärt. Die Gefahr besteht darin, dass Lernende sonst nur isolierte Kalıplar verwenden, ohne einen vollständigen Absatz zu bilden. Aus meiner Sicht ist entscheidend, dass jedes Muster einer klaren Aufgabe dient: Einleitung öffnet das Thema, Begründung erklärt den Hintergrund, Beispiel macht die Aussage konkret, Ergebnis zeigt die Folge, Risiko vertieft die Kritik und Bewertung schließt den Gedankengang ab.</p>'}
function run(){installTest();var s=best();if(!s){s='<h3>'+TITLE+'</h3><p>Satzmuster 2 kaynak modülü.</p>'}while(wc(s)<TARGET){s+=block()}setAll(s)}
window.__boostSatzmuster2Source=run;run();setTimeout(run,200);setTimeout(run,1000);setTimeout(run,2500);
})();