(function(){
  function patchWerbungLong(){
    window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};
    window.DEUTSCH_LESSONS.t31=window.DEUTSCH_LESSONS.t31||{};
    var current=window.DEUTSCH_LESSONS.t31.long||'';
    if(current.indexOf('WERBUNG_WORD_FULL_ERGAENZUNG')!==-1)return;
    var extra=`<section data-word-full="WERBUNG_WORD_FULL_ERGAENZUNG">
<h4>7A. Vollständige C1/C2-Wortschatz-Tabellen aus der Word-Datei</h4>
<h5>Manipulation und Konsumdruck</h5>
<table style="width:100%;border-collapse:collapse"><tr><td><b>Ausdruck</b></td><td><b>Prüfungstaugliche Verwendung</b></td></tr><tr><td>die Manipulation</td><td>Werbung kann eine manipulative Wirkung entfalten.</td></tr><tr><td>der Konsumdruck</td><td>Werbung erzeugt bei vielen Menschen Konsumdruck.</td></tr><tr><td>das Kaufverhalten</td><td>Das Kaufverhalten wird durch emotionale Botschaften beeinflusst.</td></tr><tr><td>die Bedürfnisweckung</td><td>Werbung arbeitet häufig mit gezielter Bedürfnisweckung.</td></tr><tr><td>die Kaufentscheidung</td><td>Kaufentscheidungen werden nicht immer rational getroffen.</td></tr><tr><td>der Materialismus</td><td>Langfristig kann Werbung materialistisches Denken fördern.</td></tr></table>
<h5>Jugendliche, Ideale und Selbstwert</h5>
<table style="width:100%;border-collapse:collapse"><tr><td><b>Ausdruck</b></td><td><b>Prüfungstaugliche Verwendung</b></td></tr><tr><td>das Schönheitsideal</td><td>Werbung vermittelt häufig unrealistische Schönheitsideale.</td></tr><tr><td>der Vergleichsdruck</td><td>Jugendliche geraten durch ideale Bilder unter Vergleichsdruck.</td></tr><tr><td>das Selbstwertgefühl</td><td>Das Selbstwertgefühl kann durch Werbung beeinträchtigt werden.</td></tr><tr><td>die Anerkennungssuche</td><td>Anerkennung wird teilweise an Konsum geknüpft.</td></tr><tr><td>die Körperwahrnehmung</td><td>Werbung kann die Körperwahrnehmung negativ beeinflussen.</td></tr><tr><td>die Konsumkultur</td><td>Werbung stärkt eine oberflächliche Konsumkultur.</td></tr></table>
<h5>Medien, Reizüberflutung und Datenschutz</h5>
<table style="width:100%;border-collapse:collapse"><tr><td><b>Ausdruck</b></td><td><b>Prüfungstaugliche Verwendung</b></td></tr><tr><td>die Reizüberflutung</td><td>Ständige Werbebotschaften können zu Reizüberflutung führen.</td></tr><tr><td>die Ablenkung</td><td>Werbung verursacht Ablenkung beim Lesen, Lernen oder Arbeiten.</td></tr><tr><td>die Aufmerksamkeitsspanne</td><td>Die Aufmerksamkeitsspanne kann durch ständige Unterbrechungen sinken.</td></tr><tr><td>die personalisierte Werbung</td><td>Personalisierte Werbung nutzt Daten über Interessen und Suchverhalten.</td></tr><tr><td>der Datenmissbrauch</td><td>Gezielte Werbung wirft Fragen nach Datenschutz und Datenmissbrauch auf.</td></tr><tr><td>die digitale Kontrolle</td><td>Personalisierte Anzeigen können das Gefühl digitaler Kontrolle verstärken.</td></tr></table>
<h4>8A. Vollständige Nomen-Verb-Verbindungen aus der Word-Datei</h4>
<table style="width:100%;border-collapse:collapse"><tr><td><b>Ausdruck</b></td><td><b>Prüfungstaugliche Verwendung</b></td></tr><tr><td>Kaufentscheidungen beeinflussen</td><td>Werbung beeinflusst Kaufentscheidungen oft stärker, als Verbraucher bemerken.</td></tr><tr><td>künstliche Bedürfnisse erzeugen</td><td>Viele Werbestrategien zielen darauf ab, künstliche Bedürfnisse zu erzeugen.</td></tr><tr><td>Konsumdruck ausüben</td><td>Besonders soziale Medien können Konsumdruck ausüben.</td></tr><tr><td>das Selbstwertgefühl beeinträchtigen</td><td>Idealbilder in der Werbung können das Selbstwertgefühl beeinträchtigen.</td></tr><tr><td>Vergleichsdruck erzeugen</td><td>Werbung erzeugt Vergleichsdruck, vor allem bei Jugendlichen.</td></tr><tr><td>zu Reizüberflutung führen</td><td>Die ständige Präsenz von Anzeigen kann zu Reizüberflutung führen.</td></tr><tr><td>die Konzentration stören</td><td>Werbung im Internet stört häufig die Konzentration.</td></tr><tr><td>Daten gezielt auswerten</td><td>Plattformen werten Daten gezielt aus, um passende Werbung zu zeigen.</td></tr><tr><td>kritisches Denken schwächen</td><td>Emotionale Werbung kann kritisches Denken schwächen.</td></tr><tr><td>finanzielle Belastung verursachen</td><td>Unkontrollierter Konsum kann finanzielle Belastung verursachen.</td></tr></table>
<h4>9A. Vollständige Redemittel aus der Word-Datei</h4>
<h5>Argumente einleiten</h5><ul><li>Ein wesentlicher Nachteil besteht darin, dass ...</li><li>Besonders problematisch ist, dass ...</li><li>Aus gesellschaftlicher Perspektive ist kritisch zu sehen, dass ...</li><li>Ein weiterer negativer Aspekt liegt darin, dass ...</li></ul>
<h5>Ursachen erklären</h5><ul><li>Dies lässt sich damit begründen, dass ...</li><li>Der Grund dafür liegt darin, dass ...</li><li>Dies ist vor allem darauf zurückzuführen, dass ...</li><li>Gerade im digitalen Alltag zeigt sich, dass ...</li></ul>
<h5>Folgen darstellen</h5><ul><li>Dies führt dazu, dass ...</li><li>Infolgedessen kann ...</li><li>Daraus ergibt sich, dass ...</li><li>Langfristig betrachtet besteht die Gefahr, dass ...</li></ul>
<h5>Vorsichtig formulieren</h5><ul><li>kann dazu führen, dass ...</li><li>könnte problematisch werden, wenn ...</li><li>unter bestimmten Umständen ...</li><li>nicht zu unterschätzen ist außerdem ...</li></ul>
<h4>10A. Musterabsätze vollständig</h4>
<h5>Musterabsatz 1: Manipulation und Konsumdruck</h5><p>Ein wesentlicher Nachteil der Werbung liegt in ihrer manipulativen Wirkung. Werbung informiert nicht nur über Produkte, sondern versucht gezielt, Wünsche und Bedürfnisse zu erzeugen. Besonders durch emotionale Bilder, Sonderangebote oder Influencer-Empfehlungen werden Menschen dazu verleitet, Dinge zu kaufen, die sie eigentlich nicht benötigen. Dadurch kann ein ständiger Konsumdruck entstehen. Langfristig betrachtet fördert Werbung somit ein materialistisches Denken und schwächt bewusste Kaufentscheidungen.</p>
<h5>Musterabsatz 2: Einfluss auf Jugendliche</h5><p>Ein weiterer negativer Aspekt der Werbung betrifft ihren Einfluss auf Jugendliche. In sozialen Medien sowie in der Mode- und Kosmetikwerbung werden häufig perfekte Körper, teure Produkte und scheinbar ideale Lebensstile gezeigt. Jugendliche vergleichen sich mit diesen Bildern und können dadurch unsicher werden. Werbung vermittelt oft den Eindruck, dass Anerkennung, Schönheit oder Erfolg von bestimmten Marken abhängen. Dies kann das Selbstwertgefühl beeinträchtigen und psychischen Druck erzeugen.</p>
<h5>Musterabsatz 3: Reizüberflutung und digitale Kontrolle</h5><p>Problematisch ist außerdem, dass Werbung im digitalen Alltag kaum noch zu vermeiden ist. Anzeigen, Pop-ups und gesponserte Beiträge unterbrechen Nutzer beim Lesen, Lernen oder Arbeiten. Dadurch wird nicht nur die Konzentration gestört, sondern auch eine Reizüberflutung gefördert. Hinzu kommt, dass viele Werbeanzeigen personalisiert sind und auf gesammelten Nutzerdaten beruhen. Somit stellt Werbung nicht nur ein Konsumproblem dar, sondern wirft auch Fragen nach Datenschutz und digitaler Kontrolle auf.</p>
<h4>11A. Schreibgerüst für einen Nachteilsabschnitt</h4><ol><li>Ein wesentlicher Nachteil der Werbung liegt darin, dass ...</li><li>Dies lässt sich damit begründen, dass ...</li><li>Ein konkretes Beispiel dafür ist ...</li><li>Dadurch kann ...</li><li>Langfristig betrachtet besteht die Gefahr, dass ...</li></ol>
<h4>12A. Kurze Übungen vollständig</h4>
<h5>Übung 1: Ergänze passende Begriffe</h5><ul><li>Werbung kann künstliche __________ erzeugen.</li><li>Personalisierte Anzeigen können das __________ beeinflussen.</li><li>Idealbilder in der Werbung können das __________ beeinträchtigen.</li><li>Zu viele Anzeigen führen häufig zu __________ und Ablenkung.</li></ul>
<h5>Übung 2: Formuliere gehobener</h5><ol><li>Werbung bringt Menschen dazu, Dinge zu kaufen.</li><li>Jugendliche vergleichen sich mit schönen Bildern.</li><li>Werbung im Internet nervt und lenkt ab.</li><li>Viele kaufen Sachen, die sie nicht brauchen.</li></ol>
<h5>Übung 3: Mini-Absatz schreiben</h5><p>Schreibe einen kurzen Nachteilsabschnitt mit diesen Bausteinen: Manipulation - künstliche Bedürfnisse - Konsumdruck - unnötige Käufe - materialistisches Denken.</p>
<h4>13A. Kompakte Kopiervorlage vollständig</h4>
<h5>Mini-Merksätze</h5><ul><li>Nachteil 1: Werbung - künstliche Bedürfnisse - Konsumdruck - unnötige Käufe</li><li>Nachteil 2: perfekte Bilder - Vergleichsdruck - Unsicherheit - geringeres Selbstwertgefühl</li><li>Nachteil 3: ständige Werbung - Ablenkung - Reizüberflutung - Konzentrationsverlust</li><li>Nachteil 4: personalisierte Werbung - Datensammlung - digitale Kontrolle - weniger Privatsphäre</li></ul>
</section>`;
    if(current.indexOf('7A. Vollständige C1/C2-Wortschatz-Tabellen')===-1){
      window.DEUTSCH_LESSONS.t31.long=current+extra;
    }
  }
  patchWerbungLong();
  document.addEventListener('DOMContentLoaded',patchWerbungLong);
  setInterval(patchWerbungLong,500);
})();
