(function(){
  function safe(v){return String(v||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]});}
  window.DEUTSCH_TESTS=window.DEUTSCH_TESTS||{};
  window.DEUTSCH_LESSONS=window.DEUTSCH_LESSONS||{};

  var WORDS=[
    'die Medienwirkung','die Meinungsbildung','die Manipulation','die Filterblase','die Polarisierung','die kritische Distanz','die öffentliche Meinung','die Falschinformation','die Desinformation','die Quellenkritik','die Medienkompetenz','die Verunsicherung','der Vertrauensverlust','der Vergleichsdruck','das Selbstwertgefühl','die Selbstdarstellung','die Anerkennungssuche','die Körperwahrnehmung','die psychische Belastung','die Reizüberflutung','der Konzentrationsverlust','die Medienabhängigkeit','die Aufmerksamkeitsspanne','die digitale Überforderung','die Bildschirmzeit','die Informationsflut','die Glaubwürdigkeit','die Öffentlichkeit','die digitale Plattform','die emotionale Inszenierung','die gesellschaftliche Spaltung','die algorithmische Steuerung','die öffentliche Meinung beeinflussen','Informationen einseitig darstellen','kritisches Denken schwächen','eine Filterblase erzeugen','gesellschaftliche Spaltung verstärken','emotionale Reaktionen auslösen','andere Perspektiven ausblenden','Meinungen gezielt steuern','Falschinformationen verbreiten','Quellen kritisch prüfen','Nutzer verunsichern','Misstrauen verursachen','Informationen einordnen','die Urteilsfähigkeit beeinträchtigen','Desinformation begünstigen','Vertrauen in Medien schwächen','Vergleichsdruck erzeugen','das Selbstwertgefühl beeinträchtigen','unrealistische Ideale vermitteln','psychischen Druck verursachen','Unsicherheit verstärken','nach Anerkennung streben','Abhängigkeit von Likes entwickeln','Selbstdarstellung fördern','die Konzentration stören','Ablenkung verursachen','Aufmerksamkeit beanspruchen','zu Reizüberflutung führen','die Aufmerksamkeitsspanne verringern','Medienabhängigkeit begünstigen','Erholungsphasen verkürzen','den Arbeitsfluss unterbrechen'
  ];

  var TEST_CORE={
    category:'Bevor Schreiben',
    slug:'werbung_nachteile_medien_word_c1_c2',
    title:'Werbung – Nachteile · C1/C2 Nachteilsabsatz',
    topic:'Quelle: Einfluss der Medien – Nachteile · Manipulation der Meinungsbildung · Fake News · Vergleichsdruck · Reizüberflutung · Medienabhängigkeit',
    words:WORDS,
    fill:[
      ['Der Einfluss der Medien kann problematisch sein, weil Medien Meinungen lenken, Falschinformationen verbreiten, Vergleichsdruck erzeugen und zu ____ führen können.','Reizüberflutung','Grundthese'],
      ['Besonders soziale Medien verstärken diese Probleme, da Inhalte schnell, emotional und oft ____ verbreitet werden.','ungeprüft','Grundthese'],
      ['Ein zentraler Nachteil liegt in der möglichen Manipulation der ____.','Meinungsbildung','Nachteil 1'],
      ['Algorithmen zeigen oft ähnliche Inhalte, wodurch Nutzer in einer einseitigen ____ bleiben können.','Sichtweise','Nachteil 1'],
      ['In einer ____ sehen Nutzer vor allem Inhalte, die ihre Meinung bestätigen.','Filterblase','Nachteil 1'],
      ['Einseitige Inhalte können zur ____ der Gesellschaft beitragen.','Polarisierung','Nachteil 1'],
      ['Medien stellen Informationen nicht immer neutral dar, sondern präsentieren Themen oft verkürzt oder ____.','emotional','Nachteil 1'],
      ['Ein weiterer Nachteil ist die schnelle Verbreitung von ____.','Falschinformationen','Nachteil 2'],
      ['Um Fake News zu erkennen, ist ____ besonders wichtig.','Quellenkritik','Nachteil 2'],
      ['Widersprüchliche Informationen können ____ auslösen.','Verunsicherung','Nachteil 2'],
      ['Fake News können zu einem ____ gegenüber Medien führen.','Vertrauensverlust','Nachteil 2'],
      ['Desinformation verfolgt oft das Ziel, Menschen bewusst in die Irre zu ____.','führen','Nachteil 2'],
      ['Soziale Medien können starken ____ erzeugen.','Vergleichsdruck','Nachteil 3'],
      ['Idealisierte Darstellungen können das ____ beeinträchtigen.','Selbstwertgefühl','Nachteil 3'],
      ['Likes können eine Form der ____ verstärken.','Anerkennungssuche','Nachteil 3'],
      ['Bearbeitete Bilder können die Körperwahrnehmung negativ ____.','beeinflussen','Nachteil 3'],
      ['Ständige Medieninhalte können zu ____ führen.','Reizüberflutung','Nachteil 4'],
      ['Benachrichtigungen können ____ verursachen.','Konzentrationsverlust','Nachteil 4'],
      ['Kurze Videos können die Aufmerksamkeitsspanne ____.','verringern','Nachteil 4'],
      ['Eine übermäßige Nutzung kann Medienabhängigkeit ____.','begünstigen','Nachteil 4'],
      ['Hohe Bildschirmzeit kann Schlaf und Erholung ____.','beeinträchtigen','Nachteil 4'],
      ['Medienkompetenz ist notwendig, um Inhalte ____ zu können.','einordnen','Kopiervorlage']
    ],
    mc:[
      ['Welche Grundthese passt zum hochgeladenen Word-Dokument?',['Der Einfluss der Medien kann problematisch sein, weil Medien Meinungen lenken, Falschinformationen verbreiten, Vergleichsdruck erzeugen und zu Reizüberflutung führen können.','Medien haben nur Vorteile und beeinflussen Menschen nicht.','Medien betreffen nur gedruckte Zeitungen.','Medien sind nur dann relevant, wenn es um Werbung auf Plakaten geht.'],0,'Grundthese'],
      ['Welche vier Nachteile stehen im Mittelpunkt der Word-Datei?',['Manipulation/Filterblasen, Fake News/Vertrauensverlust, Vergleichsdruck, Reizüberflutung/Konzentrationsverlust','Zeitmangel, Zertifikatsdruck, Weiterbildungskosten, Orientierungslosigkeit','Personalkosten, Preissteigerung, Automatisierung, Arbeitsplatzverlust','Egoismus, Anpassungsprobleme, Selbstdarstellung, soziale Isolation'],0,'Gliederung'],
      ['Was beschreibt eine Filterblase am genauesten?',['Nutzer sehen vor allem Inhalte, die ihre bisherigen Interessen oder Meinungen bestätigen.','Nutzer sehen ausschließlich neutrale und ausgewogene Inhalte.','Alle Quellen werden automatisch gleich sichtbar.','Medieninhalte verschwinden, sobald sie politisch sind.'],0,'Nachteil 1'],
      ['Welche Folge passt zu einseitiger Medienwirkung?',['Kritisches Denken kann geschwächt und gesellschaftliche Polarisierung verstärkt werden.','Nutzer entwickeln automatisch mehr kritische Distanz.','Andere Perspektiven werden grundsätzlich stärker sichtbar.','Emotionale Reaktionen verschwinden vollständig.'],0,'Nachteil 1'],
      ['Was ist ein zentrales Problem bei Fake News?',['Falsche Informationen können schnell verbreitet werden und das Vertrauen in Medien oder Institutionen schwächen.','Falsche Informationen verbreiten sich grundsätzlich sehr langsam.','Fake News verbessern die Quellenkritik automatisch.','Fake News haben keine Wirkung auf öffentliche Meinung.'],0,'Nachteil 2'],
      ['Welche Aussage passt zu Quellenkritik?',['Quellenkritik ist notwendig, um glaubwürdige Informationen von unseriösen Beiträgen zu unterscheiden.','Quellenkritik bedeutet, jede Nachricht sofort zu glauben.','Quellenkritik ist nur bei gedruckten Büchern nötig.','Quellenkritik verhindert jede Informationsflut.'],0,'Nachteil 2'],
      ['Welche Aussage passt zu Vergleichsdruck?',['Idealisierte Darstellungen in sozialen Medien können das Selbstwertgefühl beeinträchtigen.','Soziale Medien zeigen immer vollständige Realität.','Likes haben nie mit Anerkennung zu tun.','Jugendliche sind grundsätzlich nicht anfällig für ideale Bilder.'],0,'Nachteil 3'],
      ['Welche Folge passt zu ständiger Selbstdarstellung?',['Unsicherheit, Anerkennungssuche und psychische Belastung können verstärkt werden.','Alle Nutzer werden automatisch authentischer.','Vergleichsdruck verschwindet durch Filter.','Körperwahrnehmung wird nie beeinflusst.'],0,'Nachteil 3'],
      ['Welche Aussage passt zu Reizüberflutung?',['Ständige Inhalte, Benachrichtigungen und kurze Videos können Konzentration und Erholung beeinträchtigen.','Benachrichtigungen verbessern immer den Arbeitsfluss.','Kurze Videos verlängern grundsätzlich die Aufmerksamkeitsspanne.','Reizüberflutung betrifft nur Zeitungen.'],0,'Nachteil 4'],
      ['Welche Aussage passt zu Medienabhängigkeit?',['Plattformen können durch Empfehlungen und automatische Wiedergabe dazu führen, dass Nutzer immer weiter konsumieren.','Medienabhängigkeit entsteht nur durch Bücher.','Automatische Empfehlungen verkürzen immer die Bildschirmzeit.','Mediennutzung hat keinen Einfluss auf Schlaf oder Lernen.'],0,'Nachteil 4'],
      ['Welche C1/C2-Formulierung ist am besten?',['Problematisch ist, dass Medien Inhalte verkürzt oder emotional darstellen können, wodurch eine objektive Meinungsbildung erschwert wird.','Medien sind schlecht, weil sie lügen.','Medien machen einfach alles kaputt.','Internet ist immer gefährlich und fertig.'],0,'Stil'],
      ['Welche Nomen-Verb-Verbindung ist korrekt?',['kritisches Denken schwächen','kritisches Denken schlafen','kritisches Denken wohnen','kritisches Denken bekommen'],0,'NVV']
    ],
    tf:[
      ['Medien können die öffentliche Meinung beeinflussen.',true,'Nachteil 1'],
      ['Algorithmen können Filterblasen verstärken.',true,'Nachteil 1'],
      ['Eine Filterblase macht immer alle Perspektiven gleich sichtbar.',false,'Nachteil 1'],
      ['Fake News können zu Verunsicherung und Vertrauensverlust führen.',true,'Nachteil 2'],
      ['Quellenkritik ist für Medienkompetenz unwichtig.',false,'Nachteil 2'],
      ['Soziale Medien können Vergleichsdruck erzeugen.',true,'Nachteil 3'],
      ['Idealisierte Bilder stärken immer das Selbstwertgefühl.',false,'Nachteil 3'],
      ['Benachrichtigungen können die Konzentration stören.',true,'Nachteil 4'],
      ['Übermäßige Mediennutzung kann Medienabhängigkeit begünstigen.',true,'Nachteil 4'],
      ['Eine gute C1/C2-Erörterung zählt nur Stichwörter auf.',false,'Aufbau'],
      ['Ein starker Absatz verbindet Beobachtung, Erklärung, Beispiel, Folge und langfristige Wirkung.',true,'Aufbau']
    ],
    wordMatch:[
      ['die Medienwirkung','Einfluss von Medien auf Wahrnehmung, Denken oder Verhalten'],
      ['die Meinungsbildung','Prozess, in dem Menschen eine Meinung entwickeln'],
      ['die Filterblase','einseitiger Informationsraum, in dem ähnliche Meinungen dominieren'],
      ['die Polarisierung','Verhärtung und Spaltung gesellschaftlicher Positionen'],
      ['die kritische Distanz','Fähigkeit, Inhalte nicht sofort zu übernehmen, sondern einzuordnen'],
      ['die Falschinformation','falsche Information, die sich schnell verbreiten kann'],
      ['die Desinformation','bewusst irreführende oder falsche Information'],
      ['die Quellenkritik','kritische Prüfung von Herkunft und Glaubwürdigkeit einer Information'],
      ['die Medienkompetenz','Fähigkeit, Medieninhalte kritisch einzuordnen'],
      ['der Vertrauensverlust','Abnahme des Vertrauens in Medien, Institutionen oder Experten'],
      ['der Vergleichsdruck','Druck, sich mit idealisierten Darstellungen anderer zu vergleichen'],
      ['das Selbstwertgefühl','Gefühl des eigenen Wertes'],
      ['die Selbstdarstellung','bewusste Inszenierung der eigenen Person'],
      ['die Körperwahrnehmung','Wahrnehmung des eigenen Körpers'],
      ['die Reizüberflutung','Überforderung durch zu viele Informationen, Bilder und Benachrichtigungen'],
      ['die Medienabhängigkeit','problematische Gewohnheit übermäßiger Mediennutzung']
    ],
    phraseMatch:[
      ['die öffentliche Meinung','beeinflussen'],['Informationen einseitig','darstellen'],['kritisches Denken','schwächen'],['eine Filterblase','erzeugen'],['gesellschaftliche Spaltung','verstärken'],['emotionale Reaktionen','auslösen'],['andere Perspektiven','ausblenden'],['Meinungen gezielt','steuern'],['Falschinformationen','verbreiten'],['Quellen kritisch','prüfen'],['Nutzer','verunsichern'],['Misstrauen','verursachen'],['die Urteilsfähigkeit','beeinträchtigen'],['Vertrauen in Medien','schwächen'],['Vergleichsdruck','erzeugen'],['das Selbstwertgefühl','beeinträchtigen'],['unrealistische Ideale','vermitteln'],['psychischen Druck','verursachen'],['Unsicherheit','verstärken'],['nach Anerkennung','streben'],['Abhängigkeit von Likes','entwickeln'],['Selbstdarstellung','fördern'],['die Konzentration','stören'],['Ablenkung','verursachen'],['Aufmerksamkeit','beanspruchen'],['zu Reizüberflutung','führen'],['die Aufmerksamkeitsspanne','verringern'],['Medienabhängigkeit','begünstigen'],['Erholungsphasen','verkürzen'],['den Arbeitsfluss','unterbrechen']
    ],
    prep:[
      ['Ein zentraler Nachteil liegt ___ der Manipulation der Meinungsbildung.','in','liegen in + Dativ'],
      ['Medien können Einfluss ___ die öffentliche Meinung nehmen.','auf','Einfluss nehmen auf + Akkusativ'],
      ['Nutzer werden häufig ___ ähnlichen Inhalten konfrontiert.','mit','konfrontiert werden mit + Dativ'],
      ['Fake News können ___ Vertrauensverlust führen.','zu','führen zu + Dativ'],
      ['Menschen unterscheiden seriöse Quellen ___ unseriösen Beiträgen.','von','unterscheiden von + Dativ'],
      ['Jugendliche vergleichen sich ___ idealisierten Bildern.','mit','sich vergleichen mit + Dativ'],
      ['Medien können sich negativ ___ das Selbstwertgefühl auswirken.','auf','sich auswirken auf + Akkusativ'],
      ['Benachrichtigungen lenken ___ Lernen ab.','vom','ablenken von + Dativ'],
      ['Viele Plattformen sind darauf ausgelegt, Nutzer lange ___ binden.','zu','ausgelegt sein, zu + Infinitiv'],
      ['Langfristig besteht die Gefahr, ___ kritisches Denken geschwächt wird.','dass','Gefahr, dass + Nebensatz']
    ],
    hang:['Manipulation der Meinungsbildung','emotionale Schlagzeilen und einseitige Berichterstattung','eine Filterblase erzeugen','gesellschaftliche Spaltung verstärken','kritisches Denken schwächen','andere Perspektiven ausblenden','Fake News und Vertrauensverlust','Falschinformationen verbreiten','Quellen kritisch prüfen','Vertrauen in Medien schwächen','Vergleichsdruck durch soziale Medien','das Selbstwertgefühl beeinträchtigen','unrealistische Ideale vermitteln','Abhängigkeit von Likes entwickeln','Reizüberflutung und Konzentrationsverlust','Benachrichtigungen beim Lernen','die Aufmerksamkeitsspanne verringern','Medienabhängigkeit begünstigen','Erholungsphasen verkürzen','algorithmische Steuerung beeinflusst Informationen','Medienkompetenz entwickeln','kompakte Kopiervorlage für die Prüfung']
  };

  var SHORT=`<h3>Werbung / Einfluss der Medien – Nachteile · Kurz</h3><p><b>Grundthese:</b> Der Einfluss der Medien kann problematisch sein, weil Medien Meinungen lenken, Falschinformationen verbreiten, Vergleichsdruck erzeugen und zu Reizüberflutung führen können.</p><ul><li><b>Manipulation:</b> Medien können Meinungsbildung beeinflussen und Filterblasen erzeugen.</li><li><b>Fake News:</b> Falschinformationen verbreiten sich schnell und schwächen Vertrauen.</li><li><b>Vergleichsdruck:</b> Soziale Medien vermitteln unrealistische Ideale und belasten das Selbstbild.</li><li><b>Reizüberflutung:</b> Benachrichtigungen, Videos und Werbung stören Konzentration und fördern Medienabhängigkeit.</li></ul>`;

  var MEDIUM=`<h3>Werbung / Einfluss der Medien – Nachteile · Mittel</h3><h4>1. Grundidee</h4><p>Medien prägen den Alltag durch Nachrichten, soziale Netzwerke, Videos, Werbung und digitale Plattformen. In einer C1/C2-Erörterung geht es nicht darum, Medien pauschal abzulehnen, sondern problematische Wirkungen präzise zu erklären.</p><h4>2. Manipulation und Filterblasen</h4><p>Medien stellen Inhalte nicht immer neutral dar. Algorithmen zeigen ähnliche Beiträge immer wieder, wodurch einseitige Meinungsbildung, Filterblasen und Polarisierung entstehen können.</p><h4>3. Fake News und Vertrauensverlust</h4><p>Falschinformationen, Clickbait, manipulierte Bilder oder aus dem Zusammenhang gerissene Videos können Nutzer verunsichern und das Vertrauen in seriöse Quellen schwächen.</p><h4>4. Vergleichsdruck und psychische Belastung</h4><p>Soziale Medien zeigen häufig idealisierte Körper, Erfolg und Lebensstile. Besonders Jugendliche können dadurch unter Druck geraten und ihr Selbstwertgefühl verlieren.</p><h4>5. Reizüberflutung und Konzentrationsverlust</h4><p>Ständige Benachrichtigungen, kurze Videos, Werbung und neue Beiträge unterbrechen Lernen und Arbeiten. Langfristig können Konzentration, Schlaf und Leistungsfähigkeit beeinträchtigt werden.</p>`;

  var LONG=`<h3>Einfluss der Medien – Nachteile | C1/C2-Erörterungsvorbereitung</h3>
<h3>Einfluss der Medien – Nachteile</h3>
<p><b>Ausführliche C1/C2-Vorbereitung für eine Erörterung</b></p>
<h4>Ziel dieses Arbeitsblatts</h4>
<ul><li>Dieses Dokument bereitet dich nur auf die Nachteile des Medieneinflusses vor.</li><li>Der Fokus liegt auf Formulierungen, die in einer deutschen Sprachprüfung natürlich und anspruchsvoll wirken.</li><li>Du bekommst Argumentationsideen, Wortschatz, Satzbausteine, Musterabsätze und Übungen für einen C1/C2-Nachteilsabsatz.</li></ul>
<h4>1. Grundverständnis des Themas</h4>
<p>Der Einfluss der Medien ist ein sehr prüfungsgeeignetes Thema, weil fast jeder Mensch im Alltag mit Nachrichten, sozialen Netzwerken, Videos, Werbung und digitalen Plattformen konfrontiert wird. Für einen Nachteile-Absatz musst du nicht wissenschaftlich erklären, wie Medien funktionieren. Wichtiger ist, dass du zeigen kannst, welche Probleme durch Medien entstehen können und wie sie sich auf Denken, Verhalten und Alltag auswirken.</p>
<p>In einer Erörterung kannst du besonders darauf eingehen, dass Medien Meinungen beeinflussen, falsche Informationen verbreiten, Menschen psychisch unter Druck setzen und die Konzentration schwächen können. Entscheidend ist, dass du nicht nur Stichwörter aufzählst, sondern eine klare Kette bildest: Beobachtung – Erklärung – Beispiel – Folge – langfristige Wirkung.</p>
<h4>Mögliche Grundthese</h4><ul><li>Der Einfluss der Medien kann problematisch sein, weil Medien Meinungen lenken, Falschinformationen verbreiten, Vergleichsdruck erzeugen und zu Reizüberflutung führen können.</li><li>Besonders soziale Medien verstärken diese Probleme, da Inhalte schnell, emotional und oft ungeprüft verbreitet werden.</li></ul>
<h4>2. Aufbau eines starken Nachteile-Absatzes</h4>
<p>Ein guter Nachteile-Absatz besteht nicht nur aus einem Beispiel. Er sollte logisch aufgebaut sein. Beginne mit einem klaren Argument, erkläre den Mechanismus, nenne ein alltagsnahes Beispiel und zeige anschließend die Folgen. Dadurch wirkt dein Text reifer und überzeugender.</p>
<ol><li><b>Argument nennen:</b> Ein zentraler Nachteil liegt in ...</li><li><b>Begründen:</b> Dies lässt sich damit erklären, dass ...</li><li><b>Beispiel geben:</b> Besonders deutlich wird dies bei ...</li><li><b>Folge erklären:</b> Dadurch kann ...</li><li><b>Langfristige Wirkung zeigen:</b> Auf lange Sicht besteht die Gefahr, dass ...</li></ol>
<p><b>Prüfungstipp:</b> Vermeide sehr einfache Sätze wie: Medien sind schlecht, weil sie lügen. Besser: Problematisch ist, dass Medien Inhalte verkürzt oder emotional darstellen können, wodurch eine objektive Meinungsbildung erschwert wird.</p>
<h4>Nachteil 1: Manipulation der Meinungsbildung und Filterblasen</h4>
<h5>Kernidee für die Prüfung</h5><ul><li>Medien können beeinflussen, wie Menschen über Politik, Gesellschaft oder andere Gruppen denken.</li><li>Besonders Algorithmen zeigen oft ähnliche Inhalte, wodurch Nutzer in einer einseitigen Sichtweise bleiben können.</li></ul>
<h5>1. Beobachtungen aus dem Alltag</h5><ul><li>emotionale Schlagzeilen</li><li>einseitige Berichterstattung</li><li>politische Inhalte in sozialen Medien</li><li>Influencer mit starken Meinungen</li><li>Kommentare, die Vorurteile verstärken</li><li>Algorithmen zeigen immer ähnliche Beiträge</li></ul>
<h5>2. Detaillierte Erklärung</h5><p>Ein wichtiger Nachteil besteht darin, dass Medien nicht immer neutral informieren. Themen werden häufig vereinfacht, zugespitzt oder emotional dargestellt, damit sie mehr Aufmerksamkeit erzeugen. Dadurch kann der Eindruck entstehen, eine bestimmte Meinung sei besonders überzeugend oder allgemein akzeptiert.</p><p>In sozialen Medien wird dieser Effekt durch Algorithmen verstärkt. Nutzer bekommen oft Inhalte angezeigt, die zu ihren bisherigen Interessen oder Meinungen passen. So entsteht eine Filterblase, in der andere Perspektiven kaum noch sichtbar sind. Für eine demokratische Gesellschaft ist das problematisch, weil kritisches Denken und offener Austausch geschwächt werden können.</p>
<h5>3. Konkrete Beispiele für den Absatz</h5><ul><li>politische Kurzvideos auf TikTok oder Instagram</li><li>reißerische Überschriften in Online-Nachrichten</li><li>YouTube-Empfehlungen mit immer ähnlichen Meinungen</li><li>Kommentare, die Feindbilder verstärken</li><li>einseitige Darstellung komplexer Themen</li><li>emotionale Bilder, die starke Reaktionen auslösen</li></ul>
<h5>4. Ergebnisse und Folgen</h5><ul><li>einseitige Meinungsbildung</li><li>weniger kritisches Denken</li><li>stärkere Polarisierung</li><li>Misstrauen gegenüber anderen Meinungen</li><li>Verhärtung politischer Positionen</li><li>weniger Bereitschaft zum Dialog</li></ul>
<h5>5. Potenzielle Risiken</h5><ul><li>Manipulation der öffentlichen Meinung</li><li>gesellschaftliche Spaltung</li><li>Beeinflussung politischer Entscheidungen</li><li>Verbreitung von Vorurteilen</li><li>Verlust objektiver Urteilsfähigkeit</li><li>Radikalisierung einzelner Gruppen</li></ul>
<h5>6. Anwendungsbereiche</h5><ul><li>soziale Medien</li><li>Nachrichtenportale</li><li>politische Werbung</li><li>Kommentarbereiche</li><li>YouTube</li><li>TikTok und Instagram</li></ul>
<h5>7. Kurz- und Langzeitwirkungen</h5><table style="width:100%;border-collapse:collapse"><tr><td><b>kurzfristig</b></td><td><b>langfristig</b></td></tr><tr><td>schnelle Meinungsbildung</td><td>Polarisierung</td></tr><tr><td>emotionale Reaktionen</td><td>schwächeres Vertrauen in neutrale Information</td></tr><tr><td>weniger kritische Distanz</td><td>gesellschaftliche Spaltung</td></tr></table>
<h5>8. C1/C2-Wortschatz für diesen Nachteil</h5><table style="width:100%;border-collapse:collapse"><tr><td><b>Ausdruck</b></td><td><b>Verwendung im Satz</b></td></tr><tr><td>die Meinungsbildung</td><td>Medien können die Meinungsbildung stark beeinflussen.</td></tr><tr><td>die Manipulation</td><td>Manipulation entsteht, wenn Informationen gezielt einseitig dargestellt werden.</td></tr><tr><td>die Filterblase</td><td>In einer Filterblase sehen Nutzer vor allem Inhalte, die ihre Meinung bestätigen.</td></tr><tr><td>die Polarisierung</td><td>Einseitige Inhalte können zur Polarisierung der Gesellschaft beitragen.</td></tr><tr><td>die kritische Distanz</td><td>Kritische Distanz ist notwendig, um Medieninhalte richtig einzuordnen.</td></tr><tr><td>die öffentliche Meinung</td><td>Medien haben großen Einfluss auf die öffentliche Meinung.</td></tr></table>
<h5>9. Nomen-Verb-Verbindungen und starke Verben</h5><ul><li>die öffentliche Meinung beeinflussen</li><li>Informationen einseitig darstellen</li><li>kritisches Denken schwächen</li><li>eine Filterblase erzeugen</li><li>gesellschaftliche Spaltung verstärken</li><li>emotionale Reaktionen auslösen</li><li>andere Perspektiven ausblenden</li><li>Meinungen gezielt steuern</li></ul>
<h5>10. Satzbausteine</h5><ul><li>Ein zentraler Nachteil des Medieneinflusses liegt in der möglichen Manipulation der Meinungsbildung.</li><li>Medien stellen Informationen nicht immer neutral dar, sondern präsentieren Themen oft verkürzt oder emotional.</li><li>Besonders problematisch ist, dass Algorithmen ähnliche Inhalte immer wieder anzeigen.</li><li>Dadurch kann eine Filterblase entstehen, in der andere Perspektiven kaum noch wahrgenommen werden.</li><li>Langfristig kann dies zu Polarisierung und gesellschaftlicher Spaltung führen.</li></ul>
<h5>11. Musterabsatz</h5><p>Ein zentraler Nachteil des Medieneinflusses liegt in der möglichen Manipulation der Meinungsbildung. Medien informieren nicht immer neutral, sondern stellen Themen häufig emotional oder einseitig dar. Besonders soziale Netzwerke verstärken diesen Effekt, da Algorithmen Inhalte anzeigen, die zur bisherigen Meinung der Nutzer passen. Dadurch kann eine Filterblase entstehen, in der andere Perspektiven kaum noch vorkommen. Langfristig betrachtet wird dadurch nicht nur kritisches Denken geschwächt, sondern auch die gesellschaftliche Polarisierung verstärkt.</p>
<h4>Nachteil 2: Fake News, Desinformation und Vertrauensverlust</h4>
<h5>Kernidee für die Prüfung</h5><ul><li>Falsche oder ungeprüfte Informationen verbreiten sich im Internet sehr schnell.</li><li>Wenn Menschen nicht mehr wissen, welchen Quellen sie vertrauen können, entsteht Verunsicherung.</li></ul>
<h5>1. Beobachtungen aus dem Alltag</h5><ul><li>falsche Nachrichten in sozialen Medien</li><li>Gerüchte in Messenger-Gruppen</li><li>Clickbait-Überschriften</li><li>bearbeitete Bilder oder Videos</li><li>unseriöse Quellen</li><li>schnelles Teilen ohne Prüfung</li></ul>
<h5>2. Detaillierte Erklärung</h5><p>Ein weiterer Nachteil ist die schnelle Verbreitung von Falschinformationen. Digitale Medien ermöglichen es, Inhalte innerhalb weniger Sekunden mit vielen Menschen zu teilen. Das ist besonders problematisch, wenn Informationen nicht überprüft werden und dennoch glaubwürdig wirken.</p><p>Viele Nutzer haben Schwierigkeiten, seriöse Quellen von unseriösen Beiträgen zu unterscheiden. Wenn ständig widersprüchliche Informationen auftauchen, kann dies zu Verunsicherung und Misstrauen führen. Auf Dauer leidet darunter auch das Vertrauen in Journalismus, Wissenschaft und öffentliche Institutionen.</p>
<h5>3. Konkrete Beispiele für den Absatz</h5><ul><li>Fake News über Politik oder Gesundheit</li><li>falsche Überschriften, die nur Klicks erzeugen sollen</li><li>Deepfakes oder manipulierte Bilder</li><li>Gerüchte in WhatsApp-Gruppen</li><li>unbelegte Behauptungen in Kommentarspalten</li><li>Videos, die aus dem Zusammenhang gerissen werden</li></ul>
<h5>4. Ergebnisse und Folgen</h5><ul><li>Verunsicherung der Nutzer</li><li>falsche Entscheidungen</li><li>Verlust des Vertrauens in Medien</li><li>mehr Misstrauen gegenüber Experten</li><li>Informationsmüdigkeit</li><li>schwächere Orientierung</li></ul>
<h5>5. Potenzielle Risiken</h5><ul><li>Verschwörungstheorien</li><li>Panik durch falsche Meldungen</li><li>Manipulation von Wahlen oder öffentlicher Meinung</li><li>gesellschaftliche Unsicherheit</li><li>Radikalisierung durch Desinformation</li><li>sinkende Medienkompetenz</li></ul>
<h5>6. Anwendungsbereiche</h5><ul><li>soziale Netzwerke</li><li>Messenger-Dienste</li><li>Online-Nachrichten</li><li>Blogs</li><li>Video-Plattformen</li><li>Kommentarbereiche</li></ul>
<h5>7. Kurz- und Langzeitwirkungen</h5><table style="width:100%;border-collapse:collapse"><tr><td><b>kurzfristig</b></td><td><b>langfristig</b></td></tr><tr><td>Verwirrung</td><td>Vertrauensverlust</td></tr><tr><td>schnelle Verbreitung falscher Inhalte</td><td>Informationsmüdigkeit</td></tr><tr><td>Unsicherheit bei der Quellenbewertung</td><td>schwächere Urteilsfähigkeit</td></tr></table>
<h5>8. C1/C2-Wortschatz für diesen Nachteil</h5><table style="width:100%;border-collapse:collapse"><tr><td><b>Ausdruck</b></td><td><b>Verwendung im Satz</b></td></tr><tr><td>die Falschinformation</td><td>Falschinformationen können sich im Internet sehr schnell verbreiten.</td></tr><tr><td>die Desinformation</td><td>Desinformation verfolgt oft das Ziel, Menschen bewusst in die Irre zu führen.</td></tr><tr><td>die Quellenkritik</td><td>Quellenkritik ist notwendig, um glaubwürdige Informationen zu erkennen.</td></tr><tr><td>die Medienkompetenz</td><td>Ohne Medienkompetenz fällt es schwer, Fake News zu erkennen.</td></tr><tr><td>die Verunsicherung</td><td>Widersprüchliche Informationen können Verunsicherung auslösen.</td></tr><tr><td>der Vertrauensverlust</td><td>Fake News können zu einem Vertrauensverlust gegenüber Medien führen.</td></tr></table>
<h5>9. Nomen-Verb-Verbindungen und starke Verben</h5><ul><li>Falschinformationen verbreiten</li><li>Quellen kritisch prüfen</li><li>Nutzer verunsichern</li><li>Misstrauen verursachen</li><li>Informationen einordnen</li><li>die Urteilsfähigkeit beeinträchtigen</li><li>Desinformation begünstigen</li><li>Vertrauen in Medien schwächen</li></ul>
<h5>10. Satzbausteine</h5><ul><li>Ein weiterer Nachteil besteht darin, dass Medien zur Verbreitung von Falschinformationen beitragen können.</li><li>Besonders in sozialen Netzwerken werden Inhalte oft geteilt, ohne dass ihre Quelle geprüft wird.</li><li>Dadurch können Fake News schnell eine große Reichweite bekommen.</li><li>Hinzu kommt, dass die ständige Informationsflut viele Menschen überfordert.</li><li>Langfristig kann dies das Vertrauen in seriöse Medien und Institutionen schwächen.</li></ul>
<h5>11. Musterabsatz</h5><p>Ein weiterer problematischer Aspekt des Medieneinflusses ist die Verbreitung von Fake News. In sozialen Netzwerken werden Inhalte häufig geteilt, ohne dass die Quelle kritisch überprüft wird. Dadurch können falsche Informationen schnell eine große Reichweite bekommen und viele Menschen verunsichern. Besonders problematisch ist, dass manipulierte Bilder, reißerische Überschriften oder aus dem Zusammenhang gerissene Videos oft glaubwürdig wirken. Langfristig kann dies zu Misstrauen gegenüber Medien und Institutionen führen.</p>
<h4>Nachteil 3: Vergleichsdruck, unrealistische Ideale und psychische Belastung</h4>
<h5>Kernidee für die Prüfung</h5><ul><li>Soziale Medien zeigen häufig ein perfektes Leben, das mit der Realität nur wenig zu tun hat.</li><li>Vor allem junge Menschen können dadurch unter Vergleichsdruck geraten.</li></ul>
<h5>1. Beobachtungen aus dem Alltag</h5><ul><li>perfekte Körperbilder auf Instagram</li><li>Luxusleben von Influencern</li><li>Filter und bearbeitete Fotos</li><li>Likes als Zeichen von Anerkennung</li><li>Angst, etwas zu verpassen</li><li>ständige Selbstdarstellung</li></ul>
<h5>2. Detaillierte Erklärung</h5><p>Medien zeigen oft idealisierte Bilder von Schönheit, Erfolg, Glück und sozialem Status. Besonders soziale Medien vermitteln den Eindruck, dass andere Menschen ein perfektes Leben führen. Diese Darstellung ist jedoch meist ausgewählt, bearbeitet und inszeniert.</p><p>Wenn Nutzer ihr eigenes Leben mit solchen Bildern vergleichen, können Unsicherheit und Unzufriedenheit entstehen. Besonders Jugendliche, die sich noch in der Identitätsentwicklung befinden, sind dafür anfällig. Der Druck, ebenfalls attraktiv, erfolgreich oder beliebt wirken zu müssen, kann psychische Belastungen verstärken.</p>
<h5>3. Konkrete Beispiele für den Absatz</h5><ul><li>Influencer zeigen nur schöne Momente</li><li>Filter verändern Gesicht und Körper</li><li>teure Kleidung wird als Statussymbol präsentiert</li><li>Urlaubsbilder erzeugen Neid</li><li>Likes werden mit Anerkennung verbunden</li><li>Fitness- und Beauty-Inhalte setzen unrealistische Maßstäbe</li></ul>
<h5>4. Ergebnisse und Folgen</h5><ul><li>geringeres Selbstwertgefühl</li><li>mehr Unsicherheit</li><li>Vergleichsdruck</li><li>Unzufriedenheit mit dem eigenen Leben</li><li>Abhängigkeit von Anerkennung</li><li>psychische Belastung</li></ul>
<h5>5. Potenzielle Risiken</h5><ul><li>Minderwertigkeitsgefühle</li><li>Körperunzufriedenheit</li><li>soziale Angst</li><li>ständige Suche nach Bestätigung</li><li>Selbstinszenierung statt Authentizität</li><li>depressive Verstimmungen</li></ul>
<h5>6. Anwendungsbereiche</h5><ul><li>Instagram</li><li>TikTok</li><li>Influencer-Marketing</li><li>Mode und Lifestyle</li><li>Jugendkultur</li><li>Freundeskreis</li></ul>
<h5>7. Kurz- und Langzeitwirkungen</h5><table style="width:100%;border-collapse:collapse"><tr><td><b>kurzfristig</b></td><td><b>langfristig</b></td></tr><tr><td>Unsicherheit</td><td>geringeres Selbstwertgefühl</td></tr><tr><td>Neid</td><td>psychischer Druck</td></tr><tr><td>Wunsch nach Anerkennung</td><td>Abhängigkeit von sozialen Medien</td></tr></table>
<h5>8. C1/C2-Wortschatz für diesen Nachteil</h5><table style="width:100%;border-collapse:collapse"><tr><td><b>Ausdruck</b></td><td><b>Verwendung im Satz</b></td></tr><tr><td>der Vergleichsdruck</td><td>Soziale Medien können starken Vergleichsdruck erzeugen.</td></tr><tr><td>das Selbstwertgefühl</td><td>Idealbilder können das Selbstwertgefühl beeinträchtigen.</td></tr><tr><td>die Selbstdarstellung</td><td>Viele Nutzer betreiben in sozialen Medien bewusste Selbstdarstellung.</td></tr><tr><td>die Anerkennungssuche</td><td>Likes können eine Form der Anerkennungssuche verstärken.</td></tr><tr><td>die Körperwahrnehmung</td><td>Bearbeitete Bilder können die Körperwahrnehmung negativ beeinflussen.</td></tr><tr><td>die psychische Belastung</td><td>Dauernder Vergleich kann psychische Belastung verursachen.</td></tr></table>
<h5>9. Nomen-Verb-Verbindungen und starke Verben</h5><ul><li>Vergleichsdruck erzeugen</li><li>das Selbstwertgefühl beeinträchtigen</li><li>unrealistische Ideale vermitteln</li><li>psychischen Druck verursachen</li><li>Unsicherheit verstärken</li><li>nach Anerkennung streben</li><li>Abhängigkeit von Likes entwickeln</li><li>Selbstdarstellung fördern</li></ul>
<h5>10. Satzbausteine</h5><ul><li>Ein weiterer Nachteil besteht im Vergleichsdruck, der vor allem durch soziale Medien entsteht.</li><li>Viele Beiträge zeigen ein idealisiertes Leben, das mit der Realität nur wenig zu tun hat.</li><li>Besonders Jugendliche können dadurch das Gefühl entwickeln, nicht schön, erfolgreich oder beliebt genug zu sein.</li><li>Dies kann das Selbstwertgefühl beeinträchtigen und psychische Belastungen verstärken.</li><li>Somit beeinflussen Medien nicht nur die Meinung, sondern auch das Selbstbild der Nutzer.</li></ul>
<h5>11. Musterabsatz</h5><p>Ein weiterer negativer Aspekt des Medieneinflusses besteht im Vergleichsdruck. Besonders soziale Medien zeigen häufig perfekte Körper, erfolgreiche Lebensstile und scheinbar glückliche Menschen. Viele Nutzer vergleichen ihr eigenes Leben mit diesen idealisierten Darstellungen und fühlen sich dadurch unzufrieden. Vor allem Jugendliche können unter dem Druck stehen, attraktiv, beliebt oder erfolgreich wirken zu müssen. Dadurch kann das Selbstwertgefühl beeinträchtigt und psychische Belastung verstärkt werden.</p>
<h4>Nachteil 4: Reizüberflutung, Konzentrationsverlust und Medienabhängigkeit</h4>
<h5>Kernidee für die Prüfung</h5><ul><li>Medien sind ständig verfügbar und unterbrechen den Alltag durch Benachrichtigungen, Videos und neue Inhalte.</li><li>Dadurch kann es schwerer werden, sich zu konzentrieren oder bewusst Pausen einzuhalten.</li></ul>
<h5>1. Beobachtungen aus dem Alltag</h5><ul><li>ständige Benachrichtigungen</li><li>kurze Videos in sozialen Medien</li><li>Ablenkung beim Lernen</li><li>ständiges Scrollen</li><li>Werbung vor Videos</li><li>Angst, etwas zu verpassen</li></ul>
<h5>2. Detaillierte Erklärung</h5><p>Ein weiterer Nachteil ist die Reizüberflutung. Nutzer werden täglich mit Nachrichten, Bildern, Videos, Werbung und Kommentaren konfrontiert. Diese Vielzahl an Eindrücken kann die Aufmerksamkeit stark beanspruchen und die Konzentration verringern.</p><p>Besonders problematisch ist, dass viele Medienplattformen darauf ausgelegt sind, Nutzer möglichst lange zu binden. Kurze Videos, automatische Empfehlungen und Benachrichtigungen führen dazu, dass man immer weiter konsumiert. Dadurch kann Mediennutzung zu einer Gewohnheit werden, die Lernen, Schlaf und soziale Kontakte beeinträchtigt.</p>
<h5>3. Konkrete Beispiele für den Absatz</h5><ul><li>ständiges Prüfen des Smartphones</li><li>kurze Videos statt längerer Texte</li><li>Ablenkung durch Benachrichtigungen beim Lernen</li><li>lange Bildschirmzeiten am Abend</li><li>automatische Wiedergabe neuer Videos</li><li>Scrollen ohne bewusstes Ziel</li></ul>
<h5>4. Ergebnisse und Folgen</h5><ul><li>Konzentrationsverlust</li><li>weniger produktive Lernzeit</li><li>Zeitverlust</li><li>schlechtere Schlafqualität</li><li>weniger echte Erholung</li><li>oberflächliche Mediennutzung</li></ul>
<h5>5. Potenzielle Risiken</h5><ul><li>Medienabhängigkeit</li><li>sinkende Aufmerksamkeitsspanne</li><li>Leistungsprobleme in Schule oder Beruf</li><li>soziale Vernachlässigung</li><li>digitale Überforderung</li><li>dauerhafte Unruhe</li></ul>
<h5>6. Anwendungsbereiche</h5><ul><li>Smartphone-Nutzung</li><li>Lernphasen</li><li>Schule</li><li>Studium</li><li>Arbeitsleben</li><li>Freizeit</li></ul>
<h5>7. Kurz- und Langzeitwirkungen</h5><table style="width:100%;border-collapse:collapse"><tr><td><b>kurzfristig</b></td><td><b>langfristig</b></td></tr><tr><td>Ablenkung</td><td>schwächere Aufmerksamkeit</td></tr><tr><td>Unterbrechung</td><td>Medienabhängigkeit</td></tr><tr><td>Konzentrationsverlust</td><td>geringere Leistungsfähigkeit</td></tr></table>
<h5>8. C1/C2-Wortschatz für diesen Nachteil</h5><table style="width:100%;border-collapse:collapse"><tr><td><b>Ausdruck</b></td><td><b>Verwendung im Satz</b></td></tr><tr><td>die Reizüberflutung</td><td>Ständige Medieninhalte können zu Reizüberflutung führen.</td></tr><tr><td>der Konzentrationsverlust</td><td>Benachrichtigungen können Konzentrationsverlust verursachen.</td></tr><tr><td>die Medienabhängigkeit</td><td>Eine übermäßige Nutzung kann Medienabhängigkeit begünstigen.</td></tr><tr><td>die Aufmerksamkeitsspanne</td><td>Kurze Videos können die Aufmerksamkeitsspanne verringern.</td></tr><tr><td>die digitale Überforderung</td><td>Zu viele Informationen können digitale Überforderung auslösen.</td></tr><tr><td>die Bildschirmzeit</td><td>Eine hohe Bildschirmzeit kann Schlaf und Erholung beeinträchtigen.</td></tr></table>
<h5>9. Nomen-Verb-Verbindungen und starke Verben</h5><ul><li>die Konzentration stören</li><li>Ablenkung verursachen</li><li>Aufmerksamkeit beanspruchen</li><li>zu Reizüberflutung führen</li><li>die Aufmerksamkeitsspanne verringern</li><li>Medienabhängigkeit begünstigen</li><li>Erholungsphasen verkürzen</li><li>den Arbeitsfluss unterbrechen</li></ul>
<h5>10. Satzbausteine</h5><ul><li>Problematisch ist außerdem, dass Medien im Alltag zu Reizüberflutung führen können.</li><li>Besonders durch Benachrichtigungen, kurze Videos und ständige Empfehlungen wird die Konzentration gestört.</li><li>Viele Nutzer verlieren dadurch viel Zeit, ohne dies bewusst zu bemerken.</li><li>Wenn Mediennutzung den Alltag dominiert, können Lernen, Schlaf und soziale Kontakte beeinträchtigt werden.</li><li>Langfristig kann übermäßiger Medienkonsum die Aufmerksamkeitsspanne verringern.</li></ul>
<h5>11. Musterabsatz</h5><p>Problematisch ist außerdem, dass Medien zu Reizüberflutung und Konzentrationsverlust führen können. Durch Benachrichtigungen, kurze Videos und ständig neue Inhalte wird die Aufmerksamkeit immer wieder unterbrochen. Besonders beim Lernen oder Arbeiten kann dies die Produktivität deutlich verringern. Viele Plattformen sind zudem so gestaltet, dass Nutzer möglichst lange online bleiben. Langfristig kann eine übermäßige Mediennutzung daher nicht nur Zeit kosten, sondern auch Konzentration, Schlaf und Leistungsfähigkeit beeinträchtigen.</p>
<h4>3. Allgemeine C1/C2-Kopiervorlage</h4>
<h5>Wichtige allgemeine Wörter</h5><table style="width:100%;border-collapse:collapse"><tr><td><b>Ausdruck</b></td><td><b>Verwendung im Satz</b></td></tr><tr><td>die Medienwirkung</td><td>Die Medienwirkung zeigt sich besonders in der Meinungsbildung.</td></tr><tr><td>die Informationsflut</td><td>Die Informationsflut kann viele Menschen überfordern.</td></tr><tr><td>die Glaubwürdigkeit</td><td>Die Glaubwürdigkeit einer Quelle muss kritisch geprüft werden.</td></tr><tr><td>die Öffentlichkeit</td><td>Medien beeinflussen die Wahrnehmung der Öffentlichkeit.</td></tr><tr><td>die digitale Plattform</td><td>Digitale Plattformen bestimmen, welche Inhalte sichtbar werden.</td></tr><tr><td>die emotionale Inszenierung</td><td>Emotionale Inszenierung kann objektive Information verdrängen.</td></tr><tr><td>die Medienkompetenz</td><td>Medienkompetenz ist notwendig, um Inhalte einordnen zu können.</td></tr><tr><td>die psychische Belastung</td><td>Soziale Medien können psychische Belastung verstärken.</td></tr><tr><td>die gesellschaftliche Spaltung</td><td>Einseitige Inhalte können gesellschaftliche Spaltung fördern.</td></tr><tr><td>die algorithmische Steuerung</td><td>Algorithmische Steuerung beeinflusst, welche Informationen Nutzer sehen.</td></tr></table>
<h5>Starke Konnektoren für eine Erörterung</h5><ul><li>Zunächst lässt sich festhalten, dass ...</li><li>Ein zentraler Nachteil besteht darin, dass ...</li><li>Besonders problematisch ist hierbei, dass ...</li><li>Dies lässt sich damit erklären, dass ...</li><li>Hinzu kommt, dass ...</li><li>Darüber hinaus sollte berücksichtigt werden, dass ...</li><li>Dies kann zur Folge haben, dass ...</li><li>Infolgedessen besteht die Gefahr, dass ...</li><li>Langfristig betrachtet kann dies dazu führen, dass ...</li><li>Aus gesellschaftlicher / psychologischer / medienkritischer Sicht ist problematisch, dass ...</li></ul>
<h4>4. Schreibgerüste für Nachteile-Absätze</h4><p>Mit diesen Gerüsten kannst du in der Prüfung schnell einen strukturierten Absatz schreiben. Ersetze die Lücken durch deine konkreten Inhalte.</p>
<h5>Gerüst A: Manipulation und Meinung</h5><ul><li>Ein zentraler Nachteil des Medieneinflusses liegt in ...</li><li>Dies lässt sich damit erklären, dass ...</li><li>Besonders in sozialen Medien zeigt sich dieses Problem, weil ...</li><li>Dadurch kann ...</li><li>Langfristig besteht die Gefahr, dass ...</li></ul>
<h5>Gerüst B: Fake News und Informationsflut</h5><ul><li>Ein weiterer problematischer Aspekt ist ...</li><li>Viele Nutzer ...</li><li>Ein konkretes Beispiel dafür ist ...</li><li>Dies führt dazu, dass ...</li><li>Somit kann der Einfluss der Medien ...</li></ul>
<h5>Gerüst C: Vergleichsdruck</h5><ul><li>Besonders Jugendliche können durch Medien unter Druck geraten, weil ...</li><li>Soziale Netzwerke zeigen häufig ...</li><li>Wenn Nutzer sich damit vergleichen, ...</li><li>Dadurch wird ...</li><li>Auf lange Sicht kann ...</li></ul>
<h4>5. Musterabsätze auf C1/C2-Niveau</h4>
<h5>Musterabsatz 1: Manipulation und Filterblasen</h5><p>Ein wesentlicher Nachteil des Medieneinflusses liegt in der möglichen Manipulation der Meinungsbildung. Medien stellen komplexe Themen häufig verkürzt oder emotional dar, damit sie mehr Aufmerksamkeit erhalten. Besonders in sozialen Netzwerken verstärken Algorithmen diesen Effekt, weil sie den Nutzern vor allem Inhalte zeigen, die zu ihren bisherigen Interessen passen. Dadurch können sogenannte Filterblasen entstehen, in denen andere Perspektiven kaum noch sichtbar sind. Langfristig betrachtet kann dies kritisches Denken schwächen und gesellschaftliche Spaltung fördern.</p>
<h5>Musterabsatz 2: Fake News und Vertrauensverlust</h5><p>Ein weiterer negativer Aspekt ist die schnelle Verbreitung von Fake News. Im Internet können falsche Informationen innerhalb kurzer Zeit viele Menschen erreichen, besonders wenn sie emotional formuliert oder mit auffälligen Bildern verbunden sind. Viele Nutzer teilen solche Inhalte, ohne die Quelle zu überprüfen. Dadurch entsteht Verunsicherung, weil es schwieriger wird, glaubwürdige Informationen von manipulativen Beiträgen zu unterscheiden. Auf Dauer kann dies das Vertrauen in Medien, Wissenschaft und demokratische Institutionen schwächen.</p>
<h5>Musterabsatz 3: Vergleichsdruck und Selbstbild</h5><p>Problematisch ist außerdem der Vergleichsdruck, der durch soziale Medien entsteht. Plattformen wie Instagram oder TikTok zeigen häufig ein idealisiertes Leben mit perfekten Körpern, teuren Produkten und scheinbar dauerhaft glücklichen Menschen. Besonders Jugendliche können dadurch das Gefühl entwickeln, nicht attraktiv, erfolgreich oder beliebt genug zu sein. Dies kann das Selbstwertgefühl beeinträchtigen und psychischen Druck erzeugen. Somit beeinflussen Medien nicht nur Informationen, sondern auch das Selbstbild der Nutzer.</p>
<h5>Musterabsatz 4: Reizüberflutung und Konzentration</h5><p>Ein weiterer Nachteil besteht in der ständigen Reizüberflutung. Durch Benachrichtigungen, kurze Videos, Werbung und neue Beiträge wird die Aufmerksamkeit der Nutzer immer wieder unterbrochen. Besonders beim Lernen oder Arbeiten kann dies zu Konzentrationsproblemen führen. Hinzu kommt, dass viele Plattformen darauf ausgelegt sind, Nutzer möglichst lange online zu halten. Langfristig kann übermäßiger Medienkonsum daher die Aufmerksamkeitsspanne verringern und die Leistungsfähigkeit beeinträchtigen.</p>
<h4>6. Übungen zur Vorbereitung</h4>
<h5>Übung 1: Wörter sinnvoll einsetzen</h5><p>Setze passende Wörter ein: <b>Filterblase, Vergleichsdruck, Quellenkritik, Reizüberflutung, Selbstwertgefühl, Desinformation.</b></p><ol><li>Soziale Medien können eine __________ erzeugen, wenn Nutzer nur ähnliche Inhalte sehen.</li><li>Durch perfekte Bilder entsteht bei vielen Jugendlichen starker __________.</li><li>Um Fake News zu erkennen, ist __________ besonders wichtig.</li><li>Zu viele Inhalte und Benachrichtigungen führen schnell zu __________.</li><li>Idealisierte Darstellungen können das __________ beeinträchtigen.</li><li>Falsche Informationen, die bewusst verbreitet werden, nennt man __________.</li></ol>
<h5>Übung 2: Einfache Sätze auf C1/C2-Niveau umformulieren</h5><ol><li>Medien beeinflussen Menschen. → ...</li><li>Fake News sind schlecht. → ...</li><li>Jugendliche vergleichen sich zu viel. → ...</li><li>Werbung und Videos lenken ab. → ...</li><li>Man weiß nicht mehr, was wahr ist. → ...</li></ol>
<h5>Übung 3: Mini-Absatz schreiben</h5><p>Schreibe einen kurzen Nachteile-Absatz mit 5 bis 7 Sätzen. Wähle eines der Themen: Manipulation, Fake News, Vergleichsdruck oder Reizüberflutung. Nutze mindestens drei C1/C2-Ausdrücke aus diesem Arbeitsblatt.</p>
<h4>7. Kompakte Kopiervorlage für die Prüfung</h4>
<h5>Nachteil 1: Manipulation</h5><ul><li>Medien → einseitige Darstellung → Meinungsbeeinflussung → Filterblase → Polarisierung</li><li>C1/C2: die Meinungsbildung, die Manipulation, die Filterblase, kritisches Denken schwächen</li></ul>
<h5>Nachteil 2: Fake News</h5><ul><li>Informationen → schnelle Verbreitung → Fake News → Verunsicherung → Vertrauensverlust</li><li>C1/C2: die Desinformation, die Quellenkritik, die Glaubwürdigkeit, die Urteilsfähigkeit beeinträchtigen</li></ul>
<h5>Nachteil 3: Vergleichsdruck</h5><ul><li>soziale Medien → perfekte Bilder → Vergleich → Unsicherheit → psychische Belastung</li><li>C1/C2: der Vergleichsdruck, das Selbstwertgefühl, die Selbstdarstellung, unrealistische Ideale vermitteln</li></ul>
<h5>Nachteil 4: Reizüberflutung</h5><ul><li>ständige Inhalte → Ablenkung → Konzentrationsverlust → Medienabhängigkeit</li><li>C1/C2: die Reizüberflutung, die Aufmerksamkeitsspanne, die Medienabhängigkeit, die Konzentration beeinträchtigen</li></ul>`;

  window.DEUTSCH_TESTS.t31=Object.assign({},TEST_CORE,{title:'Werbung – Nachteile · C1/C2 Nachteilsabsatz'});
  window.DEUTSCH_LESSONS.t31={short:SHORT,medium:MEDIUM,long:LONG};
  window.DEUTSCH_TESTS.t32=Object.assign({},TEST_CORE,{slug:'werbung_medien_nachteile_c1_c2',title:'Werbung – Nachteile · Medien-Einfluss · C1/C2 Nachteilsabsatz'});
  window.DEUTSCH_LESSONS.t32={short:SHORT,medium:MEDIUM,long:LONG};

  function currentKey(){var c=document.querySelector('input[name="tc"]:checked');if(c&&c.value)return c.value;try{if(typeof selected!=='undefined')return selected}catch(e){}return '';}
  function levelFromButton(el){if(!el)return null;var id=el.id||'';if(id==='btnLessonShort')return 'short';if(id==='btnLessonMedium')return 'medium';if(id==='btnLessonLong')return 'long';return null;}
  function render(key,level){var test=window.DEUTSCH_TESTS[key]||window.DEUTSCH_TESTS.t31;var lesson=(window.DEUTSCH_LESSONS[key]&&window.DEUTSCH_LESSONS[key][level])||LONG;if(typeof hide==='function')hide();var lessonBox=document.getElementById('lesson');var title=document.getElementById('lessonTitle');var meta=document.getElementById('lessonMeta');var content=document.getElementById('lessonContent');if(!lessonBox||!title||!meta||!content)return false;lessonBox.classList.remove('hide');title.textContent='Konu anlatımı: '+test.title;meta.textContent='Seviye: '+(level==='short'?'Kısa':level==='medium'?'Orta':'Uzun')+' · yüklediğin Word dosyasına göre eksiksiz medya etkisi konu anlatımı';var list=(test.words||[]).slice(0,level==='short'?8:level==='medium'?24:65).map(function(w){return '<li>'+safe(w)+'</li>';}).join('');content.innerHTML='<section style="padding:14px;border:1px solid #d8d3ca;border-radius:14px;background:#fff;margin-bottom:18px"><h2>1. Genel bakış</h2><p><b>Thema:</b> '+safe(test.topic)+'</p>'+(list?'<h3>Öncelikli kavramlar</h3><ul>'+list+'</ul>':'')+'</section><section style="padding:14px;border:1px solid #d8d3ca;border-radius:14px;background:#fff;margin-bottom:18px"><h2>2. Konu açıklaması</h2>'+lesson+'</section>';lessonBox.scrollIntoView({behavior:'smooth'});return true;}
  function choose(input,key){input.checked=true;try{selected=key}catch(e){}var m=document.getElementById('modeControls');if(m)m.classList.remove('hide');}
  function injectButton(){var box=document.getElementById('testList');if(!box)return;['t31','t32'].forEach(function(key){if(document.querySelector('input[name="tc"][value="'+key+'"]'))return;var t=window.DEUTSCH_TESTS[key];if(!t)return;var label=document.createElement('label');label.className='opt';label.style.display='block';label.style.margin='8px 0';label.innerHTML='<input type="radio" name="tc" value="'+key+'"> <b>'+safe(t.title)+'</b><br><span class="muted">'+safe(t.topic)+'</span>';var input=label.querySelector('input');input.addEventListener('change',function(){choose(input,key);});label.addEventListener('click',function(){choose(input,key);});var after=document.querySelector('input[name="tc"][value="t32"]')||document.querySelector('input[name="tc"][value="t31"]')||document.querySelector('input[name="tc"][value="t30"]')||document.querySelector('input[name="tc"][value="t29"]')||document.querySelector('input[name="tc"][value="t28"]');if(after&&after.closest('label'))after.closest('label').after(label);else box.appendChild(label);});}
  document.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest&&ev.target.closest('#btnLessonShort,#btnLessonMedium,#btnLessonLong');var level=levelFromButton(b);var key=currentKey();if(!level||(key!=='t31'&&key!=='t32'))return;ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();setTimeout(function(){render(key,level);},0);return false;},true);
  document.addEventListener('pointerdown',function(ev){var b=ev.target&&ev.target.closest&&ev.target.closest('#btnLessonLong');var key=currentKey();if(!b||(key!=='t31'&&key!=='t32'))return;setTimeout(function(){render(key,'long');},120);},true);
  document.addEventListener('DOMContentLoaded',function(){injectButton();});
  setInterval(function(){injectButton();window.DEUTSCH_LESSONS.t31.long=LONG;window.DEUTSCH_LESSONS.t32.long=LONG;},700);
  window.forceWerbungLessonFinal=function(level){return render('t31',level||'long');};
  window.forceWerbungMedienLessonFinal=function(level){return render('t32',level||'long');};
})();